### ISSUE TITLE
[BLES01617] Tales of Graces F: "VM: Access violation reading location 0xa67c0770 (unmapped memory)"

### ISSUE THREAD

**Issue by IngwiePhoenix** [RPCS3/rpcs3#10042]
## Quick summary
My friend sent me his old Tales of Graces F savefiles and I wanted to boot the game up and see what would happen. But after selecting a file to load, the game freezes.

## Details
```
# I reduced log levels and cut this straight from the log view.
E SYS: 'sys_ss_access_control_engine' failed with 0x80010003 : CELL_ENOSYS [1]
E SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/MenuLayout.txt” [1]
E SYS: 'sys_ppu_thread_set_priority' failed with 0x80010005 : CELL_ESRCH [1]
F VM: Access violation reading location 0xa67c0770 (unmapped memory) [type=u32]
E SIG: Thread [SPU LLVM] is too sleepy. Waiting for it 20395.203µs already!
E SIG: Thread [SPUW.1] is too sleepy. Waiting for it 20351.266µs already!```
```

#### Please provide your system configuration:
* OS: Windows 10, 64bit
* CPU: AMD Ryzen 9 3900X
* GPU: NVIDIA GeForce RTX 2080 TI (FE)
* Driver version: 460.89.0.0
* RPCS3: `0.0.15-12026-e557c962 Alpha`

**Comment by AniLeo** [comment]
This is a support request - the issue seems to be incorrect importation of save data or bad dump, doesn't adhere to issue template as well

---

Remember that the GitHub Issue Tracker is not the place to [**ask for support**](https://github.com/RPCS3/rpcs3/wiki/How-to-ask-for-Support) or to [**submit Game Compatibility reports**](https://github.com/RPCS3/rpcs3/wiki/Game-Compatibility).

The issue has been marked as **Invalid** and closed.
