### ISSUE TITLE
[Feature Request] MIDI keyboard; make Rock Band 3 Keys playable

### ISSUE THREAD

**Issue by JapanYoshi** [RPCS3/rpcs3#10220]
## Quick summary
To make Rock Band 3's Keys mode playable, RPCS3 should support Rock Band 3 Keyboard controllers. In addition, for people who don't have the controller, it should 1) accept MIDI events from a MIDI keyboard, and/or 2) assign MIDI events to keyboard or gamepad inputs.

- [x] Support real Rock Band 3 Pro Keys controller
- [ ] Support Rock Band 3 Pro Keys controllers from Wii; they should only differ in device ID
- [ ] Support generic MIDI keyboard
- [ ] Support playing Rock Band 3 Keys with a computer keyboard or generic controller

## Details
Rock Band 3 released with a keytar-shaped controller called the Wireless Pro Keyboard Controller, which works as a fully-featured 2-octave MIDI keyboard.

![Photograph of the Rock Band 3 Wireless Pro Keyboard controller for PS3](https://upload.wikimedia.org/wikipedia/commons/7/7f/Rock_Band_3_Wireless_Pro_Keyboard_PS3.jpg)

It also supports the adapter that takes in MIDI input from an existing MIDI keyboard, and lets the player use it as a game controller. The adapter is common with the Pro Drums and Squier Stratocaster Pro Guitar Controller; the specific connected device is toggled with the switch in the center, with the letters D, K, and G standing for Drums, Keys, and Guitar, respectively.

![Photograph of the Rock Band 3 MIDI adapter](https://c1.neweggimages.com/NeweggImage/ProductImage/79-216-200-03.jpg)

RPCS3 seems to be missing a Device Class for the Keyboard Controller, so that should be added for full compat with Rock Band 3. In addition, MIDI events should be accepted from a real Keyboard Controller or a generic MIDI keyboard.

Additionally, to make Keys at least accessible without special peripherals, it should be possible to assign keyboard input to 5 keys, one of each colored dot (likely C3~G3), so that regular 5-lane Keyboard charts are playable.

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* Gameplay - This feature is necessary to access content in Rock Band 3.

#### 2. Please tell us, why your feature is important to RPCS3.
RPCS3 is one of the most reliable ways so far to play Rock Band 3 in 2021, and it's a pity that the keyboard is completely unsupported in it.

#### 3. Please attach screenshots of the feature implemented in other projects.
[Video link](https://www.youtube.com/watch?v=nGLQzCYGBls?t=50) - Dolphin (a Wii emulator) seems to support Keyboard mode. It is at the center-right at 0:50 and 3:50 in this video. It also appears at 2:17 on the left, but no notes appear in the previewed snippet.

#### 4. Please provide your system configuration:
* OS - Windows 10
* CPU - Intel® Core™ i7-8750H CPU @ 2.20GHz
* GPU - Intel® UHD Graphics 630; NVIDIA GeForce GTX 1060 with Max-Q Design
* Driver version - ?

**Comment by Megamouse** [comment]
Note for developers:
Please read the closed issue first (see above).
It mentions that there seems to be an issue with sys_usbd_attach.

**Comment by LinosM** [comment]
I do hope someone can at least get actual hardware working. Despite "Harmonix Keyboard" be listed as a whitelisted device in the wiki, it's not detected in Rock Band 3.

**Comment by echohead84** [comment]
I'm sitting at my computer with a keyboard in front of me with MIDI out to USB, and realized this is not going to work. My symptoms are the same as Kramerika. This would be such an excellent tool for learning some beginner keyboard, fingers tightly crossed that someone with the ability can manage to get this working.

**Comment by RipleyTom** [comment]
Games using sys_usbd require you to change the driver as explained here: https://wiki.rpcs3.net/index.php?title=Help:Peripherals_and_accessories#cellUsbd_Set-up_Instructions .

If you've done so and it still doesn't work please post a log.

**Comment by LinosM** [comment]
> Games using sys_usbd require you to change the driver as explained here: https://wiki.rpcs3.net/index.php?title=Help:Peripherals_and_accessories#cellUsbd_Set-up_Instructions .
> 
> If you've done so and it still doesn't work please post a log.

Two years ago I reported a problem with the Keyboard controller crashing the game though with no response. 
https://github.com/RPCS3/rpcs3/issues/8295

Pretty sure I changed the driver correctly and the log that older version showed
"sys_usbd: Found device: Harmonix Keyboard"

I redownload that version again just to see if my Keyboard is recognized and it still is along with the crash.

I downloaded the newest version and tried loading Rock Band 3, I couldn't find any mention of "Harmonix Keyboard" in the log, though the game runs and I am unable to use the controller

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8483805/RPCS3.log)

**Comment by echohead84** [comment]
I realized that my situation is slightly different than Kramerika, in that I'm using a Yamaha keyboard with MIDI out, paired with a Wii Mad Catz MIDI out adapter which has been modified for use with PS3/4. When I connect the MIDI adapter to the computer it says it's installing drivers for a Rock Band Keyboard, but once I'm in RPSC3 it doesn't seem to register. I've tried with Zadig running as well with no change in results.

**Comment by RipleyTom** [comment]
@LinosM Can you give a log with latest version?
I added some error logging for libusb init/enumeration errors.

**Comment by LinosM** [comment]
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8502052/RPCS3.log)

**Comment by Readek** [comment]
Since I recently got a bunch of PS3 Harmonix instruments, I decided to test this myself, and it is indeed broken, but not only for keyboards:

The wiki page for [USB passthrough](https://wiki.rpcs3.net/index.php?title=Help:Peripherals_and_accessories)'s whitelist lists all harmonix instruments, but no sight of the MIDI pro adapter. For convenience, I will list the vendor/product ID's of the devices I could try myself:

`Harmonix Drum kit for PlayStation®3` `12ba`:`0210`
`Harmonix RB3 Keyboard for PlayStation®3` `12ba`:`2330`
These are the 3 modes for the MIDI pro adapter:
`Harmonix Drum kit for PlayStation®3` `12ba`:`0218`
`Harmonix RB3 MIDI Keyboard Interface for PlayStation®3` `12ba`:`2338`
`Harmonix RB3 MIDI Guitar Interface for PlayStation®3` `12ba`:`2538`

Now, all of these can be added as a controller on RPCS3 manually without passthrough, but as already discussed, the controller buttons will work but the MIDI features will not work, with the exception of the drums since drums are just big controllers. This is why passtrhough is necessary. But as of my testings, none of these work. I followed the instructions of the wiki page and I tested on both Linux and Windows with the exact same results:

- When connecting the drums USB *or* the MIDI pro adapter on drum mode, the game will recognize that a drum kit has been connected, so it will show up on the interface as a player ready to join. However, you will be unable to interact with the game in any way as that player, the game will not read any input.
- For all of the rest USBs, the game will give you nothing. No player ready to join, no inputs being read, nothing. Also, for some reason, if you disconnect the USB while the game is running, the game will hang with the log spamming an error with `...sys_usbd: Usb transfers are saturated!` to infinity until the emulator is closed.

A friend with a Harmonix 5 button guitar also tried to USB passthrough with the same results as what I've seen with the drums. So my conclusion here is that USB passthrough does not work at all on Rock Band 3. Is this something that can be fixed?

**Comment by Jas2o** [comment]
I don't have a complete solution, but have hacked some changes into USB passthrough so that Rock Band 3 is able to read inputs from Keyboard, Mustang guitar, and MIDI-Pro Adapter (only tested in Keys and Guitar modes).

https://github.com/Jas2o/rpcs3/commit/6a2d25971ef9e94b82a00fe854b8445ec86ecaeb

Have no idea what should be done next, either working out why two Control Transfers aren't returning expected results, or limiting the hack to RB3/setting?

**Comment by RipleyTom** [comment]
There are several issues at work here, for some people libusb seems to fail to enumerate the connected usb devices(like @LinosM), hopefully https://github.com/RPCS3/rpcs3/pull/11894 will fix that.

All the devices you list are already whitelisted @Readek.

@Jas2o if you could post a log of RB3 interacting with the device(without the hack) and with `Log: {sys_usbd: Trace}` set in the config file(it's the last line of config.yml or your custom config file for the game).

**Comment by Jas2o** [comment]
Here's two logs from the same version of RPCS3 (without hack). The first getting to the menu without pressing any buttons on the keyboard, the second with pressing buttons (which doesn't work). The keyboard's LEDs indicate it loses connection when the intro video starts - from what I can tell it's absolutely flooded with USB requests.

[RPCS3-Keyboard-Menu.log.gz](https://github.com/RPCS3/rpcs3/files/8587368/RPCS3-Keyboard-Menu.log.gz)
[RPCS3-Keyboard-IntroButtonPress.log.gz](https://github.com/RPCS3/rpcs3/files/8587369/RPCS3-Keyboard-IntroButtonPress.log.gz)

**Comment by Jas2o** [comment]
Here's the log, the first time I missed that it had to be done in custom config. The keyboard doesn't interact with the game menu, the LEDS of the keyboard and dongle look like they're struggling to stay connected after the game intro video.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8587429/RPCS3.log.gz)

**Comment by neomanic** [comment]
I was checking out RPCS3 recently as an alternative option for rhythm games, including Rock Band 3. I have an almost complete collection of the GH and RB games that I still play on a physical Wii, mainly drums (I have a GH:WT, a RB1 kit, and just got a Pro-MIDI adapter to use with a set of e-drums)... but the original hardware is starting to fall apart with age and use. So I'm interested in its preservation, and likely will be moving over to Dolphin shortly.

So this thread jumped out at me; particularly since the problem discussed seems somewhat similar to the situation with Dolphin on Mac where the macOS driver grabs all HID devices, so you have to have a custom driver which has to be authorised through Apple! I have a [rant about it on Twitter](https://twitter.com/josh_m/status/1518731243701280769), and it's actually motivating to see this thread, since if a driver was allowed to pass through the Wii USB peripherals, it could also support PS3 USB peripherals with only adding the extra vendor/device IDs!

That USB HID driver is relevant to using the old hardware, but unfortunately that's not a realistic long-term option to ensure people can play the game. Now as was suggested above, the ideal option for drums and keys would be just to feed in MIDI from the real thing (particularly since you can get super-cheap e-drums and keyboards to start of with).

Given the the Pro-MIDI adapter is basically the same thing on Wii and PS3 (mine can be switched to be PS3-compatible one with a single hardware jumper if I open it up)... this is another situation where if the work is done it'll likely benefit both platforms.

@Readek's device ids from above:

> `Harmonix Drum kit for PlayStation®3 12ba:0210`
> `Harmonix RB3 Keyboard for PlayStation®3 12ba:2330`
> These are the 3 modes for the MIDI pro adapter:
> `Harmonix Drum kit for PlayStation®3 12ba:0218`
> `Harmonix RB3 MIDI Keyboard Interface for PlayStation®3 12ba:2338`
> `Harmonix RB3 MIDI Guitar Interface for PlayStation®3 12ba:2538`

The Wii versions are:
RB3 Keyboard: `3330`
RBS pro midi adapter: drums `3138`, keyboard `3338`, guitar `3538`.
Pretty clear there's only a single bit difference between them (except for the drums), it's likely taken straight from the jumpers.

Anyway, that was a really long way of saying I'm keen on these areas, and will help if I can find some motivation and time!

**Comment by RipleyTom** [comment]
Please test https://github.com/RPCS3/rpcs3/issues/10220 once it's built.

As for the pro adapter, it's not really handled like a unique device by the games, it's just handled as a Harmonix guitar/drum/etc by the games and the list only lists what the game lists as devices in their query.

**Comment by Jas2o** [comment]
@RipleyTom I've tested your branch with the RB3 wireless keyboard, the LEDS now show the player number, menu navigation works and Pro Keys mode is playable! There is a fatal error when closing the game.

[RPCS3.log.zip](https://github.com/RPCS3/rpcs3/files/8598391/RPCS3.log.zip)

**Comment by RipleyTom** [comment]
Thank you for testing, I'm not sure the fatal error is related, is it consistent?

**Comment by Jas2o** [comment]
Tested a few more times by closing the game after the intro videos and reaching the menu. The fatal error is consistent with either RB1 Guitar, RB3 Mustang or RB3 Keyboard connected. Without a USB device connected there's no issue.

Lego Dimensions using Toy Pad Emulator (USB passthrough) also results in a fatal error on close, without the emulated USB device there is no issue closing. Skylanders using RPCS3's built-in portal emulator is fine.

**Comment by RipleyTom** [comment]
I'll close this, please open another issue for the crash if it persists(I can't test passthrough atm).

**Comment by SCOTT0852** [comment]
Not sure if I'm just doing something wrong, but I can't seem to get my Wii keyboard to show up in-game. Are the Wii keyboard device IDs just passed straight through or are the PS3 version's spoofed instead? I know the PS3 game only detects the PS3's IDs even though the actual input given by the Wii keyboard's is the same (supposedly it can even control the XMB on real hardware, although I can't test that as I don't own a real PS3, only a blu-ray drive). A hack to force Wii keyboards to spoof the PS3 keyboard's IDs should allow all Wii keyboards to work just fine, as well as Wii Midi Pro Adapters (which are far cheaper than the PS3 and 360 models) without needing to open them up and destroy a resistor.

**Comment by Readek** [comment]
In theory you cant just plug in a device made for another console, but you have 2 options: You either modify it physically (good luck with that!), or you can plug it to a PS3 pro adapter with a midi cable. Any other solution goes out of the scope of this PS3 emulator. Though it would be a perfect world if RPCS3 could emulate the Pro adapter itself so you could just MIDI to USB anything without a physical pro adapter which today is very pricey!

**Comment by SCOTT0852** [comment]
> In theory you cant just plug in a device made for another console
The Wii and PS3 keyboards are literally the same aside from the USB identifier. I'm not asking "add native Wii remote support", if you just told a PS3 "this is a PS3 keyboard" then it would work perfectly. The PS3 can clearly read it just fine since you can control the XMB with it on a real, unmodified console despite it not being "for PS3".

**Comment by JapanYoshi** [comment]
I noticed that this issue was marked as closed.

1. Are Rock Band 3 keys playable with a MIDI keyboard?
2. Are Rock Band 3 keys playable without a controller?

Unless both of these are true, I want the issue reopened.

**Comment by SCOTT0852** [comment]
I don't believe there's any sort of MIDI support yet. You currently need the real PS3 controller, there's no way to map other devices as one.

**Comment by JapanYoshi** [comment]
> I don't believe there's any sort of MIDI support yet. You currently need the real PS3 controller, there's no way to map other devices as one.

Then it’s not resolved then. Should I wait until this issue is reopened, or shall I post a different issue?

**Comment by SCOTT0852** [comment]
I think this one should be reopened, the title specifically mentions MIDI keyboard support and that isn't implemented.

**Comment by JapanYoshi** [comment]
@RipleyTom Please reopen! The issue is not resolved.

**Comment by RipleyTom** [comment]
Please edit the original post, the game works with the real device now.
Also the device class discussion is pointless, that list comes from the ps3, there is no other device class.

For it to work it would require a new usb emulated device, something similar to the guitar hero live guitar emulation.

**Comment by JapanYoshi** [comment]
I've added a to-do list on my original post.

**Comment by SCOTT0852** [comment]
Something to note with that list, I believe the Xbox 360 keyboard is actually incompatible. It connects like any other 360 controller, so it would have to be XInput. Only Wii and PS3 keyboards (as well as midi pro adapters) are identical. I haven't tested that myself (I don't own a 360 keyboard as using it would require purchasing an Xbox 360 controller dongle), but I know I've never heard of anyone doing platform switch mods to 360 models like I've frequently seen for Wii > PS3.

**Comment by Kramerika** [comment]
I just tested all of my equipment again on the latest build.  Here are my own results.

X360 Keyboard with X360 midi pro adapter (does not work with or without WinUSB passthrough, does not show up as game controller in Windows)
X360 Keyboard with Microsoft X360 Wireless Receiver for Windows (does not work with or without WinUSB passthrough, does show up in Windows as a game controller but keys do not work)
PS3 Keyboard with dongle (works with WinUSB passthrough, game error on exit)
PS3 Keyboard with PS3 midi pro adapter (works with WinUSB passthrough, buttons only work on adapter but keys work on keyboard)

For other instruments besides keyboard just as an FYI.  I did not get a chance to test the drum kit with WInUSB passthrough for the PS3, but based on the PS3 keyboard results, it probably works.

Alesis Nitro drum kit with Xbox midi pro adapter (works without WinUSB passthrough, used MMJoystick, Rock Band, Pro Drums, but must reassign Cross, Circle, Triangle, Square, Start, and Select in config GUI and find the cymbal modifier button and bass drum pedal buttons in the control panel devices then assign the buttons manually in the config files)
Alesis Nitro drum kit with PS3 midi pro adapter (works without WinUSB passthrough, same process as above to assign buttons with MMJoystick)
X360 RB3 Guitar with Microsoft X360 Wireless Receiver for Windows (works without WinUSB passthrough, assign buttons in config GUI)
PS3 RB3 Guitar with dongle (works with WinUSB passthrough, game error on exit)
PS4 RB4 Guitar with bluetooth adapter (works except for whammy bar, guitar tilt, and solo modifier, assign buttons in config GUI)

If you want me to test anything else specifically with any of this or provide logs in particular, let me know what to do.

**Comment by zurgeg** [comment]
FYI, I found a [bot](https://github.com/mtolly/rocker) that communicates with the RB3 Midi Adapter. I think that might help with emulating the adapter.

**Comment by DarkRTA** [comment]
https://github.com/TheNathannator/PlasticBand/tree/main/Docs/Instruments

There's a *lot* of documentation on how these instruments work which will likely go a long way to properly emulating them.
On the midi side, there's some stuff that still needs to be properly documented.

**Comment by DarkRTA** [comment]
I am currently working on supporting midi instruments in #13632. So far I've got keyboards fully implemented and working, but I need to also support guitars and drums, along with creating a proper configuration UI for this.

**Comment by DarkRTA** [comment]
I am needing people to test #13632. That PR is almost complete and ready for merge.

**Comment by AARP41298** [comment]
Hey @DarkRTA do you still need the log?

**Comment by Megamouse** [comment]
Closing as Essentially implemented

**Comment by SArpnt** [comment]
this doesn't look complete, why was this closed?
it's not clear how i would, for example, use my wii rockband keytar to play pro keys

**Comment by DarkRTA** [comment]
> this doesn't look complete, why was this closed?
Technically with the MIDI input support, you can use any MIDI device or external software to drive the whole thing. Its very easy to see why it would be closed.

> it's not clear how i would, for example, use my wii rockband keytar to play pro keys
As of right now, you'd need a 5 pin MIDI interface or some external software that does not exist yet to handle the dongle instead.

**Comment by DarkRTA** [comment]
> But even with the MIDI input stuff, controller navigation with the d-pad and face buttons on the keyboard isn't supported, correct? While it's technically playable, having to modify your MIDI octave simply to navigate menus isn't exactly what I'd consider "complete".

While you are correct here with the fact that its unsupported in RPCS3 itself (hardware limitation), the door is now open for external software to handle the keyboard directly and send the correct MIDI events through a virtual device.

RPCS3 won't be able to pass through Wii keyboards without some pretty invasive modifications to the USB stack.

**Comment by AARP41298** [comment]
@SArpnt check #14155

**Comment by EPICXMO** [comment]
iv been trying to get this to work for almost 7 hours now lol. im now getting really really tired and cant think. If anyone knows how to connect a 360 version with out using a cable connected to it pleeeeaaaaaseeessss let me know

**Comment by SCOTT0852** [comment]
> If anyone knows how to connect a 360 version with out using a cable connected to it pleeeeaaaaaseeessss let me know

This isn't currently possible. You need to either be using a real PS3 keyboard, a real PS3 MIDI pro adapter, or a standard USB MIDI interface (not recommended for Rock Band keyboards, you will need to shift octaves to navigate menus). I ultimately ended up buying a Wii MPA and modifying it to be detected as a PS3 one so I could use my real Wii keyboard.

**Comment by movy** [comment]
Folks, sorry for hijacking, but cannot find answer elsewhere, maybe someone here can give me a direction.

I run rpcs3 + RB3 Deluxe on M1 Macbook and it works amazing with e-drums (Yamaha DTX) plugged in directly via USB and set up via Emulated MIDI in rpcs3.

But whenever I connect a RB3 guitar with a dongle OR the same e-drums set via Pro Midi adapter, none of them are detected by rpcs3. 

For example, the guitar dongle is plugged in and blinking red, then I turn on the guitar and press pair button, the PS button on the guitar turns red and dongle stops blinking (which means they're paired?), but I cannot see this controller in Custom Gamepad Configuration in SDL section or elsewhere (as passthru is not available on Mac version). Am I missing something, or support for instruments not implemented on MacOS (as guessed in https://github.com/RPCS3/rpcs3/issues/13195)? Thanks for your help in advance.
