### ISSUE TITLE
[Feature Request] Add DirectX 12 Renderer for devices that don`t support OpenGL or Vulcan

### ISSUE THREAD

**Issue by danprice142** [RPCS3/rpcs3#10421]
RPCS3 would be affected by your feature:

* Gameplay
* Debugging
* UI
* Patches
* Installation
* Github
* CI
* etc.

I understand that Devs at RPPCS3 do not wish to add the DirectX 12 renderer as it is not as good as Vulcan but adding it would allow more devices that don`t support Vulcan or OpenGL.

It would be good if this Feature request could be left up and those who want DirectX 12 implemented could see this request and work on it them selves

**Comment by dio-gh** [comment]
> I understand that Devs at RPPCS3 do not wish to add the DirectX 12 renderer

Then why open a ticket begging for it anyways?

**Comment by danprice142** [comment]
for devices that dont support it and if the devs from RPCS3 wont be working on it what's the problem with leaving this open? i thought RPCs3 is Open Source?

**Comment by dio-gh** [comment]
Oh, it's plenty open source. You (or anyone else interested in adding a DX12 renderer) is plenty welcome to fork the project and add it themselves.

The reason this ticket got closed is because as far as the team is concerned, as you said, we do not wish to add it. Therefore, there's no reason to keep around a ticket for it.

**Comment by MSuih** [comment]
Open source means that if someone wants to implement a feature then they can, it doesn't mean that we have to implement it ourselves if someone makes a request. If you manage to find such person then talk with them, not us.

We'd be delighted to have DX12 renderer but have decided not to add one ourselves as maintaining both Vulkan and OpenGL is already too much work for just one developer. Opening a ticket about this is pointless as we're aware of this and it has been an intentional choice by us, we don't need a reminder of this.

**Comment by Asinin3** [comment]
>We'd be delighted to have DX12 renderer but have decided not to add one ourselves

Actually, we had a DirectX 12 Renderer for years, but it was removed in 2018 because it was pointless to maintain an api exclusive to Windows 10 when it added a huge workload and wasn't even proving to be better than Vulkan in most cases. There's a lot of good comments on these issues mainly by Ruipin: https://github.com/RPCS3/rpcs3/issues/5064 https://github.com/RPCS3/rpcs3/issues/5000

**Comment by Augusto7743** [comment]
Please you that created that topic wait and read lines below.

In my little knowledge in programing the because D3D12 was removed is because :
- PS3 API graphics use OpenGL code.
- Vulkan is exactly an opengl api updated.
- Using D3D12 need much CPU time and thus will have less performance than OpenGL.

Doing D3D12 is much work for nothing.

**Comment by AniLeo** [comment]
> PS3 API graphics use OpenGL code.
False, PSGL exists but is very, very, very rarely used, mostly by homebrew applications

> Vulkan is exactly an opengl api updated.
Sort of, yes

> Using D3D12 need much CPU time and thus will have less performance than OpenGL.
False for both assumptions

The reasons why we don't want to have a D3D12 were already mentioned above. We already have a Vulkan render, which is a better API as well as multi-platform.

**Comment by Augusto7743** [comment]
You are saying that PS3 games had an custom graphic API ?
D3D12 renderer use same cpu time than OpenGL ?

All D3D12 GPUs has Vulkan drivers ? if yes because users demand D3D12 ? only to use D3D12 not help the project.
Thanks for all informations.

**Comment by HerrHulaHoop** [comment]
Can we lock this issue? The only way this discussion can be of any value is if someone submits a pull request to add DX12 support and agrees to maintain it. Anything lesser is just pointless pings in our server.
