### ISSUE TITLE
R&C :  A Crack In Time - Rail-Grinding Collision Issue

### ISSUE THREAD

**Issue by jy95** [RPCS3/rpcs3#10514]
## Quick summary
Rail-Grinding Collision Issue

## Details

When rail-grinding on metal rails specifically, after a jump we occasionally fall through the rail.
I experimented it on Planet Torren IV(Molonoth Fields)

#### 0. Make sure you're running with settings as close to default as possible
I only enabled the advanced option "Read Color Buffers" as recommanded by the [wiki](https://wiki.rpcs3.net/index.php?title=Ratchet_%26_Clank_Future%3A_A_Crack_in_Time)

#### 1. Please attach RPCS3's log.
[RPCS3 v0.0.17-12437-770a607b.log](https://github.com/RPCS3/rpcs3/files/6759518/RPCS3.v0.0.17-12437-770a607b.log)

#### 3. Please attach videos of your problem.
I recorded at least three times where the physics becomes weird

https://user-images.githubusercontent.com/9306961/124376816-0ec04f00-dca9-11eb-9cb3-5ff27487b1f9.mp4
https://user-images.githubusercontent.com/9306961/124376817-12ec6c80-dca9-11eb-8693-46fef9058351.mp4
https://user-images.githubusercontent.com/9306961/124376830-1a137a80-dca9-11eb-9913-1aa234633c56.mp4

#### 4. Please provide comparison with real PS3.
This problem doesn't exist in the real PS3

#### 5. Please provide your system configuration:
* Operating system: Windows, Major: 10, Minor: 0, Build: 19042, Service Pack: none, Compatibility mode: 0
* Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz | 12 Threads | 15.85 GiB RAM | TSC: 2.208GHz | AVX+ | FMA3
* GPU: 'NVIDIA GeForce GTX 1050' running on driver 471.11.0.0
* RPCS3 version : v0.0.17-12437-770a607b Alpha

#### 6. Anything else you find important ?
I checked if my backup wasn't corrupted and it isn't the case : 

![unknown](https://user-images.githubusercontent.com/9306961/124376940-a2921b00-dca9-11eb-822c-39f1213163d3.png)

**Comment by MSuih** [comment]
This could just be caused by performance not being good enough. If the interval between physics calculations is large, it means that objects will be moving a lot for each physics processing step. In this case it could be that the game sees you above the rail for one step and then below the rail in next one, and there's no point in time where you collide with it. Some games slow down during bad performance to avoid issues like this.

**Comment by kd-11** [comment]
I also observed this, but it appears to be performance related. Generally the grind rail section runs rather poorly on the emulator which easily explains the issue.

**Comment by jy95** [comment]
Is there any (combination of) settings to make the grind rail section runs smoother ?

**Comment by kd-11** [comment]
Not that I know of, but you should as around on our discord channels. It is very likely someone has figured out options that give a good balance between visuals and performance. Technically going down in resolution should help (even if your GPU utilization is nowhere near 100% it still matters for emulators) but the game natively runs at an obscenely low resolution and looks awful without MSAA due to how their DRS implementation works. But if it at least helps you get past the grind rails it can only be a good thing.
Also note that due to some unrelated issues, performance in this game can become sluggish the longer you remain in one level, in such cases reloading the level fixes the problem. This is a known problem with the insomniac PS3 engine and is being tracked separately.

**Comment by jy95** [comment]
With the recent builds (like RPCS3 v0.0.17-12535-c54ddabe Alpha ), I somehow managed to pass this.
I discovered something useful to mention : it seems to occur more frequently when `Multithreaded RSX` is enabled.

At Axiom City, I noticed that the Hover boots-area with before Neurox Plaza was simple impossible to achieve with that setting enabled. Without it, 2-3 tries were enough ...

**Comment by Darkhost1999** [comment]
Does getting past this area of the game qualify the issue to be closed?
Cause it sounds like from the message that closed this is that the issue happens less often when a setting is changed but nothing about actually being resolved.

**Comment by MSuih** [comment]
To me this sounds like a "physics can break if performance is bad" scenario rather than some emulator bug. We know that performance needs to be improved for many games, opening a ticket for them isn't really helpful. Closing this one was a good call.
