### ISSUE TITLE
UP [BLES00543] blue graphics issue

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#10530]
- SYS: RPCS3 v0.0.17-12446-6a7324ab Alpha | HEAD
- SYS: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz | 8 Threads | 15.96 GiB RAM | TSC: 2.808GHz | AVX+ | FMA3
- SYS: Operating system: Windows, Major: 10, Minor: 0, Build: 18363, Service Pack: none, Compatibility mode: 0
- RSX: Found vulkan-compatible GPU: 'NVIDIA GeForce GTX 1070' running on driver 471.11.0.0
- SYS: Firmware version: 4.88

The game is playable only it has this problem with the graphics 

![FPS_ 60 00 _ Vulkan _ 0 0 17-12446 _ UP  BLES00543  7_11_2021 12_37_46 AM](https://user-images.githubusercontent.com/45731484/125175901-68aca180-e1e0-11eb-9edf-9e9635733205.png)

![FPS_ 60 00 _ Vulkan _ 0 0 17-12446 _ UP  BLES00543  7_11_2021 12_38_28 AM](https://user-images.githubusercontent.com/45731484/125175904-6c402880-e1e0-11eb-92d2-72ecce73bf17.png)

capture file

[BLES00543_20210711195255_capture.zip](https://github.com/RPCS3/rpcs3/files/6797220/BLES00543_20210711195255_capture.zip)

log file
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6795918/RPCS3.log.gz)

**Comment by AniLeo** [comment]
Same issue as WALL-E, another Pixar game

**Comment by uaqlover** [comment]
update capture file

[BLES00543_20210711195255_capture.zip](https://github.com/RPCS3/rpcs3/files/6797220/BLES00543_20210711195255_capture.zip)

**Comment by kd-11** [comment]
The capture surprisingly shows the game attempting to only use the blue channel (or specifically, a mask that affects the blue channel only). I'll run some hw tests later for this.

**Comment by uaqlover** [comment]
@kd-11 any updates ?

**Comment by Shroomerian** [comment]
Hello, I think I've found something which may be useful to this bug. I ran my disk of WALL-E (BLES00279) which has the same problem and I was changing settings in a trial-and-error fashion to see if any settings could fix it.

Because every time you start a new game there's an unskippable cutscene I decided to instead go into a "challenge mode" of the game (PvP game modes), I connected a second controller I had lying around, and I used that method because it was faster than go through the cutscene.

What I discovered is that whenever you fire a laser in this game, the blue tint goes away ONLY for the second player. 

Here's a short video of what is happening in game:


https://user-images.githubusercontent.com/54857786/154849634-dc4aa3e2-f3e5-4fbd-8ecf-ecef134715e8.mp4

**Comment by Daniel3674** [comment]
It's 2022, any updates? @kd-11

**Comment by mgtpt** [comment]
Any news? Can I do anything to help resolve this? @kd-11

**Comment by JazzFlay** [comment]
Have progress on this? @kd-11 
1 year after...

**Comment by AniLeo** [comment]
Locked comments and cleaned up due to spam

kd-11 can unlock whenever he decides to work on it
