### ISSUE TITLE
Sengoku Basara 4 [BLJM61063] - Music and Dialog randomly cut out from the game

### ISSUE THREAD

**Issue by Orpheros** [RPCS3/rpcs3#10610]
## Quick summary
The music, and dialogue, seem to completely cut out at random points.

## Details
When they cut out, all the stage event triggers, like, gates opening, and dialogue boxes seem to stop appearing altogether. Even after restarting the level, it seems the dialog doesnt have sound

#### 4. Please provide comparison with real PS3.
With my ps3 the game runs fine no sound bug at all
#### 5. Please provide your system configuration:
* OS: Windows 10 Home 64-bit
* CPU: i7 9700k
* GPU: Nvidia 1070 strix oc edition
* Driver version: 471.41
* RAM: 16 gb

**Comment by AniLeo** [comment]
Missing half of the report template

**Comment by Guerdem** [comment]
It seems to happen very often in both Basara 4 Sumeragi and Yukimura Den (https://www.youtube.com/watch?v=a671sYi2PQY&t=141s&ab_channel=Emulators%26GameplayHD 2:16). But It doesn't always happen, and sometimes audio came back and event triggers normally (as the video show), though it's kinda Russian roulette.
Basara 4 Sumeragi: ![Sengoku basra 4 S audio issue](https://user-images.githubusercontent.com/77809260/127876237-22bd201d-84f9-456c-90b9-f4362d90e6a5.png)

**Comment by omar189** [comment]
having the same issue the game soft locks randomly making missions stopping you from completing missions even if you won achieved all the objectives

**Comment by omar189** [comment]
E SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLJM61063/USRDIR/nativePS3/rom/ui/pause.arc” [1]
E SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLJM61063/USRDIR/nativePS3/rom/ui/pause.arc” [2]
E SYS: Stat: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x27]
E SYS: Stat: 'sys_vm_lock' failed with 0x80010002 : CELL_EINVAL [x10502]
E SYS: Stat: 'cellSaveDataAutoLoad2' failed with 0x8002b401 : CELL_SAVEDATA_ERROR_CBRESULT [x4]
E SYS: Stat: 'sys_vm_lock' failed with 0x80010002 : CELL_EINVAL [x8450]
E SYS: Stat: 'sys_vm_unlock' failed with 0x80010002 : CELL_EINVAL [x9321]
E SYS: Stat: 'sys_vm_unlock' failed with 0x80010002 : CELL_EINVAL [x7145]

**Comment by Megamouse** [comment]
If no one is gonna provide a proper log then this issue will be closed soon

**Comment by Guerdem** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7542617/RPCS3.log.gz)

**Comment by mogwaimon** [comment]
I would also like to chime in and say that this issue also happens on Sengoku Basara 3 Samurai Heroes (MRTC00005) as well. Here's my log file from the last time I played using the latest version of RPCS3, but the bug was also present on RPCS3 0.0.18-12953-78bcb0fd Alpha as well.

It does seem that as of version 0.0.19-13055 at least, that the audio stopping still causes a delay with the event progression but no longer leads to an immediate full softlock as it did in the earlier version. Instead, the audio cuts out far more often than in the previous version listed above and the softlock seems to happen when the game progresses to the save screen at the end of the level rather than in the middle of the level. Please find my log attached below

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/7612809/RPCS3.log.gz)

As for my system specs, I'm running an i7 10700k CPU, GTX 1080Ti GPU (driver 471.11, I know it's old but another game I plan to play has issues on the latest driver so I haven't updated yet) , 32GB of RAM, and runs Win 10 Home 64-bit edition.

**Comment by Iifriet** [comment]
I encountered this issue in Sengoku Basara: Samurai Heroes. The music would stop playing and about 30 seconds later the game would crash. Changing the SPU  to interpreter precise(fast) fixes it, albeit with obvious performance issues.

**Comment by indra-constantine** [comment]
https://github.com/indra-constantine/basara4sumeragifix

**Comment by Iifriet** [comment]
> https://github.com/indra-constantine/basara4sumeragifix

What does this do exactly?

**Comment by MSuih** [comment]
We have pretty much no way to know. It's random executable so when ran it can do anything that's possible on rpcs3. In theory it can also escape from emulator and do anything to your system. Or it could just be changes to couple of bytes which cause this issue.

It'd be best to submit binary changes as patches so that user does not need to replace any files, and also it'd be easier to know what exactly is changed.

**Comment by jihyosbandana** [comment]
I just downloaded the "fix" ZIP, it's an eboot.bin file inside, I'm pretty sure it's modded and modified in some way, I'll play test tomorrow and see if the error still occurs.

**Comment by RipleyTom** [comment]
It's a modified executable of the BLJ version 1.02, did a comparison and all it changes are:
changes 2 strings:
```
< ゲームを終了して、戦国BASARA4 皇 のゲームデータの削除を行ってください。Game data is corrupted.
< Please exit the game and delete ○○○○○○○ game data.Les donnees de jeu sont corrompues.
---
> ゲームを終了して、戦国BASARA4 皇 のゲームデータの削除を行ってください。Data Game korup/rusak. 
> Keluar dari game dan hapus file ○○○○○○○ data game.Les donnees de jeu sont corrompues.
```

Also changes one byte that changes the sdk version used in one elf section header.
That change has literally no effect on rpcs3 behaviour.

Basically this fixes nothing.

**Comment by jihyosbandana** [comment]
So it just changes a few strings and that's it? What was even the point of that "fix" 🤦‍♂️

**Comment by indra-constantine** [comment]
To be honest but its work for me & for my tester too in my discord btw

**Comment by indra-constantine** [comment]
You wouldn't know if you hadn't tried.

**Comment by indra-constantine** [comment]
Gameplay https://www.youtube.com/watch?v=2L8TbuxW5rI

**Comment by indra-constantine** [comment]
even I have lower hardware than the one above

**Comment by indra-constantine** [comment]
Nevermind my fix only for BLJM61248 not BLJM61063

**Comment by AniLeo** [comment]
Stop spamming

**Comment by indra-constantine** [comment]
Try this setting https://github.com/indra-constantine/basara4sumeragifix/releases/tag/basara4sumeragifix

**Comment by Megamouse** [comment]
Please try again with the latest version

**Comment by Iifriet** [comment]
Just completed a mission and didn't have any audio cutting out or crashing issues.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8546228/RPCS3.log.gz)
.

**Comment by Megamouse** [comment]
Let's assume it's fixed then

**Comment by aethral** [comment]
Far from fixed, I have same issue still.

**Comment by Guerdem** [comment]
It's not fixed, it still happens in the latest build.

[RPCS3-S.log.gz](https://github.com/RPCS3/rpcs3/files/9085435/RPCS3-S.log.gz)
[RPCS3-M.log.gz](https://github.com/RPCS3/rpcs3/files/9085434/RPCS3-M.log.gz)
[RPCS3-L.log.gz](https://github.com/RPCS3/rpcs3/files/9085432/RPCS3-L.log.gz)

**Comment by Guerdem** [comment]
RPCS3 v0.0.23-13909-e548743c Alpha | master 
new logs
[RPCS3-L.log.gz](https://github.com/RPCS3/rpcs3/files/9115728/RPCS3-L.log.gz)
[RPCS3-S.log.gz](https://github.com/RPCS3/rpcs3/files/9115729/RPCS3-S.log.gz)

**Comment by Guerdem** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10078274/RPCS3.log.gz)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10078356/RPCS3.log.gz) 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10078411/RPCS3.log.gz)
