### ISSUE TITLE
[Feature Request] Config GUI Size and General application scaling

### ISSUE THREAD

**Issue by Chaython** [RPCS3/rpcs3#10679]
## Quick summary
There should be an option to increase the settings window size / RPCS3 font / GUI size.

## Details
I find details hard to read on a 4k panel... The advanced tab is much hidden by scrollbar/overflow. Such things would be fixed with a setting to stretch the settings app/GUi. Using native windows scaler to enlarge all apps, causes issues with some games & apps[unrelated to RPCS3]. Making an in-app scaler important. 

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* UI

#### Please include.

**Comment by VelocityRa** [comment]
> Using native windows scaler to enlarge all apps, causes issues with some games & apps[unrelated to RPCS3].

If you mean that things look smudgy, the solution is to right click the app -> Properties -> Compatibility -> Change high DPI settings -> Override high DPI scaling override -> Application.

It's annoying that you have to do this though. RPCS3 can/should actually make Windows default to this (it's some winapi call, I don't recall which).

**Comment by Chaython** [comment]
> If you mean that things look smudgy, the solution is to right click the app -> Properties -> Compatibility -> Change high DPI settings -> Override high DPI scaling override -> Application.

Native scaler can cause some games to run off screen, break some games edge scrolling, cause blurry text, break borderless window/causes the game to render off axis.
As stated it's unrelated to RPCS3, I'm just unwilling to use windows scaling as there's too many incompatible apps.
Anyways setting custom scaling in windows didn't effect font size in RPCS3 settings...

**Comment by Darkhost1999** [comment]
From my testing. Change high DPI scaling properties has no effect on anything does absolutely nothing for every single application I've ever tried.
And the only "issue" with RPCS3 scaling on my 4k TV is needing to resize the pads window to hit the save button.
So the very first time I setup my controller was like "there is no save button" then people sent pictures of their 100% windows scaled screens.
But all Fonts and Interfaces are fully legible with clear to read and accurately scaled appearances.

**Comment by Chaython** [comment]
It's legible, but it's uncomfortable. The description of setting is size 8 font.
As per windows "recommended" scaling it's 150%.
Which would be size 12 font for a 4k screen.
10 is comfortable 12 is great.
The settings panel has no option to stretch, no option to change font scaling.
I was saying it would also be good to allow stretching, so there's no overflow in advanced.
...
Image from POV
![NjA81kvolYL69y3IVLdvY0E5JR7GbBV-IshAuN_vBzm6qdshHi6wqV0AICJdhwTiQWpnnn3eDP3s9Hz9Rfo6smRCkVDhksDJLrNxI_88SYK6_3xTl1hqKdW8Sm-tiM9slsQXGarB5tzh9M7q3wqDssyMfRGc2PEuWRhTzXgE50Jnfbd7h6EAiNT6Y8V-SQR0oHILWxcfVCeG8CoEG](https://user-images.githubusercontent.com/6486343/128630478-8df6ca19-337f-4420-be6e-ca2eb12d2dbd.jpg)
It's hard to convey human eyes perspective from a cellphone camera, impossible to reference in a screenshot.

**Comment by Megamouse** [comment]
> > Using native windows scaler to enlarge all apps, causes issues with some games & apps[unrelated to RPCS3].
> 
> If you mean that things look smudgy, the solution is to right click the app -> Properties -> Compatibility -> Change high DPI settings -> Override high DPI scaling override -> Application.
> 
> But yeah, it's annoying that you have to do this.
> RPCS3 can/should actually [make Windows default to this](https://docs.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process).

We don't do this as it's:
A: worse than the regular scaling. You may remember the argument we had with Zang and Ruipin.
B: it shouldn't make a difference if the user doesn't scale anyways.

Therefore we simply use the Qt auto scaling.
I'm not on a PC right now but iirc there are already cli options for that.

I don't see why setting it manually for rpcs3 wouldn't work. The user probably didn't logout and back in after changing it.

To me this is simply a user issue with windows and handled properly by us by now.

**Comment by lextra2** [comment]
> > If you mean that things look smudgy, the solution is to right click the app -> Properties -> Compatibility -> Change high DPI settings -> Override high DPI scaling override -> Application.
> 
> Native scaler can cause some games to run off screen, break some games edge scrolling, cause blurry text, break borderless window/causes the game to render off axis.
> As stated it's unrelated to RPCS3, I'm just unwilling to use windows scaling as there's too many incompatible apps.
> Anyways setting custom scaling in windows didn't effect font size in RPCS3 settings...

If you do the fix he mentioned, any game simply ignores the windows DPI settings. It is also what steam sets by default for all games. Sounds like a "You" issue. I'm too using rpcs3 on a 4K tv, and 300% dpi works just fine.

**Comment by lextra2** [comment]
> From my testing. Change high DPI scaling properties has no effect on anything does absolutely nothing for every single application I've ever tried.
> And the only "issue" with RPCS3 scaling on my 4k TV is needing to resize the pads window to hit the save button.
> So the very first time I setup my controller was like "there is no save button" then people sent pictures of their 100% windows scaled screens.
> But all Fonts and Interfaces are fully legible with clear to read and accurately scaled appearances.
> (Maybe some pictures/screenshots can illustrate the OP's issues)

Well you mustn't have used many apps then, because I have plenty that need to manually be tweakee via those settings.

**Comment by dio-gh** [comment]
So you're expecting RPCS3 to implement an end-to-end UI scaling solution because Windows' DPI scaling works suboptimally for you in some odd cases? You'd rather have every userland application write their own UI scaling facilities that you have to configure one-by-one, than expecting Microsoft to fix their scaling issues with their WM?

I've also never had an issue with blurry apps, maybe you didn't configure DPI scaling correctly? It's a bit counter-intuitive, but to get correct scaling, you have to not only set it in the dropdown.. (see below)

![image](https://user-images.githubusercontent.com/10439488/128648095-c16b5233-68d3-41d0-b385-ba9a0985545b.png)

.. but also in the "Custom scaling" settings right under. It'll ask you to type in your desired custom scaling; you're to just type in the same thing there that you selected in the drop down (in your case, that should be 150).

This should fix all the blurry text issues. I didn't experience your other listed issues, though I don't really play games on the screen where I have to scale.

In general, I disagree with this request.

**Comment by Megamouse** [comment]
I'll close this since
A: it's clearly not our problem
B: A bunch of solutions have been provided
C: it's not really feasible to implement

**Comment by VelocityRa** [comment]
To be clear, blurriness with Windows' scaling happens, and it is _very_ ugly in some cases.
Maybe it doesn't happen for simpler set ups, bit In my case I have 2 monitors, one 4k primary one at 150% and one at 1080p 100%.

And yes, it is up to applications to include proper support for this. There are many levels of support that they can report to the OS like "Unaware", "System aware", "Per-monitor aware", etc (see the MSN article I already linked: https://docs.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process)

RPCS3 seems to only be System aware, not Per monitor. Which means that for set ups like mine you either get the awful smudgy scaling, or if you do the force Application workaround, you can _only_ get it to look fine for the primary monitor. If I move it to the other 1080p 100% monitor, it looks gigantic (since the workarounds basically leaves it up to the app to re-adjust, which it doesn't, so it remains scaled to 150%).

This issue was not well described in the OP itself though... or it's different issue. So you can keep this closed. But there are definitely still issues with scaling in RPCS3, as mentioned. To deal with this I currently just never use RPCS3 (the GUI, not gsframe) on my secondary monitor.

**Comment by Megamouse** [comment]
You can try
--platform windows:dpiawareness=[0|1|2]
Where 2 should be per monitor.
I don't know if it works.

**Comment by VelocityRa** [comment]
@Megamouse Huh, I removed the override to test this, and it looks like it works even without the option you mentioned now.
Must have been fixed with a Qt update at some point.
