### ISSUE TITLE
Cmake can't find the LLMV jit library when compiled against the latest (3.6.0) llvm package on gentoo

### ISSUE THREAD

**Issue by Putrefalcis** [RPCS3/rpcs3#1070]
`CMake Error at llvm/cmake/modules/llvm-config.cmake:143 (message):`
`Library ```jit' not found in list of llvm library`

Compiles just fine with llmv 3.5.0 though.

If this is working as intended, perhaps the dependency section of the README could reflect the need for a specific LLVM version

**Comment by Syphurith** [comment]
@Putrefalcis What? Travis builds (Linux) with 3.6.0 specified seem just fine. Maybe that is a problem related to gentoo builds. You may build it yourself a later version of LLVM with CMake.

**Comment by Syphurith** [comment]
@Putrefalcis Well i got the same error when i tried to build it with debian. After checks i found out the distributed debs don't have a `LLVMJIT` library `so`. There isn't any problem with Ubuntu as mentioned above. Even from the same website that offers nightly builds it caused trouble.
For me i suggest you to build LLVM yourself, that would get yourself the library.

**Comment by Syphurith** [comment]
@Putrefalcis In short you would have to build llvm binary yourself for the `libLLVMJIT.so` which is not always included in distributed packages. And for clang you would have to get one not lower than 3.6.

**Comment by Putrefalcis** [comment]
Thanks, I'll do that.

**Comment by Syphurith** [comment]
@Putrefalcis If you would like to build it, you can just clone llvm into `rpcs3/llvm` directory.
Then follow `.travis.yml`, change to `llvm_build` folder, do:
`cmake -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_BUILD_RUNTIME=OFF -DLLVM_BUILD_TOOLS=OFF -DLLVM_INCLUDE_DOCS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF -DLLVM_INCLUDE_TOOLS=OFF -DLLVM_INCLUDE_UTILS=OFF -DWITH_POLLY=OFF ../llvm`
then `make` then `make install`.
That is a optimized version of llvm build script just for rpcs3.
If you may need llvm for your other projects, you may follow tutorials from web, doing a full build.

**Comment by Syphurith** [comment]
@Putrefalcis I've given up trying to deal with this.. At least on Debian. Read the `.travis.yml` to get working operations i think that is a bug of llvm packages. If you succeded using manually compiled version of llvm which may include non-static version of binary, or others ways at last, please do not hesitate to update the build instructions on `README.md`.
If you could want a few steps further, please run `valgrind` with arguments `--tool=memcheck --leak-check=all --show-leak-kinds=all --track-origins=yes` to launch rpcs3, pick a few elfs from the test folder `dev_hdd0/game/TEST12345/USRDIR` to see if there is any memory leaks that easy to be detected, and talk about the log with others..
Good luck.

**Comment by Putrefalcis** [comment]
While I tinker around with this, could it have something to do with the old implementation of jit being removed from LLVM for versions >3.5.0? More info in the link below:

http://article.gmane.org/gmane.comp.compilers.llvm.devel/75175

**Comment by Syphurith** [comment]
@Putrefalcis Well that seems to be related to the problem. ~~Ubuntu installed~~

**Comment by Syphurith** [comment]
@Putrefalcis Finally linked rpcs3 on Xubuntu vivid recently. Unfortunately some changes needed:
* build LLVM directory according to `.travis.yml` even you've installed llvm-dev
* install zlib-dev
* comment some lines which included `kX86CpuFeatureSSE4_1` since not all ones have such macro. **Even you can find sse4 or similar when `cat /proc/cpuinfo`.**
* on Linux you would have to edit `vm.cpp` to use `rpcs3_vm` not `/rpcs3_vm`. Maybe on MacOSX that is ok, but if you shm_open /rpcs3_vm it would just fail (at least for me).

Well rpcs3 linking is slow, and its debug version almost 250MB+.
I ran valgrind for it and get plenty of errors and warnings, some of those from wx yup.
Cause i installed it on a VM, and currently something wrong with my 3D accel.
Hope you could build it successfully sometime later.

@Bigpet Eh.. I may upload the valgrind log sometime after. But i hope someone could build a DEBUG version of rpcs3 on Linux and run it again if that is not on a VM.

**Comment by vlj** [comment]
I got llvm 3.6 working on rpcs3 with the d3d12-rebase branch, unfortunatly it doesnt build with VS2013 (apparently VS2013 type inference for templates conflicts with the vm_ptr templates but it does work with VS2015).

**Comment by vlj** [comment]
likely fixed

**Comment by danilaml** [comment]
It is fixed (see travis). lvvm >3.5 didn't include jit (deprecated). Now we use mcjit.

**Comment by tambry** [comment]
@Putrefalcis Is this fixed?

**Comment by tambry** [comment]
Probably irrelevant.
