### ISSUE TITLE
MGS2: Crash right when credits roll

### ISSUE THREAD

**Issue by BoukObelisk** [RPCS3/rpcs3#10803]
The game crashes right when the credits start rolling at the end. Otherwise flawless playthrough. 

On RPCS3 Version: 0.0.17-12698-43cc62d2 Alpha

Link to log https://mega.nz/file/qH4RnSQI#5sdIU-7TruO77CNIQQOnCMQ0sghevhj8OT641vuJvFs

**Comment by Asinin3** [comment]
Please upload a save file for us to reproduce the crash, and also retest to make sure it's still happening.

**Comment by Darkhost1999** [comment]
Do you think LLE Libvdec could help this game like it helped Kingdom hearts?

**Comment by delcake** [comment]
Ran in to this issue on my playthrough using RPCS3 Version: 0.0.22-13800-42627946 Alpha.

Here's a save file directly at the final boss fight for testing: [BLUS30847_MGS2000G002.zip](https://github.com/RPCS3/rpcs3/files/8936608/BLUS30847_MGS2000G002.zip)

I crashed three out of four attempts once the staff roll began without making any config changes, but so far I've succeeded four out of four attempts with LLE libvdec set. Maybe not enough to say a crash won't ever happen, but it's looking a lot more reliable so far from my quick testing.

**Comment by Darkhost1999** [comment]
Thanks for testing most likely an HLE issue then. And can be solved when the cause is found.

**Comment by Jonathan44062** [comment]
Still an issue, just finishing the game and crashes when the credits were just beginning
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8986011/RPCS3.log.gz)

**Comment by austin-millan** [comment]
@Jonathan44062  I just tested about a dozen configurations at the boss/credits part of the game... Surprisingly though, the only thing that seems to reliably work is to put the game into windowed mode and then minimize it before it gets to the credits, I just did it twice, right after skipping through all the skippable cut-scenes, and I was able to make it to the very end (no freeze/crash).

If this doesn't work, maybe following my below configuration will:

```
CPU:
- PPU Decoder: LLVM
- SPU Decoder: LLVM
- TSX Instructions: Disabled (my CPU doesn't support it)

GPU:
- Renderer: Vulkan
- Anti-Aliasing: Disabled
- Default Resolution: 1280x720
- Disable Vertex Cache
- (Optional?) Resolution Scale: 300% (for 4K monitor)

Advanced:
- Firmware Libraries: libvdec.sprx 
- (Optional?) I left unchecked "Read Color buffers", which goes against compatibility recommendations [here](https://wiki.rpcs3.net/index.php?title=Metal_Gear_Solid_HD_Collection).
```

Good luck.

**Comment by Jonathan44062** [comment]
Well, someone said it happens in hardware too, even it is in the speedrun category

https://www.youtube.com/watch?v=VSAurnFNUAk <- 1:01:57

https://www.youtube.com/watch?v=vkeKPVE8Waw

If you read the comments, it happen for everyone too
If that happens in the real PS3 console, then, there's no fix

**Comment by delcake** [comment]
> If you read the comments, it happen for everyone too If that happens in the real PS3 console, then, there's no fix

While I agree that means this might not ever be resolved completely, I'm still curious as to why it would be so much more common when emulated compared to playing on a physical PS3. What counts as "solved" for this issue might just be bringing crash rates in line with real hardware.

I'm also interested in the speculation of one of those Youtube comments about whether this credits crash might be due to playing the physical version of the game instead of the digital. Learning the speedrun for this game is how I came across this problem to begin with, but for my part I play the digital version on an OG fat PS3 and haven't experienced any credit scene crashes on that setup yet.

**Comment by RainbowCookie32** [comment]
> I'm still curious as to why it would be so much more common when emulated compared to playing on a physical PS3.

Real HW doesn't have all the emulation overhead, *is* the targeted platform, and has pretty good (if not basically perfect) run-to-run consistency. On an emulator, stuff that usually just barely happens to work fine on a console because of its consistency tends to break or be more unreliable. *End credits* having issues like this is a bit cursed, but game devs can be pretty creative sometimes

**Comment by z411** [comment]
Someone in Reddit posted this (https://www.reddit.com/r/metalgearsolid/comments/pd84qz/mgs_2_credits_freeze_the_revengence/) regarding the credits freeze on a real console:

> So, after years I finally decided to replay MGS2 and platinum it. But, I saw from an old thread that the PS3 version keeps crashing on the credits. This unfortunately also happened to me. Now, that thread is locked and can't be posted to anymore, but I am here to say that I just found the solution. All you have to do is in your system settings disable "trophy notifications" and I also turned off the other message notifications also. Credits played all the way through - no freezing at all. I hope this helps at least someone!

Apparently some behavior related to the trophy notifications is causing the freeze. Can this fix be replicated in the emulator? I sadly don't have a save right now to test.

**Comment by delcake** [comment]
Great find! I've done some quick testing on my end with trophy notifications disabled in RPCS3 (and without LLE libvdec set, which we tested earlier) and so far I've made it through the credits on each of my four attempts.

**Comment by z411** [comment]
It could be the console model, and I've also heard this only happens in the BD version (as opposed to digital) of the HD collection. Also I think you need to enable trophies before starting the game with the triangle button at the difficulty selection screen, not sure if that makes any difference. Either way it could be unrelated but since it happens in the credits there's at least something weird happening in the original game code. I just got myself a copy and I'll try it on my PS3 soon.

**Comment by ddubs13** [comment]
I want to update this by saying I had turned Show Trophy Popups off, but the credits still crashed for me. I didn't try to recreate it.

**Comment by Darkhost1999** [comment]
There's some good news and some bad news and they're actually the same news.

This issue has discussions 9 years old scattered across forums about this happening on real console too. Discussions of disabling trophy messages and other messages on real hardware is the solution while others have said just leaving their console off for several hours and coming back later fixes the issue.

Essentially this is a game bug and happens on real hardware as well.

**Comment by z411** [comment]
Not surprising considering the HD collection has other bugs like long delays inbetween codec conversations in MGS2 or the extremely laggy final boss fight in MGS3 (all of which happen both in real consoles and in the emulator).

**Comment by JaskaRoman** [comment]
I experience the crash roughly half of my runs on a unmoded PAL fat PS3 (CECH 04) with a random 2.5" SSD a with a BD copy of the game (BLUS30847). Feels loading related, I can hear the BD drive seek on a successful playthroughs in the part where it otherwise crashes.

**Comment by elad335** [comment]
Not an emulator bug it seems.
