### ISSUE TITLE
[Feature Request] Automatic game list updates

### ISSUE THREAD

**Issue by DoganM95** [RPCS3/rpcs3#11123]
## Quick summary
Function to automatically check for new games periodically (e.g. every 10 seconds) by defining folders which hold games.

## Details
For example i have a folder containing all my games, like `TEKKEN 6 - (BLES00635)[EUR]`. Whenever i add a new game to the folder of games, i have to click on File -> Add Games choose the parent folder, so it refreshes my games list and adds the new games to the library. This should happen automatically, by letting the user define a list of folders, containing ps3-game-folders (like `TEKKEN 6 - ...`) and periodically check/poll for new games in that folder, to add them automatically.

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* Installation

#### 2. Please tell us, why your feature is important to RPCS3.
Automates an unnecessarily manual (and thus annoying) process

#### 4. Please provide your system configuration:
Irrelevant for this feature request

**Comment by DrEVILish** [comment]
Alternative instead of Automatically updating, having a GUI button on the dashboard "Refresh Games" would search any preAdded folder directories that contain a game disc and add them to the list.

**Comment by Megamouse** [comment]
I think this can be closed.
There's a refresh button in the UI and we also have a games folder (also as VFS path) that will be searched for disc games.

Adding periodic updates is suboptimal, since it can take a long time to do this depending on your system and it only adds unnecessary DISK and CPU usage for the off-chance that the user copied some file into the folder.
