### ISSUE TITLE
Last Of Us Flashlight Light Bounce

### ISSUE THREAD

**Issue by Antonio1994** [RPCS3/rpcs3#11208]
Flashlight light bounce does not work.

I am sorry if the issue has been mentioned but cant seem to find it. There is a nice effect in the ps3/ps4 version of the game where your flashlight light bounces from the walls and objects casting the color of the wall/object. I cant replicate the effect on rpcs3(updated to the latest version). I tried many settings with Color Buffers and Depth Buffers and without patches and it does not work.

![bandicam 2021-11-27 18-48-13-776](https://user-images.githubusercontent.com/4595014/143732422-66f4f0ea-3256-4d47-94c5-66849608d7b0.jpg)
![bandicam 2021-11-27 18-51-00-575](https://user-images.githubusercontent.com/4595014/143732423-6ec059f0-b2be-49a1-8d44-b84ab9e6674d.jpg)
![bandicam 2021-11-28 07-37-36-194](https://user-images.githubusercontent.com/4595014/143732424-dc2003fa-6263-40bc-8c2f-bc24fc9242a7.jpg)
Win 10
GTX 1650
 Ryzen 5 3600

**Comment by Xcedf** [comment]
@Antonio1994  This issue is a patch issue, you can disable GPU Lighting patch and you'll see this blueish bounce you're talking about, but of course SPU lighting is broken for now
![image](https://user-images.githubusercontent.com/7060586/143764897-d532acbc-df65-4fa4-812c-b22c1043caaa.png)
And since it's a patch issue, it should be closed
