### ISSUE TITLE
Prevent RPCS3 from running from temporary directories

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#11236]
A lot of people unadvertised run RPCS3 from temporary directories and then complain that their data (obviously) disappeared. 

RPCS3 should not run, and error out, when it's being ran from `%TEMP%` (`C:\Temp\` or `%APPDATA%\Local\Temp`, for example), `/tmp` on Unix

**Comment by orbea** [comment]
Running a program in /tmp/ might be useful for testing changes where there is no need to keep the binary long term.

**Comment by Asinin3** [comment]
@orbea  I haven't heard a single one of our testers doing that and I've been an active tester since 2017 and active in our community.

The biggest issue is the winrar temporary directory as people don't extract files properly and then come asking for help. Luckily other archival software doesn't create temporary directories like it does. Otherwise though, I haven't really seen people using temporary folders.
