### ISSUE TITLE
Would it be possible to use GitHub releases instead of RapidGator?

### ISSUE THREAD

**Issue by voltagex** [RPCS3/rpcs3#1125]

**Comment by tambry** [comment]
@voltagex This is in no way handled by rpcs3's team, but rather the EmuNewz's crew. You have to contact them, if you want to convince them to change. Here's a thread about RapidGator on forums: http://www.emunewz.net/forum/showthread.php?tid=168362

**Comment by voltagex** [comment]
Understood, thanks.

@voltagex <https://github.com/voltagex> This is in no way handled by
rpcs3's team, but rather the EmuNewz's crew. You have to contact them, if
you want to convince them to change. Here's a thread about RapidGator on
forums: http://www.emunewz.net/forum/showthread.php?tid=168362

—
Reply to this email directly or view it on GitHub
<https://github.com/RPCS3/rpcs3/issues/1125#issuecomment-115109361>.

**Comment by Bigpet** [comment]
@voltagex I can try to maintain some builds on github here: https://github.com/Bigpet/rpcs3/releases

but I don't think it's a good idea to make frequent builds on the main repository, because each "release" adds a tag to the actually git repository.

I'll try to see if I'll upload llvm builds, it's currently just non-llvm
