### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by vgturtle127** [RPCS3/rpcs3#1134]
First off, is this site owned by you guys?

http://rpcs3.net/

It seems kind of fishy, so I didn't think it was affiliated. If not, we should probably denounce it publicly so people know.

Also, I heard that code was committed that was just "PS Vita emulation added" or something of that effect. Did you guys mean that you are implementing certain PS Vita features, like adding PSP/PS1/PS2 emulation features just like the actual PS3 hardware, or are you guys actually adding PS Vita emulation eventually? I know that seems like it would be a silly thing to ask, but you know, stranger things have happened...

I started to write stuff for the Vita, but I wanted to ask in case you guys have stuff I don't.

Any help would be appreciated as always. :smile: 

PS - If that website isn't real, we should steal that logo, it doesn't look too bad. Just switch the R around. :smirk:

**Comment by tambry** [comment]
@vgturtle127 I suggest you pop into our IRC channel sometimes. It's #RPCS3 on EFNET.

Also AFAIK, that website is (kinda) official, but you might want to check with @AlexAltea or someone else from the forums to see who is currently maintaining it. Also, we can't simply steal the logo, since it falls under copyright.

**Comment by AlexAltea** [comment]
That website is being managed by *shadow*, who also runs EmuNewz. If the contents look fishy or just too non-technical probably is due to the lack of communication between him and the current developers.

Regarding PSvita emulation, an ARMv7 interpreter and high-level emulation of certain PSvita system libraries was added a long time ago. You can follow that at rpcs3/Emu/ARMv7/. Although it can run a couple of "Hello World!" tests, it's definitely way too early to call that "*PSvita emulation*".

Just one disclaimer: This was the status last year. I have been since unrelated to the project so I'm not really aware whether there have been any other changes.

**Comment by vgturtle127** [comment]
I would go to IRC, but I'm currently using a mobile device. And mobile IRC clients are kind of...not at all usable.

Good to know about the website, though.

"it falls under copyright"

Ironic. :laughing: 

@AlexAltea Emulation of even a single line of code is still emulation. :smile: 

Good to know, I will check that out. Thanks guys!

Is there a chance the website could be open-sourced or maybe we could somehow contribute?

**Comment by Nekotekina** [comment]
Hi, are you interested in Vita emulation?

**Comment by vgturtle127** [comment]
I think everybody would be?

**Comment by Nekotekina** [comment]
I mean rather contributing, do you run your own project, or you thought about working on rpcs3? I probably misunderstood. There are long-term plans about Vita emulation, but there is no significant progress currently.

**Comment by vgturtle127** [comment]
What I was thinking of (in the long term, anyway), was creating my own set of emulators. But also as I modify specific emulators to meet my needs, contribute to the projects that I am modifying.

So I would be forking RPCS3, creating my own PS3 emulator, and then also contributing to RPCS3. And also I may use the Vita emulation in RPCS3 in tandem with PPSSPP's Vita stuff to try and create a stand-alone Vita emulator. All very alpha, though.

**Comment by vgturtle127** [comment]
I suppose I can close this, as the issues have been "resolved".
