### ISSUE TITLE
rsx/vk: Broken shadows on NieR Replicant

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#11350]
This issue is specific to Vulkan, and doesn't seem to happen on all drivers. As such, I'm tagging this with the RADV tag.

How to reproduce:
- Boot NieR Replicant with default settings and Write Color Buffers
- Select New Game
- Don't skip the initial cutscene, wait around 1 minute for it to get to the frame displayed below

Reproduced on: `RPCS3 v0.0.20-13156-1adc408a`, `mesa 21.3.2`, RDNA2 on RADV

### Vulkan (RADV)
![Screenshot from 2022-01-10 07-35-54](https://user-images.githubusercontent.com/10283761/148732304-70b6ccaa-4a4f-480b-83db-05734cfcd1ea.png)

### OpenGL (RadeonSI)
![Screenshot from 2022-01-10 07-42-33](https://user-images.githubusercontent.com/10283761/148732337-c118e28a-8f19-4ed3-a76a-3baa8633db50.png)

RSX Capture: [NieR.zip](https://github.com/RPCS3/rpcs3/files/7837381/NieR.zip)
- Rename from NieR.zip to NieR.7z;
- The RSX Capture will throw a device lost exception if replayed on Vulkan, and also log validation layer errors if Debug Output is enabled;
- The RSX Capture will replay on OpenGL but show broken graphics as shown on the Vulkan screenshot above. If playing the game itself on OpenGL, the issue will not occur, as shown on the OpenGL screenshot above;

**Comment by kd-11** [comment]
Incompatibility between AMD fp16 (rapid packed math) vs RSX's implementation of fp16. Investigating a workaround.

**Comment by kd-11** [comment]
Tested AMD windows driver - no issue. NV driver has some minor glitching only.
I'll have to investigate why only RADV has a big problem with this.

**Comment by AniLeo** [comment]
Retested and still present on `RPCS3 v0.0.22-13565-1cab99b3 Alpha` and `mesa 22.0.2`

**Comment by dkeruza-neo** [comment]
I have a similar problem with TLOF. I am in Arch Linux and AMD 6700s GPU.
Didn't happen to me before with an nVidia GPU
I uploaded some pics and I also have a video but does no let me upload it because is to big.

![BCES01584_screenshot_2022_06_28_00_55_48](https://user-images.githubusercontent.com/16725214/176336084-1b0b671c-a8dd-47c0-93fe-ca6a8dcb6bc7.png)
![BCES01584_screenshot_2022_06_28_00_56_04](https://user-images.githubusercontent.com/16725214/176336086-b846b8cb-c923-451e-b174-42825b418c09.png)
.

**Comment by kd-11** [comment]
Flagging for the next bugfix cycle.
