### ISSUE TITLE
Softoal.dll not found, and nothing is solving the issue.

### ISSUE THREAD

**Issue by MisterHubs** [RPCS3/rpcs3#1143]
I have the correct dependencies:

![3](https://cloud.githubusercontent.com/assets/13189357/8661282/8aa3cb12-2984-11e5-8027-cd1b9aec8a4b.jpg)

I tried downloading the DLL manually, but it's 32-bit only and it gives this issue:
![2](https://cloud.githubusercontent.com/assets/13189357/8661292/9e425b34-2984-11e5-9bb1-fafea9db514c.jpg)

I tried System32 and no difference.

Without it, after unpacking, it just shows this error message:

![1](https://cloud.githubusercontent.com/assets/13189357/8661305/af4a445a-2984-11e5-9046-bab3fa0dfafd.jpg)

So I did as it said, reinstalled it, and nothing changed. This is the latest auto-build running on Windows 7 Home Premium 64-bit. Some recent builds worked just fine though, so I'm wondering what the issue is.

I downloaded it from the auto-builds section page of these forums from RapidGator.

I know I could've asked this in the forums, but this is just a quick conundrum.

**Comment by Bigpet** [comment]
Yeah, this is something for the forums. The people making the RapidGator builds are on the forums. 

I started automatically compiling and uploading some of the recent builds to github here: https://github.com/bigpet/rpcs3/releases (didn't use the main Github page because doing a "release" adds a tag, that we don't need and would just spam the tag-list)

**Comment by MisterHubs** [comment]
@Bigpet Thanks! The latest builds from Github are working perfectly.
