### ISSUE TITLE
Bug: Ratchet & Clank: Into the Nexus emulator crash in certain areas of the game

### ISSUE THREAD

**Issue by nitroos-ai** [RPCS3/rpcs3#11495]
## Quick summary
In the game "Ratchet & Clank: Into the Nexus" and specifically in the "PLANET YEREK : Meero Ruins" the game triggers a lot of RSX errors and eventually crashes the game.

## Details

The errors are: `·E 0:05:18.023823 {RSX [0x445d070]} RSX: [Performance warning] Texture gather routine encountered too many objects! Operation=3, Mipmaps=1, Depth=6, Sections=20, Ratio=800%`

`·E 0:05:18.024113 {RSX [0x445d070]} RSX: Stale surface at address 0xc1ae8180 will be deleted`

#### 0. Make sure you're running with settings as close to default as possible
Modified settings are:

TSX: Forced
PPU Decoder: Interpreter
ZCULL Accuracy: Approximate
Use GPU texture scaling: true
Read Color Buffers: true

#### 1. Please attach RPCS3's log.

[Rpcs3_latest._Master.log.zip](https://github.com/RPCS3/rpcs3/files/8010686/Rpcs3_latest._Master.log.zip)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.

PC too weak for RSX capture
#### 3. Please attach screenshots of your problem.

![Nexus](https://user-images.githubusercontent.com/68450737/152694122-48ccabf4-04e1-476d-bf6c-1fdcee089c06.jpg)
![Nexus](https://user-images.githubusercontent.com/68450737/152694444-402505e4-c3d7-4535-8091-2e49fe7681a8.png)

#### 5. Please provide your system configuration:
* OS:   Lubuntu 20.04
* CPU: intel core i5-4590
* GPU: Nvidia GTX 1070 ti
* Driver version: 495.46-0ubuntu0.20.04.1
* etc.

#### Please include.
* Anything else you deem to be important

**Comment by kd-11** [comment]
To clarify - these are performance warnings. They do not cause crashes, they are warnings about severe performance degradation. I tried to reproduce this for about an hour, but couldn't get it to happen with gdb attached. In a free process, I got a crash after about a half hour mentioning a detected heap corruption but ofc without a debugger, this is not useful information. This may have the same root cause as https://github.com/RPCS3/rpcs3/issues/11435
