### ISSUE TITLE
[Feature Request] Change xfloat accuracy to a drop-down

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#11523]
Rather than two tick boxes (accurate and approximate xfloat) and have users confused when you tell them to use relaxed xfloat when no setting exists for it (it refers to having approximate and accurate turned off) we really need to switch to a drop-down like this but change Loose to Relaxed:
![image](https://user-images.githubusercontent.com/15137035/153741869-0f1e2bb0-edbc-4308-a93e-5697a3464845.png)
This will also avoid confusion on if there is any difference between Accurate & Approximate being on vs just accurate being on.

**Comment by Darkhost1999** [comment]
I agree this feature is needed.

Information wise: I remember the conversation going there will be more than those 3 options soon. I don't know what options are thought about or planned. But I do remember reading the drop down menu will be easy to add with the new options together all in 1 PR.

**Comment by Nekotekina** [comment]
There is some misunderstanding apparently.

If there are 4 boolean options, for example, there are only 4 checkboxes.
But if you try to put all combinations into a combobox, you have 16 possible variants (power of 2). 5 become 32, etc. It would be madness, it does not scale.

**Comment by legend800** [comment]
I get that, but what combos exactly? I feel the UI needs to be reworked as current options/UI is pretty unusable/misleading IMO. That or rework the options/booleans so combos aren't a thing.

Here's what I posted in the PR:
----------------------------------------
It looks like there's 4 possible configs - Both Off, Both On, Accurate On+Approx Off, Accurate Off+Approx On. When really it's just 3: Both off (using secret Relaxed), Accurate On (Approx should be grey), Approx On (Accurate grey).

Really the dropdown above is the only way to fix. There's 3 options. Let them select it from the list instead of a mini-puzzle. Not sure why there's push back on that when there's dropdowns for almost everything.

Keep in mind this is the first thing that users see - center in first tab. It should make sense and not mislead them to think Both On is using Approx for example which I literally thought today (been using emu for 4yrs) would override Accurate - tooltip doesn't explain this at all and users will be split on what they think will happen with both checked.

The team keeps adding options to the UI, here's a change to reduce it by 1 AND simply the CX for users.

**Comment by Asinin3** [comment]
@Nekotekina At the moment, we only have two boolean options in the UI (Accurate & Approximate xfloat) and Relaxed Xfloat hidden in the config.yml

The issue at the moment is if you turn **on** Accurate Xfloat, the Approximate Xfloat option doesn't do anything when it looks like it should. And the other issue is that if you tell someone to use "relaxed xfloat" they have no idea what you mean because it's not written anywhere in the UI.

I understand your concern if approximate+accurate xfloat did something different than just accurate xfloat. But it doesn't. If this is something that would change in the future it makes sense to keep it the way it is, but otherwise this is just messy. We could even go further and have four drop-downs: Accurate, Approximate, Relaxed, Relaxed off. But that's not really necessary.

**Comment by jokoputera** [comment]
Close?

**Comment by Darkhost1999** [comment]
https://github.com/RPCS3/rpcs3/pull/11738 was merged so yes.
