### ISSUE TITLE
[enhancement] CI server?

### ISSUE THREAD

**Issue by Mstrodl** [RPCS3/rpcs3#1156]
Would it be possible for you to set up [Travis CI](http://travis-ci.org) for your linux builds? At the moment it's a pain to compile the emulator and some of the Linux n00bs may appreciate it :wink:. I believe they also support OS X compiles (hint, hint!). If not, I may be able to figure some other method out with Jenkins on my mac and linux servers.

**Comment by paulsapps** [comment]
Someone would need to provide FTP to upload the builds - I think most of the time it fails to link too. The user name and password need to be stored in secure env vars so no one can steal the creds.

**Comment by tambry** [comment]
@paulsapps It fails to link, because AFAIK, it runs out of memory.

**Comment by Mstrodl** [comment]
I can provide FTP. As for the vars you can do that too.

**Comment by danilaml** [comment]
@tambry travis was fine since we moved to llvm3.6.

**Comment by tambry** [comment]
@danilaml I guess then my message can be ignored. Striked it out.

**Comment by paulsapps** [comment]
I think encrypting the user name/password can only be done via someone who has write access to the main repo, for example of how to do uploading with secure vars see here: https://github.com/paulsapps/alive/blob/master/.travis.yml

One of the "secure" vars is the user name and another is the password, then:

- if [[ "$CXX" == "g++" && "${COVERITY_SCAN_BRANCH}" == 0 && "${COVERAGE}" == 0 ]]; then curl --ftp-create-dirs -T $fileToUpload -u $FTP_USER:$FTP_PASSWORD ftp://yourftp.com/$hash/$fileToUpload; fi

I added conditional as I only wanted to upload g++ builds rather than g++ and clang, also dont upload coverity or coverage builds.

**Comment by paulsapps** [comment]
@Mstrodl if you join IRC we could see about setting up FTP?

**Comment by Mstrodl** [comment]
@paulsapps Sorry, no irc.

**Comment by danilaml** [comment]
@Mstrodl you can use web one like mibbit or kiwirc

**Comment by Mstrodl** [comment]
I know, I just _don't do_ the IRCs

**Comment by Mstrodl** [comment]
We could exchange e-mails though

**Comment by tambry** [comment]
I guess this hasn't progressed anywhere.
