### ISSUE TITLE
The Simpsons the Game [BLES00142] - Broken Resolution Scale

### ISSUE THREAD

**Issue by tazzkiller** [RPCS3/rpcs3#11690]
InGame Engine doesn't scale to the defined resolution on GPU Resolution Scale Option (1080p / 1440p / 2160p )

Tested Build :
RPCS3 Version: 0.0.21-13371-e650d11b Alpha

Hardware Specs :
Nvidia GeForce RTX 2070
Ryzen 5 3600X
16GB of Ram
Windows 11
Xbox 360 Controller

![option](https://user-images.githubusercontent.com/171819/160121604-40a1419f-3d6f-4aca-b1d2-4e7237e4e0ea.jpg)

![InGame](https://user-images.githubusercontent.com/171819/160121653-7e900df6-6106-40e2-ba65-bcccf33fe923.jpg)

Log File: 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8350537/RPCS3.log)

**Comment by Asinin3** [comment]
Not all games can support resolution scaling with the way they work, some may require game specific hacks (patches) in order to disable inbuilt MLAA or other post processing, and some may just be outright incompatible. But either way, Resolution scaling is a hack, and we don't support people making issues about it on the issue tracker.

That being said, the overwhelming majority of games do work with resolution scaling, we generally mention if a game doesn't work with it on our wiki, and you should be looking there for what settings to use anyway. https://wiki.rpcs3.net/index.php?title=The_Simpsons_Game
