### ISSUE TITLE
Perfomance troubles in Sly trilogy

### ISSUE THREAD

**Issue by EvilPlayer1** [RPCS3/rpcs3#11802]
## Quick summary
GPU overloading and FPS drops.

## Details
In all three Sly games graphical effects like smoke, clouds and fire are causing GPU overloading and huge FPS drops.

#### 1. Please attach RPCS3's log.
Log says nothing about it.

#### 3. Please attach screenshots of your problem.
![Screenshot 2022-04-13 13-32-37](https://user-images.githubusercontent.com/90133207/163212709-751e8cca-d527-44a9-a5c7-89411289eac4.png)
![Screenshot 2022-04-13 13-32-49](https://user-images.githubusercontent.com/90133207/163212716-603b649f-5de3-4c1a-a4cb-6c4cf051b258.png)
![Screenshot 2022-04-13 14-41-28](https://user-images.githubusercontent.com/90133207/163212717-778d4a32-67e2-4511-85c0-f9453f73f0e8.png)
![Screenshot 2022-04-13 14-42-06](https://user-images.githubusercontent.com/90133207/163212719-1b2d527c-0030-4c51-a7b2-f78d56d296d3.png)
![Screenshot 2022-04-13 14-46-15](https://user-images.githubusercontent.com/90133207/163212722-2f85ab88-02e1-4b51-81be-972943803dd4.png)
![Screenshot 2022-04-13 14-46-26](https://user-images.githubusercontent.com/90133207/163212723-aca74252-19f6-4070-9d9a-dce56caa045d.png)

#### 5. Please provide your system configuration:
* OS - Windows 11
* CPU - Intel Core i7-11700
* GPU - NVIDIA GeForce GTX 1660 SUPER
* Driver version - 512.15.0.0
*  Firmware version - 4.88

**Comment by YuriNator557** [comment]
Missing log file

**Comment by EvilPlayer1** [comment]
> Missing log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8483302/RPCS3.log) - Sly 1
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8483331/RPCS3.log) - Sly 2
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8483359/RPCS3.log) - Sly 3

**Comment by YuriNator557** [comment]
Unable to replicate in Sly 1 and Sly 2, haven't got far enough into Sly 3 to check this area
![sly1](https://user-images.githubusercontent.com/76178650/163260849-b1bd57c7-dc2f-4d50-88ad-091fb957c2d2.jpg)
![sly2](https://user-images.githubusercontent.com/76178650/163260854-57c43149-2e94-4cef-9ff9-e7136cad3918.jpg)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8484340/RPCS3.log.gz)

I notice you are at 300% resolution scale, try turning it down

**Comment by Megamouse** [comment]
Performance issues vary wildly on each system.
If we had an issue for every game then there would be 3000 issues

**Comment by EvilPlayer1** [comment]
> Performance issues vary wildly on each system.
> If we had an issue for every game then there would be 3000 issues

So, you think this is normal that the whole game is running at stable 60 FPS, but suddenly drops to 20 FPS because of graphical effects at full screen? Or I just need to install RTX 3090 to have NO questions to performance?

**Comment by Asinin3** [comment]
The game could have slow-down on real hardware because of these alpha effects too. And even if it was a RPCS3 specific issue, unless this game is doing something very strange there's not much we can do specifically to resolve this one issue. Performance problems improve over time with overall optimisations to the emulator.

If everyone opened issues about them back in 2016, our tracker would be full of people saying things like X game drops to 5fps in Y location. And even if it was all fixed 5 years later our tracker would be full of these ancient issues we have to ask people to retest and hope they are available years later... Why should we go through all that hassle?

If this is an emulator specific performance issue then you'd need to do some debugging to find what causes it, or what build made it slower. Otherwise these issues are just not helpful for developers, and at the end of the day that is exactly what an issue tracker should be used for. Otherwise it's a gigantic mess.

**Comment by EvilPlayer1** [comment]
> The game could have slow-down on real hardware because of these alpha effects too. And even if it was a RPCS3 specific issue, unless this game is doing something very strange there's not much we can do specifically to resolve this one issue. Performance problems improve over time with overall optimisations to the emulator.
> 
> If everyone opened issues about them back in 2016, our tracker would be full of people saying things like X game drops to 5fps in Y location. And even if it was all fixed 5 years later our tracker would be full of these ancient issues we have to ask people to retest and hope they are available years later... Why should we go through all that hassle?
> 
> If this is an emulator specific performance issue then you'd need to do some debugging to find what causes it, or what build made it slower. Otherwise these issues are just not helpful for developers, and at the end of the day that is exactly what an issue tracker should be used for. Otherwise it's a gigantic mess.

OK. Just let's think that this is a remaster problem, which can't be fixed
