### ISSUE TITLE
God of War Ghost of Sparta Audio stutter and high Cpu usage 

### ISSUE THREAD

**Issue by Red1860** [RPCS3/rpcs3#11895]
## Quick summary
God of war Ghost of Sparta works fine for 15-20 minutes before the audio starts to stutter and cpu usage increases (almost double).

## Details
It was happening like this on the default settings so I tried changing a few settings like (changing spu threads to 1-3, enabling SPU ⁪Loop ⁪Detection, etc) but nothing seems to work.
 
#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8587585/RPCS3.log)

#### 3. Please attach screenshots of your problem.
https://drive.google.com/file/d/1KLtV6S9TdTGYpJoZ6VUbF8bbIim2nJrw/view?usp=sharing
https://drive.google.com/file/d/1ifhV3yZj947ns0BsDO2EMo_RuGaNioyf/view?usp=sharing

Recorded some footage of this. Sorry I can't attach them here as they are greater than 10mb. 

#### 5. Please provide your system configuration:
* MacBook Air M1 8gb Ram
* OS- macOS 12.3.1
* CPU- M1
* GPU- M1

**Comment by Asinin3** [comment]
We don't really support people making performance issues as it will lead to a giant mess in GitHub, macOS is also going to be slower than Other operating systems due to limitations with the operating system, having to use translation layers, moltenVK etc etc. I will close this off, but you can try the following:

Try changing preferred spu threads, 2 may not be good for you and might be starving the games audio thread. Try Auto, and 3. Also, use Mega block size, it's faster than safe in most games and can help a bit.

**Comment by Red1860** [comment]
I tried the above settings and they did not help. The Mac gets really hot after 20 minutes of gameplay which I don't think should be happening as this is not a cpu intensive game. The cpu usage almost doubles (I don't know why it happens) but the fps remains the same more or less.
