### ISSUE TITLE
[Feature Request] Zoom game window

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#11958]
## Quick summary
I want to get rid of annoying lines in infamous 1 + 2 games and maybe others want to as well in other games
![Screenshot](https://user-images.githubusercontent.com/60384196/167222642-9cfe00c8-ce45-4fc9-a70d-0448f25f33ff.png)
I do not consider these a bug we just should be able to push them off screen effectively hiding them.

## Details
Picture this but you are allowed to go offscreen
![image](https://user-images.githubusercontent.com/60384196/167222346-782a6d74-dad7-45c4-b02d-4182dd7f00d6.png)

I considered this
![Screenshot_20220506-163244](https://user-images.githubusercontent.com/60384196/167223341-e0fcd70b-b4bc-491c-8e33-c0f76a504eb0.png)
But values larger than what is shown are reset upon attempting to set

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* Gameplay
* UI

#### 2. Please tell us, why your feature is important to RPCS3.

For every game with garbage pixels on the outside borders.

#### 3. Please attach screenshots of the feature implemented in other projects.
PCSX2 (I know I'm using the QT version. It works and I like it)
![image](https://user-images.githubusercontent.com/60384196/167221850-9b7e60c5-b557-47f0-9103-b80c124356b1.png)

#### 4. Please provide your system configuration:
Not important to Feature Requests. The idea is for the feature to work for everyone.

#### Please include.
I'm not that great at explaining my thoughts. Ask me anything related to this topic to clarify any questions or concerns.
From my GitHub searches I didn't see a duplicate. If it is a duplicate please cite it before closing this.

**Comment by Asinin3** [comment]
This is out of scope, the lines are not there on a real PS3. It seems to me the reason PCSX2 has this is mainly due to many games being 4:3. I'm sure you can acheive similar results with third party settings, adjusting options in gpu drivers for scaling on the window or adjusting monitor/tv overscan.

This bug in infamous also doesn't appear on a real PS3, the underlying issue should be fixed.

**Comment by NotSoCheezy** [comment]
This feature request deserves to be reopened. Some games actively expect overscan on the display, with Sly 3 being the most gruesome example. You can even see the problem in a video on the RPCS3 YouTube channel!

![image](https://user-images.githubusercontent.com/38305197/211271945-110f5ea8-293f-4934-bf63-d3733c631bc6.png)
Source: https://www.youtube.com/watch?v=pNmLjPpw5xY

The black bars don't reach the edges of the screen because the game expects you not to be able to see the entire screen at all, and this is exactly as it behaves on real hardware. Is this a big deal? Not really, but it's an aspect of the console experience that isn't currently represented in RPCS3.

**Comment by Asinin3** [comment]
Most PS2 games ported to PS3 that have this issue e.g original God of War have an ingame setting to adjust for overscan and let you zoom in or out to prevent it. The infamous game issue in this thread was a game bug. I know that Sly 3 doesn't have this option, so I guess there are some usecases.. But zooming also makes the game look worse. If kd wants to implement it he's free to re-open but I'm not sure if we are planning on doing this.
