### ISSUE TITLE
[Feature Request] Ea active 2 dongle / kit support

### ISSUE THREAD

**Issue by tryface1** [RPCS3/rpcs3#11996]
## Quick summary
Please briefly describe what feature you would like RPCS3 to have.
So i have an ea active 2 kit and i would like to try it on rpcs3
## Details
It comes with a dongle and 3 body attachments
Please describe the feature as accurately as possible.
I would like that the EA active 2 sports kit works on rpcs3
#### 1. Please describe, what part of RPCS3 would be affected by your feature:
Gameplay
* Debugging
* UI
* Patches
* Installation
* Github
* CI
 etc.

#### 2. Please tell us, why your feature is important to RPCS3.
This should be added because it would be great to connect the kit to the pc and play on it

#### 4. Please provide your system configuration:
* OS Windows 11 x64
* CPU Ryzen 3020e with Radeon graphics
* GPU Radeon integrated gpu
* Driver version 
* etc.

#### Please include.
* Anything else you deem to be important

**Comment by Darkhost1999** [comment]
Adding a visual aid of the bundle.
![Screenshot_20220511-102601_Amazon Shopping.png](https://user-images.githubusercontent.com/60384196/167888043-6c6033a5-44a8-43b7-b83f-7ff725f41bff.png)

You just need to try plugging in the USB and syncing the attachments to the USB device then simply see if RPCS3 detects the USB.

If it does great and then try it in game if it works then the feature is already implemented.

Although we probably need a PID and VID to add the usb device to the whitelist in order to detect the device.

**Comment by tryface1** [comment]
is there an fix or somthing

**Comment by FlexBy420** [comment]
USB\VID_21A4&PID_AC27&REV_0300
USB\VID_21A4&PID_AC27
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10094341/RPCS3.log.gz)

**Comment by ChwaraeTeg** [comment]
> but the game is stuck in a ínfinte loop loading

You could try this workaround which has helped other EA Sports games:

After booting the game at least once and getting to the point where it gets stuck, exit RPCS3 and then browse to the RPCS3 install directory and open the \dev_HDD0\game\BLUS30572\ folder if you have the US version or \dev_HDD0\game\BLES00965\ folder for the Euro version. Delete the file 'param.sfo' from that folder. Open RPCS3 and try launching the game again, and see if it gets any further.
