### ISSUE TITLE
[Compilation] RPCS3 Throws Floating Point Exception on Launch when Compiled with LTO

### ISSUE THREAD

**Issue by ThisNekoGuy** [RPCS3/rpcs3#12013]
## Quick summary
Compiling RPCS3 with LTO succeeds but crashes with a floating point exception on launch.

## Details

Compiling RPCS3 via the Clang toolshain using LTO throws a SIGFPE (floating point exception signal) whenever attempted to be launched. It's been a issue for a while, I just hadn't gotten around to reporting it until now.

#### 1. Please provide your system configuration:
* OS: Arch Linux
* CPU: Ryzen 3700X
* GPU: RTX 2080 Ti
* Driver version: 510.60.02 (Proprietary)
* Compiler: Clang 13.0.1
* Compile flags: 
```make
CC=clang
CXX=clang++
LD="/usr/bin/ld.lld"
AR="/usr/bin/llvm-ar"
NM="/usr/bin/llvm-nm"
AS="/usr/bin/llvm-as"
RANLIB="/usr/bin/llvm-ranlib"
STRIP="/usr/bin/llvm-strip"
OBJCOPY="/usr/bin/llvm-objcopy"

CFLAGS="-march=znver2 -mtune=znver2 -O3 -pipe -fno-plt -minline-all-stringops -fexceptions -Wall \
        -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection"
CXXFLAGS="$CFLAGS"
LDFLAGS="-Wl,-O3,--sort-common,--as-needed,-z,relro,-z,now"
```
* LTO was enabled via Arch Linux's [`makepkg.conf`](https://man.archlinux.org/man/makepkg.conf.5.en) with `LTOFLAGS="-flto=full"`

#### 2. Additional Information:
* [Compiled via the AUR](https://aur.archlinux.org/packages/rpcs3-git)

**Comment by RipleyTom** [comment]
I dig into this out of curiosity and the issue happens during the global initialization phase because it initializes `ppu_module_manager::cellAdec` before initializing `ppu_module_manager::s_module_map` (and ppu_module_manager constructor emplaces on ppu_module_manager).

In theory it should be initialized before cellAdec as s_module_map is always defined(by being inline static and being included through PPUModule.h) before cellAdec in all translation units, this may be a compiler bug? (maybe @Nekotekina can confirm that)

Anyway I "fixed" the issue by removing the inline definition and putting the actual definition in cellAdec.cpp (so for sure it would be defined before cellAdec) and now it fails on:
```
$ ./bin/rpcs3
Debugger: 0
QWidget: Cannot create a QWidget without QApplication
Aborted
```

Looking at the bt it's happening after main so global initialization unrelated but QT related. And I think QT is known to have issues if LTO is used so that's that.

As a side note, LTO would give little advantage as an overwhelming majority of the cpu time is spent in recompiled code.

As it is maybe we should add a check to ensure we remove -flto flags from CMAKE_CXX_FLAGS?

**Comment by MSuih** [comment]
LTO does not work with Qt. Qt devs blame compilers for not supporting their project and compiler devs blame Qt for doing dodgy things to break LTO, so most likely it'll not work for a while either.

See these links for example:
https://bugreports.qt.io/browse/QTBUG-61710
https://github.com/InBetweenNames/gentooLTO/issues/444
https://github.com/RPCS3/rpcs3/issues/2959

But I suppose we can fix the floating point exception.
