### ISSUE TITLE
Dark mode on mac is wrong and it make it hard to read the UI

### ISSUE THREAD

**Issue by ellipticaldoor** [RPCS3/rpcs3#12065]
## Quick summary
When you open the latest version in mac on dark mode you get a UI that is hard to read and use

![image](https://user-images.githubusercontent.com/3449006/169697390-0353fc88-e230-4b20-8537-23b461fa32dc.png)

**Comment by AniLeo** [comment]
That's because the OS is trying to repaint the app
That's the macOS version of https://stopthemingmy.app/

Try using one of the custom stylesheets that come with RPCS3 instead

**Comment by ellipticaldoor** [comment]
for now I edited the info.plist and added this to opt out of dark mode
```
	<key>NSRequiresAquaSystemAppearance</key>
	<true/>
```

**Comment by Behodar** [comment]
I'm not so sure that this is an OS issue. It would seem that something in RPCS3 is explicitly setting the background of the game list to white, but isn't setting the text to black. The OS therefore displays the text according to the theme, but the background gets overridden.

The easy fix would be to do as @dortamiguel has suggested above, and set NSRequiresAquaSystemAppearance to true by default, so that it doesn't need to be hand-edited every time there's an RPCS3 update. The more involved fix would be to ensure that either all colours are explicitly specified, or none of them are.

**Comment by guoyunhe** [comment]
Same in Linux/KDE. Qt Widgets will read system color schema. If you don't modify Qt's default widget styles, it is fine. If you only changed background color but not text color, you will get this problem. I can provide a PR to fix this.
