### ISSUE TITLE
GeForce 840m and possibly other Nvidia GPUs - Exclusive fullscreen is broken/not working.

### ISSUE THREAD

**Issue by Hasster1** [RPCS3/rpcs3#12064]
## Quick summary
Dedicated GeForce 840m - Exclusive fullscreen is not true - i can see the windows changing sound while pressing volume up. Both on open gl and vulkan.
Integrated Intel HD Graphics - Exclusive fullscreen is true - i cannot see the volume changing while pressing volume up/down. Open GL only, since vulkan is not supported.

## Details

I've got a laptop with two graphics card - Dedicated Nvidia GeForce 840m and Integrated Intel Graphics HD.

I love exclusive fullscreen mode, but the problem is that it's usually hard to enable. Some apps require me to disable fullscreen optimizations for that, some require changing graphics backend.
And not that long ago, i've found out that my GPU also might be the reason why exclusive fullscreen mode doesn't work sometimes.
There are a few apps, that require me to turn on my integrated GPU on - like osu!. There's an issue about the same problem in there - https://github.com/ppy/osu/issues/6075.

And right now i've tried to do the same here - disabled my dedicated GPU completely through device manager (Running with graphics processor doesn't do anything, it still boots with nvidia's gpu, even if i will change it through nvidia control panel ), leaving only integrated gpu, and it magically turned my fullscreen into an exclusive fullscreen. Turned it back, and the fullscreen isn't exclusive anymore. 
It's easy to test out, you just need to press volume up/down, and if you see how the volume changes - then you're not in exclusive fullscreen mode.
I don't even need to load the game, the loading screen itself in fullscreen mode shows when it's enabled or disabled.

Tested it on the Open GL only, since integrated GPU doesn't support vulkan.

It might be possible that other Nvidia GPUs are affected by this.

#### 0. Make sure you're running with settings as close to default as possible
Doesn't really matter.

#### 1. Please attach RPCS3's log.
Integrated GPU - 
[Integrated.log](https://github.com/RPCS3/rpcs3/files/8749264/Integrated.log)
Dedicated GPU - 
[Dedicated.log](https://github.com/RPCS3/rpcs3/files/8749266/Dedicated.log)

#### 3. Please attach screenshots of your problem.
That's how you know that you're not in exclusive fullscreen mode.
![image](https://user-images.githubusercontent.com/20757715/169692266-43e1b937-1ff0-4b88-bd24-cf53f7caaca7.png)

#### 4. Please provide comparison with real PS3.
N/A.

#### 5. Please provide your system configuration:
* OS - Windows 10 1909.
* CPU - I5-4210U
* GPU - Dedicated Nvidia GeForce 840m and integrated Intel HD Graphics
* Driver version - Nvidia - 512.77.0.0.

**Comment by kd-11** [comment]
OpenGL does not do "exclusive fullscreen". Fullscreen is always exclusive and the only way to control this is using the driver's control panel. Now, because of how optimus works, you get a split display setup. 3D rendering is done on the NVIDIA card, but display is actually handled by the intel GPU so you need to configure some things in your intel graphics command center.
If you have a HDMI cable, try connecting that directly to the side of the laptop and test on an external display. NVIDIA drivers are superior to the intel ones you find on laptops.

**Comment by Hasster1** [comment]
Yeah, you're right. I've done some more testing, and found out that the only render that allows exclusive fullscreen on my laptop - is the direct x. Open GL and Vulkan both give me the fake exclusive fullscreen in every app. This has nothing to do with RPCS3, it's my laptop.
Btw, i've tried plugging in another monitor through hdmi, and it connected to my intel's gpu, which resulted in the same thing. So there's no hope for me :(
Thanks anyway.

**Comment by mirh** [comment]
> OpenGL does not do "exclusive fullscreen".

I guess you could be technically correct that there's no other associated concept in opengl-proper, but at the same time (when achieving the right window style and composition is paramount) what you do in your application is not tangent either. 

> Fullscreen is always exclusive and the only way to control this is using the driver's control panel.

Not really. 
Behind the scenes, there are probably like three or four kinds of "fullscreen" that you can achieve in Windows, each one with their own different merits/overhead. 
And even though there might be some settings in the control panel that eventually influence this aspect, there's really no "how do you want fullscreen" choice. 

> so you need to configure some things in your intel graphics command center.

I don't know if their latest Xe/Alchemists cards brought in anything new to the table then, but for the longest time that was an absolute joke. 
Like, the only three 3D settings are AA, AF and vsync (which on top of being probably specific to some api they don't disclose, it could anyway only apply once the DWM has ceded control to the driver/game). 

> If you have a HDMI cable, try connecting that directly to the side of the laptop and test on an external display.

That would only make a difference on high-ish end gaming-oriented laptops that have their video output wired to the dGPU. 
Office-focused (or if not any the cheapest) builds would still have that hooked to internal. 

---
With all of this said and premised, OP is super lucky because their GM108-based gpu is like the oldest and slowest still supported by the mainline nvidia driver. 
And in 526.47 they added DXGI swapchain presentation. 
Which does not allow for 100% exactly the same of legacy exclusive fullscreen, but for most intent and purposes it should be identical (*if not even better*).
