### ISSUE TITLE
Red Dead Redemption doesn't start anymore

### ISSUE THREAD

**Issue by Priler** [RPCS3/rpcs3#12104]
## Quick summary
RDR used to work on older RPCS versions.
So, recently I've updated it to the newest version and, it's now even not starting.
I've also tried to completely reinstall RPCS3, - no changes.

## Details
I'm constantly getting this error message in the logs:
`E SYS: Stat: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [x845]`
No matter what configuration to use, default or recommended.

#### 1. RPCS3's log.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/8787276/RPCS3.log.gz)

#### 2. Please provide your system configuration:
* OS: Windows 11 v21H2 build 19044.1706
* CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* GPU: NVIDIA RTX 2080Ti
* Driver version: Latest (Game Ready 512.95)

**Comment by Darkhost1999** [comment]
![image](https://user-images.githubusercontent.com/60384196/170721696-9bde79dc-4583-40b2-9975-4b2cd4cfc8cc.png)
I can get in game and performance is worse than ever
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/8787392/RPCS3.log)
R5 3600
GTX 1660S
Win11

**Comment by Priler** [comment]
> but didn't bother testing old builds to find where it broke
Have no clue on what older version of RPCS3 it was working, cuz I've updated it with new one straight.
More of that, I have neither time nor opportunity to test it out with previous versions.
Anyway, devs may fix this with the logs attached & issue opened now.

**Comment by Asinin3** [comment]
> > but didn't bother testing old builds to find where it broke
> 
> Have no clue on what older version of RPCS3 it was working, cuz I've updated it with new one straight. More of that, I have neither time nor opportunity to test it out with previous versions. Anyway, devs may fix this with the logs attached & issue opened now.

Don't open an issue if you aren't prepared to test. It should never be on devs to work through a incomplete issue report. Especially when we do not know if they will waste lots of time trying to find a bug they can't reproduce... Like I did when I tested this, and found my FPS to be the same, and could get ingame just fine on latest.

**Comment by MSuih** [comment]
If the developers want to fix this they need to know what causes it, and the first step is usually to reproduce it themselves. Since we already have 3 people saying that they can't reproduce it and RPCS3 Discord hasn't gotten a flood of complaints either, I'm going to assume it is somehow related to your system, settings or other similar details.

Right now there's no information aside from "I can't get my game dump to work for some reason" which isn't much to go on. If you need help with this kind of issue then our Discord would be a better place for asking help.
