### ISSUE TITLE
Rayman Legends issue

### ISSUE THREAD

**Issue by KraXarN** [RPCS3/rpcs3#1214]
So, just to try and see how well this worked, I tried running Rayman Legends which does not work.

Upon loading the game, rpcs3 just instantly crashes.
Sometimes when loading the same up again, it tells me that the game data is corrupted, but can be continued and then it just crashes again.

I also tried running it through the terminal only to get this error

/rpcs3_vm: g_base_addr = 0x7fedbe1c2000, g_priv_addr = 0x7fecbe1c2000
Segmentation fault (core dumped)

I also managed to grab this screenshot with some errors being shown, don't know if it helps:
http://i.imgur.com/UPPwNpY.png

I also tried some different settings with PPU and SPU without anything different

**Comment by tambry** [comment]
@KraXarN Always provide the full log when reporting issues. Not only that, but specific problems should be reported on the Github issue tracker (ie. vertex shader is broken or *this* instruction in ppu recompiler is broken), otherwise post them on the (forum)[http://www.emunewz.net/forum/forumdisplay.php?fid=162].

Chances are though, that it's fixed by this commit, which is not in master yet: https://github.com/tambry/rpcs3/commit/8672a33d256fc97f0b3129d1a370ceb81175356e.

**Comment by tambry** [comment]
Re-open if you're able to provide more info.
