### ISSUE TITLE
ModNation™ Racers [NPUA80535] VM: Access violation reading location 0x3c (unmapped memory)

### ISSUE THREAD

**Issue by FormulaGX** [RPCS3/rpcs3#12181]
OS: Windows 11 Pro 21H2
Build: 22000.675

CPU: AMD Ryzen 7 2700X Eight-Core Processor - 3.70 GHz
RAM: 32 GB

GPU: Radeon RX 580 - 8GB
Driver version: 22.2.1

Additional Settings:
- Write Color Buffers ✅ - Fixes a map glitch blocking the road in the race.

Log File: [RPCS3.log](https://github.com/RPCS3/rpcs3/files/8841460/RPCS3.log)

I cannot load the ModSpot hub world for the first time after the prologue; any time I attempt to, the game freezes at 5% on the following loading screen.

`F {PPU[0x1000012] Thread (CommerceManagerThread) [0x00519248]} VM: Access violation reading location 0x3c (unmapped memory)`

![image](https://user-images.githubusercontent.com/18689449/172084655-b7275cea-b99c-40f9-9d93-5bab2d4a9daf.png)
![image](https://user-images.githubusercontent.com/18689449/172084677-5f33170d-5458-4ab8-9ba2-2bc5765c38cb.png)

**Comment by RipleyTom** [comment]
Unimplemented sceNpCommerce2GetCategoryInfo.

**Comment by motomagx** [comment]
![image](https://user-images.githubusercontent.com/40811525/172521761-516b16ae-9575-4990-9b49-afc398c5f216.png)
i 
![image](https://user-images.githubusercontent.com/40811525/172522005-ddefab7a-1909-4769-a26a-f3b1aef6a3c3.png)


I had this exact problem, and the fix was simple: I just had to disconnect the Network/PSN and the game no longer crashed, and I was able to proceed to ModSpot.

**Comment by FormulaGX** [comment]
> I had this exact problem, and the fix was simple: I just had to disconnect the Network/PSN and the game no longer crashed, and I was able to proceed to ModSpot.

Thank you so much, I totally overlooked that setting!

**Comment by marcoluc97** [comment]
@RipleyTom should remain open for tracking Unimplemented HLE or do you prefer something else?
