### ISSUE TITLE
Regression: Horrible noise in Skate 3

### ISSUE THREAD

**Issue by MSuih** [RPCS3/rpcs3#12194]
Skate 3 has horrible buzzing sound after #12112. This starts during the autosave dialog where the game loads more PPU modules and initializes things and continues until getting ingame. It only happens when audio format is set to stereo, any other option will 

The actual bug is probably related to the game downmixing to 2 channels. Previously we only exposed multichannel audio and did all downmixing ourselves which most likely hid the bug. Still, it should be treated as a regression because stereo is the default output mode.

https://user-images.githubusercontent.com/19759300/172418315-a4317141-81c2-4abb-840f-67c4c3d8d379.mp4

Logs:
[RPCS3-stereo.log](https://github.com/RPCS3/rpcs3/files/8854456/RPCS3-stereo.log)
[RPCS3-auto.log](https://github.com/RPCS3/rpcs3/files/8854477/RPCS3-auto.log)

**Comment by capriots** [comment]
Went back to a commit before that PR and made it so that cellAudioOutGetSoundAvailability() returns 2 instead of 8 and sure enough, I had the exact same buzzing.

**Comment by capriots** [comment]
The reason this is happening is because we are always downmixing all the surround channels into the stereo channels if stereo output is configured. The game however specifically configures to not downmix anything. The buzzing is coming from the center and surround channels. 
By patching out calls to cellAudioOutConfigure() to make the game run in stereo mode while outputting surround, you will discover that the buzzing is also present when running on a PS3.
![Buzzzzzz](https://user-images.githubusercontent.com/29807355/174459766-cd361b6b-3c42-4a89-8a2a-556269029942.png)

**Comment by W0lf4llo** [comment]
This keeps happening on my real ps3, on a legit disc. It only seems to happen when I'm using my headset for game audio though.

**Comment by capriots** [comment]
USB/Bluetooth audio on the PS3 has downmixing forced on at all times.
It should go away if you enable surround sound on your PS3.
