### ISSUE TITLE
[Feature request] Exclusive Fullscreen mode

### ISSUE THREAD

**Issue by abwezi** [RPCS3/rpcs3#12382]
### Quick summary

Hello I am hoping to use your awesome emulator with this excellent fix that was released here: http://helixmod.blogspot.com/2019/08/rpcs3-playstation-3-emulator-opengl.html which is supposed to allow one to take the RPCS3's game output and display it in stereoscopic 3D on Nvidia's older "3D Vision" hardware. Over time however updates to Nvidia's drivers have borked functionality of the 3D Vision feature in multiple ways and so this fix no longer works on the newest cards and the drivers that support them. On the newest Nvidia drivers, exclusive fullscreen is required to activate the 3d hardware. From what I can gather this is not a feature that has ever been supported in RPCS3 and most likely why this fix no longer works with the newest drivers. While I know most people prefer borderless window and exclusive fullscreen seems largely left in the past anymore, please, consider adding an exclusive fullscreen option. It would be very helpful, thank you!

**Comment by YuriNator557** [comment]
This is already implemented in RPCS3, there's even an option in the GUI to disable it in the Advanced tab

**Comment by TorutheRedFox** [comment]
try disabling those fullscreen 'optimizations' that Windows 10 applies as they're basically just a borderless window mode pretending that it's exclusive fullscreen to the application that activates some system-level optimizations to make it faster than regular windowed

**Comment by Darkhost1999** [comment]
RPCS3 itself doesn't do anything with exclusive fullscreen mode. The graphics drivers apparently do.
Sure we can ask the drivers nicely in the advanced tab "please don't use exclusive fullscreen mode."
Ultimately though it's up to them. And this request seems to be asking to make the feature RPCS3's decision instead of your graphics drivers.

![Screenshot_20220723-073021.png](https://user-images.githubusercontent.com/60384196/180605232-9bd38e53-9a4c-4061-81b0-a47296a1de91.png)

Maybe they want a force exclusivity button

![Screenshot_20220723-072956.png](https://user-images.githubusercontent.com/60384196/180605240-1e1c359d-b895-4203-bc51-910c094caf42.png)

Only a handful of people in discord have discussed that there is no actual exclusive fullscreen mode in RPCS3.

**Comment by MSuih** [comment]
To clarify, there's four different modes for exclusive fullscreen in Vulkan:

* Unspecified: Let the drivers decide what to do about this feature.
* Allowed: Hint the drivers that it is okay to enable exclusive fullscreen for this application.
* Disallowed: The driver should avoid using exclusive full screen for this application.
* Application controlled: The application has full control over exclusive full screen, and can request to enable and disable it at any time. The application must also monitor if the fullscreen is lost (f.ex. when alt-tabbing or minimizing) and then attempt to regain it if desired.

By default we use unspecified, which in practise seems to be same as allowed as most drivers seem to enable exclusive full screen. Disallowed can be used with the Force disable exclusive fullscreen setting. Application controlled would probably be what people want, but it requires some knowledge of Vulkan to implement.

**Comment by abwezi** [comment]
Thank you very much for looking into this. The wrapper I am attempting to use currently only supports the OpenGL API however I believe somebody is working on a fix for Vulkan eventually using this: https://3dsurroundgaming.com/Vk3DVision.html and similarly would require exclusive fullscreen in order to work

**Comment by AniLeo** [comment]
This already seems solved by #12945, does it still not work with the current options?

**Comment by abwezi** [comment]
It works now yes. Thank you!
