### ISSUE TITLE
SXS DS3 player light incorrect if it's connected (or reconnected) after RPCS3 launches

### ISSUE THREAD

**Issue by TorutheRedFox** [RPCS3/rpcs3#12447]
### Quick summary

Opening the controls config fixes it, but only for the controllers that are currently connected.
If a controller is connected after that (either because a new player joined in or a controller disconnected due to inactivity), the issue will reappear on it.

### Attach a log file

(not applicable I don't think?)

**Comment by Darkhost1999** [comment]
A log is applicable. It'll help.
Additionally how is the controller connected? Nefarious dshidmini, USB, Bluetooth, official Sony drivers, archived project SCP toolkit the developer of the project says discontinued and do not use?
This might help to know if it's an RPCS3 issue or an issue with a 3rd party software

**Comment by TorutheRedFox** [comment]
dshidmini in SXS mode

**Comment by Darkhost1999** [comment]
Using bthps3?

**Comment by TorutheRedFox** [comment]
both wired and bthps3

**Comment by TorutheRedFox** [comment]
the light is only set correctly if the controller is either connected already when starting RPCS3 or when entering the gamepad settings menu

**Comment by Darkhost1999** [comment]
Can confirm
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9248784/RPCS3.log)
DSHIDMINI BTHPS3 using an official DualShock 3.
This issue is replicable. Don't even need to launch a game. Just turn off and on your controller while RPCS3 is running.
In game for me turn off controller. Light goes out. Reconnect controller light remains out.
The light is only correct before starting RPCS3 or when entering the pad settings menu.

**Comment by TorutheRedFox** [comment]
sometimes it's not even out but on the wrong port number

**Comment by Megamouse** [comment]
We recently fixed some LED issues.
Please try again

**Comment by TorutheRedFox** [comment]
i think it works correctly now

**Comment by Megamouse** [comment]
Thanks. Let us know if you encounter further issues

**Comment by TorutheRedFox** [comment]
will do
