### ISSUE TITLE
2 RPCS3 Errors

### ISSUE THREAD

**Issue by jasonbof75** [RPCS3/rpcs3#1246]
I head that some commercial game that doesn't require much will run on rpcs3 and I thought NCAA FOOTBALL 14 would be one of those but I keep getting two errors.
E PSFLoader::Load() failed: unknown magic (0x0)
E Loading 'C:\Users\SirJasonB\Desktop\NCAA.Football.14.PS3-PROTON\FIX\USRDIR\EBOOT.BIN' failed
There is one bin file with it I tried to load.
Also on the right side it says illegal address.
Is it just that rpcs3 want play it or could it be that someone got the files wrong?
Am I doing something wrong?
Oh do you have to have the PS3 bios for rpcs3 or what?
THANKS
![rpcs3](https://cloud.githubusercontent.com/assets/15038651/10377748/afa475a8-6dca-11e5-87f9-5ea205c22670.PNG)

**Comment by tambry** [comment]
"I head that some commercial game that doesn't require much will run on rpcs3"
Well then, let's try to run a very complicated 3D game, because that will surely work.

It would actually help us, if you posted the actual bloody log file, as described [here](http://www.emunewz.net/forum/showthread.php?tid=171465).
Also it seems you haven't read the [FAQ](https://github.com/DHrpcs3/rpcs3/wiki/FAQ), which also states, that almost all commercial games wont work, see [here](http://www.emunewz.net/forum/forumdisplay.php?fid=195) for the list of playable games (mostly very simple 2D/2.5D games). RPCS3 is a HLE emulator, which means that no BIOS/FW files are required.

"Also on the right side it says illegal address."
Well, it obviously says "Debugger" on the sub-window and the illegal addresses are in the assembly output, which obviously wont show anything until you use it properly and are running/debugging the game.

**Comment by jasonbof75** [comment]
First I couldn't find anything on this damn website when I first started and second why do you want to look at log If you know it won't play it.
I was just trying game a game I like hoping it would work.
If you want to waste your time here is the log anyway.

G: ! RPCS3 v0.0.0.6-3695-86720f9
G: ! 
HLE: ! (S)ELF: booting...
G: ! Stopping emulator...
LDR: ! Loading 'C:\Users\SirJasonB\Desktop\NCAA.Football.14.PS3-PROTON\FIX\USRDIR\EBOOT.BIN'...
G: W fs::file::open('C:/Users/SirJasonB/Desktop/NCAA.Football.14.PS3-PROTON/FIX/dev_bdvd.path', 0x1) failed: error 0x2
LDR: ! 
LDR: ! Mount info:
LDR: ! /dev_usb000/ -> C:/Users/SirJasonB/Desktop/ps3-2/EmuCR-rpcs3-20151006-x64/dev_usb000/
LDR: ! /dev_flash/ -> C:/Users/SirJasonB/Desktop/ps3-2/EmuCR-rpcs3-20151006-x64/dev_flash/
LDR: ! /host_root/ -> 
LDR: ! /dev_hdd0/ -> C:/Users/SirJasonB/Desktop/ps3-2/EmuCR-rpcs3-20151006-x64/dev_hdd0/
LDR: ! /dev_hdd1/ -> C:/Users/SirJasonB/Desktop/ps3-2/EmuCR-rpcs3-20151006-x64/dev_hdd1/
LDR: ! /dev_usb/ -> C:/Users/SirJasonB/Desktop/ps3-2/EmuCR-rpcs3-20151006-x64/dev_usb000/
LDR: ! 
LDR: ! Settings:
LDR: ! CPU: PPU Interpreter
LDR: ! SPU: SPU Interpreter (precise)
LDR: ! Renderer: OpenGL
LDR: ! Resolution: 720x480
LDR: ! Write Depth Buffer: No
LDR: ! Write Color Buffers: No
LDR: ! Read Color Buffers: No
LDR: ! Read Depth Buffer: No
LDR: ! Audio Out: OpenAL
LDR: ! Log Everything: No
LDR: ! RSX Logging: No
LDR: ! 
LDR: E PSFLoader::Load() failed: unknown magic (0x0)
LDR: ! Title: 
LDR: ! Serial: 
LDR: ! Elf path: /host_root/C:/Users/SirJasonB/Desktop/NCAA.Football.14.PS3-PROTON/FIX/USRDIR/EBOOT.BIN
LDR: ! 
LDR: ! loader::init() failed: Bad file
LDR: ! loader::init() failed: Bad file
LDR: E Loading 'C:\Users\SirJasonB\Desktop\NCAA.Football.14.PS3-PROTON\FIX\USRDIR\EBOOT.BIN' failed
LDR: ! 
HLE: S (S)ELF: boot done.
G: ! Stopping emulator...

**Comment by Aaahh** [comment]
Don't be rude...

Anyways, the log helps us narrow the problem of why the game doesn't work.

As for this website, github is not where discussion happens, although the wiki should be improved

**Comment by jasonbof75** [comment]
tambry was rude first, like people are suppose to know where everything is on this website when they first start so I was just returning the favor. OK Aaahh so what does all of that mean? 
And what does just this mean? I got this when I started the game.
(LDR: E PSFLoader::Load() failed: unknown magic (0x0))
(LDR: E Loading 'C:\Users\SirJasonB\Desktop\NCAA.Football.14.PS3-PROTON\FIX\USRDIR\EBOOT.BIN' failed)

**Comment by Aaahh** [comment]
Eboot.bin can't be read or isn't recognized.
Either a bug in the code, bad file, or we don't this type. 

I also think that you can't just load a commercial game, but I'm not sure. 

Tambry care to help?

**Comment by jasonbof75** [comment]
OK Aaahh so It was eboot that I was suppose to load but it may not recognize it or the file could be bad. If the claim is real and if any is a real copy of ncaa football it might do something at least.
I will try to find other copy's of ncaa football 14 to test RPCS3.

**Comment by Aaahh** [comment]
You loaded the folder right?

**Comment by jasonbof75** [comment]
Thanks Aaahh, I will keep on trying and hope I can find a good copy of the game to test. It might be a little while before I post again but I will reading any help that anyone puts on here. +1:

**Comment by Aaahh** [comment]
You boot eboot.bin or boot.*  . Why it gaves you that exact error I don't know. Heads up, even if you fix that issue you'll get many more though. @tambry can you look at that? Seems simple enough, (they you find out it isn't...)

Anyways, it's true the wiki should be updated... Even if useless tickets keep coming, we could start sorting the actual issues. (I would)
Not that you need more work... 😉 (:wink:)

**Comment by tambry** [comment]
@jasonbof75 @Aaahh The problem seems to occur while reading the PARAM.SFO file, which includes the needed info about the game. PARAM.SFO files should **always** start with u32 equivelant of the string "PSF" (we check for "\0PSF"). If it isn't there, we can assume the .SFO is corrupt or not a proper .SFO file.

@jasonbof75 Could you join our IRC channel on EFNET at #rpcs3? I would like to obtain the game's .SFO file to check it's header to see, if it really is corrupt.

**Comment by jasonbof75** [comment]
@tambry Is this the right place?
http://chat.efnet.org/irc.cgi?chan=%23rpcs3
I joined but I don't see you on there.

**Comment by tambry** [comment]
@jasonbof75 Oops, I for accidentaly wrote EFNet instead of Freenode. Our channel is on Freenode instead. Sorry.

**Comment by jasonbof75** [comment]
@tambry is this it?
https://freenode.net/
I seem to only go to web chat and can't find rpcs3

**Comment by tambry** [comment]
Issue was the way of booting the game. Game still doesn't boot due to unknown reasons.
