### ISSUE TITLE
after #12319(0.0.23-13961) RPCS3 don't start and close with no error

### ISSUE THREAD

**Issue by kyh96403** [RPCS3/rpcs3#12472]
### Quick summary

The game list looks normal, but when start the game, it just close without any error message.
All games have this problem, and previous versions have no problem at all.

### Attach a log file

No error

### Attach capture files for visual issues

https://user-images.githubusercontent.com/21171837/183246411-a45b5fdb-46ad-4a2e-80e8-353c54fc1a5f.mp4

### System configuration

CPU: 12th Gen Intel(R) Core(TM) i9-12900K   3.20 GHz
32G memory
GPU: NVIDIA 1050, driver: 30.0.15.1295

**Comment by YuriNator557** [comment]
Log file is missing

**Comment by Juan12233** [comment]
and ami when installing the current firmware it does not compile causing the simulator to close the same thing happens to me without trying to start any game it also closes and I have tried with all the games and it does not compile and the same thing happens to me when starting the PS3 system and what I did was to delete RPCS3 because it was a waste of time to download it since it closes with everything except the command settings the configuration generates seriously I hope this gets fixed because the emulator is useless right now :(

**Comment by Juan12233** [comment]
and ami when installing the current firmware it does not compile causing the simulator to close the same thing happens to me without trying to start a game it also closes and I have tried with all the games and it does not compile and the same thing happens to me when starting the PS3 system and what I did was to delete RPCS3 because it was a waste of time to download it since it closes with everything except the command settings the configuration generates seriously I hope this gets fixed because the emulator is useless right now :(

**Comment by Juan12233** [comment]
and ami when installing the current firmware it does not compile causing the simulator to close the same thing happens to me without trying to start a game it also closes and I have tried with all the games and it does not compile and the same thing happens to me when starting the PS3 system and what I did was to delete RPCS3 because it was a waste of time to download it since it closes with everything except the command settings and the configuration generates seriously I hope this gets fixed because the emulator is useless right now :(

**Comment by Juan12233** [comment]
and ami when installing the current firmware it does not compile causing the simulator to close the same thing happens to me without trying to start a game it also closes and I have tried with all the games and it does not compile and the same thing happens to me when starting the PS3 system and what I did was to delete RPCS3 because it was a waste of time to download it since it closes with everything except the command settings and the configuration generates seriously I hope this gets fixed because the emulator is useless right now :(

**Comment by AniLeo** [comment]
I locked the ticket because there's some idiot spamming it, please open a new regression ticket once you have the log file to complete it
