### ISSUE TITLE
Resolution scale not work properly  in Dragon Ball Z: Budokai HD Collection

### ISSUE THREAD

**Issue by staticz97** [RPCS3/rpcs3#12481]
### Quick summary

When increasing the resolution , the game seems to have a worsening in the image quality , only working properly in the native resolution.

### Attach a log file

Empty

### System configuration

Windows 11, i5 12600k , RTX 3070 , Nvidia Studio Driver 516.93

**Comment by MSuih** [comment]
Resolution scaling is not guaranteed to work with every game. There is probably some post-processing effect being added to the image that forces emulator to scale the image back to 100% and the only solution would be to remove it with a game-specific patch. Without one, your only options are to use FSR or just play at native resolution.

Also, your issue is missing a screenshot of the problem, a log file and a capture.
