### ISSUE TITLE
DualSense gyro doesn't work in rpcs3

### ISSUE THREAD

**Issue by xDShot** [RPCS3/rpcs3#12504]
### Quick summary

DualSense gyro doesn't work in games where it's supposed to work.

### Details

For ex. in Call of Duty 3, on first level there's crate with ammo. The game prompts to rotate controller quickly to do melee attack. No matter how I shake it, nothing happens.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9314241/RPCS3.log.gz)

### System configuration

Arch Linux
AMD Ryzen™ 7 5800X × 16
AMD Radeon™ RX 5700
mesa 22.1.4-1

**Comment by jeremybris** [comment]
This issue is more noticeable in "Super Rub a Dub" (and not exclusive to Linux). I noticed two issues:

1.  When laid flat, on the ground or a table, the controller acts like it is being tilted to the bottom left.
2. The controller is constantly shaking, like it's pull rate/refresh rate is too high.

**Comment by ethanrushh** [comment]
+1, DualSense support seems to be a bit borked. In GT5 it rumbles near constantly. The engine needs to be tweaked a bit. If nobody else gets to it first, I'll add it to my TODO list.
