### ISSUE TITLE
[Regression] Madden 12 has black lines corruption on top of the menu (#11717)

### ISSUE THREAD

**Issue by Moodo1** [RPCS3/rpcs3#12514]
### Quick summary

I found through regression testing an issue that caused Madden 12 to have black lines appear on the main menu, as shown in the picture below.

### Details

The most recent working version of Madden 12 through me doing a regression test is from 135 days ago as of 8/15/2022. It will be linked below. Anyone wanting to play currently Madden 12 on the most recent version or any until then will experience annoying black lines over the menu making the game unplayable. The last good version will be linked below. The 

### Build with regression

v0.0.21-13399-fc055113

### Attach two log files

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9336171/RPCS3.log.gz)

Recent build that Madden 12 doesn't work with

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9336181/RPCS3.log.gz)

Last build from 135 days ago that actually works with Madden 12.

**Comment by Moodo1** [comment]
![2022-08-14 (1)](https://user-images.githubusercontent.com/111274780/184608679-8f978720-fe5b-47e7-9fe5-ee5b78eb8f07.png)

Forgot to link in OP. This is what it looks like for me when loading it up.

**Comment by elad335** [comment]
1. It seems like you went through alot of trouble with testing. There is a simple method to test which build caused a regresssion called binary search: you check a build around the middle of the last known broken build and the first known working build, if it's broken you go over this process again between this build and the last working build and the opposite if it's working. You go over this process until you find it.
2. The build in question doesn't make much sense so you may need to do this process again.

**Comment by ChwaraeTeg** [comment]
To quickly summarize findings from the other two issue reports:

A similar issue exists in the title and menu screens of Madden NFL 10 and 11. As with Madden NFL 12, the issue is not present in RPCS v0.0.21-13393 and starts occurring from v0.0.21-13399.

Madden NFL 10 (NVIDIA)
https://user-images.githubusercontent.com/71127352/201546863-a844237b-858d-494c-9c63-f2a74ca65ac6.png
https://github.com/RPCS3/rpcs3/files/9998314/RPCS3.1.log.gz
https://github.com/RPCS3/rpcs3/files/9998317/NPUB90282_20221113205452_capture.zip

Madden NFL 11 (NVIDIA)
https://user-images.githubusercontent.com/71127352/201546858-9e741bd3-abff-4e72-b21a-18807d4a116a.png
https://github.com/RPCS3/rpcs3/files/9998327/RPCS3.Madden.NFL.11.log.gz
https://github.com/RPCS3/rpcs3/files/9998318/NPUB90387_20221113221347_capture.zip

On Intel graphics, a similar issue occurs but as small amount of vertical black bars rather than the large amount of horizontal black bars seen on NVIDIA graphics. As with the original report, not a problem on 13393 and starts occurring from 13399 onwards.

https://user-images.githubusercontent.com/104720038/204137058-a8b4bf52-08ca-4120-8a8b-2e6e64c03c90.png - Madden NFL 12 in -13393 (Intel)
https://user-images.githubusercontent.com/104720038/204137060-45dcd7a0-e3d3-435e-a935-16b7b89acadd.png - Madden NFL 12 in -13399 (Intel)

**Comment by Mumkey35334** [comment]
Hey so I know this might be a little bit late but i might have fixed your problem when I disable Anti-aliasing it removes this problem 

(I know this because I regularly have anti aliasing off normally so I turned it on to try and fix a different problem and the black lines appeared I turned it off and the black lines are gone)

**Comment by ChwaraeTeg** [comment]
I tested your suggestion and can confirm the black lines are indeed gone with anti-aliasing disabled. Here's some logs and captures from Madden NFL 12:

With Anti-Aliasing Disabled (no black lines):
[Capture madden12_aadisabled.rrc.gz](https://github.com/RPCS3/rpcs3/files/11502214/madden12_aadisabled.rrc.gz)
[Renderdoc madden12_aadisabled.rdc.gz](https://mega.nz/file/7FFHVLKJ#n3Lvz98WhYMEYs-u2iFg8Nz6ji-rRn9QJMlHG2LvgvI)
[Log: madden12_aadisabled.log.gz](https://github.com/RPCS3/rpcs3/files/11502213/madden12_aadisabled.log.gz)

With Anti-Aliasing left on Auto for comparison (black lines):
[Capture: madden12_aaauto.rrc.gz](https://github.com/RPCS3/rpcs3/files/11502218/madden12_aaauto.rrc.gz)
[Renderdoc: madden12_aaauto.rdc.gz](https://mega.nz/file/CEdRlQwB#lEwRBD7uUJsmh_WXJpbjQ2C1QgfvDhRnFhSPBSGUe58)
[Log: madden12_aaauto.log.gz](https://github.com/RPCS3/rpcs3/files/11502217/madden12_aaauto.log.gz)

**Comment by Triticum0** [comment]
This also affects Madden 11 and 10
