### ISSUE TITLE
Toy Story 3 - Flickering Texture Bug

### ISSUE THREAD

**Issue by Jonathan44062** [RPCS3/rpcs3#12527]
### Quick summary

That bug has been a quite around, I know there was an ticket issue, but now is closed, for now, the workaround to fix this is enabling "Strict Rendering Mode" in GPU Tab, without it, the game flickers a lot.

I do this just to the emulator developers take it into account, I know kd-11 is aware of it, but I do it just in case.

### Details

RPCS3
![image](https://user-images.githubusercontent.com/78843189/185503244-591d5e82-0922-4836-aa9e-8acfde02de9c.png)

PS3
![image](https://user-images.githubusercontent.com/78843189/185506589-e359249c-98e7-4495-879d-7e801cb13e67.png)

### Attach a log file

Log with STM -> [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9377999/RPCS3.log.gz)

Log without STM -> [RPCS3 Toy Story 3 No Strict Rendering Mode.log.gz](https://github.com/RPCS3/rpcs3/files/9377983/RPCS3.Toy.Story.3.No.Strict.Rendering.Mode.log.gz)

### Attach capture files for visual issues

RSX Capture 
https://www.mediafire.com/file/35n3fjdxl7yauou/BLUS30480_20220818172109_capture.rrc/file

I hope this rsx capture help

### System configuration

OS - Windows 10 21H2 Build: 19044
CPU - i7 8700
GPU - GTX NIVIDIA 1070 Ti
Driver version - 516.59

**Comment by RainbowCookie32** [comment]
> the workaround to fix this is enabling "Strict Rendering Mode" in GPU Tab, without it, the game flickers a lot.

If SRM still fixes it, then there's no issue here. Without SRM RPCS3 takes shortcuts when rendering for performance, which is fine with most games but some don't like it. Same principle as games that require WCB for example.

**Comment by Jonathan44062** [comment]
"that game requires full zcull sync on a texture semaphore which is just dumb. Strict mode is still required for that due to the performance penalty."
According to kd-11

https://github.com/RPCS3/rpcs3/issues/5526, in this, someone said that setting does not work on a RTX 3060 Ti, perhaps a different architecture from other GPUs will give a rather strange result

**Comment by MSuih** [comment]
For context, read [this pull request](https://github.com/RPCS3/rpcs3/pull/7302)

kd-11 knows what the issue is, and could make the fix not require SRM (as it originally didn't). However, the performance overhead is simply far too big to justify having it enabled at all times. If more games would use this feature then maybe it could be reconsidered, but as far as we know only Toy Story 3 behaves like this.

Strict rendering mode is a feature which focuses on accurately emulating the RSX, while the default codepath is allowed to optimize things for better performance as long as compatibility doesn't take too big of a hit. There will always be some games which require full accuracy and for those SRM is required.

**Comment by MSuih** [comment]
Also, in https://github.com/RPCS3/rpcs3/pull/11568 kd mentioned this

> [Toy Story 3] requires full zcull sync on a texture semaphore which is just dumb. Strict mode is still required for that due to the performance penalty.
