### ISSUE TITLE
[Feature request] add qt fontengine settings?

### ISSUE THREAD

**Issue by kokutoukiritsugu** [RPCS3/rpcs3#12569]
### Quick summary

windows, 4k, 200% dpi scale.
horizontal strokes of letters soo bad.

![Snipaste_2022-08-28_17-28-15](https://user-images.githubusercontent.com/5471433/187067367-670eecec-aecb-49f0-8ede-99310cca3d6a.png)

### Details

on windows, 4k, 200% dpi scale.
qt default gui font render engine soo bad. chinese fonts are even worse.
some program can set fontengine on qt.conf
but on rpcs3, qt.conf not work.

example:
add this on windows pcsx2 qt.conf
```
[Platforms]
WindowsArguments = fontengine=freetype
```

the 'E', 'D'

![Snipaste_2022-08-28_17-30-05](https://user-images.githubusercontent.com/5471433/187067361-02fb11dd-8f9b-4366-b5b6-a20d36b82627.png)

the full compare 4k, 200% dpi scale freetype&default
'P', 'E', '5', 'D', 'F'

![Snipaste_2022-08-28_17-36-53](https://user-images.githubusercontent.com/5471433/187067599-fbe26e5d-b84b-4080-a90c-45145ef30b66.png)
![Snipaste_2022-08-28_17-36-36](https://user-images.githubusercontent.com/5471433/187067602-b889481d-69fb-476e-bde0-d80a8a25dddc.png)

**Comment by Darkhost1999** [comment]
You are able to change font color, font type, font size, font weight and probably more when editing the .qss files inside your gui configs folder. In order to not overwrite your changes when updating RPCS3 make sure you give your changes a unique name.
And I agree it'll be nice to have more control over the GUI in the GUI settings.
There are plenty of references among the gui configs files you can compare and contrast, test and try. The worst that'll happen is the .qss just reverts your changes from a certain point to the bottom of the file back to default.

**Comment by kokutoukiritsugu** [comment]
i mean the font render issue
not the font family

like no font Sub-Pixel-Antialiasing

![Snipaste_2022-08-29_11-24-22](https://user-images.githubusercontent.com/5471433/187116931-ca942112-4f5e-42e1-a327-d288b83507e5.png)

**Comment by kokutoukiritsugu** [comment]
i found a commandline to enable the freestyle font render engine.
`rpcs3.exe -platform windows:fontengine=freetype`

up
qt default font render engine
down
qt freetype font render engine

![Snipaste_2022-09-22_15-54-26](https://user-images.githubusercontent.com/5471433/191690248-68243b78-907b-4e84-b0b1-2a173f9d1c48.png)
![Snipaste_2022-09-22_15-54-18](https://user-images.githubusercontent.com/5471433/191690267-0515ac4c-4497-491c-9127-f0c9605d23d3.png)
