### ISSUE TITLE
How to get Vulkan Renderer on Intel?

### ISSUE THREAD

**Issue by WildMemes** [RPCS3/rpcs3#12566]
### Quick summary

Skylanders Giants won't boot due to OpenGL not working. I assume I need Vulkan but it isn't an option.

### Details

A few of the issues are stated in the log file

### Attach a log file

![image](https://user-images.githubusercontent.com/112265748/187036974-06200c3d-42a0-44ac-b19a-88bf24e6dad4.png)

![image](https://user-images.githubusercontent.com/112265748/187037039-c6b521fa-437e-400b-8db3-5f0a328b42c5.png)

### System configuration

Intel(R) HD Graphics - Version 10.18.10.5059

**Comment by MSuih** [comment]
It does not boot because your GPU doesn't support the OpenGL 4.3 features that RPCS3 requires. The missing features are printed to log. Your OpenGL support is limited because Intel has stopped supporting this GPU, whicj is also why you can't enable Vulkan on that GPU.

You'll need to upgrade your hardware to something that at least meets the minimum requirements listed in our [quickstart guide](https://rpcs3.net/quickstart). Try to exceed the recommended requirements as well.
