### ISSUE TITLE
“RPCS3.app” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by rakleed** [RPCS3/rpcs3#12679]
### Quick summary

When running RPCS3 on macOS, the following error appears: `“RPCS3.app” cannot be opened because the developer cannot be verified.`

### Details

When launching a macOS app, I get this error: `“RPCS3.app” cannot be opened because the developer cannot be verified.` As I understand, this is because your app is not signed with a certificate that you need to buy from Apple for $99 per year.

And if you think such spending is irrational, then it would be nice if you mentioned in [Quickstart](https://github.com/DAGINATSUKO/www-rpcs3/blob/master/public_html/quickstart.php) that users need to open the app once at the first start and after the update by clicking on it while holding Ctrl.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9595495/RPCS3.log)

### System configuration

macOS 12.6

### Other details

![Screenshot 2022-09-19 at 02 39 13](https://user-images.githubusercontent.com/19418601/190933050-be8ead35-6954-4ea4-85ff-db2c1160d526.png)

**Comment by AniLeo** [comment]
While this can be added to the guide just to be safe, this is OS behaviour not specific to RPCS3 that users should already know when downloading programs.

This is the equivalent of going around the SmartScreen warning on Windows by pressing "More Info".

**Comment by marcoluc97** [comment]
Yeah I think so, i mean is also something pretty common for FOSS unfortunately but is also understandable in most case if there is not a company behind development.

**Comment by banagale** [comment]
Thought I'd upvote this, as some macOS applications distributed via GH do get a distribution certificate.

IIRC, macOS now defaults to not allowing running apps lacking certification. So, adding a note to the macOS docs noting that the error may appear and writing or linking out to the steps to get around this blocker would be a good idea.

I came here after wanting to simply verify the project does not distribute signed macOS just in case the project was under attack.  Would be better to furnish this info in the official docs rather than requiring it be sleuthed from an open issue.

I would be happy to do a PR for these changes, but did not see an easy link for how to modify the project docs or find an easy example of docs changes in a closed issue when searching for "update documentation."

**Comment by MortenHofft** [comment]
In my case I'm not allowed to bypass this (by going to settings and allow it) as my machine is under partial administration by the university.

**Comment by RipleyTom** [comment]
Just to be clear, the only way to have your application certified is to sign up for the Apple developer program, which costs 99$ per year. There is no way in hell we're paying Apple to sign our free and open source program.
