### ISSUE TITLE
My Computer don't enable PPU Recompiler ( LLVM )

### ISSUE THREAD

**Issue by zminhquanz** [RPCS3/rpcs3#1277]
![image](https://cloud.githubusercontent.com/assets/11285640/10810042/78ca2ce2-7e2f-11e5-883e-3861f0cc0210.png)
Please fix this on the next build version

**Comment by tambry** [comment]
@zminhquanz This is most likely caused by your build not including the LLVM recompiler. To compile with LLVM select the profile as "Release - LLVM" in Visual Studio. If you're not compiling yourself, you could ask someone to compile you a build with LLVM included.

I think @Bigpet compiles some builds with DX12 and LLVM [here](https://github.com/Bigpet/rpcs3/releases).
