### ISSUE TITLE
[Regression] Audio crackling issue/Demon's Souls (#12751)

### ISSUE THREAD

**Issue by 2mg** [RPCS3/rpcs3#12833]
### Quick summary

Audio crackling/stuttering issue with newer 0.0.24 versions.

### Details

Demon's Souls BLUS30443 worked fine with 0.0.23 releases, and the very first 0.0.24 release, but on latest 0.0.24 the issue arises.

Issue is audio crackling/stuttering that wasn't present before.

Clicked Yes to clean old entries in custom and emulator config menu when updater prompted for it.

No other changes to game or custom config was made when updating.

### Build with regression

0.0.24-14285-035d410a Alpha | master

### Attach two log files

[0.0.23 RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9805491/0.0.23.RPCS3.log.gz)
[0.0.24 RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9805493/0.0.24.RPCS3.log.gz)

### System configuration

R5 3600, 1060 6G, W10 21H2.

No HW changes between old and new RPCS3 versions.

### Other details

No audio issues in 0.0.23 releases, no audio issue in first 0.0.24-14104 (#12590) release, audio issues in 0.0.24-14285.

No hardware changes, no config changes, no game changes in the process.

**Comment by RainbowCookie32** [comment]
"0.0.23 releases" is not really giving us any meaningful info of when the issue started, there are a lot of builds on that release cycle.
You have to find the actual build that introduced the issue for you if you want to report a regression. See [this wiki article](https://wiki.rpcs3.net/index.php?title=Help:Using_different_versions_of_RPCS3#How_to_find_the_build_that_caused_a_regression?) for an efficient way of regression testing.

**Comment by solarmystic** [comment]
Seems to affect Soul Calibur IV as well based on this discord help request and resolution. 

https://discord.com/channels/272035812277878785/277227681836302338/1031788498908364811

**Comment by solarmystic** [comment]
> I don't know how much more exact can I be here.

@2mg What he means is that its not enough to just quote the latest master build (0.0.24-14285-035d410a) and claim that it is the one to introduce the problem, when it clearly isn't, since the last build you tested that worked properly is the first build of 0.0.24 (0.0.24-14104)

There are 100+ builds in between the latest master and that working build you stated, and within one those builds lies the true culprit.

You, as the issue reporter, have the responsibility in isolating the true culprit, that was his point. Otherwise the developers will not be able to act on the issue and it will be stuck in github limbo.

In order to that, you have perform what is called extensive regression testing. The guide is as follows:-

As quoted from the rpcs3 bot:-

If you found a regression (an issue that only started happening recently) and want it to be fixed, then you must figure out which exact version broke it and report it on appropriate channels. But first, make sure the issue hasn't already been reported by doing a quick search: https://github.com/RPCS3/rpcs3/issues If it hasn't been reported, follow the steps:

1. Go to https://rpcs3.net/compatibility?b, download an old build of RPCS3 that's in-between the build where you ran into the issue and a build where it was working.
2. Extract the RPCS3.exe file, rename it to e.g RPCS3-<version>.exe then place it in your rpcs3 folder.
3. Test the version you downloaded to see if it has the issue or not.
3a. If it does, assume all versions after it are broken.
3b. If it doesn't, assume all versions before it are working.
4. Go back to step 1 using the new version range until you have figured out which exact version caused the issue.
5. Once you've identified the build that caused the issue, go to https://github.com/RPCS3/rpcs3/issues/new/choose, create a regression report which follows the template, and make sure you note the exact build number/pull request where it started happening.

**Comment by 2mg** [comment]
@solarmystic 

"download an old build of RPCS3 that's in-between the build where you ran into the issue and a build where it was working."

I apologize, but I believed that providing info that 0.0.23 builds worked, that the start of 0.0.24 worked and the latest 0.0.24 broke something. 0.0.23 builds fit the _old build_ criteria, and the first 0.0.24 build fits the _in-between criteria_, but obviously it needs a more granular, finer approach approach.

I'll try a few on a week per week basis, is that good enough?

**Comment by AniLeo** [comment]
We need to know the exact PR that broke it, read the guidelines for regression reports. 
If we don't know the PR then it's impossible to ping the developer and the ticket will just go obsolete.

**Comment by YuriNator557** [comment]
14218 is #12751 
@elad335
