### ISSUE TITLE
[Regression] Silent Hill HD Collection - Installing trophies message does not disappear (#11935)

### ISSUE THREAD

**Issue by Jonathan44062** [RPCS3/rpcs3#12862]
### Quick summary

Without realizing it, the game is in regression only for this message, it is not removed somehow, but of the games itself, there is no problem, there is only that.

### Details

Working - 0.0.22-13565
![image](https://user-images.githubusercontent.com/78843189/197311313-cbe55de6-07d8-4069-bfff-e3c7254500b9.png)

Regression - 0.0.22-13570 [#11935](https://github.com/RPCS3/rpcs3/pull/11935) 
![image](https://user-images.githubusercontent.com/78843189/197311398-2d81a3f7-7a4c-4519-b4b0-42515247ef35.png)

### Build with regression

0.0.22-13570

### Attach two log files

Working
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9843297/RPCS3.log.gz)

Regression
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9843302/RPCS3.log.gz)

### Attach capture files for visual issues

None

### System configuration

Windows 10 21H2
Intel Core i7-8700
15.93 GiB RAM
GPU: NVIDIA GeForce GTX 1070 Ti (516.79)

**Comment by Megamouse** [comment]
The issue here is that the game tries to register an non-existing trophy file.
The sceNpTrophyRegisterContext function then first calls the statusCallback which contains code to open that progress dialog, and then fails because the file is not found.

It seems logical that we should somehow call the statusCallback with a proper error status again whenever sceNpTrophyRegisterContext fails, in order to give the game a chance to deal with the previously opened dialog.

**Comment by Megamouse** [comment]
Or it's just missing permissions on the file.

**Comment by elad335** [comment]
I think it's because sceNpTrophyCreateContext should fail here, look at commSign.

**Comment by Jonathan44062** [comment]
Master:
![image](https://github.com/RPCS3/rpcs3/assets/78843189/bf946833-337f-4eb9-a176-aec47e70e5d6)

PR:
![image](https://github.com/RPCS3/rpcs3/assets/78843189/ed230ab3-46e6-48cb-8771-6d4200ebf74b)

Can confirm, this fixes the issue https://github.com/RPCS3/rpcs3/pull/14040
