### ISSUE TITLE
FPS issue

### ISSUE THREAD

**Issue by branciUwU** [RPCS3/rpcs3#12942]
### Quick summary

I have been trying to play GOW3 in my computer, but the game stays at 10-20 fps while im playing but then in cut sceens it shoots up to 60fps.
I dont know why im having this problem because my computer can run virtually run any modern game with 200+ fps without a problem.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9992755/RPCS3.log)

### System configuration

- Windows 11
- i5-10500H CPU @ 2.50GHz
- NVIDIA GeForce RTX 3060 Laptop GPU
- 16GB Ram

**Comment by Jonathan44062** [comment]
Ask for help in RPCS3 server Discord, not on github issues
Also, native PC Games vs Emulation are totally different, emulating a PS3 console is hard

**Comment by MSuih** [comment]
Cutscenes are prerendered, you're just playing back a video file. That's why they run at locked 60 fps.

The performance you mentioned is roughly what you should expect from that CPU. You can join our Discord and ask for tuning suggestions to squeeze out some extra frames, but do keep in mind that GoW3 is very heavy game to run and requires strong desktop CPU for console-level performance.

**Comment by branciUwU** [comment]
> Cutscenes are prerendered, you're just playing back a video file. That's why they run at locked 60 fps.
> 
> The performance you mentioned is roughly what you should expect from that CPU. You can join our Discord and ask for tuning suggestions to squeeze out some extra frames, but do keep in mind that GoW3 is very heavy game to run and requires strong desktop CPU for console-level performance.

ok thanks, but cant i use mt gpu to run the game?
