### ISSUE TITLE
PPU Recompiler can be support SSSE3

### ISSUE THREAD

**Issue by zminhquanz** [RPCS3/rpcs3#1298]
Please developer support it , i'm using core 2 quad q6600 and it's doesn't support SSE 4.1

**Comment by tambry** [comment]
@zminhquanz You wont be able to run literally anything with such an old CPU. Best case scenario, if you would be able to even render a cube, with a couple FPS.

If you want a performance estimate, use the Interpreter 2. Also PPU Recompiler is currently very inaccurate compared to the Interpreter 1/2. Chances are you wouldn't even be able to start a bigger game, without it crashing due to the problems with the recompiler.
