### ISSUE TITLE
[Feature Request] Add option to boot with log to manually select configuration

### ISSUE THREAD

**Issue by Darkhost1999** [RPCS3/rpcs3#13225]
### Quick summary

I noticed that when the utilities -> check configuration option was added to RPCS3 that the ability to check configurations from log files was added and would like to request that the feature is added to booting games with manually selected configuration. That if there are multiple configurations in a log only 1 is used.

### Details

This can benefit users, testers, and others alike to reproduce issues cause all you gotta do is take the log from someone boot the game with that log file and see if you get the same issue.
You could just open the log -> copy and paste the configuration into a new text document and rename it config.yml yet the feature to check configs from logs alreasy exists and can save some small time while adding convenience.
I'm sure not many people use the boot with manually selected config file but this added convenience can most certainly improve reproducing issues and can encourage people using the option more frequently.
If a user is unsure about settings someone can upload their log of the game working great and the user that is unsure can just boot that file and see there's nothing to be unsure about.

**Comment by Darkhost1999** [comment]
> I've tested around 600 of games, and never once felt the need for this to be a thing or to copy people's shitty settings from their logs as 99% of people use some bad settings.

That's the entire reason of this feature request right there illustrated in text.
To assist people attempting to reproduce someone else's issues not need to COPY someone else's settings but hey instead of saying to the end user "I couldn't replicate your issue" replicate the issue by using their settings and tell them which settings are bad and close an extra hundred or 200 issues.

**Comment by Darkhost1999** [comment]
Were you just having a bad day. Can I buy you a cup of coffee?

**Comment by Asinin3** [comment]
And for what reason would you ever want to re-produce someones bad settings to see why they are having issues when THEY should just.. use the correct settings and be done with it? Its so pointless. Tri-state configs, or pulling settings from wiki/db is something that will actually help.

I haven't seen a single other person asking for this in the 6 years I've been in the server, and basically no comments on this request, nor any real reason for it, so I closed it. Our Issue tracker becomes a giant mess of "feature requests" that people do not want to implement or have any interest in otherwise. And I don't mind stepping on some toes if it means less issue spam.
