### ISSUE TITLE
RPCS3 crashes when opening a Game - Vulkan Error

### ISSUE THREAD

**Issue by DatBoyMax** [RPCS3/rpcs3#13344]
### Quick summary

The app throws an error up and then hangs until closed via task manager when opening a game/xmb

### Details

I just tried opening the XMB and this error came up. I used to use rpcs3 on this same computer months ago but deleted it. just reinstalled today and this happened?

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/10593531/RPCS3.log)
<img width="960" alt="image" src="https://user-images.githubusercontent.com/74514964/216735392-f6eb5458-1886-4048-ba28-d8867d86c560.png">

**Comment by kd-11** [comment]
You may be asking too much of the intel drivers. To debug a possibility why the crash could be happening you need to follow these steps:
1. Install the vulkan SDK for windows. Check the lunarG site for details.
2. Enable the debug settings menu for rpcs3
3. Enable "Debug output"
4. Run the app until it crashes.
5. Attach the log to this report.

**Comment by DatBoyMax** [comment]
If now i'm asking too much, how come it worked a few months ago?

**Comment by kd-11** [comment]
> If now i'm asking too much, how come it worked a few months ago?

Different drivers, different emulator features, etc.
If you're not going to be helpful in solving a bug that affects you, close the ticket.

**Comment by elrod829** [comment]
I am also having this issue

`RPCS3 v0.0.27-14800-0d34b979 Alpha | master
11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz | 8 Threads | 15.70 GiB RAM | TSC: 2.803GHz | AVX-512+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 22621, Service Pack: none, Compatibility mode: 0
Qt version: Compiled against Qt 5.15.2 | Run-time uses Qt 5.15.2
Current Time: 2023-03- 5T16:38:23`

`·A 0:00:33.837519 RSX: Found vulkan-compatible GPU: 'Intel(R) Iris(R) Xe Graphics' running on driver 0.405.50
·W 0:00:33.837561 RSX: Dedicated transfer+compute queue was not found on this GPU. Will use graphics queue instead.
·E 0:00:33.837563 RSX: Your GPU does not support double precision floats in shaders. Graphics may not render correctly.
·! 0:00:33.837564 RSX: GPU/driver supports float16 data types natively. Using native float16_t variables if possible.
·F 0:00:33.845504 SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\vkutils\device.cpp:646[:3], in function create)
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\vkutils\shared.cpp:107[:24], in function die_with_error)
·W 0:00:33.850487 SYS: Emulation has been frozen! You can either use debugger tools to inspect current emulation state or terminate it.
·! 0:00:43.208087 {Performance Sensor} SYS: CPU Usage: Total: 1.6%, Cores: 4.7%, 0.0%, 1.6%, 1.6%, 1.6%, 0.0%, 3.2%, 0.0%
·! 0:00:53.210504 {Performance Sensor} SYS: CPU Usage: Total: 5.5%, Cores: 4.7%, 4.7%, 6.3%, 9.4%, 14.1%, 1.6%, 1.6%, 1.6%
·! 0:01:03.215094 {Performance Sensor} SYS: CPU Usage: Total: 0.8%, Cores: 0.0%, 0.0%, 3.2%, 0.0%, 1.6%, 0.0%, 1.6%, 1.6%
·! 0:01:13.217677 {Performance Sensor} SYS: CPU Usage: Total: 1.4%, Cores: 1.6%, 1.6%, 3.2%, 1.6%, 1.6%, 0.0%, 1.6%, 0.0%
·! 0:01:23.221574 {Performance Sensor} SYS: CPU Usage: Total: 3.4%, Cores: 4.8%, 1.6%, 6.3%, 3.2%, 4.8%, 1.6%, 1.6%, 3.2%
·! 0:01:33.224092 {Performance Sensor} SYS: CPU Usage: Total: 0.4%, Cores: 0.0%, 1.6%, 1.6%, 0.0%, 0.0%, 0.0%, 0.0%, 0.0%
·! 0:01:43.226735 {Performance Sensor} SYS: CPU Usage: Total: 0.4%, Cores: 3.2%, 0.0%, 0.0%, 0.0%, 0.0%, 0.0%, 1.6%, 0.0%
·! 0:01:53.228895 {Performance Sensor} SYS: CPU Usage: Total: 0.2%, Cores: 0.0%, 0.0%, 1.6%, 0.0%, 0.0%, 0.0%, 0.0%, 3.1%
·! 0:02:03.231355 {Performance Sensor} SYS: CPU Usage: Total: 2.4%, Cores: 3.1%, 1.6%, 4.7%, 1.6%, 3.1%, 1.6%, 1.6%, 1.6%
·! 0:02:13.234983 {Performance Sensor} SYS: CPU Usage: Total: 1.6%, Cores: 4.7%, 3.1%, 0.0%, 0.0%, 3.1%, 1.6%, 0.0%, 0.0%
·! 0:02:23.237639 {Performance Sensor} SYS: CPU Usage: Total: 1.8%, Cores: 0.0%, 4.7%, 3.1%, 4.7%, 0.0%, 0.0%, 0.0%, 1.6%`
^hangs here

**Comment by kd-11** [comment]
Reinstall your driver. The game didn't even start.
