### ISSUE TITLE
[NPJB00512] Mobile Suit Gundam Extreme VS Full Boost-Disconnect after the game starts

### ISSUE THREAD

**Issue by JumpingY** [RPCS3/rpcs3#13599]
### Quick summary

I host RPCN locally.Devices are connected through wired router.
Always disconnected after starting a game .
Mainly from the connection between AMD platform and Intel platform.

### Attach a log file

[RPCS3-Intel.log.gz](https://github.com/RPCS3/rpcs3/files/11128804/RPCS3-Intel.log.gz)
[RPCS3-AMD.log.gz](https://github.com/RPCS3/rpcs3/files/11128805/RPCS3-AMD.log.gz)

### System configuration

AMD case:
CPU:3700X
RAM:32G DDR4 3200Mhz
GPU:GTX1660

Intel case:
CPU:12400F
RAM:16G DDR4 3200Mhz
GPU:GTX3050

### Other details

Network adapters are Realtek

**Comment by kubacAkaGoomba** [comment]
This issue sounds oddly familiar to a problem with joining players between AMD and Intel CPUs on LittleBigPlanet games - https://github.com/RPCS3/rpcs3/issues/13449

**Comment by descatal** [comment]
After some extensive investigation, it has been determined that the disconnect is caused by out of sync coordinates between users. 

The game originally has a sync mechanism where it will forcefully disconnect players who does not have synced up states, thus not allowing illegal moves / dropped frames causing parallel universes.

What we found is that if we start the game (between different CPU brands) and just stay there, the game will still continue without any issue, even using weapons and reducing HP is fine as long as you don't change the coordinates of either player. 

Hope this can narrow down the scope of investigation, and we'll be lucky if it is just caused by one instruction between two CPU that's outputting different calculation.

**Comment by maxmadzz** [comment]
This issue has reappeared in the recent Git version.
