### ISSUE TITLE
Call of Duty Modern Warfare 3

### ISSUE THREAD

**Issue by Gerold55** [RPCS3/rpcs3#13654]
### Quick summary

When booting up the game the menus are fine. When loading into the game it takes forever to load up the maps and then once it does it runs @ 10-15fps....

### Details

On the ps3 version it runs at roughly 60fps and on rpcs3 it runs @ less than 30fps

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11224431/RPCS3.log.gz)

### Attach capture files for visual issues

![Screenshot (20)](https://user-images.githubusercontent.com/13843095/231827067-e66e42c0-f652-4dc5-832d-a685d4a7d65a.png)

### System configuration

Ram: 8GB
CPU: Intel Core i5-9300H
GPU: Nvidia Geforce GTX 1650

**Comment by Darkhost1999** [comment]
This sounds like a compatibility report.
The fps is to be expected.
The time it takes to load a map the 1st time is to be expected.
The black textures is unfortunately to be expected with a similar issue to the Far Cry 3 and Far Cry 4 games.
The black textures will hopefully be reworked and fixed with the surface cache and texture inconsistencies. But I'm wondering what is the goal of this issue ticket?
What clear objective is trying to be acheived?

**Comment by YuriNator557** [comment]
Performance is going to be low on your PC, this is expected

**Comment by AniLeo** [comment]
Closing as this is a compatibility report
