### ISSUE TITLE
[Regression] Rock Band 3 [BLUS30463] - Hangs after the splashes (#9760)

### ISSUE THREAD

**Issue by Sl3dge78** [RPCS3/rpcs3#13663]
### Quick summary

Rock Band 3 [BLUS30463] hangs (black screen) after the splashes, after the ea logo. The emulator stays responsive but the game doesn't progress further. 

rpcs3-v0.0.19-13075-49c02854 > No issue
rpcs3-v0.0.19-13082-e3e39e8d > Issue started appearing here

Here are both version's logs
[RPCS3_13075.log](https://github.com/RPCS3/rpcs3/files/11239073/RPCS3_13075.log)
[RPCS3_13082.log](https://github.com/RPCS3/rpcs3/files/11239074/RPCS3_13082.log)

### Details

Upon booting the game, the splashes display fine, until the EA logo then the game stays on a black screen at 20 fps indefinitely.  

The log in the main window has a couple of 
```E SYS: '_sys_lwmutex_lock' failed with 0x80010005 : CELL_ESRCH [3]```
Reverting to 0.0.27-14845, clearing caches and reinstalling the game doesn't fix the issue.  
I've tried tweaking the configs with threading and stuff to no avail.

Let me know if you need anything else. 

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11237294/RPCS3.log)

### System configuration

OS: EndeavourOS Linux x86_64 
Host: MS-7917 1.0 
Kernel: 6.2.10-arch1-1 
Uptime: 2 hours, 59 mins 
Packages: 1040 (pacman) 
Shell: bash 5.1.16 
Resolution: 1920x1080, 2560x1440 
DE: Cinnamon 5.6.8 
CPU: Intel i7-4771 (8) @ 3.900GHz 
GPU: NVIDIA GeForce RTX 2060 SUPER 
Memory: 4869MiB / 23982MiB 

### Other details

Did a full system upgrade prior to testing so drivers should be up to date. 
Haven't tried a lot of games, but Rock Band 2 [BLUS30147] works perfectly so far. 

Also did a check of the game with [blu-ray disc validator](https://wiki.rpcs3.net/index.php?title=Help:Validating_PlayStation_3_game_dumps#Validating_Blu-ray_disc_games) as instructed on the help channel on discord.

**Comment by solarmystic** [comment]
> Reverting to 0.0.27-14845, clearing caches and reinstalling the game doesn't fix the issue.
> I've tried tweaking the configs with threading and stuff to no avail.

You need go further back then, and figure out which is the exact build that broke it, otherwise the devs cannot fix this.

1. Go to https://rpcs3.net/compatibility?b, download an old build of RPCS3 that's in-between the build where you ran into the issue and a build where it was working.
2. Extract the RPCS3.exe file, rename it to e.g RPCS3-<version>.exe then place it in your rpcs3 folder.
3. Test the version you downloaded to see if it has the issue or not.
3a. If it does, assume all versions after it are broken.
3b. If it doesn't, assume all versions before it are working.
4. Go back to step 1 using the new version range until you have figured out which exact version caused the issue.
5. Once you've identified the build that caused the issue, go to https://github.com/RPCS3/rpcs3/issues/new/choose, create a regression report which follows the template, and make sure you note the exact build number/pull request where it started happening.

**Comment by Sl3dge78** [comment]
Ok finally found the build that introduced the issue.
rpcs3-v0.0.19-13075-49c02854 > Works
rpcs3-v0.0.19-13082-e3e39e8d > Doesn't work

Here are both version's logs
[RPCS3_13075.log](https://github.com/RPCS3/rpcs3/files/11239073/RPCS3_13075.log)
[RPCS3_13082.log](https://github.com/RPCS3/rpcs3/files/11239074/RPCS3_13082.log)

**Comment by Asinin3** [comment]
That means #9760 broke it. The PR referrs to PPU LLVM. Does it work on latest with PPU Interpreter on cpu tab?

**Comment by Sl3dge78** [comment]
Latest and 13082 don't work with the PPU in interpreter.

**Comment by AniLeo** [comment]
We need a retest on this bug on latest build just in case as #13807 was merged

**Comment by Sl3dge78** [comment]
Issue is fixed I'm closing the issue, thank you!
