### ISSUE TITLE
[Regression] F1 Championship Edition new visual glitch (#13608)

### ISSUE THREAD

**Issue by DoctorTangible** [RPCS3/rpcs3#13685]
### Quick summary

This visual glitch appears when entering any race, screen flickering everywhere.

![Sin títulofdsa](https://user-images.githubusercontent.com/130948960/232365635-b035b889-85b1-4228-9a82-e15dc6dde407.png)

### Details

When I updated RPCS3 to newer builds it started flickering, v0.0.27-14854-6fbca1ac and earlier did not glitch the game.

### Build with regression

v0.0.27-14876-44b3709d

### Attach two log files

Build with regression
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11245704/RPCS3.log.gz)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11245703/RPCS3.log.gz)
Build that works

### Attach capture files for visual issues

https://mega.nz/file/Ey5wmIpY#VM_SCEYihbe7Z52tJzFywiBnobnVF8xHZp8GgFmD0Ag
Capture file for visual issues

### System configuration

NVIDIA GeForce GTX 1660 SUPER running on driver 516.94.0.0
Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Windows 10
16gb RAM

**Comment by Triticum0** [comment]
Turn off rpcn status to fix the issue

**Comment by DoctorTangible** [comment]
@Triticum0 Noice, I don't know why it works but thank you.

**Comment by Asinin3** [comment]
You should never close an issue just because you found a work-around, this is an issue tracker for helping us develop the emulator. Not a support forum... I will re-open but it should be fixed by the recent PR. Test the PR build with RPCN setting enabled and see if it fixes it. https://github.com/RPCS3/rpcs3/pull/13723 > Windows details for Cirrus > View more details at Cirrus Ci > Artifact > download it and use the rpcs3.exe and test.

**Comment by Frenthor** [comment]
One of the RPCS3 testers from discord gave me this build (https://api.cirrus-ci.com/v1/artifact/task/4813002168336384/Artifact/rpcs3-v0.0.27-6c6796d8_win64.7z) as Diablo 3 was encountering this same issue when network status is connected. Graphics glitch disappeared when I used it, even when network status is connected and RPCN is turned on.

**Comment by Triticum0** [comment]
@AniLeo This can be closed
