### ISSUE TITLE
Newest update not allowing saving in AC4

### ISSUE THREAD

**Issue by Dragon0TWest** [RPCS3/rpcs3#13819]
### Quick summary

when playing armored core 4, whenever i attempt to save my game it will deadlock and will not save

### Details

during play, whenever i click to save or the game itself attempts to save, it will simply freeze 
<img width="1280" alt="Screenshot 2023-05-06 150005" src="https://user-images.githubusercontent.com/78452314/236646423-470cb2a1-e0bf-44da-9abb-a36ab07801fa.png">

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11413397/RPCS3.log.gz)

### System configuration

nvidia rtx 3060
amd ryzen 7
current geforece experience driver

**Comment by solarmystic** [comment]
Your report is incomplete. What is the last build saving worked correctly?

Do proper regression testing, and figure it out, otherwise this issue cannot be fixed by the developers:-

1. Go to [Builds History](https://rpcs3.net/compatibility?b), download an old build of RPCS3 that's in-between the build where you ran into the issue and a build where it was working.
2. Extract the RPCS3.exe file, rename it to e.g RPCS3-<version>.exe then place it in your rpcs3 folder.
3. Test the version you downloaded to see if it has the issue or not.
  * If it does, assume all versions after it are broken.
  * If it doesn't, assume all versions before it are working.
4. Go back to step 1 using the new version range until you have figured out which exact version caused the issue.

**Comment by solarmystic** [comment]
Also, just tested saving using the US version of the game (BLUS30027) on the latest master of rpcs3 (0.0.27-14980) and it works perfectly

https://user-images.githubusercontent.com/4345150/236662025-3de83157-17dd-4517-a893-56f28b361fc0.mp4

**Comment by Dragon0TWest** [comment]
what settings do you have for the game in the gpu settings, cause everytime i go to save it does that small black it did at th end of your recording but stays there

**Comment by solarmystic** [comment]
My settings are irrelevant for this issue. I'm just using the defaults + WCB and RCB as recommended by the wiki page for the game.  

What is relevant is that you **still** haven't done proper regression testing on your end to determine which build started not to work for you for saving in this game. 

1. Go to [Builds History](https://rpcs3.net/compatibility?b), download an old build of RPCS3 that's in-between the build where you ran into the issue and a build where it was working.
2. Extract the RPCS3.exe file, rename it to e.g RPCS3-<version>.exe then place it in your rpcs3 folder.
3. Test the version you downloaded to see if it has the issue or not.
  * If it does, assume all versions after it are broken.
  * If it doesn't, assume all versions before it are working.
4. Go back to step 1 using the new version range until you have figured out which exact version caused the issue.

**Comment by Dragon0TWest** [comment]
so it started working about an hour ago, not sure why it was being stupid.
i wonder if maybe the save had corrupted itself somehow
