### ISSUE TITLE
Booting test on arm64 linux build?

### ISSUE THREAD

**Issue by mio-19** [RPCS3/rpcs3#13998]
### Quick summary

rpcs3 now has basic support for arm64. So I built it on archlinux arm for testing using script from AUR https://aur.archlinux.org/packages/rpcs3-git

Every test elf stuck on building SPU if I use LLVM Recompiler or ASMJIT Recompiler
Linking PPU modules took a very long time or stuck.

When I chose both Interpreter for SPU and PPU I got the following error

```
RPCS3: RSX [0x0001614]: SIG: Thread terminated due to fatal error: Unhandled GL format 0x8058
(in file /home/user/.cache/paru/clone/rpcs3-git/src/rpcs3/rpcs3/Emu/RSX/GL/glutils/image.cpp:118, in function texture) (errno=16=Device or resource busy)
```

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11714201/RPCS3.log)

**Comment by kd-11** [comment]
This is a not-our-bug situation, which to me indicates a misbehaving OpenGL driver (mobile phone?). glGetTexLevelParameteriv returns 0 for the channel size on query which is why you get this error. Desktop OGL has different requirements than GLES which probably means some functions may be stubs in place of a real implementation. Format 0x8058 is GL_RGBA8 which is the most common format for use here.

**Comment by mio-19** [comment]
> This is a not-our-bug situation, which to me indicates a misbehaving OpenGL driver (mobile phone?). 

Linux container on arm chromebook

**Comment by kd-11** [comment]
Then probably a configuration issue, because it would seem that proper OpenGL support is lacking. Maybe it's falling back to a minimal driver with desktop capabilities but it certainly is not doing GL4.3. If you want to debug further, you can disable the native interface in the emulator tab. It will still crash before rendering anything, but some more information will be dumped to the log about which driver was loaded and some basic capabilities.

**Comment by MSuih** [comment]
Container might be using virtual GPU which usually is very restricted with capabilities as it is only intended for simple desktop applications.
