### ISSUE TITLE
Launcher freeze when starting a game

### ISSUE THREAD

**Issue by Healsu** [RPCS3/rpcs3#14036]
### Quick summary

The launcher is freezing indefinitely when opening a game

### Details

After having tested a game where it runned perfectly, after trying to open same game or others again the launcher just freeze withouth any sign of stopping

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11772922/RPCS3.log)

**Comment by Asinin3** [comment]
Right-click the game > remove > remove all caches - Demon's Souls can hang on load screens sometimes if you dont.
Disable framelimiter (the game has a framerate cap already, using limiter only makes it run slower).
Validate your game files, this issue is likely to do with that, your game looks pirated/illegal and this is a known issue that can happen in those cases... Closing
