### ISSUE TITLE
Gran Turismo 6 freeze after getting a medal in National B

### ISSUE THREAD

**Issue by dangouseboy** [RPCS3/rpcs3#14041]
### Quick summary

When I finished any race in National B and get a meal for that race, the game will freeze at the moment when I exit the race. 
It seems that it won't freeze if I didn't get a medal for the race. 
Log file is attached.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11778663/RPCS3.log.gz)

**Comment by Asinin3** [comment]
Dont post issues without confirming they can be reproduced, and having a save on where they can be reproduced etc. Also settings are odd.. 75% res scale wont help perf and will only look worse than 100%. SPU Loop should be off. 4 SPU Preferred threads instead of auto..?

**Most importantly, you are on game ver 1.00 instead of 1.02 which fixes a crash in the game. The issue was fixed by the developers of the game.**
