### ISSUE TITLE
[Regression] [macOS] Build failure after #14065

### ISSUE THREAD

**Issue by shinra-electric** [RPCS3/rpcs3#14067]
### Quick summary

Build fails on `RSX/VK/vkutils/sync.cpp` after #14065

### Build with regression

#14065

### Attach two log files

[RPCS3 00cca7b (Success).txt](https://github.com/RPCS3/rpcs3/files/11834049/RPCS3.00cca7b.Success.txt)
[RPCS3 715e385 (Fail).txt](https://github.com/RPCS3/rpcs3/files/11834051/RPCS3.715e385.Fail.txt)

### System configuration

M1 MBP

**Comment by kd-11** [comment]
Ok, I checked the clang support for the "parenthesized initialization of aggregates" feature and it shows as supported in clang16.
I'm guessing xcode is just too outdated here and doesn't actually support c++20

**Comment by shinra-electric** [comment]
Xcode supports up to C++23, though I don't know if it supports every feature. 

[Here is a list](https://developer.apple.com/xcode/cpp) for your reference.

As far as I remember, the CI uses Xcode 14.0.

**Comment by kd-11** [comment]
From that list it seems to not support the feature. But the CI version would also not work in that case. I hate that apple only shows what they support instead of a feature matrix including what they don't support. Clang however has this at https://clang.llvm.org/cxx_status.html
The section that is making the build fail is "parenthesized initialization of aggregates". We can work around it by replacing the construction with an initializer list.

**Comment by shinra-electric** [comment]
I'm not able to install Xcode 14.3.1 to test, since I'm on macOS 14 and it won't run. 

If you'd like I'll close this issue for now, and will re-open if it's still a problem once Xcode 15 gets out of beta. (Or if someone else on Xcode 14 can confirm it's not working there either).

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/14070 should fix this
