### ISSUE TITLE
[BCKS10276] The Evil Within (Intro random crash)

### ISSUE THREAD

**Issue by darkuser89** [RPCS3/rpcs3#14071]
### Quick summary

Start new game and don't skip the intro, the game hangs always in the intro

`Verification failed
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\vkutils\image.cpp:454[:3], in function get_view)`

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/11839598/RPCS3.log)

### System configuration

RPCS3 v0.0.28-15225-715e3856 Alpha | master | FW 4.90 | Windows 11 22H2
AMD Ryzen 7 7700X | 16 Threads | 31.15 GiB RAM | AVX-512+ | FMA3
GPU: NVIDIA GeForce RTX 3060 (536.23)

**Comment by Asinin3** [comment]
Does it happen in OpenGL?

**Comment by kd-11** [comment]
Reproduced as reported. Very strange bug indeed.

**Comment by kd-11** [comment]
Ok, it's caused by some silent change (surface addresses changed, formats didn't) that doesn't invalidate the textures correctly. Reference is detected as expired and reloaded (correctly) but the shader configuration isn't changed because the state bits aren't flagged. Leaving this as a note-to-self so I don't forget.
