### ISSUE TITLE
[Feature request] Logitech G29 (PS3 mode) support

### ISSUE THREAD

**Issue by Yuuyatails** [RPCS3/rpcs3#14085]
### Quick summary

I noticed that one PS3-compatible racing wheel that is missing from the support peripheral list is the Logitech G29. The G29 has a toggle switch on the top of the wheel that switch the wheel mode between PS3 mode and PS4 mode, and for the PS3, the PS3 mode is used.  Currently, RPCS3 doesn't detect the G29 regardless of the handler even after switching to PS3 mode and the WinUSB driver downgrade.

Hardware ID of the G29 in PS3 mode is USB\VID_046D&PID_C24F

**Comment by Yuuyatails** [comment]
Nevermind; it seems that the G29 is supported, but is treated as a G27.

**Comment by leillo1975** [comment]
The truth is that it would be great to connect my G29, which is an official PS3/PS4 peripheral, to enjoy my driving games, but there doesn't seem to be much enthusiasm in giving this support. I guess they will have other preferences. 
The only reason I bought my PS3 was to enjoy Gran Turismo 5 and 6, and the only reason I use RPCS3 is to use these games on my PC, instead of the sofa, as I could use my steering wheel more easily.

I do not see where it is supported, by the way, it does not work for me, and I use Linux (Ubuntu 22.04). I think this issue should be reopened

**Comment by RipleyTom** [comment]
https://wiki.rpcs3.net/index.php?title=Help:Peripherals_and_accessories

Next time use the forums or discord for support.

**Comment by leillo1975** [comment]
OK, although if I don't know that this support for steering wheels exists, and I see that I can connect a gamepad, but not a steering wheel, the logical thing is to open or search for an issue demanding this feature. At least in other projects it is done like this. By the way, the link you sent does not specify which are those steering wheels:

- lgFF_c283_c29b (a group of Logitech wheels supported by GT5/6)
- lgFF_ca03_ca03 (Logitech wheels supported by GT6)

**Comment by MSuih** [comment]
RPCS3 techically does not support wheels at the moment. It supports USB passthrough and the actual use of wheel is implemented in the game code. 

As for those names they're like that because the wheels all use same vendor and product id's and thus they are indistinquishable from games point of view. We don't know how many different wheels logitech manufactured with those id's and thus just have them listed as "group of" category. But you can edit the wiki yourself if you know the exact model list.

**Comment by matthewliut** [comment]
Ok but how to you get usb passthrough working??

**Comment by matthewliut** [comment]
> https://wiki.rpcs3.net/index.php?title=Help:Peripherals_and_accessories
> 
> Next time use the forums or discord for support.

this site only shows how to configure guitars and such. No wheels
