### ISSUE TITLE
Blank files being created instead of folders

### ISSUE THREAD

**Issue by slashiee** [RPCS3/rpcs3#1416]
I have only come across this while trying to boot up LittleBigPlanet Demo, LittleBigPlanet Full, LittleBigPlanet 2 Demo, and LittleBigPlanet 2 Full.

When I boot it up first time, it'll create a temp file instead of folder, preventing the game to boot up.

If you delete that file and then make a folder named that, it'll boot up. After the ESRB logo, it creates another file named dl and crashes. If you do the same thing to dl as you did to temp, it'll get to the loading screen.

![output_2016-01-10_08-24-39](https://cloud.githubusercontent.com/assets/15317421/12222559/cbe2382e-b774-11e5-8c9c-8c9ed775d4d2.png)
![2016-01-10_08-25-30](https://cloud.githubusercontent.com/assets/15317421/12222561/d09f85e2-b774-11e5-80d8-2c4822b12bce.png)
![2016-01-10_08-25-59](https://cloud.githubusercontent.com/assets/15317421/12222562/d6526a0e-b774-11e5-873d-c42a358a23d2.png)
![output_2016-01-10_08-26-47](https://cloud.githubusercontent.com/assets/15317421/12222564/d8fd0caa-b774-11e5-9e65-264e3b5a48b9.png)

I only have to do the temp file to folder solution to LBP2, as it seems like it does nothing after you do that.

**Comment by tambry** [comment]
@GoldtexTwitch Seems like something I could research, after I'm done with #1359.

**Comment by tambry** [comment]
@GoldtexTwitch Is this still case on the latest master? File handling had a bit of a rewrite after you opened the issues.

**Comment by GoldtexTwitch** [comment]
The problem still happens on the latest master.

**Comment by Uramekus** [comment]
Any progress?

**Comment by tambry** [comment]
I'll look into this.

**Comment by Nezarn** [comment]
@tambry since you will look into this file handling issue, can you take a look at #1391 too?

**Comment by tambry** [comment]
@Nezarn As I have noted on the issue, I suspect that the faulty implementation of cellGame* functions are at fault. There are multiple issues with those functions, that will require testing on an actual PS3 to confirm the behaviour. I don't have access to a PS3 to write tests to confirm the behaviour.

**Comment by tambry** [comment]
I've now got access to a PS3, so I'll be taking a look at this.

At a first glance of using LittleBigPlanet Demo [NPEA00147], it seems quite odd.
It uses cellGame and obtains permission to use the cache - /dev_hdd1/cache/. After obtaining the permission it make sure that /dev_hdd1/cache/ exists and creates its own folder - NPEA00147 in it, along with another folder in it - output. After doing that it tries to create a folder with no name, at the root directory of the filesystem, which doesn't make much sense, perhaps it's trying to create the /temp/ folder, but something went wrong?
But continuing after that it tries to create all the aforementioned folders again. After that it opens */dev_hdd1/cache/NPEA00147/output/temp* with flags to create the file, if it doesn't exist. As a note, folders can't be "opened" to obtain a file descriptor for them. After that it wants to allocate space for the created file without zero fill. That function happens to be unimplemented, but doesn't seem too hard to implement. I'd love to see what it tries to do after allocating space for the temp file.

**Comment by tambry** [comment]
After implementing the cellFsAllocateFileAreaWithoutZeroFill, it allocates the size of the temp file to be 1GB. There also seem to be non-deterministic Win32 API errors about invalid memory locations and such. They don't seem to happen too often, though.

It seems to now continue execution normally, loading some font files and initializing rendering related things. Sadly it terminates right after the *cellUserInfoGetStat* call for me. This is apparently caused by me not having the localusername file in my dev_hdd0/home/0000001. That doesn't make sense and I'll fix that along with the previous fix.

**Comment by tambry** [comment]
The non-deterministic errors for Win32 API are contuing to be annoying. I have absolutely no idea what's causing them and how to fix them. :/

Managed to fix the bug associated with cellUserInfoGetStat, that affected me. There also was another bug with socketselect, that caused it to infinitely spam the log and get stuck at the loading screen. After fixing that, it seems to spam indefinitely inet_ntoa. Sadly that is not something that I can implement, so that'll probably be up to @Nekotekina.

It also strangely keeps comparing network IDs (PSN ids) forever during the loading process. It might be expecting to receive some information from some server, that it tries to connect to using cellHttp (and cellSsl). After a while it abruptly quits with no real indication of what went wrong.

Could you see if [this build artifact](https://ci.appveyor.com/project/tambry/rpcs3/build/1.0.3/artifacts) fixes the previous problems?

**Comment by paulsapps** [comment]
What non-deterministic errors are you seeing and with what APIs? Probably a char/byte count has been mixed up or something if its access violation/memory corruption?

**Comment by tambry** [comment]
@paulsapps It's with sys_fs_read (called by cellFsRead). The final read function is fs::file::read at line 677 of File.cpp. This seems to still happen very inconsistently, but more often when the cache files don't exist yet. The error code from Win32 is 0x3E6 (ERROR_NOACCESS) and occurs when calling ReadFile. Maybe the game wants to read a size bigger than the actual size of the file? I'm not too sure.

**Comment by paulsapps** [comment]
if (!ReadFile((HANDLE)m_fd, buffer, size, &nread, NULL))

nread isn't checked that it == size, if it reads less than expected this is how you can find out (even if the call worked).

Otherwise unless the size isn't in bytes there is no obvious bug. The memory mapping stuff is hard to get right but I assume this takes the CreateFileW path.

**Comment by AniLeo** [comment]
Is this still an issue?

**Comment by slashiee** [comment]
This has not been an issue for a long time now. Completely forgot about this issue, lol.
