### ISSUE TITLE
Demon souls vulkan crash

### ISSUE THREAD

**Issue by Appeyapple** [RPCS3/rpcs3#14200]
### Quick summary

Whenever i launch demon souls with vulkan turned on it crashes upon launching loading not even getting in game, however when i use open gl the screen strobes black and white while textures are fucked up, this problem is exclusive to demon souls as ridge racer 7 works perfectly fine

### Details

My gpu is AMD Radeon rx 6600 xt
My cpu is an intel i7
I have 32 gigs of ram
These are the settings that crash my game upon launch
![image](https://github.com/RPCS3/rpcs3/assets/49661263/30d6fd1d-5c26-4688-a68c-49635b3bf291)
![image](https://github.com/RPCS3/rpcs3/assets/49661263/4090e416-2496-47ce-9e48-5943dcae7aff)

### Attach a log file

I think this is the log
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12059459/RPCS3.log)

**Comment by Asinin3** [comment]
Seems like the issue is on your end. Have you tried updating to the latest GPU drivers, and running https://github.com/13xforever/vkdiag/releases/latest to see if there's anything wrong with Vulkan on your system?

Should be using SPU LLVM as its faster than ASMJIT, also dont use framelimiter in games that already limit your frame-rate, you are just lowering performance for no reason.

**Comment by Appeyapple** [comment]
Just needed a fresh install, thanks for the tips though
