### ISSUE TITLE
The module msvcp140.dll was incorrectly installed

### ISSUE THREAD

**Issue by gir489returns** [RPCS3/rpcs3#14214]
### Quick summary

![image](https://github.com/RPCS3/rpcs3/assets/100792176/7d24cf55-1dca-476d-8dc0-51aa11fe66c8)

I click the link and run it, but it fails.

![image](https://github.com/RPCS3/rpcs3/assets/100792176/2493430a-e831-4125-acb5-20859d975cee)

It says:

[4B74:447C][2023-07-17T14:12:54]e000: Error 0x80070666: Cannot install a product when a newer version is installed.

### Details

If I run RPCS3 as admin it works.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12072722/RPCS3.log.gz)

**Comment by YuriNator557** [comment]
Not an RPCS3 issue, blame OneDrive

**Comment by gir489returns** [comment]
> Not an RPCS3 issue, blame OneDrive

How is RPCS3 expecting an older version of the runtime than what Microsoft is deploying a OneDrive issue? OneDrive is just the program that installed it.

**Comment by ChwaraeTeg** [comment]
If I understood it correctly, the check RPCS3 is doing here is to see if msvcp140.dll is installed under the Windows folder (e.g. in C:\Windows\System32\) which should be the default install location. If not, most of the time this is because someone has tried copying the dll file into the RPCS folder, which I believe is why the error message seems to assume this is the case and advises the file needs to be deleted from the RPCS folder.

Uninstalling the redistributible and then reinstalling it in the correct location should fix the issue in the OP, but possibly the check/error message could do with a tweak to account for the possibility msvcp140.dll is in neither the Windows folder or the folder where RPCS3 is running from.

**Comment by Asinin3** [comment]
This isn't an emulator issue, its an issue with how you have setup the redistutable. As mentioned above, uninstall current version(s), remove any unneccessary DLLs you downloaded off the internet and placed in weird folders e.g rpcs3 folder (if you did that). Then reinstall.

Closing. Next time ask for help in discord, not github.
