### ISSUE TITLE
Gran Turismo 5 Crashing mid-drive (spec b)

### ISSUE THREAD

**Issue by Jack10685** [RPCS3/rpcs3#14222]
### Quick summary

Gran Turismo 5 is crashing in the middle of driving an event, characterized by freezing (with no sound), staying that way for a minute or 2 before going to a screen that looks similar to the PPU loading screen before bootup for a few seconds before closing. I have only noticed it in spec b, it happens despite 

### Details

I have noticed this occuring with LLVM (accurate xfloat and approximate xfloat) and ASMJIT

### Attach a log file

https://1drv.ms/u/s!Al8w_tB0Uod2jAzXV2D4gSvhy08O?e=efrGR2

### System configuration

Ryzen 7 5700x
NVIDIA RTX 2070 driver version 536.40
16 GB ram
RCPS3 and OS on m.2 nvme

**Comment by Jack10685** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/12111320/RPCS3.log.gz)
[TTY.log](https://github.com/RPCS3/rpcs3/files/12111323/TTY.log)

another log

**Comment by Asinin3** [comment]
Both logs have Accurate Xfloat on, which kills perf and not needed. Don't use it.
Both logs do not have a fatal error output making the logs fairly useless unless they were caused by a setting you used which doesn't seem to be the case.
We already have stability issues open for GT5, I don't see any reason to open this separately.
