### ISSUE TITLE
Fullscreen issue.

### ISSUE THREAD

**Issue by Battler624** [RPCS3/rpcs3#14536]
### Quick summary

The fullscreen on rpcs3 causes issues on my end (as I run an HDR monitor), it briefly flickers my monitor and once i get out of the game I have to re-adjust sdr content brightness (it shows 50, but the value is actually at 0). Its probably a windows bug but I hope that it can be fixed by adding a borderless fullscreen option.

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12414297/RPCS3.log)

**Comment by Battler624** [comment]
I do have a fix that wont work for all, forcing auto-hdr to work via nvcontrol panel "Vulkan/OpenGL Present Method" "Prefer Layerd on DXGI Swapchain"

**Comment by Darkhost1999** [comment]
This issue has been opened and closed a few times on the github already.
You can enable prefer borderless fullscreen in the advanced tab I believe.
All the issues with fullscreen will be gone with borderless fullscreen because they often only occur with exclusive fullscreen not that they should occur at all.

**Comment by Battler624** [comment]
Man f me then didn't even check the tabs
