### ISSUE TITLE
RPCS3 (Linux AppImage) doesn't boot in Wayland

### ISSUE THREAD

**Issue by efeme4** [RPCS3/rpcs3#14576]
### Quick summary

The AppImage version of RPCS3 is unable to boot when setting QT_QPA_PLATFORM=wayland. I tried using both GNOME and Sway desktops, but none of them solve the issue. The flatpak version works well with wayland enabled, so it's only a problem of the AppImage somehow.
The error message showed by the console output is:
Failed to set RLIMIT_MEMLOCK size to 2 GiB. Try to update your system configuration.
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/12465930/RPCS3.log)

### System configuration

CPU: Intel Core i7 1165G7
GPU: Intel iRIS Xe
Driver: Mesa 23.1.6
OS: Fedora 38

**Comment by AniLeo** [comment]
Cannot reproduce on Manjaro Gnome with Wayland

**Comment by inferrna** [comment]
Same error on
CPU: Intel Xeon 2680V2
GPU: AMD RX560
Diver: Mesa 23.2
OS: Clear Linux

**Comment by yann-boyer** [comment]
Same problem here on :
CPU : i5-12450H.
RAM : 32GB DDR5.
GPU : RTX 4060 Laptop GPU 8GB.
Driver : Proprietary Nvidia drivers 545.29.06.
OS : openSUSE Tumbleweed.

Note : The issue is caused by missing qt6-wayland stuff in the AppImage, adding these into the AppImage will solve the issue, RPCS3 already works well under native Wayland(tested with the binary I built from source with Clang 17).

**Comment by kd-11** [comment]
> Same problem here on : CPU : i5-12450H. RAM : 32GB DDR5. GPU : RTX 4060 Laptop GPU 8GB. Driver : Proprietary Nvidia drivers 545.29.06. OS : openSUSE Tumbleweed.
> 
> Note : The issue is caused by missing qt6-wayland stuff in the AppImage, adding these into the AppImage will solve the issue, RPCS3 already works well under native Wayland(tested with the binary I built from source with Clang 17).

I'll try and reproduce.

**Comment by ArtyIF** [comment]
On Fedora 39 GNOME Wayland, the AppImage starts, but keeps freezing up with the "RPCS3 is not responding" window popping up. On X11, everythin works fine.

CPU: Ryzen 2600
RAM: 16GB DDR4
GPU: RX 570 8GB, using latest AMDGPU drivers

**Comment by yannb2159** [comment]
On my Linux system the issue is still there, Qt6 Wayland stuff are not integrated into the AppImage, RPCS3 works natively under Wayland(without XWayland) if you build it from source... If I run the AppImage version is says tha the QPA plugin "wayland" is not found and the only available are xcb(basically X11).

CPU : Intel Core i7-13620H.
RAM : 64GB DDR5.
GPU : Intel iGPU + RTX 4050 Laptop GPU 6GB.
OS : Fedora 40 Beta(same behavior happens with Fedora 39).

**Comment by cipherxof** [comment]
I have the same issue. Compiling from source works fine.

​ ​​  OS : Arch Linux x86_64 
​​ ​  Kernel : 6.8.4-arch1-1 
​​ ​  DE : Hyprland 
​​ ​  CPU : 12th Gen Intel i7-12700KF (16) @ 4.900GHz 
​​ ​  GPU : NVIDIA GeForce RTX 3080 
​​ ​  GPU Driver : NVIDIA 550.67 
​​ ​ ﬙ Memory : 32GB

**Comment by hcorion** [comment]
Please retest with the latest build!

**Comment by yannb2159** [comment]
> Please retest with the latest build! Should be fixed

This is why I got when testing with the latest AppImage :

Found AppImage path: /home/yann/Downloads/rpcs3-v0.0.31-16341-c58959eb_linux64.AppImage
Debugger: 0
RPCS3: SYS: RPCS3 v0.0.31-16341-c58959eb Alpha | HEAD
RPCS3: SYS: 13th Gen Intel(R) Core(TM) i7-13620H | 16 Threads | 62.54 GiB RAM | TSC: 2.918GHz | AVX+ | FMA3
RPCS3: SYS: Operating system: POSIX, Name: Linux, Release: 6.8.6-300.fc40.x86_64, Version: #1 SMP PREEMPT_DYNAMIC Sat Apr 13 15:03:28 UTC 2024
RPCS3: SYS: Current Time: 2024-04-15T23:29:27
qt.qpa.wayland: No shell integration named "xdg-shell" found
qt.qpa.wayland: No shell integration named "wl-shell" found
qt.qpa.wayland: No shell integration named "ivi-shell" found
qt.qpa.wayland: No shell integration named "qt-shell" found
qt.qpa.wayland: Loading shell integration failed.
qt.qpa.wayland: Attempted to load the following shells QList("xdg-shell", "wl-shell", "ivi-shell", "qt-shell")
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-egl, wayland, xcb.

Aborted (core dumped)

**Comment by cipherxof** [comment]
> Please retest with the latest build! Should be fixed

It works properly for me now.

**Comment by efeme4** [comment]
I still have the same problem as @yannb2159 , this issue is not solved.

**Comment by kd-11** [comment]
This is a Qt bug, not much we can do. Basically we create the window and ask Qt to show it, but Qt sometimes doesn't do so. The window remains invisible. When you try to use a window that is not fully created, wayland always complains and crashes out.
We could eventually stop using Qt for the game window but that is a lot of extra work for the moment.

**Comment by kd-11** [comment]
Let's track this in https://github.com/RPCS3/rpcs3/issues/14550

**Comment by kd-11** [comment]
AppImage launching should be fixed now, but only on arm64 for now. https://github.com/RPCS3/rpcs3/pull/16173 should fix remaining platforms.

**Comment by efeme4** [comment]
The appimage now perfectly runs in wayland and games run fine after merging #16173 , so I think we can close this issue now.
