### ISSUE TITLE
DX12: Dice test broken on R9 290

### ISSUE THREAD

**Issue by danilaml** [RPCS3/rpcs3#1459]
![image](https://cloud.githubusercontent.com/assets/2046350/12630981/28f15e0c-c560-11e5-83c0-03afcabedee0.png)
intel gpu works fine.
It seems to be caused by https://github.com/RPCS3/rpcs3/commit/acd384ae2d57644ee8d9db829e4ad4ed33fd3216 (I'll investigate further tomorrow).

**Comment by tambry** [comment]
@danilaml What GPU do you have? What driver version? Try to update, if not the latest.

**Comment by danilaml** [comment]
@tambry R9 290, Crimson 16.1

**Comment by ikki84** [comment]
Radeon R7 200, also driver updated, tested with previous version, the screen show as the same.
With the new bigpet commit it only shows black screen when amd gpu is selected, with intel gpu, show graphics.

**Comment by vlj** [comment]
I have a fix but unfortunatly it is driver dependent.

I'm actually passing vertex attribute as texture buffer from descriptor point of view but I use texture1d in the hlsl code.
I initially read them as tbuffer in hlsl as it is the right thing to do. Unfortunatly Nvidia drivers take age to compile the vertex shader (ie it takes a minute per shader instead of a second). I suspect it's trying to optimise buffer arithmetic somehow but it's quite inneficient.
On AMD the compilation doesn't take a hit with tbuffer. On the other hand it doesn't support the texture1d cast.
The solution is to allow user to select the tbuffer/texture1d based on the driver.

**Comment by tambry** [comment]
@vlj Maybe you could make a thread about it on Nvidia developer forums and have them take a look at fixing it? I don't think driver workarounds are a good idea, as it's something, that DX12 and Vulkan are meant to solve.

**Comment by danilaml** [comment]
@vlj I agree with @tambry . But I think it should be reported to both Nvidia and AMD. (of course if texture1d cast is not a "hack" but and actual feature that supposed to be supported)

**Comment by tambry** [comment]
@danilaml Is this fixed?

**Comment by danilaml** [comment]
Yes.

**Comment by bevanweiss** [comment]
@danilaml Sorry to comment on such an old issue.  Would you have a copy of the fw_dice.ppu.elf that I could get a copy of (perhaps added to the github repo)?
I'm looking at some RSX changes, and wanted a way to keep track of performance impacts.

**Comment by danilaml** [comment]
@bevanweiss it's from Short Waves PS3 emulator: http://wololo.net/downloads/index.php/download/8128

**Comment by bevanweiss** [comment]
@danilaml absolutely amazing, more than I was hoping for 👍
Do you know who would own copyright to them, and whether there would be issues adding them into the RPCS3 testsuite?

I haven't yet run through them all yet, but having such additional short-form tests would be useful I expect.

**Comment by danilaml** [comment]
@bevanweiss I think it's all been written by InoriRus. I'm not sure what copyright is on those but it's likely belongs to them. I'm not sure if there is a problem with using them for tests (but there likely will be if RPCS3 somehow ends up redistributing them).
