### ISSUE TITLE
Read/write buffer option

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1460]
Just wonder the read/write buffer option still valid for DX12 ? i remember it is for OpenGL previously

**Comment by tambry** [comment]
I think DX12 renderer doesn't need to handle that, as it's done automatically or something
vlj probably can give a proper answer.

**Comment by raven02** [comment]
As i seen one demo show speed boost when it turn off the buffer option using DX12

https://www.youtube.com/watch?v=HL-FcfComXo

**Comment by vlj** [comment]
Currently they don't do anything useful besides executing extra copy command. Most of the surface management happens in surface_store, but currently it lacks a mechanism to invalidate a stored surface.
On the other hand no app I tested write to rsx surface from Cell so far.
It sure happens for instance in game that migrated postprocessing on the SPU, but these games are currently out of rpcs3 reach (think The Last of Us).

The issue with surface write/read is that it requires all surface to be dumped in memory at every semaphore release and this is very costly. A possible way of doing is to only dump surface stored in main memory. Cell can read data from local memory too but on a PS3 it's slow, and app are unlikely to store their surface in main memory if they don't intend to read them since there is a penalty occured by RSX drawing to non local memory (fwiw it was said that nv4X couldn't write to PC main memory and this feature was added to RSX at the cost of some ROP units and bandwidth from the original design but it allowed spu to be used for image processing).

**Comment by raven02** [comment]
Thanks for the explanation. @vlj

**Comment by raven02** [comment]
OpenGL one with write color buffers enabled has been speedup significantly .Tested with Dragon ball Z Burst limit which require write color buffers enabled to show up graphics

**Comment by kd-11** [comment]
@raven02 Read color buffers with opengl is no longer needed, but write buffers does have an effect. I've chosen to leave it as an option since it does cause a minor performance hit. Some games however do require read/write depth which works a little bit differently but has also been improved.

**Comment by raven02** [comment]
Good @kd-11 .

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/1530 merged. Read/write buffers is no longer required for opengl unless we're talking games that use SPUs for rendering in which case even DX12 needs it.

**Comment by tambry** [comment]
Can this be closed?

**Comment by raven02** [comment]
Sure
