### ISSUE TITLE
Dark Souls II - visual problems!

### ISSUE THREAD

**Issue by willianholtz** [RPCS3/rpcs3#14710]
### Quick summary

Since the game doesn't need any custom configuration to run well, there are some visual problems that I couldn't resolve, one of which is some strange artifacts that appear in the game. When we look at water this is more visible!

### Attach capture files for visual issues

1080 Resolution
![1080](https://github.com/RPCS3/rpcs3/assets/23488207/7ae8924f-a0b7-422a-8c46-46dbf686d48e)

4K Resolution
![Artefatos](https://github.com/RPCS3/rpcs3/assets/23488207/f81690c0-6b2d-4d6f-9439-d4969ffd0e32)

### System configuration

Ryzen 7 5700x
RTX 2060 12GB (latest driver)
64GB Ram
4K monitor
Arch LInux OS

**Comment by Megamouse** [comment]
Missing logfile, capture etc.

**Comment by FlexBy420** [comment]
Pretty sure those are side effects of upscaling

**Comment by willianholtz** [comment]
No, I tested in completely standard mode and the same thing happens..  Unless it considers my 4K screen and does automatic upscaling!

**Comment by kd-11** [comment]
Seems to only affect vulkan. OpenGL is fine.

**Comment by kd-11** [comment]
Fixed by enabling strict rendering mode. I lost a lot of time reverse engineering their water shader, but the real culprit here is just that the shader sources from it's own output. I guess this can eventually be solved using ROV at some point in future, but this is not required for now and strict mode works well enough.
