### ISSUE TITLE
[Feature request] https://rpcs3.net/compatibility : Add "Perfect" to Status

### ISSUE THREAD

**Issue by davidhedlund** [RPCS3/rpcs3#14747]
### Quick summary

Both Cemu, and Yuzu, lists games with "Perfect" status:
* https://compat.cemu.info/
* https://yuzu-emu.org/game/

It would be useful if:
* "Perfect" was added to https://rpcs3.net/compatibility as well, and
* if you changed the status from "Great" to "Perfect" for qualified games.

**Comment by AniLeo** [comment]
Qualifying Perfect status properly is extremely difficult, I'd rather not.

Even if you have a game running perfectly, there's recompilation stutters the first time you play a game, maybe some missing feature like networking on otherwise very playable games, issues determining if it runs well on the recommended specs which is already an issue for the playable status itself.
