### ISSUE TITLE
gl: Wrong pitch calculation?

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#1495]
In resogun, OpenGL shows some corruption where the bottom half of the screen is green. This is because the video player uploads the component textures separately, but 2 of the 3 channels have the wrong pitch encoded in the rsx::texture object. The textures in question are 8-bit single channel textures, but two of them give pitch() as double the width which makes no sense. Of course, setting the unpack settings to use the given width instead of pitch fixes this but I feel this is hacky.

![resogun_good1](https://cloud.githubusercontent.com/assets/15904127/12962004/7f4d5586-d054-11e5-8bb6-28d1734247fc.PNG)

**Comment by jarveson** [comment]
Hmm, well i can't get opengl to boot this successfully to test it, but looking at the values stored in method_registers while on the same screen with dx12 (which only uses width() and avoids this), I think the issue is 
https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/RSX/RSXTexture.cpp#L210
needs to take the texture index into account like so:
`return method_registers[NV4097_SET_TEXTURE_CONTROL3 + m_index] & 0xfffff;`
that range of registers seems to be filled with the correct values

The weird part is that the depth() function above it should also be changed if this is the issue, but depth() seems to be used in various functions, unless its just been a coincidence so far

**Comment by kd-11** [comment]
@jarveson OpenGL also used width until recently but then use of pitch was added later. I'll check if the method_registers affect the texture information passed on to GL.
As for the crash, I'm assuming it occurs right after the screen about legal use. Thats because of the unimplemented sys_memmove function. Someone probably has already submitted an implementation if i'm not wrong. If not i'll submit one.

**Comment by kd-11** [comment]
@jarveson You're right! The invalid pitch value is copied from the texture bound to index 0. Depth should probably not affect anything since it is almost always 1 anyway.

**Comment by tambry** [comment]
The sys_memmove implementation is in #1481.

**Comment by kd-11** [comment]
@jarveson You mentioned problems with OpenGL booting at all. Are you using AMD by any chance?

**Comment by jarveson** [comment]
Yeap, amd R9 280x, I had tried booting it with the memmove pr intially but still no dice, and haven't looked into it much since

In case its an amd specific issue, here's parts of what i remember from debugging it:
I was getting a heap corruption within the first couple 'texture::init' calls. 
I believe it was when it went to cleanup `vector<u8>  data_upload_buf` as the exception would trigger at the end of the function https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/RSX/GL/rsx_gl_texture.cpp#L453 

My guess was that the texture data corrupted during one of the glCompressedTexImage2D calls, but given my lack of graphics knowledge, thats where I kind of gave up haha

Let me know if i can be of more help! i can look deeper into it if necessary

**Comment by kd-11** [comment]
@jarveson I've also noticed the overrun with DXT textures. I'll open an issue for it when I narrow down the cause. I should have access to an AMD system soon, so I'll look into those issues as well.

**Comment by kd-11** [comment]
@jarveson The corruption occurs during the upload_texture call, during one of the templated mipmap_copy functions. To confirm, set the size of the data_upload_buf to double and the problem disappears. It seems the get_placed_texture_storage_size call returns a value that is too small for some texture formats. glTexImage* functions are read-only and therefore do not affect this. Tested on a 270x.
If you can assist in identifying some cases where this occurs, that would be great.

**Comment by vlj** [comment]
get_placed_texture_storage_size may indeed be wrong if all mipmap level are used and storage is linear.
Which game does crash ?

**Comment by kd-11** [comment]
Outrun online crashes just after loading using OpenGL. It goes ingame if the value is doubled but color output is black for shaded geometry anyway and framerate is terrible (Nvidia). Someone also mentioned resogun crashing on AMD.

**Comment by vlj** [comment]
I reproduced the issue with DX12 on a branch that uses gsl::span check system.

**Comment by vlj** [comment]
The crash is fixed with 1504.

**Comment by kd-11** [comment]
Closed as fixed
