### ISSUE TITLE
[Task] RSX tiling breaks visual effects in Split/Second at 100% render scale

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#14984]
Seems to be a problem with compatibility between RSX tiling and optimized DMA buffers. We don't store image dimensions so the detiler emits garbage.
Relates to https://github.com/RPCS3/rpcs3/issues/14682

**Comment by legend800** [comment]
Just posted in the other thread that this PR broke Split Second gfx: https://github.com/RPCS3/rpcs3/issues/14682#issuecomment-1873407207

This didn't fix anything either - effects don't render at native res and massive pixelation at non-native resolutions. 

Aside from that known issue, gfx were fine on the previous Master build and now broken on the build that just came out a couple mins ago:

<img width="961" alt="2024-01-01 09_34_50-FPS_ 30 00 _ Vulkan _ 0 0 29-15899 _ Split_Second  NPUB30450" src="https://github.com/RPCS3/rpcs3/assets/20983844/9777b824-85ea-4acd-b011-bb971c47c6ce">

**Comment by legend800** [comment]
@kd-11 Did you see this comment above? Game was not improved and actually regressed. Details above.

**Comment by Asinin3** [comment]
If a game regressed from a PR, why are you commenting about it in an issue that was already closed and is a task list? Just make a new issue and link to the PR that broke it. No need for pinging on a closed issue unless it was improperly closed.

**Comment by legend800** [comment]
I pinged the PR, [this ](https://github.com/RPCS3/rpcs3/issues/14984) and [the original issue](https://github.com/RPCS3/rpcs3/issues/14682) and it was ignored. I'm pinging all 3 spots to call out 1) nothing was fixed and 2) this actually broke the gfx

**Comment by kd-11** [comment]
1. The game always was pixelated at non-native res when correct settings are used.
2. I confirmed the fix myself. This points to oossibly incorrect settings being used.

**Comment by kd-11** [comment]
Double checked. The effects are rendered as expected. There is an unrelated bug with blit engine display wrapping but that is not a regression. The effects you see repeating simply did not render at all before. That is already tracked in a separate task.
![image](https://github.com/RPCS3/rpcs3/assets/15904127/33816041-95cc-4250-9396-b22a41881dc0)

**Comment by legend800** [comment]
Looks like that blit engine display wrapping issue is what prevents the smoke/explosion effects from **_fully_** rendering in native res. So that explains my results in native res. 

Native Res:
<img width="960" alt="2024-01-21 09_35_57-FPS_ 30 14 _ Vulkan _ 0 0 30-15989 _ Split_Second  NPUB30450" src="https://github.com/RPCS3/rpcs3/assets/20983844/164c7c4e-cdad-4f4c-8cbb-aa85308d04a6">

101%+ Res:
<img width="760" alt="2024-01-21 09_20_12-FPS_ 30 03 _ Vulkan _ 0 0 30-15989 _ Split_Second  NPUB30450" src="https://github.com/RPCS3/rpcs3/assets/20983844/407ad289-7091-42f2-a8bc-a92fc4651482">

Glad that's being tracked. Hopefully once that's sorted out, then this game should be rendering correctly (with the right config-pasted below). 

Config:
1. AF off(fix red outlines)
2. WCB (smearing)
3. RCB(env lighting/fix skybox?)
4. RSX tiled memory (tiling-vk only)
5. 100% res (fix pixelation)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14002218/RPCS3.log.gz)

**Comment by kd-11** [comment]
I use ideal world settings for this game. All buffer options + RSX detiling.

**Comment by legend800** [comment]
Sure, I'll keep that on for testing but no change in rendering (that I notice at least) for SS:

<img width="961" alt="2024-01-21 10_05_49-FPS_ 29 98 _ Vulkan _ 0 0 30-15989 _ Split_Second  NPUB30450" src="https://github.com/RPCS3/rpcs3/assets/20983844/294d9a20-57d4-498b-a634-5c3a68d2375b">
