### ISSUE TITLE
Joust Graphical Issue

### ISSUE THREAD

**Issue by Triticum0** [RPCS3/rpcs3#15017]
### Quick summary

This game has a severe graphical issue making it unplayable

### Details

When multiple Foundation 9 Entertainment are in the games directory the game does not render a menu screen or render a menu screen from a different game series based on which game has been booted first
(Joust Demo with no menu)
![NPEB90013_screenshot_2024_01_06_16_19_34](https://github.com/RPCS3/rpcs3/assets/71127352/e4e34d00-0a93-4dde-ae0a-9b205d116781)
(Rampage World Tour Demo with Joust menu banner)
![NPEB90012_screenshot_2024_01_06_16_23_32](https://github.com/RPCS3/rpcs3/assets/71127352/c78b6024-4b06-4fcb-891e-baa4bb813b44)
(Rampage World Tour Demo with Joust ingame banner)
![NPEB90012_screenshot_2024_01_06_16_23_48](https://github.com/RPCS3/rpcs3/assets/71127352/a59fc5cf-3254-4879-9b4c-a26f42ce4460)

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13850356/RPCS3.log.gz)

### Attach capture files for visual issues

[Ingame.zip](https://github.com/RPCS3/rpcs3/files/13850461/Ingame.zip)
[Menu.zip](https://github.com/RPCS3/rpcs3/files/13850465/Menu.zip)

### System configuration

RPCS3 v0.0.30-15916-80b7fd5f Alpha | master | FW 4.88 | Windows 10
AMD Ryzen 7 5700X 8-Core Processor | 16 Threads | 15.55 GiB RAM | AVX+ | FMA3
GPU: NVIDIA GeForce RTX 3060 Ti (535.104)

### Other details

**Comment by Triticum0** [comment]
#14860 is the same issue as the instability of multiple titles causes most of the issues.

**Comment by kd-11** [comment]
I noticed this as well. I loaded Joust when debugging the visual bugs and noticed it loaded the banners from mortal kombat. This kind of issue is not a rendering bug, it just means the game loaded paths from the wrong location which is curious. Maybe it is relying on dev_hdd1 caches?

**Comment by Triticum0** [comment]
So you saw it too then. When you closed issue #14001 and you said "it appears to be fixed" I thought you couldn't reproduce it.

**Comment by Triticum0** [comment]
Be warned I ended up installing multiple Foundation 9 Entertainment and ended up with a state where the game would freeze before going into the menu. Also So of the games like Rampage World Tour Demo [NPEB90012], I couldn't boot into without having booted joust previously.

**Comment by ChwaraeTeg** [comment]
Removing \dev_hdd0\cache.dat and \dev_hdd0\cache.idx seems to clear the issue and ensure the correct graphics show for the next launched title (the problem then returns for the 2nd title that's launched)

**Comment by kd-11** [comment]
@ChwaraeTeg Check if something is stored in /dev_hdd1.
My guess is that creating a /dev_hdd0/cache.data file should fail, but I haven't experimented much with fs ACLs. Pinging @elad335 who would know more about this.

**Comment by elad335** [comment]
So this is the same issue as #14958 basically

**Comment by ChwaraeTeg** [comment]
> @ChwaraeTeg Check if something is stored in /dev_hdd1. 

So with the game running on console, the dev_hdd1 folder appears to be empty, and the cache.data file does not seem to be created on the root of /dev_hdd0 (or anywhere else on /dev_hdd0 it would appear)

**Comment by ChwaraeTeg** [comment]
> My guess is that creating a /dev_hdd0/cache.data file should fail, but I haven't experimented much with fs ACLs.

As a test I removed write access to the /RPCS3/dev_hdd0 folder (only) in Windows - the game then seems to run perfectly:
[Joust_devhdd0readonly.log.gz](https://github.com/RPCS3/rpcs3/files/13865292/Joust_devhdd0readonly.log.gz)

**Comment by ChwaraeTeg** [comment]
As another test, I tried taking the cache.dat/idx files from the RPCS3 folder and dropping them into the root of /dev_hdd0 on a real console. When starting the game they came from, it loads a broken/glitched version of the game, very similar to the issues seen in the emulator (#14860). When trying to launch a different Foundation 9 game to the one the cache files came from, the console crashes altogether.

My theory is that the developers have left in some broken code that mistakenly tried to write the cache files to the root of HDD0 and on real hardware this is blocked from happening. After a few retries, the game gives up trying to create them and continues to run without using the cache files and everything works fine. In RPCS3 however it is permitted to create these cache files, but given that it was not tested with them present on console they don't work properly, and because they could never exist on real hardware there was no code put into games to either remove the files on exit or overwrite during start-up.
