### ISSUE TITLE
Error when starting the game Heavy Rain

### ISSUE THREAD

**Issue by ChapmanC1** [RPCS3/rpcs3#1517]
Hi, the developers of RPCS3. Recently I tried to run your emulator on a game like heavy rain. But when you start FPS is displayed(black screen). After 30 seconds(approximately), I get the pink text(like this): 
{PPU Thread [0x20] (traversal thread)[0x0017b404]} Exception: 
(in file C:\rpcs3\rpcs3\Emu\SysCalls\Modules\cellL10n.cpp:719, in function UTF8toUTF32) 
Please report this to the developers.
How do I get rid of this error?

**Comment by DPersonalized** [comment]
Read the [FAQ](https://github.com/RPCS3/rpcs3/wiki/FAQ).

**Comment by tambry** [comment]
You don't. Wait for someone to implement it. Also: [list of playable games](http://www.emunewz.net/forum/forumdisplay.php?fid=195).
Please alos remember that you'll need to grab files from your CFW PS3 to properly use the emulator. I'd suggest you to play on the PS3 for now, since game compatibility is very low and there's no point in playing the games on your PC, yet.

**Comment by MyaniPT** [comment]
Non implemented HLE functions should output something like "Function not implemented in HLE" instead of a blank exception to prevent questions like this imo

**Comment by raven02** [comment]
It is well-known issue that we have lots of unimplemented HLE functions .This one can be workaround using LLE module , libl10n.elf . Therefore , i'm closing it.
