### ISSUE TITLE
Demon’s Souls crashes during boot on Aarch64 Linux

### ISSUE THREAD

**Issue by lacamar** [RPCS3/rpcs3#15222]
### Quick summary

When attempting to boot Demon’s Souls on Aarch64 Linux, it crashes with an error that appears to be related to OpenGL.

### Details

When attempting to run Demon’s Souls on `rpcs3` (compiled locally from the git repo, version 0.0.30-16122-7abc5f3e), the game fails to boot. 

```
F {RSX [0x0000000]} SIG: Thread terminated due to fatal error: Could not bind OpenGL context
(in file /home/snow/software/rpcs3-files2/rpcs3/rpcs3/rpcs3qt/gl_gs_frame.cpp:89[:4], in function set_current) (errno=25=Inappropriate ioctl for device)
```

The game can launch into the start menu when using Vulkan as the renderer and llvmpipe as the graphical device, so it shows that games can boot but something with OpenGL isn’t working properly. 

### Attach a log file

This is the log output from RPCS3: 
[RPCS3 Asahi OpenGL Demons Souls.log](https://github.com/RPCS3/rpcs3/files/14325052/RPCS3.Asahi.OpenGL.Demons.Souls.log)

This is the output for `asahi-diagnose`:
[asahi-diagnose-20240217-154410.txt](https://github.com/RPCS3/rpcs3/files/14325050/asahi-diagnose-20240217-154410.txt)

### System configuration

I’m using a 14" M1 Pro Max with 10 cores, I’m running Asahi Linux Fedora with KDE5 as the DE.

**Comment by kd-11** [comment]
I'm slowly working on aarch64 support, but it'll be a while since I'm also working on other stuff.
I have tested DeS but I haven't completely tested if it goes ingame. OpenGL works ok for most games I have tested it with, but you need to override GL and GLSL versions.
To do this you need to configure mesa the way we used to do it on wine many years ago:
```
MESA_GL_VERSION_OVERRIDE=4.5 MESA_GLSL_VERSION_OVERRIDE=450 ./bin/rpcs3
```
That should fix the shader compilation crash but there is no guarantee that visuals will be correct. Many PPU/SPU instructions are broken on aarch64 right now.

**Comment by lacamar** [comment]
Closing since the game works on the official Linux Arm64 builds and with manually compiled builds for a while now.
