### ISSUE TITLE
[Regression] CA signer not available for verification

### ISSUE THREAD

**Issue by zSavT** [RPCS3/rpcs3#15321]
### Quick summary

When I start the program, it results in the following error and does not allow to update.
```
NET: curl_easy_perform(): Curl error (77): Problem with the SSL CA cert (path? access rights?)
Details:  CA signer not available for verification
```

### Details

I find this old issue  #13005. I tried to re-download the program and replace all files but nothing changed. I extracted the file to another folder but nothing changed. I even tried to extract it on my second PC but nothing changed.

### Build with regression

RPCS3 Version: 0.0.31-16205-40adf4b9 Alpha | master

### Attach two log files

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14623202/RPCS3.log)

**Comment by ThePapaw** [comment]
I also started getting this. It just started this morning. Possibly something in the checking for an update process??
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14623316/RPCS3.log)

**Comment by MSuih** [comment]
It seems to be an issue with the certificate on rpcs3.net, but I'm not sure why it only affects the updater

**Comment by ThePapaw** [comment]
@MSuih - When I run a game, it says it is connecting to RPCN network successfully though?

**Comment by TheGamer0013** [comment]
Well, I'm glad I'm not the only one with this issue. 🥴

**Comment by turbo25** [comment]
The same issue happens even when trying to Download Compatibility Database

**Comment by EliasTLJ** [comment]
Happening with game patches too

**Comment by ThePapaw** [comment]
I'm not 100% sure, but I believe all was working for me last night, because I had noticed an "Update Available" last night (didn't do it though) and no changes have been made on my end over the past 24hrs if that is of any help

**Comment by saminxx** [comment]
me too on last build with win 11

**Comment by kostakis** [comment]
Most probably it is a problem with the certificate of rpcs3.net
Should not be a client application bug (?)

**Comment by AniLeo** [comment]
No, it shouldn't be a problem with the server.

**Comment by GastyFP** [comment]
Same here. didn't update, tried updating manually and same errors.

**Comment by Shinnok789** [comment]
Same here. Tried to update an older version, and got the same error. Which was weird because automatic updating worked on it flawlessly about 1 month ago. 
Downloaded the latest windows version from the official website today, but receiving the same error while trying to check for updates. All files were extracted from the new archive, nothing missing. All files were put in a fresh folder, not overwritten on the old version, to avoid using corrupted files if some were not overwritten (like configs etc).
Using Windows 11 x64
Latest RPCS3 Version I got: 0.0.31-16205-40adf4b9 Alpha | master

![error](https://github.com/RPCS3/rpcs3/assets/104922844/94789e0c-8130-4a78-8284-df9773beef7c)

**Comment by dkettenm94** [comment]
getting the same error

**Comment by DevLuc4** [comment]
I have the same error

**Comment by DevLuc4** [comment]
I did some research and didn't find much about this particular error.

**Comment by coco-belo** [comment]
> No, it shouldn't be a problem with the server.

Shouldn't be? Hypotheses aren't answers. 
I too think this is a server-side problem.

**Comment by FidRay16** [comment]
Same error

**Comment by AniLeo** [comment]
Everyone, please stop flooding the issue if you don't have any new information, we are already aware of the issue and you're just cluttering the ticket.

> I too think this is a server-side problem.

Then you can go ahead and explain why it is a server-side problem, as the server is providing two SSL certificates with full chain, and on top of that it's working fine on non-Windows platforms, that's why this issue is labelled as OS: Windows.

What we suspect so far is a clientside curl issue, but we don't have any solutions yet.

**Comment by shinra-electric** [comment]
It's not Windows only, it affects macOS too...

<img width="1225" alt="Screenshot 2024-03-16 at 23 15 39" src="https://github.com/RPCS3/rpcs3/assets/50119606/358f6695-4eb5-4d2d-89a4-56b994de3b11">

**Comment by AniLeo** [comment]
We can't reproduce on Linux. I've added the macOS tag then.

**Comment by autofire372** [comment]
Unfortunately, I'm running into this issue on Linux (EndeavourOS).

**Comment by AniLeo** [comment]
That's unfortunate, we don't repro on Manjaro and Gentoo at all. 

Also, when testing on Windows, I randomly had update checks working before it went back to not work again, I was able to do a few auto updates, but completely at random.

**Comment by Shinnok789** [comment]
One extra bit of info
It seems to be only windows 11 related
I also have a windows 10 x64 on a virtual machine - installed the latest RPCS3 and the update check works flawlessly.
Image is below.

![Windows 10 ok](https://github.com/RPCS3/rpcs3/assets/104922844/d725bed6-8a46-4574-be11-d236a37bf912)

**Comment by JustGuardian** [comment]
same here, on win11

**Comment by AniLeo** [comment]
No, it's not related to a specific version of Windows. As I said above, it works and doesn't work randomly.
