### ISSUE TITLE
After Burner Climax, DX12, broken graphics

### ISSUE THREAD

**Issue by danilaml** [RPCS3/rpcs3#1535]
AMD R9 290:
![image](https://cloud.githubusercontent.com/assets/2046350/13498403/d4af3db0-e16a-11e5-8450-d71470858518.png)
![image](https://cloud.githubusercontent.com/assets/2046350/13498410/d9bb4cfe-e16a-11e5-9636-afbbadf2b9fc.png)
Intel HD4600:
![image](https://cloud.githubusercontent.com/assets/2046350/13498524/72ef2f26-e16b-11e5-90b6-d9876b07e1d6.png)

Started happening around https://github.com/RPCS3/rpcs3/commit/422f5c00083a40bee0aeddc18e551f2a35c4d4d5 . Haven't pinpointed exact commit yet. Affects both intel and amd.

**Comment by tambry** [comment]
Looks like a lot of fog. Probably post-processing related. I think #1533 fixes the same issue for OpenGL.

**Comment by danilaml** [comment]
@vlj git bisecting gave me 35db227af4718d9dc055cb2d5fd9b9cb95906d9f as an offending commit.

**Comment by vlj** [comment]
Same on nvidia.

I'm investigating however I think https://github.com/RPCS3/rpcs3/commit/35db227af4718d9dc055cb2d5fd9b9cb95906d9f only uncovered a bug rather than being responsible for it. I had debug layer complaining about wrong format for depth texture (and fog is related to depth). If some pass were disabled before 35db227 then it didn't matter since texture wasnt read.

**Comment by vlj** [comment]
I may have a fix tomorrow or the day after

**Comment by danilaml** [comment]
Can confirm that this is fixed.

**Comment by pepodmc** [comment]
this bug is happening again with vulkan/opengl

NVIDIA GEFORCE 750TI
