### ISSUE TITLE
RPCS3 is hang

### ISSUE THREAD

**Issue by trantien1997** [RPCS3/rpcs3#15396]
### Quick summary

![image](https://github.com/RPCS3/rpcs3/assets/50040708/da9e7b7b-d031-40a3-ba5c-a010bce381c4)
RPCS3 not responding

### Details

RPCS3 not responding

### Attach a log file

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14863054/RPCS3.log)

**Comment by FlexBy420** [comment]
Already fixed in latest build

**Comment by MSuih** [comment]
Since you can't use the updater you'll have to manually update to the latest version. For windows this means going to https://rpcs3.net/download, downloading the latest version and overwriting all your currents versions files with the ones from latest version.

Ask in help channel of our discord for more help

**Comment by trantien1997** [comment]
Thanks
