### ISSUE TITLE
Uncharted: Drakes Fortune [BCES00065]: Water does not render correctly

### ISSUE THREAD

**Issue by Flori98** [RPCS3/rpcs3#15422]
### Quick summary

Water does not render correctly every time in the Jetski-Levels (Chapter 8, 9 and 12).

### Details

First of all, I am not an native English-Speaker. I'm sorry if there are grammatical errors. 

In the Jetski-Levels, the rendering of the water looks strange. Directly in sight, the water looks "blocky" I don't know how to describe it correctly, so I made screenshots.
![BCES00065_screenshot_2024_04_10_00_37_56](https://github.com/RPCS3/rpcs3/assets/166349235/d529a32e-5e92-47c2-b990-a807c3d8794b)

That happens when the chraracter is swimming too.

![BCES00065_screenshot_2024_04_10_00_42_00](https://github.com/RPCS3/rpcs3/assets/166349235/19c1227a-2259-4417-91bb-76dd6bdb96c3)

But originally in the PS3, the water should look like on the right in this video: 
https://youtu.be/TtdFW50vtQk?si=-wxNXELV-_QHJGzw&t=97

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/14925080/RPCS3.log.gz)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/14925102/RPCS3.log)

### Attach capture files for visual issues

[Uncharted Drakes Fortune Renderdoc Capture.zip](https://github.com/RPCS3/rpcs3/files/14925994/Uncharted.Drakes.Fortune.Renderdoc.Capture.zip)

### System configuration

There is my PC configuration:

GPU: NVIDIA RTX 2060 6GB VRAM
CPU: AMD Ryzen 5600X
16 GB RAM
Windows 10

NVIDIA GPU Driver Version: 552.12

### Other details

This Problem is also present when I change the Default Resolution from 720p to 480p.

**Comment by JimScript** [comment]
Sorry to say this is a duplicate of issue #13973.

**Comment by Flori98** [comment]
@JimScript OK. I didn't see that older post from June 2023. Strangely, the problem exists only when the player can drive the jetski. I looked if the problem is present in Chapter 3 and 13 too but it isn't. I don't know if this extra information would help to solve the issue. I look if the problem also exists when the player drive the jetski in Chapter 12 to Chapter 13. I don't considered this in my playthrough.

**Comment by kd-11** [comment]
So this issue doesn't appear if you "jump" to the target level but it is there when coming in from a different one. This points to a cache corruption/aliasing problem. I'll circle back to this.

**Comment by Flori98** [comment]
> So this issue doesn't appear if you "jump" to the target level but it is there when coming in from a different one. This points to a cache corruption/aliasing problem. I'll circle back to this.

I don't have the water issue on Chapter 13 when I select the Chapter directly in the main menu as well as I drive with jetski from Chapter 12 to the area of Chpater 13. For the record, the transition from Chpater 12 to 13 is flurent and there aren't any cutscenes between them.

**Comment by Flori98** [comment]
By the way, this case can be closed because it's a duplicate.



> Sorry to say this is a duplicate of issue #13973.

**Comment by Flori98** [comment]
By the way, this case can be closed because it's a duplicate.



> Sorry to say this is a duplicate of issue #13973.

**Comment by Jonathan44062** [comment]
![image](https://github.com/user-attachments/assets/9957e0ea-0060-49db-ac87-354857b3a4c5)
I'm so glad to Duckhost for saving this screenshot (it was from the original report)
This is the build which breaks the water in Uncharted https://github.com/RPCS3/rpcs3/pull/13901

**Comment by digant73** [comment]
It is properly working in OpenGL.

If I disable the custom border color commenting out the line 35 in `vkutils/sampler.cpp`:

```
//if (!g_render_device->get_custom_border_color_support())                    // <-- line 35
{
	value = get_closest_border_color_enum(color_value);
	return;
}

```
the issue is no more present.

I also verified that the broken water effect in Killzone 3 reported in ##15949 is also fixed by the above change in the code.
Below some screenshots of the issue and the temporary fix.

### `OpenGL - working:`

![BCES00065_screenshot_2024_09_25_22_37_45](https://github.com/user-attachments/assets/8c886c53-9887-4f6e-bc2f-d44ea3ecb525)

### `Vulkan - broken - custom border color enabled since #13901:`

![BCES00065_screenshot_2024_09_25_22_29_52](https://github.com/user-attachments/assets/cd68b894-86ba-4f38-8ef2-7ef92732e955)

### `Vulkan - working - custom border color disabled by temporary fix:`

![BCES00065_screenshot_2024_09_25_22_50_27](https://github.com/user-attachments/assets/5256ff53-77f2-4aff-8e89-1950343750c3)

**Comment by kd-11** [comment]
This is a known issue, I honestly just forgot about it.

**Comment by digant73** [comment]
> This is a known issue, I honestly just forgot about it.

For that reason I provided an update (obviously not my intention to bore anyone) reporting a sort of history (for what I see and understand) of the issues and if there could be some relationships with the new/changes features you are periodically implementing/improving that hopefully could help the developers to discover and fix the issues more easily.
I see you have tons of bugs in the list to investigate, so the minimum effort from our (users) side is just to try to help you.

If there should be no relationship (interference) between custom border color and SNORM/GAMMA/BX2/UNSIGNED_REMAP (you clarified to me in #15949) hopefully my report above could help.
With current RPCS3 (updated just today), if a disable the custom border color the issue in Killzone 3 is not present.

**Comment by kd-11** [comment]
No problem, tickets get forgotten about all the time due to the overwhelming number.

> With current RPCS3 (updated just today), if a disable the custom border color also the issue in Killzone 3 is not present.

Does killzone 3 also work correctly with OpenGL by default?
Also if possible can you capture a RSX capure of the scene? It would be a great help. The attached trace here is old and also incorrect format.

**Comment by digant73** [comment]
> No problem, tickets get forgotten about all the time due to the overwhelming number.
> 
> > With current RPCS3 (updated just today), if a disable the custom border color also the issue in Killzone 3 is not present.
> 
> Does killzone 3 also work correctly with OpenGL by default? Also if possible can you capture a RSX capure of the scene? It would be a great help. The attached trace here is old and also incorrect format.
> 
> PS. In this case I mean a capture of uncharted, not killzone.

I tried also Killzone 3 in OpenGL and there were more issues in general than with Vulkan. I mean the issue on the water was present but there are also other glitches (the water had also a white bloom). I will provide screenshots and RSX captures (possibly in the related bug report #15949 just to avoid confusion with this bug report).

Yes, I got an RSX capture for UC1 yesterday (about 75MB). I will provide the download link here this night (currently at work now)

**Comment by kd-11** [comment]
The reason UC1 is failing with border color may be different. In this case it's just because vulkan has some stricter requirements on how border colors must be used that we ignored. That will be fixed soon, but if KZ3 is broken in OpenGL then it could be a different matter altogether. The fact that border color affects it though tells me the remapper pipeline needs to be expanded a little bit, but I need to do the hardware tests to decide the correct texel path which needs time.

**Comment by digant73** [comment]
Yes, I had also the feeling that the issue in K3 still present in OpenGL could (unfortunately) be a different story. Performance in OpenGL for K3 are really bad, I mean ultra slow performance (just few fps) and I also thought that the issues were due to that, so I didn't consider the result solid enough to be reported. If possible I will also get a recording of that

**Comment by digant73** [comment]
@kd-11 attached the RSX capture for UC1

https://mega.nz/file/arQSkADQ#OdLx_Qf0QZMvnYV-M1DraC21ThZx9W-hEkdtCxyPnWA

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/16169 fixes this issue. No idea if it does anything for KZ3 though.

**Comment by digant73** [comment]
thanks. I will check also in KZ3!

**Comment by digant73** [comment]
> #16169 fixes this issue. No idea if it does anything for KZ3 though.

bug on UC1 fixed. As you already suspected, the issue on KZ3 is a different story and unfortunately was not fixed by you PR
