### ISSUE TITLE
Yakuza/ rgg Kenzan! - freezing on final boss fight

### ISSUE THREAD

**Issue by percy617** [RPCS3/rpcs3#15535]
### Quick summary

During the first battle of the series of final boss long battles, the game freezes. It freezes at random points during the first fight each time.

### Attach a log file

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/15157525/RPCS3.log.gz)

### System configuration

Windows 10 
AMD Ryzen 9 5950X 16-Core Processor
NVIDIA GeForce RTX 3080 Ti - driver version 551.61
 64 Gb ram

### Other details

i think its happening when the boss is tying to use a specific move? that part is just a guess though

**Comment by Fwha** [comment]
I can also attest that it freezes within 2 seconds of the red aura going on the first boss of the final area. Interestingly enough, it doesn't happen in the arena when you fight a character that has the exact same moveset and appearance + a mask. It only happens during this 1 particular fight and you have to do it to progress throughout the rest of the final area and it only happens when he activates his aura which only happens if he hits you so you basically have to do the fight flawlessly without getting hit or knock him out of his aura within 1 second after he activates it. That's the only way I've been able to move past that fight. There's no freezes before or after this fight. Not even on the Amon fight.

This is the Sasaki Kojiro fight at the beginning of the final island by the way.

**Comment by percy617** [comment]
Sorry for the late replay, but this isnt an issue with the emulator but with the English patch for the game
