### ISSUE TITLE
Compiling in Linux - lasmjit AND  lpng16_static

### ISSUE THREAD

**Issue by gabrielirdeb** [RPCS3/rpcs3#1561]
/usr/bin/ld: cannot find -lasmjit
/usr/bin/ld: cannot find -lpng16_static
collect2: error: ld returned 1 exit status
CMakeFiles/rpcs3.dir/build.make:9103: recipe for target 'rpcs3' failed
make[2]: *** [rpcs3] Error 1
CMakeFiles/Makefile2:188: recipe for target 'CMakeFiles/rpcs3.dir/all' failed
make[1]: *** [CMakeFiles/rpcs3.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: *** [all] Error 2

Anyone knows how to compile with this issue?

**Comment by tambry** [comment]
@gabrielirdeb Please give full CMake log along with commands used.

**Comment by gabrielirdeb** [comment]
I used the commands of github in rpcs3/rpcs3 

But now i use in rpcs3 (only) and was compiled, sorry for the thread.

Thanks!

But now i wanna see if have a way to make a AppImage with this project (make a selfexecute file for linux), there is a topic with this theme?

**Comment by tambry** [comment]
@gabrielirdeb Use search. As far as I'm aware there's has been no discussion about something like that. Good luck.

**Comment by probonopd** [comment]
Since you are already building on trusty on Travis CI we could use these build artefacts and bundle them up as an AppImage. This can be nicely integrated into the Travis CI builds. See these examples:
https://github.com/cpvrlab/ImagePlay/pull/93/files
and 
https://github.com/mavlink/qgroundcontrol/pull/3136/files
