### ISSUE TITLE
Dimensions Manager Range Check Crash

### ISSUE THREAD

**Issue by sentrywasbored** [RPCS3/rpcs3#15886]
### Quick summary

Out of Range error in Dimensions Manager tool causes PS3 application to crash

### Details

Whilst using Dimensions Manager to facilitate a playthrough of LEGO Dimensions (BLES0205), an out of range error was thrown by the tool whilst moving a piece to the upper right position, crashing the PS3 Executable. 

### Attach a log file

[RPCS3.log](https://github.com/user-attachments/files/16482905/RPCS3.log)

**Comment by ReLyf47** [comment]
`Range check failed (index: 255, container_size: 7)
(in file D:\a\1\s\rpcs3\Emu\Io\Dimensions.cpp:256[:11], in function struct dimensions_figure &__cdecl dimensions_toypad::get_figure_by_index(unsigned char)) (error=0x2) (PPU: sys_usbd_transfer_data)`

Seems like this error happens if you move/load the toys too fast and not clearing them beforehand

i got mine for having the pad full and then changing from Lunatic Amp to Batmobile without clearing the Lunatic Amp entry first

[RPCS3.log.gz](https://github.com/user-attachments/files/16486929/RPCS3.log.gz)
