### ISSUE TITLE
[Regression] [macOS] [ARM] SDL doesn't appear for ARM builds

### ISSUE THREAD

**Issue by meh7an** [RPCS3/rpcs3#16028]
### Quick summary

The app on macOS ARM has no SDL available on its controller Settings.

### Details

![image](https://github.com/user-attachments/assets/af430697-81c5-42f4-8918-eed2095449c5)

### Build with regression

v0.0.33-16885-e56164f1

### Attach two log files

[External Log](https://mega.nz/file/TNMjBKgT#M-x-5svMZr6vngPWzdKMfw2G-I63FP4t5T4vpJEcPTM)

**Comment by kd-11** [comment]
Since we're not yet shipping the macOS for arm binaries yet, I think this is a problem caused by the configuration script people are using. Most build instructions to build on ARM do not mention removing SDL, but it is normal for developers and enthusiasts to remove it to cut down compile time if they know they won't need to use it.
Request the maintainer you got your build from to include SDL for you. There is nothing wrong with SDL on arm64 afaik, it just needs to be added at build time like we do for public builds.
