### ISSUE TITLE
[Bug] You can accidentally boot a game using right mouse button.

### ISSUE THREAD

**Issue by Hasster1** [RPCS3/rpcs3#16031]
### Quick summary

It is pretty inconsistent, but right clicking on a game multiple times can boot it, as if double right clicking on it. Kinda annoying, because sometimes it causes the game to boot when just pressing RMB on it right after stopping it.

### Details

It is NOT accidentally pressing the "Boot with custom configuration", just in case someone comments on that.

### Attach a log file

not needed

**Comment by Megamouse** [comment]
Invalid report.
Missing a log file with it happening.

**Comment by Megamouse** [comment]
Either way:
Turns out Qt doesn't care what button you press when you double click a list/table item, and they don't give us the means of knowing which button was pressed.
It's another case of Qt being stupid. You can even trigger this with any other mouse button like the mouse wheel.
To fix this we would have to implement our own event handling just for this nonsense.

**Comment by Hasster1** [comment]
So... should i close this issue then?

**Comment by Megamouse** [comment]
Maybe it would make more sense to open a feature request in their bug tracker.
But it can probably be fixed anyway.
