### ISSUE TITLE
Crystal Defenders [NPUB30092]

### ISSUE THREAD

**Issue by LasagnaPie** [RPCS3/rpcs3#16197]
### Quick summary

The game is running slow and kanji over the screen

### Details

The game is running slow and kanji over the screen, i tried default settings and clearing the cache but makes no difference.  

![crystal](https://github.com/user-attachments/assets/3785379b-b916-48cd-ba98-3c995bc22a36)

### Attach a log file

[RPCS3.log.gz](https://github.com/user-attachments/files/17342308/RPCS3.log.gz)

### System configuration

Windows 11
Ryzen 7800X3D
Radeon 7900XTX

**Comment by Triticum0** [comment]
I had the same issue 2 years ago. You should try and get a capture file if you want this to be fixed. Seem to also occur on other games as well so also fixed them too when the root cause is found #12895

**Comment by Triticum0** [comment]
Also shouldn't be getting performance issues when I last tested it, it was a locked 60 using llvm

**Comment by LasagnaPie** [comment]
![pricgy](https://github.com/user-attachments/assets/6237f5c8-a21c-48e7-bd04-775102e1fe88)

When the game runs slow, it goes back and forth,  "sys_timer_usleep" and "cellSysutilGetBgmPlaybackStatus". 



```
Type: PPU; State: 0x10224[w|s|mem|PAUSE] (LV2 suspended)
Priority: 1001
Stack: 0xd0001000..0xd0010fff
Joiner: detached
Last function: sys_timer_usleep
```

```
Type: PPU; State: 0x10224[w|s|mem|PAUSE] (LV2 suspended)
Priority: 1001
Stack: 0xd0001000..0xd0010fff
Joiner: detached
Last function: cellSysutilGetBgmPlaybackStatus
 
```

**Comment by someother1n** [comment]
Enabling "Allow Host GPU labels" in the Advanced menu seems to fix both the framerate and the graphics.


https://github.com/user-attachments/assets/97d50ce8-3666-4a87-bd67-77367808325f

**Comment by LasagnaPie** [comment]
With "Allow Host GPU labels" enables it runs around 60FPS but introduces input lag

**Comment by kd-11** [comment]
This game is advancing PPU logic so fast it starts to destroy it's own stuff because RSX gives a green light constantly. Host GPU labels works around this perfectly since the game will basically pause until the actual GPU has finished rendering previous work (basically like a glFinish command) -  but this is by design. You can "improve" performance by using PPU interpreter and downclocking your CPU as well which is hilarious.

**Comment by kd-11** [comment]
I'll leave the ticket open to remind me to implement host GPU labels for OpenGL which would be a perfect fit. Since OpenGL suffers from draw call dispatch overhead it the slow pace of command ingestion would be perfect for a game like this.
The feeling of input lag is caused by vulkan's rendering model which does batched recording and submission. This causes the renderer's responsiveness to be very spiky and can cause the game to feel weird.

**Comment by kd-11** [comment]
GPU labels for OpenGL implemented in https://github.com/RPCS3/rpcs3/pull/16234
Responsiveness is better than vulkan but the downside is that it only works with AMD cards. The same restriction actually applies with Vulkan but in some cases the host labels can work on NVIDIA without crashing. Future work will expand the feature to be properly multi-platform using the base framework added in the new PR.
