### ISSUE TITLE
de-synchronization between audio and video

### ISSUE THREAD

**Issue by BlackRocksShooter** [RPCS3/rpcs3#1728]
When he played for Hatsune Miku it happens many times that the video and audio you plan desynchronised increasingly plan. but if I pause the game and then resume put the image of the game stops and the audio is resynchronized with the video (temporarily, then returns as before)
desynchronization is preceded by a strange noise During audio

**Comment by Nezarn** [comment]
This isn't audio desync issue, at least for me it happens only in DX12, and audio isn't desyncing, but game either starts running at half speed (on my pc, idk how it runs on others), or just the audio becomes muted\garbage while having fullspeed.

It's easy to reproduce, for me 90% of the time its enough to just select a song, wait for it to load, and before pressing start, just go back to song selection screen.

With Vulkan, rpcs3 uses 346MB and 40-60% CPU, with DX12 1080MB and when this issue occur 80-90% CPU (otherwise 40-70%CPU) 

Im gonna try find out why does it starts using more cpu (i just need to redownload from git, but i have bad connection so it will take a while)

**Comment by BlackRocksShooter** [comment]
I was able to remain stable emulator for 3 continuous hours. after it went into crisis

**Comment by kd-11** [comment]
This is an issue with Xaudio2 and is seemingly intentional (it ignores the ingame framerate). With OpenAL you should get proper sync but extreme stuttering if your fps is below fullspeed. If you have a 1GB card, please do not use DX12. That backend has resource allocation issues causing it to use > 1GB even for simple 2D stuff and will cripple your performance greatly.

As such, this issue can be closed, unless OpenAL also lags behind.

**Comment by raven02** [comment]
@kd-11 .I wonder can we have smaller heap size here instead of 896M+128M

	m_readback_resources.init(m_device.Get(), 1024 * 1024 * 128, D3D12_HEAP_TYPE_READBACK, D3D12_RESOURCE_STATE_COPY_DEST);
246		m_buffer_data.init(m_device.Get(), 1024 * 1024 * 896, D3D12_HEAP_TYPE_UPLOAD, D3D12_RESOURCE_STATE_GENERIC_READ);

**Comment by kd-11** [comment]
@raven02 Yes, however, it'll require that we are smart about it though. Remember that vulkan had an issue with running out of descriptors and I had to track resource usage and flush the commandbuffers if we went over budget. A smaller readback resource is just fine. In my opinion 896M is too much. Most games aren't even pushing 100M. We can set a smaller readback heap e.g 512M and it should be ok. I'll have to look deeper into the DX12 code to see why that allocation is so large anyway.

**Comment by raven02** [comment]
Yes , i try to resize as 256M and tested few 2D and 3D games , it looks fine .

**Comment by kd-11** [comment]
I think querying available VRAM and setting to a fraction of it will be ok.

**Comment by raven02** [comment]
It would be better approach .For example my GT 650M only have 512M VRAM

**Comment by kd-11** [comment]
Ok. Add it to the list of graphics tasks. I'll investigate and see if we can have a better way of dealing with this, like maybe lazy allocation for the large buffers heap, or like vulkan where the heap is in smaller chunks allocated on demand. For now, I think it can be reduced to something like 256M

**Comment by raven02** [comment]
Ok. i will add it to the task list and pull out a reduced memory footprint PR .

**Comment by raven02** [comment]
Meanwhile , i'm wondering do we still need to keep the d3d adapter list as i think we are not going to use the Microsoft basic rendering driver.

**Comment by raven02** [comment]
Alright .

**Comment by minuteworld1** [comment]
this exact issue happens with hatsune miku on steamdeck

**Comment by alexou2** [comment]
i get the same issue on drakengard3 if i don't cap my fps at 30. even auto or ps3 default will have the issue

**Comment by joyboyxbt** [comment]
setting the framelimit to 30 in the gpu settings fixes this
