### ISSUE TITLE
DX12: missing blend factor 

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1759]
In DX12 , we have the following missing blend factor that not matching with DX12 blend factor function 

> 	case CELL_GCM_CONSTANT_ALPHA:
> 	case CELL_GCM_ONE_MINUS_CONSTANT_ALPHA:

However DX12 doesn't have corresponding blend mode while Vulkan has VK_BLEND_FACTOR_CONSTANT_ALPHA and VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA

@kd-11 , CONSTANT_COLOR is currently using DEST_COLOR instead to emulate , what do you think if it is okay to use DEST_ALPHA and INV_DEST_ALPHA for these 2 blend modes?

**Comment by kd-11** [comment]
constant color and alpha values are a color key passed to the rendering pipeline for computation in the blend equation. using DEST_ALPHA and INV_DEST_ALPHA is a hack and would return incorrect results, since they are a variable function across the canvas while the color key would be constant, and there is no guarantee that it even has to occur on screen. I'm not sure why dx12 would be missing such functionality, but a better solution would be required.

**Comment by raven02** [comment]
Alright . i think we can only leave it .Not too sure if we can do it in-shader using image load/store to setup custom blending

**Comment by SakataGintokiYT** [comment]
@raven02 
https://github.com/vlj/rpcs3/pull/53/commits/c337bb3251651a4db046115c5961312b6ce427ff

**Comment by kd-11** [comment]
@SakataGintokiYT That is a hack (incorrect)
