### ISSUE TITLE
TNT Racers [NPEB00221]-- Black screen--[OGL/Vulkan]

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#1762]
@kd-11 
@raven02 

Build {4260f68f}

Settings:
-PPU - Interpreter (Fast)
-SPU - Interpreter ASMJIT
-Vulkan / OGL
-1280x720 
-Xaudio2
-Frame limit OFF

LLE:
-libfiber
-libl10n.prx
-libresc
-libsre

*Vulkan- Log / FragmentProgram / VertexProgram : http://www91.zippyshare.com/v/nrssRAPf/file.html 

*OGL- Log /FragmentProgram /VertexProgram : http://www69.zippyshare.com/v/OSGWrGgQ/file.html

**Comment by raven02** [comment]
Yep , only DX12 works (resc+sre can also in-game)

**Comment by raven02** [comment]
Checked with rsx_cache branch , also black screen for OGL.

**Comment by kd-11** [comment]
Flickers badly even with dx12 for me on AMD.
By the way, this seems to be due to some oddity with the vertex shader generation code where the shader is bound before the vertex attributes are set. I'll change the default action in such a case.
It works in DX12 somewhat, but that is because dx12 combines all actions handled in begin<-->end in one large coalesced function.

**Comment by kd-11** [comment]
Fixing shader compilation fixes the opengl backend but introduces a freeze in vulkan similar to https://github.com/RPCS3/rpcs3/issues/1679. I'll submit a solution to both issues as soon as i'm able to.

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/pull/1766 fixes opengl and vulkan. DX12 stutters heavily for me in menus probably due to resource allocation issues (the menu is over ~1984 draw calls for whatever reason) and i'll look into that issue separately. This game could be a good target for optimizing the opengl backend as it is the most heavily impacted with performance being very poor but vulkan being the fastest on my machine.
