### ISSUE TITLE
OpenGL/Vulkan : depth read gcm sample issue

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#1775]
DX12 renders correct while OGL is broken and Vulkan only bit wrong scaling .

[depth_read.ppu.zip](https://github.com/RPCS3/rpcs3/files/312045/depth_read.ppu.zip)

![1](https://cloud.githubusercontent.com/assets/3000282/16011582/b891292e-31b8-11e6-962b-0244dd895a0c.jpg)
![2](https://cloud.githubusercontent.com/assets/3000282/16011584/b8bffdbc-31b8-11e6-8d2d-58b516b637fa.jpg)
![3](https://cloud.githubusercontent.com/assets/3000282/16011585/b8e5d8c0-31b8-11e6-904b-8ba0ab984f3f.jpg)

**Comment by raven02** [comment]
OGL one looks like it is scissor issue . Disable scissor in flip() fixed it but not too sure if it is the correct one .

**Comment by kd-11** [comment]
Those buffer width and height values in flip are often wrong and are the cause of various scaling issues in games. I'm considering just ignoring them in flip and using render-target dimensions but that might break more games. It is good that you have found a simple reproducible test that shows the problem.

As for the scissor test, i think you should check what value it is trying to set and compare with the correct value for this case (buffer_width and height) so we can pinpoint the cause of these problems. If it is only the scissor test in flip() however, it can be disabled imo, since the flipping function is part of the GPU emulation and not controlled by the application.

**Comment by raven02** [comment]
Yes, probably why vlj is not using it during flip . I'm checking out the rsx_cache to see how it is handling .
