### ISSUE TITLE
GL: fw_dice gcm sample broken texture

### ISSUE THREAD

**Issue by danilaml** [RPCS3/rpcs3#1887]
Works fine with D3D12 and Vulkan.
![](http://i.imgur.com/iBhbwEI.png)
Happened after https://github.com/RPCS3/rpcs3/pull/1865 by @vlj

**Comment by raven02** [comment]
@vlj  . In that refactoring commit , i observed 

-	__glcheck glDepthMask(rsx::method_registers[NV4097_SET_DEPTH_MASK]);
 +	__glcheck glDepthMask(rsx::method_registers.depth_write_enabled());

where 

		bool depth_write_enabled() const
		{
			return !!registers[NV4097_SET_DEPTH_MASK];
		}

It is true for DX12 and Vulkan but not GL i think

**Comment by kd-11** [comment]
Just noticed this as well. The depthmask seems correct by the way since GL just sets it to 0 or 1

**Comment by raven02** [comment]
I see @kd-11

**Comment by kd-11** [comment]
The problem seems to be the separable back and front diffuse lighting, but that makes no sense (looking at the shaders, they should have the same value, but they dont)

**Comment by kd-11** [comment]
I'm not sure what's happening here but I've noticed the following:

The sample passes diffuse color using the vertex_registers. The register data size is 16 bytes and attribute the size is given as 4. Unless the size parameter is the size of the whole vertex attribute, 
this implies that only one vertex is defined since float4 is 16 bytes wide. The buffer is then accessed using vertexID which is out of bounds hence the black bits. For some reason texel reads on vulkan and gl seem to be more lenient. Can confirm that hacking the vertex shader to read vertex 0 always returns correct results. Why it worked before at all I have no idea.

**Comment by kd-11** [comment]
Found the issue here https://github.com/RPCS3/rpcs3/pull/1865/files#diff-b7984c633ee70a99b6c5ade52375b28dL251

Other backends ignore this flag and mark all register access as non_array, while the current rsx decompiler still relies on this behavior. I'll submit a fix for this soon by adding a is_register field to the raw program state

**Comment by raven02** [comment]
Nice catch.
