### ISSUE TITLE
DX12/GL/Vulkan: Ethan: Meteor Hunter missing textures

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2052]
This applied to all backends that missing the same background texture .

![ethan 1](https://cloud.githubusercontent.com/assets/11453507/16085491/8b937f48-331c-11e6-8204-3aaacf27788b.PNG)

![ethan 2](https://cloud.githubusercontent.com/assets/11453507/16085524/a1bb18b2-331c-11e6-9fae-8b47d23f8273.PNG)

[LOG](https://mega.nz/#!GVtGRbRS!rYsbuzdlE8FF2jBdbqFlCdC-0Au4ZAP8uuTPAaXfIk0)

**Comment by raven02** [comment]
Original PS3 should be 

![ethan 3](https://cloud.githubusercontent.com/assets/11453507/16085513/99480546-331c-11e6-9ca2-2c52e007d46e.PNG)

**Comment by raven02** [comment]
Tested with latest build . Still missing the background in all backends

**Comment by SakataGintokiYT** [comment]
@AniLeo 
@raven02 

Fixed by #3057

**[DX12]**
![dx12](https://user-images.githubusercontent.com/13681488/28492038-91c5092e-6efb-11e7-9c56-39c5f2695672.png)
**[OpenGL]**
![opengl](https://user-images.githubusercontent.com/13681488/28492035-85e9766c-6efb-11e7-8508-c869607e3d9b.png)
**[VK]**
![bez tytulu](https://user-images.githubusercontent.com/13681488/28492004-e9985418-6efa-11e7-9c19-759eedfa2364.png)
