### ISSUE TITLE
DX12/GL/Vulkan : Project Diva F 2nd issue

### ISSUE THREAD

**Issue by RainKikyou** [RPCS3/rpcs3#2068]
To get into game, we have to create a hdd1 folder, ignore that data install failed message and boot into game.For api, dx12 will always stuck at menu, and always white screen for vulkan 
specs：I7 6700K-4.0GHZ+ GTX 1070 GAMING X 8G
log：https://drive.google.com/open?id=0B4z-S0oOZ2FgbVVPWWVLejhwLVE
![r0ow mu1f_47z sm zqk c](https://cloud.githubusercontent.com/assets/20301499/17630549/5f97b004-60f2-11e6-8c09-21baac529c61.png)
![yyi ojwre4 voehzjf d1e9](https://cloud.githubusercontent.com/assets/20301499/17630536/57bbf30e-60f2-11e6-8bee-5a147b09dc54.png)
dx12
![qq 20160813010631](https://cloud.githubusercontent.com/assets/20301499/17630998/aa9bac2a-60f4-11e6-9e0f-21cdb5d738b0.jpg)
![fy5c 9p i k g4j ug 2bf9](https://cloud.githubusercontent.com/assets/20301499/17630795/816f7012-60f3-11e6-8a9d-8a592798cdd6.jpg)
![_65ujwn0rn4nvy c zs55](https://cloud.githubusercontent.com/assets/20301499/17630808/939dfb00-60f3-11e6-8879-f9966e2c02a3.jpg)
vullkan
![rhq45qw4d2imp24 rlh1e2h](https://cloud.githubusercontent.com/assets/20301499/17630991/9a92da42-60f4-11e6-9fa0-92fb632fccc6.png)
ogl
![nl l4vlry_9 fna9 7t2k](https://cloud.githubusercontent.com/assets/20301499/17630994/a316b9d6-60f4-11e6-89ab-9b303192823d.png)

**Comment by Nezarn** [comment]
@RainKikyou its not getting stuck at menu, if you're talking about spinning miku, hold you right stick down+right and your left stick too, you can select play then. in vulkan if the fps counter is still going at white screen, just wait, game has ridiculous loading times sometimes because of #1810 (but either way you can't get ingame, since it goes on infinite loading (or extremely slow loading), i've tested it by waiting 8 hours to load.), so wait ~10-15 min (depending on your PC)

Also you don't need to make hdd1 folder, you can fix it by making 2 folders in dev_hdd0\game, my game's ID is NPEB02013 so i need to make NPEB02013_CACHE and NPEB02013_DATA. (if you have the DISC version instead of PSN, then just simply press no at install, since it can't install)

Also fix typo in your issue's title + post PC specs and rpcs3.log (upload it somewhere or pastebin.com)

**Comment by zminhquanz** [comment]
so . Project Diva F 2nd is working on intro , menu and ingame not booting into , hang blackscreen

**Comment by Nezarn** [comment]
@raven02 labels are a bit incorrect, game works fine (as long as it can go) with OpenGL (aside from miku beign a little pale), the only bug in DX12 that its dark+black 3D models, and IDK about Vulkan (but if i need to guess its either the same as ogl or as dx12), this game has long loading issue (as i said its because #1810) + threading\cpu issue (sometimes no\late sound, theres 2 warnings about 2 cpu related stuff (PPU: MFFS PPU:MTFSF), and also Miku is spinning in the main menu, and that can be related to cpu issue)

That opengl error @RainKikyou is getting, i got that only in linux with my intel igpu (that has only OGL 3.3 support in linux), in windows game boots fine with OGL too (my igpu has 4.3 support here), video proof: (this is what the game can do currently)

https://www.youtube.com/watch?v=DBhdTmBn83A

Log: https://gist.github.com/Nezarn/002b97e9acf74cdf0e5737a6f0ede36c

**Comment by kd-11** [comment]
About OGL: I'll update the renderer to not crash due to op errors and instead rely on driver debug reporting which should be much better for these kinds of reports. Any output on vulkan with debug output enabled?

**Comment by Nezarn** [comment]
@kd-11 it would be nice if someone could test the game in vulkan, since sometimes the game likes to have ~5 min load time, and sometimes it stays on white screen for a while.

**Comment by Nekotekina** [comment]
#1810 only makes file access slightly slower (depends on your hardware).

I suspect RSX cache may affect loading times, in Project Diva F (not 2nd) it invalidates 0x20000000+ memory region quite a lot during loading. With debugger attached, it's almost dead.

**Comment by Nekotekina** [comment]
Nevermind, this is unrelated.

**Comment by Nezarn** [comment]
@Nekotekina how can i disable RSX cache? I wanna check if the game can load ingame (and i wouldn't care about 1 fps, im quite patient)

**Comment by Nekotekina** [comment]
I didn't try to disable it yet and I doubt it would help in this situation. You can try to cherry-pick 86a092815aa6362368604783c59eeaa1bd7733e0 and check thread times in logs.

**Comment by Nezarn** [comment]
@Nekotekina full log: https://www.dropbox.com/s/ry4ptx1jqxz7a7j/RPCS3_threadtime_log.zip?dl=0

cherry picked thread times (since i guess you mainly need these): https://gist.github.com/Nezarn/49cc273ccc6854c12df817cdc9b84051

**Comment by raven02** [comment]
This one indicate something?

·! {PPU[0x70000000] Thread (main_thread) [0x006af4a4]} Thread time: 124.843750s (434.616609Gc); Faults: 396356 [rsx:124, spu:0];

**Comment by Nezarn** [comment]
@Nekotekina btw in 0.0.0.6 (before your 0.0.0.9 PR was merged) the demo worked better than now, because back then, the tutorial was completely playable (just had graphical issue that the background was "black" + by some reason the sticks doesn't work correctly on gamepad, sometimes it doesn't even register, sometimes its slower), and the menus worked fine, there was no ridiculous loading times\"hangs". (but still doesn't go into ingame at normal songs...)

**Comment by AniLeo** [comment]
Tutorial works, you don't have to do those shinenigans to make the game work currently, but you still can't get ingame.

**Comment by AniLeo** [comment]
Menu is now visually okay, can be closed. Any remaining issues can be tracked using #2075
