### ISSUE TITLE
[D3D12 Texture] HRESULT = The parameter is incorrect

### ISSUE THREAD

**Issue by SakataGintokiYT** [RPCS3/rpcs3#2108]
Log : https://gist.github.com/SakataGintokiYT/ed27b614018d4ae076722f6c1823cb75
Shaderlog : https://mega.nz/#!oNww0LgK!9yIDE7A0AfRwTkXu6Yr150JkqZeS_gBPOpm4AhMtA-g

```
F {rsx::thread} class std::runtime_error thrown: HRESULT = The parameter is incorrect.
(in file C:\rpcs3\rpcs3\Emu\RSX\D3D12\D3D12Texture.cpp:137)
```

**Comment by SakataGintokiYT** [comment]
@kd-11
Do you know how to fix it ?

**Comment by raven02** [comment]
I did track this compressed texture (CELL_GCM_TEXTURE_COMPRESSED_DXT45) but it looks good .

 Vulkan also return this value but no problem

```
E {rsx::thread} RSX: dxgi_format = 4d, texture.width() = 200, texture.height() = 4e, texture.get_exact_mipmap_count() = 1
F {rsx::thread} class std::runtime_error thrown: HRESULT = The parameter is incorrect.
(in file Emu\RSX\D3D12\D3D12Texture.cpp:138)
```

**Comment by raven02** [comment]
Or it is alignment issue?

**Comment by kd-11** [comment]
This error is identical to the opengl error GL_INVALID_PARAMETER. It just means an illegal value was passed to the texture function (in this case, it could be anything from dimensions to the passed data size; compressed textures are sensitive like that). That's why it is only present on some games and not others, making it difficult for devs to reproduce.
