### ISSUE TITLE
RSX: Unknown vertex base type 0

### ISSUE THREAD

**Issue by lightsteam** [RPCS3/rpcs3#2116]
Title: LittleBigPlanet

F {rsx::thread} class std::runtime_error thrown: Unknown vertex base type 0
(in file C:\rpcs3\rpcs3\Emu\RSX\gcm_enums.cpp:16)

**Comment by raven02** [comment]
Disgaea 3 also hit the same error and cannot boot up .

**Comment by Nezarn** [comment]
Hatsune Miku Dreamy Theater 2nd hits this too when trying to go ingame (with kd-11's pr since that is needed for this game to boot)

> F {rsx::thread} class std::runtime_error thrown: Unknown vertex base type 0
(in file C:\rpcs3\rpcs3\Emu\RSX\gcm_enums.cpp:16)

**Comment by Nezarn** [comment]
Theres a way to workaround this issue until its properly fixed
> case 0: return rsx::vertex_base_type::f;

This doesn't break everything (like raven02's attempt to workaround), and can make games go further.
For example: https://www.youtube.com/watch?v=ng49CyaAPHo

**Comment by raven02** [comment]
It mostly came from vertex data zero size that return type 0 .

**Comment by kmrkevin** [comment]
I have exactly the same problem when trying to run disgaea 4, it seems to be charging with a white screen till:

U {PPU[0x70000000] Thread (main_thread) [0x0042afa0]} cellPamf TODO: cellPamfReaderInitialize(): verification
S {SPU[0x73] Thread (_synth2 Thread)} SPU: Function detected [0x01d28-0x022b0] (size=0x588)
S {SPU[0x73] Thread (_synth2 Thread)} SPU: Function detected [0x00d00-0x0158c] (size=0x88c)
S {SPU[0x73] Thread (_synth2 Thread)} SPU: Function detected [0x024b8-0x02e78] (size=0x9c0)
F {rsx::thread} class std::runtime_error thrown: Unknown vertex base type 0
(in file C:\rpcs3\rpcs3\Emu\RSX\gcm_enums.cpp:16)

The last two lines is where it fails and appears in red. Don't know about computing neither program so any easy fix or explanation about it?

**Comment by andre4688** [comment]
in version  O1L committed with Nekotekina Fixed NV4097_SET_COLOR_CLEAR_VALUE (#2135) 
affect all game F {rsx::thread} class std::runtime_error thrown: Unknown vertex base type 0
(in file C:\rpcs3\rpcs3\Emu\RSX\gcm_enums.cpp:16)if I update NVIDIA last

**Comment by hcorion** [comment]
I get a white screen on Terraria as well. Reverting fixes it.
GTX 1070
Windows 10

**Comment by kd-11** [comment]
This is getting ridiculous. @raven02 just set the default value to float (1).

Here's what is now causing this:
Since vlj added the register decoders, calls to get vertex attribute properties are now wrapped. If an attribute is not set, it has size 0, and the type becomes unreliable especially when the application has just started. If you query an attribute's existence by checking its size() method, a type comparison is done to check if it is of cmp type (more on that here https://github.com/RPCS3/rpcs3/issues/2136). This will almost always cause this error to show up if an attribute is not yet prepared. Or maybe we should clear attribute type to float on startup?
