### ISSUE TITLE
Regression :  1942 Joint Strike broken in-game (CMP vertex base type)

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2136]
1942 Joint Strike broken (vertex corruption) in-game using Vulkan backend .

Revert this following line make it back to normal https://github.com/RPCS3/rpcs3/pull/2134

		if (decode_reg().type() == rsx::vertex_base_type::cmp)
			return 4;

![untitled](https://cloud.githubusercontent.com/assets/3000282/18479047/0c3469b6-7a06-11e6-8d16-745903e6954e.jpg)

**Comment by vlj** [comment]
In VKvertexBuffers.cpp, in VkFormat get_suitable_vk_format(rsx::vertex_base_type type, u8 size) :
if you replace the 5th element of const VkFormat vec4_types[] array (VK_FORMAT_R16G16B16A16_SFLOAT) to VK_FORMAT_R16_SFLOAT (value in vec1_types) does it change output ?

**Comment by vlj** [comment]
Another possible solution, in 	void copy_inlined_data_to_buffer(void *src_data, void *dst_data, u32 vertex_count, rsx::vertex_base_type type, u8 src_channels, u8 dst_channels, u16 element_size, u16 stride)
 if you set dst_channels to 1 in case of vertex type cmp, does it work better ?


The issue is that if base type is CMP, the vector size is irrelevant (as long as it's non null). CMP is a compressed format, it encodes on 32 bits a vec4 whose last component is always 1.0.

**Comment by O1L** [comment]
@vlj  It also breaks the most of GCM samples (throw "Unknown vertex base type 0" exception). If you want, I can send you gcm and other samples.

**Comment by raven02** [comment]
1st solution fixes the issue while 2nd one not.

BTW , unknown vertex base type 0 issue has been existed for a while and it is a regression recently.

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp#L117-L123
I used the src attibute size to determine number of elements to copy. If we return cmp as 4, it assumes we are copying 4 elements from src to dst which is wrong since cmp only has 3 usable components and the fourth should be 1, but is not actually set in the stream.

**Comment by kd-11** [comment]
See https://github.com/RPCS3/rpcs3/issues/2116#issuecomment-247786269 on why vertex base type is now failing.
