### ISSUE TITLE
GL/Vulkan : Depth read GCM sample wrong scaling 

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2143]
GL (Right Top corner scaling wrong)
![1](https://cloud.githubusercontent.com/assets/3000282/18615728/99e27ffe-7de0-11e6-805d-3b42da7bdac0.jpg)

Vulkan (Right Top corner scaling wrong)
![2](https://cloud.githubusercontent.com/assets/3000282/18615731/a1967516-7de0-11e6-846e-3c7addc94a7f.jpg)

DX12 (Correct)
![3](https://cloud.githubusercontent.com/assets/3000282/18615729/9de084e8-7de0-11e6-9d78-24ad3543c3b1.jpg)

**Comment by kd-11** [comment]
@raven02 Could you please attach the sample here?

Also, as a suggestion, we need a task tracker for all these samples that are currently buggy. When adding features, we can check that we don't break anything by checking output against them.

**Comment by raven02** [comment]
[depth_read.ppu.zip](https://github.com/RPCS3/rpcs3/files/479097/depth_read.ppu.zip)

It is nice and less regression.

**Comment by kd-11** [comment]
Seems the vertices passed and/or the transform matrix are glitchy. The verts sent for the overlay are too small, but the viewport is correctly set.

**Comment by O1L** [comment]
Earlier this issue has been fixed here https://github.com/RPCS3/rpcs3/commit/3b5cd4845e6885160649d11214e7a98b5b9b34fc

**Comment by kd-11** [comment]
With that commit, the matrix buffer is filled manually rather than using the shared rsx code. I'll look into how the two schemes differ.

**Comment by kd-11** [comment]
the issue here is with the scale_offset_matrix computation: Its made for the d3d backend. We are "multiplying" the viewport clip volume with the viewport scale dimensions then using glViewport with the viewport dimensions multiplying the value again (hence shrinking it). DH separated the matrices (but still multiplied them together, which doesnt work for this case) and vlj used the clip volume as the viewport parameter. Either one should work fine.

It seems one has to ignore either the clip volume or the viewport itself. Since the viewport matrix is already in scale_offset_matrix, I'll use the clip volume dimensions for viewport and we can decide from there.

**Comment by kd-11** [comment]
This is now fixed
