### ISSUE TITLE
Error compiling rpcs3 on Linux

### ISSUE THREAD

**Issue by luntik2012** [RPCS3/rpcs3#2229]
`                                       ^
[ 78%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/stdafx.cpp.o

[ 79%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/rpcs3_version.cpp.o

/tmp/rpcs3/rpcs3/rpcs3_version.cpp:3:25: fatal error: git-version.h: No such file or directory
compilation terminated.

rpcs3/CMakeFiles/rpcs3.dir/build.make:7626: recipe for target 'rpcs3/CMakeFiles/rpcs3.dir/rpcs3_version.cpp.o' failed

make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/rpcs3_version.cpp.o] Error 1

CMakeFiles/Makefile2:233: recipe for target 'rpcs3/CMakeFiles/rpcs3.dir/all' failed

make[1]: *** [rpcs3/CMakeFiles/rpcs3.dir/all] Error 2

Makefile:127: recipe for target 'all' failed

make: *** [all] Error 2
`

**Comment by luntik2012** [comment]
2001  sudo apt-get install cmake build-essential libopenal-dev libwxgtk3.0-dev libglew-dev zlib1g-dev libedit-dev libvulkan-dev
 2002  cd /tmp/
 2004  git clone https://github.com/RPCS3/rpcs3
 2005  cd rpcs3/
 2006  git submodule update --init
 2009  cmake CMakeLists.txt && make && cd ../

**Comment by Nezarn** [comment]
git-version.h is always broken, just manually make one like this

https://github.com/MissValeska/rpcs3/blob/master/rpcs3/git-version.h

**Comment by Nekotekina** [comment]
I don't understand why it's broken, when it works on Travis.

**Comment by paulsapps** [comment]
Someone should just make a docker image

**Comment by legluondunet** [comment]
Same problem for me with the last git version from December, 15th 2016:

`
$ make
...
[ 81%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/rpcs3_api.cpp.o
cc1plus: warning: /home/romain/Applications_persos/Jeux/Emulateurs/Consoles/Sony Playstation 3/rpcs3/rpcs315122016/rpcs3/cotire/rpcs3_CXX_prefix.hxx.gch: not used because `__STDC_CONSTANT_MACROS' is defined [-Winvalid-pch]
[ 81%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/rpcs3_version.cpp.o
cc1plus: warning: /home/romain/Applications_persos/Jeux/Emulateurs/Consoles/Sony Playstation 3/rpcs3/rpcs315122016/rpcs3/cotire/rpcs3_CXX_prefix.hxx.gch: not used because `__STDC_CONSTANT_MACROS' is defined [-Winvalid-pch]
/home/romain/Applications_persos/Jeux/Emulateurs/Consoles/Sony Playstation 3/rpcs3/rpcs315122016/rpcs3/rpcs3_version.cpp:3:25: fatal error: git-version.h: Aucun fichier ou dossier de ce type
 #include "git-version.h"
                         ^
compilation terminated.
rpcs3/CMakeFiles/rpcs3.dir/build.make:7776 : la recette pour la cible « rpcs3/CMakeFiles/rpcs3.dir/rpcs3_version.cpp.o » a échouée
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/rpcs3_version.cpp.o] Erreur 1
CMakeFiles/Makefile2:233 : la recette pour la cible « rpcs3/CMakeFiles/rpcs3.dir/all » a échouée
make[1]: *** [rpcs3/CMakeFiles/rpcs3.dir/all] Erreur 2
Makefile:127 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2
`

It doesn't compile because of a missing file: git-version.h
Then I found this file on google:
https://github.com/MissValeska/rpcs3/blob/master/rpcs3/git-version.h
I put it in the main rcps3 git folder and it finally 100% compiled.
Why this file is missing? That is the question.

Thank you for your help.
LGDN

Ubuntu 17.04 Zesty Zapus 64 bits
NVIDIA GeForce GTX 770
official Ubuntu Nvidia drivers 367.57 - 1920x1080
Processor Intel i5-3570 3,4 Ghz
8 Go RAM

**Comment by zekesonxx** [comment]
Issue still in place as of 2017-01-21.

**Comment by al0xf** [comment]
As of 2017-01-21 the correct build instructions that work around any bugs are as follows (assuming a completely new install of debian/ubuntu/similar):

```
sudo apt-get install cmake build-essential libopenal-dev libwxgtk3.0-dev libglew-dev zlib1g-dev libedit-dev libvulkan-dev git
mkdir ~/git/ && cd ~/git/
git clone https://github.com/RPCS3/rpcs3.git
cd rpcs3/
git submodule update --init
cmake CMakeLists.txt && make GitVersion && make
cd bin/ && ./rpcs3
```

**Comment by opensrx** [comment]
Here is what I have with new installation instructions.

srx@srx-desktop:~/rpcs3/rpcs3$ cmake CMakeLists.txt && make GitVersion && make
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type selected, default to Release
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
CMake Warning (dev) at 3rdparty/libpng/CMakeLists.txt:317 (get_target_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "png16_static".  Use
  the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- cotire 1.7.3 loaded.
-- Initializing RPCS3_SRC_DIR=/home/srx/rpcs3/rpcs3/rpcs3
-- Found wxWidgets: TRUE  
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found OpenAL: /usr/lib/x86_64-linux-gnu/libopenal.so  
CMake Error at /usr/share/llvm-3.8/cmake/LLVMConfig.cmake:178 (include):
  include could not find load file:

    /usr/share/llvm/cmake/LLVMExports.cmake
Call Stack (most recent call first):
  rpcs3/CMakeLists.txt:91 (find_package)


CMake Error at /usr/share/llvm-3.8/cmake/LLVMConfig.cmake:181 (include):
  include could not find load file:

    /usr/share/llvm/cmake/LLVM-Config.cmake
Call Stack (most recent call first):
  rpcs3/CMakeLists.txt:91 (find_package)


-- RPCS3: using builtin libpng
-- RPCS3: using builtin ffmpeg
CMake Error at rpcs3/CMakeLists.txt:159 (llvm_map_components_to_libnames):
  Unknown CMake command "llvm_map_components_to_libnames".


-- Configuring incomplete, errors occurred!
See also "/home/srx/rpcs3/rpcs3/CMakeFiles/CMakeOutput.log".
srx@srx-desktop:~/rpcs3/rpcs3$

**Comment by luntik2012** [comment]
I can compile current version, closing

**Comment by CoalaJoe** [comment]
Note: It workes when installing `qt5-default` on Ubuntu.

**Comment by jbeich** [comment]
> I don't understand why it's broken, when it works on Travis.

Travis uses [3 make jobs](https://github.com/RPCS3/rpcs3/blob/89f676de75e0/.travis.yml#L75) during build. 67b82debb3ab while ugly fixed it. Downstream automation may build several packages at once but allocating only one job for each.
