### ISSUE TITLE
[Linux]: no Vulkan render

### ISSUE THREAD

**Issue by legluondunet** [RPCS3/rpcs3#2255]
Hello,
I just compiled rpcs3 from git on Linux Ubuntu and I don't have the Vulkan render in the render list, only OpenGL.

Though libvulkan-dev is installed and I set the "VULKAN_PREBUILT" option to "ON ".

**Comment by magiruuvelvet** [comment]
As far as I know the Vulkan renderer is still not finished for Linux. There is a fork you can try, but don't expect too much from it at this time. https://github.com/rcaridade145/rpcs3

**Comment by giovannilaura** [comment]
hi folks i have managed to get rpcs3 https://github.com/rcaridade145/rpcs3.git to work on vulkan fps counter does not work and i had to implement xbox joystick (simplistic by emulating keypresses) but i have a problem that prevent me to publish it since i managed to get it to work but by modifiiing cmake linkings (because of GTK version) and now i cannot cmake .. anymore because i always get linking with gtk2 and i neeed it for gtk3 can anyone help me btw gtk 3 is needed because of vulkan bindings AND because wxWidget ist against gtk3 
![ps3air tonelico quoga](https://cloud.githubusercontent.com/assets/25445576/22454779/afc0c42c-e788-11e6-8d41-4ccbdf579d77.jpg)

**Comment by ShalokShalom** [comment]
@giovannilaura Is there an own dedicated issue open for this?

**Comment by AniLeo** [comment]
Solved by #2842
