### ISSUE TITLE
Would a patreon/crowdfunding speed things along?

### ISSUE THREAD

**Issue by tkoham** [RPCS3/rpcs3#2263]
Is this something you'd even consider? I am very interested in seeing this project thrive, as are many others, but I, like the majority of those watching the project, do not have the expertise to help through direct code contributions.

**Comment by XeClutch** [comment]
If it means they are able to get newer or a more diverse set of hardware to test compatibility, probably. But unless you were able to get enough money together to allow the guys to quit their jobs and work on this full-time, the difference would probably be relatively minimal.

**Comment by ssshadowww** [comment]
It's probably not impossible to gather the money, cemu sits at $5600/month right now: https://www.patreon.com/cemu  
The question is who it goes to and if that person is willing to take it. It was discussed on the forum a long time ago and people weren't to keen to do it. However today rpcs3 can actually boot some real games so the situation is quite different I suppose. But in the end it's up to Nekotekina or whoever.

**Comment by tkoham** [comment]
feature/bug bounties and hiring full-time devs would probably be the best ways to distribute the funds. I can try to drum up some interest and get exposure for the project if I can get the core devs on-board. anyone here have a way to contact them?

**Comment by SakataGintokiYT** [comment]
@Nekotekina

**Comment by Nekotekina** [comment]
Hi, this could be very interesting in theory, but I'm not really sure how it's supposed to work. There is inactive https://www.patreon.com/RPCS3 page btw. I "own" it currently (it was created by tambry).
How Patreon page should look like, i.e. what devs offer to the patrons?
RPCS3 is free and open-source and will always be, and it seems impossible to pay for every contribution, especially small ones. What if it will cause conflicts?
I personally would be glad to continue my work on RPCS3, if I could get some $, and I don't need much. I'll probably continue it anyway though.

**Comment by al0xf** [comment]
One word: marketing. 

You go to big sites with interested people like Reddit and show some very popular game like Demon's Souls, The Last of Us, Red Dead Redemption (these currently don't work at all though) or maybe even Persona 5 (unstable and 1 fps) and say "I need $1000/month to actively work on rpcs3, we hope to greatly improve compatibility and performance by implementing x, y, and z over the coming month and year". You will get even more support by providing easy to digest content like short developer comments on YouTube or something similar, although it can take some time to produce. For instance YandereDev is a indie game developer that sits at $5000/month on Patreon pretty much solely based on his YouTube updates (the game itself looks pretty bad TBH). 

Basically get Demon's Souls or something to boot/barely go in game and then hit reddit and other places with enthusiasts willing to pay for something like this with a clear message and well defined goals. Push hard and try to get as far as possible from the initial exposure. Consider even timing the announcement so it coincides with say EU/US evening when most people will be looking.

Emunewz can also help here, we can have a special subforum for people who donate >$5/month or something where they will get faster and better technical support, maybe even get "exclusive" updates directly from you, and so on. 

Since you have years of commits to the project so no one can doubt your abilities. Of course you can't be certain that it's possible to get Demon's Souls (or some other advanced game) playable, and you have to be open about this, but it doesn't look like anyone else has a better chance of succeeding. 

And one last thing: there is definitely interest, Look at the cemu patreon. Or consider how many comments posts about rpcs3 get on reddit, different forums, youtube, and so on.

**Comment by tkoham** [comment]
Exactly. The fact that there are far more worthwhile exclusives on PS3 compared to the WiiU should be enough to drive interest. Like I said, I can generate interest and get some pr in the hands of the media if you need exposure, and I'm willing to donate my time for community managment and marketing, since it's the only capacity i can help the project with. 

As for implementation: you ask for a wage to pay yourself and a few committers to consistently work on the project. bonus goals could include a bug bounty budget, a contributor forum with early build access, etc. big donators could suggest games that they want compatible down the line, etc. There's tons of ways to go with it.

**Comment by AniLeo** [comment]
That's a good point you touched above. People donating for a dev to work in functions that improve a game of their choice. It keeps the project open-source and its win-win for both sides. 
I do believe a new website with more functions is needed though, something like citra's or pcsx2's websites. Also a game compatibility list that can be better managed than a bunch of threads in the forums. 
The forums also need an update but not sure on what needs to be changed.

**Comment by al0xf** [comment]
It can be hard for a layman to determine what needs to be worked on in order to get a specific game working. I mean how many people knows what "AOT LLVM PPU Recompiler" even means? What the purpose of spurs is? Common reasons multi threaded applications explode in your face? 

As you can see the course forward needs to be carefully evaluated. 

But yes the forum and website needs updating, and a wiki with settings used for certain games and so on could certainly be useful. At the very least let some of the trusted forum members have basic mod powers so threads can be moved, the first post of a thread be updated, and so on.

**Comment by tkoham** [comment]
Yep, an overhaul of the forums would be necessary, and a compatibility database would need to be created. The latter could easily be a funding goal, and the former is a realistic undertaking. The key is good management and communication with the folks ponying up the dosh. Transparency and honesty is paramount.

**Comment by ikki84** [comment]
I don´t know how patreon would help in RPCS3 since it is an open-source project and I just hope that people don´t stop sending pull requests because only the main team are earning money.
I also don´t know if the main devs are working now and if is possible for them to quit their jobs and keep working on it like a full-time job.

A thing that could help is work in a better compatibility list, with logs too.

**Comment by tkoham** [comment]
Open source doesn't mean you can't pay the people spending a lot of time developing it. Also: Bug bounties and part time contributor pay are other, easily implemented options. It also has the benefit of getting devs with more free time interested in contributing, and attracting more talent to the project.

**Comment by RainKikyou** [comment]
As we all know, rpcs3 is an open source project, but if the patreon is on, I would be happy to patreon it, but as you know, there is a network blockade in China, especially youtube, etc. I have access to make China understand This information in turn leads to more patreones

**Comment by zminhquanz** [comment]
i think you can open RPCS3 patreon , as you see , Cemu Wii U Emulator , patreon donate would help developer feel better to development and project todo finished to be faster than developer plan expected

**Comment by AniLeo** [comment]
Cemu and RPCS3 work differently. Cemu is closed soy

**Comment by AniLeo** [comment]
Cemu and RPCS3 work differently. Cemu is closed source and devs are paid to work full time in it, the community can't submit changes to the code whatsoever. People donate so they can get early access builds and some other perks. 
RPCS3 is open source so these perks can't be offered. Also, there are no devs working full time and that's costly

**Comment by al0xf** [comment]
An alternative is to just start small and consider the patreon a personal tip jar for Nekotekina, not for rpcs3 as a project. Say it like it is, the money will buy him coffee and maybe computer upgrades for continued development. A completely voluntary donation where the only thing you get in return is further development. There are other open source free software that's funded like this, Gimp for instance.

**Comment by Nekotekina** [comment]
I created a preview page: https://patreon.com/preview/53f9ddef35c54127aa423febeb8c1be2
Any suggestions are appreciated.

**Comment by AniLeo** [comment]
We should probably also get a more friendly chat for the common users - like a Discord server - instead of having an IRC channel only. They're free and almost everyone has one nowadays. What do you think?

**Comment by kirbyfan64** [comment]
Gitter?

**Comment by al0xf** [comment]
Looks very good at a glance. A few things:

"Emulation is tricky thing" should be "Emulation is **a** tricky thing"

"Other **expences**. Something that will help to improve the emulator." Not very specific, maybe problematic for some people. Also the spelling is "expenses". 

Supporter+ names could be added to the about dialog in the emulator instead of the readme, just make a few headings like "developers", "thanks to", and "supporter+"

There should be more tiers between $1 and $10, at least also $5. Not sure what the reward should be. 

Lastly with a compatibility DB and support forum we need more moderators. Even with the old guys + Annie and me (ssshadow) I don't know if it's enough. 

Also a Discord server is not a bad idea in theory but we need to spend time in it for it to be meaningful. 

But yeah, this looks good. There are a few practicalities to solve and then we just need some good marketing material to push the Patreon with, like at least some very popular game going to the main menu or something. We have Catherine and Persona 5 which I guess are decently popular but there are bigger titles out there that more people care about.

**Comment by AniLeo** [comment]
Gitter seems to have a few limitations that Discord doesn't have.
For example, private rooms can only take up to 25 users and there are no voice channels. 
But seems like a pretty solid option nevertheless, although I believe Discord would be better to gather up folks that aren't that keen in the development process / GitHub and just want to get on the bandwagon.

**Comment by Nekotekina** [comment]
https://discord.gg/fNfa6Wd I created a "server", let's see how it looks like...

**Comment by YaPeL** [comment]
You can offer the same perks as cemu, you don't have to push your local changes to github in a public way, IIRC as long as you give the source code to patreons, you are not breaking the GNU GPLv2, sure, you cant have a drm version of it, but cemu drm has been broken countless of times and things keep working for them

**Comment by al0xf** [comment]
But that would be a shit thing to do.

**Comment by YaPeL** [comment]
if the gpl allows it, then is not.

**Comment by yahfz** [comment]
I think this is not going to work out by being open-source. How are you going to decide who needs more money than the other dev? How are you going to manage the money between the developers? Can anyone prove me wrong? I would like to see someone else opinion towards my thoughts.

**Comment by al0xf** [comment]
This patreon is basically for Nekotekina and not rpcs3 as a project. Other foss projects do the same thing, Gimp for instance: https://www.patreon.com/pippin

**Comment by yahfz** [comment]
Yes, al0xf. I really think he should just fund himself, so he can focus on the project.

**Comment by DAGINATSUKO** [comment]
Hello, I've been following RPCS3 for quite awhile now, since 2014 and I'm obsessed with the PlayStation 3's hardware and hardware emulation in general. I'm a fairly experienced web developer and I would love to re-imagine the official RPCS3 website. (I tend to visit the current website every now and then) I've realized that the current website isn't exactly fitting and could use some work due to the fact that most newcomers think it's one of those bait emulator sites and the fact that it's lacking a good deal of content an emulator developer's website should have. I primarily focus on front-end design and usability that scales across different devices. My workflow is composed of experience with html, css, jquery and php. I'd love to show some of my work if need-be, and I'm willing to work on the site for free purely out of passion and support for the emulator.

Here's a video of of my personal website that isn't yet published. I'm just using it as an example to show what I'm capable of. You may need to download the video due to Google Drive's low quality previews.

https://drive.google.com/open?id=0Bz1LDq47Nef8bWRJak9USTRoTkE

**Comment by yahfz** [comment]
That sounds awesome DAGINATSUKO. Talk to some of the mods here: https://discordapp.com/invite/BhNFwR7

**Comment by AniLeo** [comment]
Btw official link of the server is http://discord.me/RPCS3

**Comment by kirbyfan64** [comment]
I didn't even realize rpcs3 had a website... Also:

> html, css, **jquery**

So you aren't obsessed with using random new frameworks or contraptions wherever possible... This guy knows his stuff!

**Comment by al0xf** [comment]
The Patreon is live! https://www.patreon.com/Nekotekina

Spread the word.

**Comment by raven02** [comment]
I'll support Patreon and paid as well .

**Comment by Nekotekina** [comment]
Test

**Comment by tkoham** [comment]
Haha wow, this really took off! Didn't know you guys would take the suggestion to heart like this!

**Comment by RaulDJ** [comment]
@tkoham Man, thank you. Seriously, THANK YOU.

Hopefully we'll get something out of this great idea.

**Comment by tkoham** [comment]
@Nekotekina If you can secure me some footage I'll cut together a promo video for you guys, and see who I can get to pick up the story

**Comment by al0xf** [comment]
@tkoham Send a message to ssshadow or Ani on our Discord https://discord.me/RPCS3

**Comment by AniLeo** [comment]
Will be closing since we're actively in touch now, feel free to reopen if needed
