### ISSUE TITLE
Debug info from Tier 3 Dx12 card 

### ISSUE THREAD

**Issue by Gamedev1909** [RPCS3/rpcs3#2296]
https://www.sendspace.com/file/nlkc22 game used was eternal Sonata 
API used was DX12 
tool used was https://blogs.msdn.microsoft.com/pix/download/ 

note i saw in the debug into DX12 is running as Dx11 it shows in the Driver over head as not all cpu cores are being used i hope the info helps

**Comment by kd-11** [comment]
This is expected. Most DX12 implementations in games will actually use feature level 11 (DX11 features) since the DX12-only features are not important for most scenarios and some DX12 GPUs do not support some of the features (see https://en.wikipedia.org/wiki/Feature_levels_in_Direct3D). The most impactful would be resource binding, but we aren't hitting the FL_11 limit. The architecture of the emulator makes it difficult at the moment to really utilize all cores since the ps3 game handles all the game-level multithreading (e.g data streaming, etc) and we have to guarantee draw order.
