### ISSUE TITLE
Libretro core

### ISSUE THREAD

**Issue by CoalaJoe** [RPCS3/rpcs3#2304]
Are there any plans on making this emulator retroarch-compatible?

**Comment by Q3CPMA** [comment]
Also interested by this. Even if this is obviously a last order priority, this would be good to know.

**Comment by arabek** [comment]
👍 +1 on that and since retroarch comes with basically an xmb like interface (it even has ribbons) it'd be a great fit ;)

**Comment by FinixFighter** [comment]
I'm also very interested! :D

**Comment by gouchi** [comment]
Are there any plans to officially integrate with libretro?

hcorion
RPCS3 - Developer (Linux/CI) Arch Linux, GTX 1070, i7 4770

> There's an open issue regarding that on GitHub here: https://github.com/RPCS3/rpcs3/issues/2304
> Unfortunately nobody has mentioned any interest, and there is some refactoring work to make it so that RPCS3 has the flexibility to run two supported UI backends. If we ever do get developer interest, I would love it if the support was kept upstream on our repo, rather than having an outdated fork like I've seen with some libretro ports.

AnnieLeo
RPCS3 - Web Developer, Community Manager

> No plans, specially with endless high priority stuff that needs to be done, but if someone wants to work on it they can open a discussion issue on the repository. I assume if it's not intrusive on the current codebase and people are willing to maintain it, it won't be a problem, but again, whoever is interested on working on it should open a discussion thread.

[Source](https://www.reddit.com/r/pcgaming/comments/cxx5h3/we_are_team_rpcs3_the_playstation_3_emulator_we/eyofwi3/)

**Comment by FinixFighter** [comment]
@CoalaJoe I think you should not ask if there are any plans for a libretro rpcs3 core, I think you should write something like "Create a rpcs3 libretro core" and similar things... Also try to give as many details as possibile, so that the bounty is more tempting both for new backers and for potential developers.

**Comment by IngwiePhoenix** [comment]
So I have been fooling around with RetroArch for a while and am rather impressed by it. Sure, the PPSSPP core crashed while it was doing literally nothing as I was having a cig break, but... I tried to look into libretro's headers to see what it essentially takes to allow a core to be made available to it.

From what I gathered, all it does is provide basic abstractions and ways to retrive native handles and scopes to platform specific functions and features. For instance, it appears that it is possible to draw directly on a native GL surface, or to push frames to libretro, to then have them rendered. Both is possible, but with the latter preffered in order to support more platforms and renderers.

Now, looking at the PS3 itself, I seem to remember that it had a dedicated GPU and one hell of a complicated CPU. Assuming that libretro does indeed allow drawing on a native surface, my initial thought would be to stub a few of the basic drawing functions to the point where the GL context is retrived through libretro, and then used to draw upon. The CPU can be processed all in the core - as far as I am aware, this is very much core internal for essentially all cores. As for inputs... I am not sure how they work, so I couldnt put out an estimate there.

To round it up a little: In order to make a libretro core out of RPCS3, one would have to sit down and start replacing and partially refactoring functions - maybe even whole files. The most two obvious ones - to me at least from my initial thought - would be input and graphics. I don't think sound is that hard since the PS3 itself used actual mainstream things like OGG and even MP3 in some places. But yes, this too would have to be factored in. Depending on how the project is structured, this might be more or less of an issue - and then, there is also the question of `#ifdef`ing the code. This would probably end up in the actual emulating component of RPCS3 to be split from the frontend that has already been worked on, which would create more hassle.

I think, that while I would absolutely love to see a RPCS3 core for RetroArch, that it will take a lot of work to achieve this. And as the demand does not seem to be so high, as stated by @gouchi's quotes, I unfortunately doubt this would happen any time soon. It would be great, but the work that would go into this would also have to be done by someone, y'know ;)

**Comment by SaVavZ** [comment]
I'm also interested! :3

**Comment by NeoNight1986** [comment]
Im interested! I would love to keep everything in one place.

**Comment by AlanRibas** [comment]
> Im interested! I would love to keep everything in one place.

I dream with this day.... :-)

**Comment by NeoNight1986** [comment]
Between PS2 and now PS3 cores... which i imagine will be insane to eventually put in, but if all the groups could work together... one program to rule them all.

**Comment by AniLeo** [comment]
No need to keep bumping unless adding new information

As previously mentioned, we obviously won't work on this ourselves but whoever wants to work on it can suggest / submit changes, perhaps starting by providing a list of blockers and discussing with the respective developers for those parts of the code how to solve them in upstream

**Comment by JustinSUF** [comment]
we. need. a. core.

**Comment by AniLeo** [comment]
Then you can start working towards one, as it has been said several times

**Comment by FinixFighter** [comment]
> we. need. a. core.

You can also support whoever is going to work on this: https://www.bountysource.com/issues/80019144-bounty-5-create-a-ps4-port-of-retroarch :)

**Comment by IllMethods** [comment]
This would be awesome, especially now with the series x. New Xbox, backwards compatible with Original Xbox, Xbox 360, Xbox One, Playstation, Playstation 2, PSP, Playstation 3. Compatibility list has now become quite high.

**Comment by AniLeo** [comment]
libretro implementation wouldn't matter in the slightest for Xbox Series X unless Microsoft magically starts allowing Vulkan to be used through UWP on Xbox Series X. No one is going to waste a bunch of time writing an entire Direct3D render just for that.

**Comment by Passingby1** [comment]
You might as well close this now. Later on you'd start getting complaints because RPCS3 does not run RDR too well on 300usd consoles or smartphones.

**Comment by PrismFlux** [comment]
+1 for the suggestion

**Comment by AniLeo** [comment]
> No need to keep bumping unless adding new information

Specially since you have a +1 reaction button on GitHub for this same reason, so you don't have to waste people's time with an empty ping

**Comment by RainbowCookie32** [comment]
Gonna re-iterate Ani's previous message here. 

Unless you want to *actually code something* for the core, _please_ stop bumping and +1'ing the issue. It's pointless, and just annoys everyone still subscribed to the issue with a pointless notification, and also sends a (also poinless) notification on our github channel on Discord.

If you want to show your support for this idea, just add a +1 to the issue with the emojis on the main comment. With the pointless bumping you'll just end up getting the issue locked.

**Comment by StoppingBuck** [comment]
Now that somebody has already bumped this pointlessly, let me take the opportunity to remind people that there's an open bounty for this issue on Bountysource: https://www.bountysource.com/issues/41443894-libretro-core 

Instead of your thumbs up or '+1' comments on this issue, you can use the above link and put your money where your mouth is. An issue with a high bounty attached to it is much more likely to attract attention.

**Comment by nitroos-ai** [comment]
Why not just install RetroArch for PS3?
https://store.brewology.com/ahomebrew.php?brewid=152

**Comment by Darkhost1999** [comment]
> Why not just install RetroArch for PS3?
> https://store.brewology.com/ahomebrew.php?brewid=152

1: Retroarch on PS3 is not maintained by Retroarch atm.
2: The request is RPCS3 on Retroarch not Retroarch on RPCS3.

**Comment by FinixFighter** [comment]
@kd-11 why has this been closed?

**Comment by MSuih** [comment]
The current active developement team is not interested in adding retroarch compatibility. If someone wants to implement a core then it can be included in the emulator but since we're not going to do one ourselves we also don't need an issue to remind us about it.

**Comment by awz** [comment]
"let me take the opportunity to remind people that there's an open bounty for this issue on Bountysource: https://www.bountysource.com/issues/41443894-libretro-core"

Since the issue is closed the bounty appears closed as well?  The $80 people have committed seems unlikely to move the needle. 

Has anyone been willing to look into the engineering hours required to make a RetroArch core?  Is it really pointless for the teams to collaborate?

I assume a bounty would be $10K+ or is this more of multiple person year effort project and a maintenance nightmare for both teams on top of that?

**Comment by StoppingBuck** [comment]
> or is this more of multiple person year effort project and a maintenance nightmare for both teams on top of that?

The latter. AFAIK, the only way to port RPCS3 to Libretro would essentially be a hard fork (like [LRPS2](https://github.com/libretro/LRPS2) is for PCSX2) as you'd probably have to strip a gazillion things in order to only target Libretro APIs, etc. 

Such a hard fork could be done with LRPS2, as PCSX2 it was already at such a mature level where [99.15% of all PS2 games are playable](https://pcsx2.net/compat/). However, doing the same for RPCS3 when "only" [67.51% of all PS3 games are playable](https://rpcs3.net/compatibility) would be pretty dumb, as you'd essentially have to shoulder the burden of further development of the core emulator on your own, without help from the RPCS3 team.

So I guess the answer is a) Yes, it'd be a hard fork and b) Let's talk about it once RPCS3 reaches the maintenance phase

**Comment by paulo101977** [comment]
For me it would be interesting, since I could run PS3 games in the environment I'm developing, based on stable-retro and retroarch for AI training using Reinforcement Learning: 
https://github.com/paulo101977/sdlarch-rl
