### ISSUE TITLE
RSX: Unknown cull face 0x0

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#2444]
I saw that in hack/versus too
[VIDEO](https://www.youtube.com/watch?v=2hOjqmS4vVc)

```
F {rsx::thread} class std::runtime_error thrown: Unknown cull face 0x0
(in file Emu\RSX\gcm_enums.cpp:861)
```

[LOG](https://mega.nz/#!HEc2EbYa!HfmcLZ6B5IUKzOqd92l2-tytEB7-okgUF7PruLcBYk4)

**Comment by raven02** [comment]
I can see it ran using GL backend .How about DX12 and Vulkan ? has same cull face error .

**Comment by JohnGodgames** [comment]
All backends have the same issue.

**Comment by raven02** [comment]
I see. Thanks @JohnGodgames

**Comment by standsup** [comment]
So apparently there are select versions of RPCS3, where this issue does not appear,at least with Soulcalibur 4. Might be worth trying those out:
http://www.emunewz.net/forum/showthread.php?tid=179000

**Comment by ikki84** [comment]
The same error happens in Naruto Shippuden: Ultimate Ninja Storm 3 [BLES01764] when you use the Shikamaru´s Ultimate Jutsu.

"F {rsx::thread} class std::runtime_error thrown: Unknown cull face 0x0"
"(in file C:\rpcs3\rpcs3\Emu\RSX\gcm_enums.cpp:838)"

The game is sending a null value to the switch case.
Setting a default case, "default: " to the switch prevent it to trigger and appearently doesn´t affect the game negatively.

![image](https://user-images.githubusercontent.com/16824659/27990406-85fda076-642c-11e7-98e5-3a659460f95d.png)

**Comment by derrysan7** [comment]
This problem still exist in Hack Versus with the latest master build version as of 6 august 2017... its happens constantly when sora did the r1 r2 attack

**Comment by elad335** [comment]
From hardware testing, when an invalid value targets these registers it gets discarded and replaced by previous value. tested with NV4097_SET_CULL_FACE and NV4097_SET_CULL_FACE_ENABLE
this is unfixable at the current code state without a rewrite, as register writes always modify previous value.
an optional solution is to save the previous value of the register before writing a new one, and then checking the validality of the value later in a method call.

[Testcase](https://github.com/elad335/myps3tests/tree/master/rsx_tests/unknown%20cull%20face), the testcase is using an intentional crash dump to get the current state of these registers.

Adding a default case and returning rsx::cull_face::back in rsx::to_cull_face gets [Monster Jam: Path of Destruction](https://forums.rpcs3.net/thread-188969.html) from loadable into ingame.

![image](https://user-images.githubusercontent.com/18193363/43939179-e69a8b7e-9c70-11e8-9380-f156ff650313.png)

**Comment by kd-11** [comment]
Its also tricky since I know that writing invalid values to some registers will kill hardware with a method error exception. We'll need to identify those that can survive bad writes from those that can't.
