### ISSUE TITLE
Vulkan : 1942 Joint Strike - title screen polygon flickering 

### ISSUE THREAD

**Issue by raven02** [RPCS3/rpcs3#2450]
Probably it is NV specific . GL and DX12 works fine and no flickering .

**Snapshot**
![untitled](https://cloud.githubusercontent.com/assets/3000282/23498539/1a4bae3c-ff63-11e6-8a4a-f4a06366d6b9.jpg)

**Video** 
https://www.youtube.com/watch?v=xIiGX33FU4I&feature=youtu.be

**Comment by kd-11** [comment]
Anything unexpected in the debug output?

**Comment by raven02** [comment]
From the debug output , i cannot see anything abnormal .

**Comment by kd-11** [comment]
I've recently made changes to vertex processing code, hopefully fixes this one for nvidia users. Has the situation changed?

**Comment by raven02** [comment]
No, still same vertex corruption

**Comment by kd-11** [comment]
I have encountered this in the past with partial clip space declaration which is why on opengl the declaration is mandated when any of any group of 3 planes are defined. Its difficult to know why without access to actual hw, but I suspect its a corner case the nvidia driver doesnt like. Its also odd that this is the only game affected; more data from more games would actually be better.

**Comment by raven02** [comment]
i remember when first vulkan implementation , it is okay and no corruption . it got broken in later time when doing optimisation

**Comment by AniLeo** [comment]
Version: rpcs3-v0.0.3-2017-10-04-33182650_win64
Driver: 385.41
VulkanSDK: 1.0.61.1

![image](https://user-images.githubusercontent.com/10283761/31226205-302aa388-a9cd-11e7-8dc4-b9972100361b.png)

Still an issue, debug output is completely silent.

**Comment by AniLeo** [comment]
Still an issue

**Comment by raven02** [comment]
This also affect P5 and SRW Dark Prison .
