### ISSUE TITLE
GL: Bayonetta graphics issue

### ISSUE THREAD

**Issue by RainKikyou** [RPCS3/rpcs3#2481]
In the official version of the character map is not normal, demo version is normal, of course, there are other graphics problems
official version
![qq 20170307141154](https://cloud.githubusercontent.com/assets/20301499/23647210/9390e3da-034f-11e7-82fd-b3bfb4870095.jpg)
rdc
https://drive.google.com/open?id=0Bx8uo9n4xIWccnBXMkRKbGRNU3c
demo version
![qq 20170307141658](https://cloud.githubusercontent.com/assets/20301499/23647222/a3ceb1a0-034f-11e7-95b0-a3018e1917f8.jpg)
rdc
https://drive.google.com/open?id=0Bx8uo9n4xIWcZFpvVVprYjhaZjQ

**Comment by raven02** [comment]
@RainKikyou , do you mind helping checking this game on DX12? if it is okay , probably we can close https://github.com/RPCS3/rpcs3/issues/2046

**Comment by RainKikyou** [comment]
This game is currently only checked write color buffers to get output.
DX12 still and
`{rsx::thread} class std::range_error thrown: bad conversion`
I can only use Baidu network disk at present, as I said above
demo version rdc
http://pan.baidu.com/s/1c27VtOc
office version rdc 
http://pan.baidu.com/s/1qYnUfUG

**Comment by raven02** [comment]
I see. Thanks for testing it.

**Comment by kd-11** [comment]
Still an issue?

**Comment by Asinin3** [comment]
@kd-11 OpenGL doesn't need WCB anymore, however vulkan does or it will display like this:
 ![rpcs3_2017-09-01_00-05-34](https://user-images.githubusercontent.com/15137035/30137768-168efd32-93a4-11e7-8d5a-deec4b4cbcfd.png)
All the characters on screen are completely black at all times:
![rpcs3_2017-09-01_00-08-20](https://user-images.githubusercontent.com/15137035/30137872-90477014-93a4-11e7-99a9-b440115d4b10.png)

**Comment by Asinin3** [comment]
Vulkan no longer needs WCB and the black character models has been fixed in master, Strangely enough I tested it 4 days ago and the issue was there, but now when I go back through builds even a month old It's still working with the same settings and clearing cache. Maybe I had an old cache that caused it to persist or something 😕
![image](https://user-images.githubusercontent.com/15137035/32412506-9d901310-c249-11e7-8d9c-9e4feb197ca8.png)

Anyway should be safe to close this.

**Comment by AniLeo** [comment]
@Asinin3 is this still an issue

**Comment by Asinin3** [comment]
Played for an hour and didn't notice the black character issue although not 100% if it can still happen since it was rather random.

I do however get this bug with a lot of in-game models not limited to characters.
![2018-01-06_14-35-22](https://user-images.githubusercontent.com/15137035/34636407-7871eb80-f2f0-11e7-8a74-0721a14268cc.gif)

**Comment by woj1993** [comment]
@Asinin3 It is SPU Loop detection hack issue if you turn it off for this game clothes should work normally (tested only on demo). I you can test in on full version.

**Comment by Asinin3** [comment]
Clothes still flicker with it off.
![2018-01-07_13-41-25](https://user-images.githubusercontent.com/15137035/34646148-929dfd62-f3b0-11e7-8452-38be871026c6.gif)

**Comment by kd-11** [comment]
The physics issue should be tracked separately imo. The original report about graphical glitches was resolved long ago.
