### ISSUE TITLE
GL/Vulkan: One Piece Unlimited World Red graphical issues

### ISSUE THREAD

**Issue by MarioSonic2987** [RPCS3/rpcs3#2568]
This game has problems with shadows and depth. Tested in https://github.com/RPCS3/rpcs3/commit/c729d6d65a8952c4195b2beaaf83204a873cf2a2.

![](http://i.imgur.com/abrRRyb.jpg)
![](http://i.imgur.com/8MgGEDU.jpg)
[Shaderlog GL](https://drive.google.com/open?id=0B9LymxJkpT48bzhxWER3WEQ0WG8)
[Log GL](https://drive.google.com/open?id=0B9LymxJkpT48WHh3MW5GcFlxYzA)

**Comment by MarioSonic2987** [comment]
[Video](https://youtu.be/G05slQP2fdU)

**Comment by SakataGintokiYT** [comment]
@kd-11 
Do you know how to fix depth issue in this game.

**Comment by kd-11** [comment]
Haven't checked this one yet.

**Comment by MarioSonic2987** [comment]
Tested with https://github.com/RPCS3/rpcs3/commit/334327df67acec9f7e53313b1719479d913ebb6e:
![image](https://user-images.githubusercontent.com/20027681/29397869-66002460-8321-11e7-811e-2ea8e0686ebb.png)

**Comment by scribam** [comment]
@MarioSonic2987 Can you test again with the latest build?

**Comment by MarioSonic2987** [comment]
With https://github.com/RPCS3/rpcs3/commit/db9a6113d7155eb14cb2770bbd6af46b26797fd9, Vulkan has the same depth issue as in old OpenGL, but now is worse with OpenGL. Luffy isn't visible.
![](https://cdn.discordapp.com/attachments/361063300487970818/455351159977410561/unknown.png)
![](https://cdn.discordapp.com/attachments/361063300487970818/455351474965184533/unknown.png)

[RSX Capture OpenGL](https://github.com/RPCS3/rpcs3/files/2087877/CaptureRSX.OPUWR.10-6-18.GL.zip)

**Comment by MarioSonic2987** [comment]
With #4866, OpenGL looks the same as Vulkan.

![image](https://user-images.githubusercontent.com/20027681/42447304-acef42c6-8379-11e8-8e99-5a4475f60373.png)
![image](https://user-images.githubusercontent.com/20027681/42447346-d612bf2a-8379-11e8-963e-de47aa8dbb75.png)

**Comment by uaqlover** [comment]
ONE PIECE Unlimited World Red [BLES02020]

have graphical issues again why i don't know 

![fps_ 38 39 _ opengl _ 0 0 5-7621 _ one piece unlimited world red bles02020 12_26_2018 5_34_34 pm](https://user-images.githubusercontent.com/45731484/50447554-5a098200-0935-11e9-95f1-d904b3844f35.png)

it was fixed in build rpcs3-v0.0.0.6-7598-6762e242_win64

https://github.com/RPCS3/rpcs3/pull/5436

**Comment by kd-11** [comment]
Retest

**Comment by MarioSonic2987** [comment]
Needs SRM to fix broken depth and some blur effects in some cutscenes.

<details>
<summary>OGL with SRM</summary>

![image](https://user-images.githubusercontent.com/20027681/54647320-4c7e1700-4aa2-11e9-84fb-91feed370f85.png)
</details>
<details>
<summary>Vulkan with SRM</summary>

![image](https://user-images.githubusercontent.com/20027681/54647352-6c153f80-4aa2-11e9-8e27-5ac89af8dd0a.png)
</details>

[RSX Capture (GL SRM)](https://github.com/RPCS3/rpcs3/files/2985837/OPUWR.GL.SRM.zip)
[RSX Capture (VK SRM)](https://github.com/RPCS3/rpcs3/files/2985838/OPUWR.VK.SRM.zip)

**Comment by Emulator-Team-2** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/6213.
[Vulkan]
![1](https://user-images.githubusercontent.com/38318848/61252184-fcb41180-a75c-11e9-94f8-0c8d61b979c2.png)
![2](https://user-images.githubusercontent.com/38318848/61252206-135a6880-a75d-11e9-90c9-a9d4579ea578.png)

-----------------------------------------------------------------------------------------------------------
[OpenGL]
![3](https://user-images.githubusercontent.com/38318848/61252257-3f75e980-a75d-11e9-9afc-2ec78782201b.png)
![4](https://user-images.githubusercontent.com/38318848/61252283-4ef53280-a75d-11e9-81ca-53b6078b073c.png)

**Comment by kd-11** [comment]
Closing as fixed via https://github.com/RPCS3/rpcs3/pull/6213
