### ISSUE TITLE
Project Diva F [BLJM60527] Black screen

### ISSUE THREAD

**Issue by AkagiShiroe** [RPCS3/rpcs3#2622]
am i doing something wrong? nothing show just black screen with Audio being perfectly rendered. i use OpenGL with required libraries. heres some log :
[RPCS3.txt](https://github.com/RPCS3/rpcs3/files/887899/RPCS3.txt)

**Comment by AniLeo** [comment]
Adapter: NVIDIA GeForce 9600 GT
Unsupported GPU. Please check our website for requirements.

**Comment by AkagiShiroe** [comment]
sorry im just asking since Minecraft are bootable and showing loading screen + menu instead of black screen without anything, that's just making it nonsese

**Comment by AniLeo** [comment]
9600 GT only has OpenGL 3.3 support. RPCS3 uses calls from OpenGL 4. Minecraft may work out of luck, but most games won't, and they only do because there's no exception being thrown when the GPU doesn't support the required OpenGL API level currently needed.

Try running the cube sample, for example, and you'll see it's deformed, if it even works. I remember trying that on an unsupported GPU a while back.

**Comment by AkagiShiroe** [comment]
^lol i remember that deformed phase when RPCS3 aren't even able to emulate any commercial, glad to follow this project for 3 years.. probably i have to work with source code to 3.3 or just bought a newer PC but i have no budget yet...

**Comment by AniLeo** [comment]
You can just replace the GPU. You can get cheaper new (~100$) or used GPUs for less that have OpenGL 4.3+ support, and even Vulkan/DX12.
