### ISSUE TITLE
Questions: about using rpcs3 for as a start point for a PS4 emulator..

### ISSUE THREAD

**Issue by oscarbg** [RPCS3/rpcs3#2750]
Hi,
I know I know we are just starting to get some serious Ps3 games running well on rpcs3 and I'm starting dreaming about a potential future PS4 emulator..
Some questions to say:

1) rpcs3 can be a solid base as a start for a ps4 emulator? or much has changed that is better to start from scratch.. (I assume pkg and pup file format to be similar for example also some system libraries APIs)..

2) it's required a leaked PS4 SDK to have required headers/documentation of new libs like new graphics libGNM API to start considering coding a PS4 emulator or not?
i.e. RPCS3 uses knowledge learned through "leaked official PS3 SDKs" or not? I asume yes..

3) how hard a ps4 emulator seems to be (obviating performance considerations) compared to PS3 emulator.. I say because PS3 has CELL chip PowerPC arch and SPUs but PS4 uses "standard" x86 and AMD GCN architecture and with new Vulkan API seems seems exposes as much as needed for emulating new PS4 libGNM API?
PD: sorry if it's not right place to ask rpcs3 devs about this questions..

**Comment by kirbyfan64** [comment]
IIRC the PS4 uses a totally different CPU from the PS3 (4 is x86-based, with changes (?), 3 is Cell).

Then again, maybe some of the graphics-related stuff would be kinda similar?

**Comment by hcorion** [comment]
*Disclaimer: I am not a RPCS3 developer, and my emulator developer knowledge is not very high.*

No.
RPCS3 is not a very good jumping off point for PS4 emulation. 
The PS3's processor had a very odd architecture, the Cell, which had a bunch of weird things like PPEs, SPEs, the PS4 is just running simple x86_64.

A PS4 emulator could benefit from the research done by RPCS3, but not much else.

I'm also pretty sure using leaked PS4 SDKs (or PS3 for that matter) are a big no-no, because that's illegal, and nobody wants their emulator shut down.

Emulating the PS4 would require a much different approach than RPCS3, it would probably be best to go the route xqemu is trying to do with original Xbox emulation.

You are right that libGNM is closer to Vulkan/DX12 but the difference that makes for emulation is negligible.

AFAIK there are no homebrew games for the PS4 yet either, which pretty much a requirement before emulation. Linux on the PS4 is a good step though.

-----
I've previously compared making emulators like buying a car, trying to make an exact clone of that car from scratch without the user manual, and then learning how to drive the car.

Basically the rule of thumb right now is don't expect Xbone or PS4 emulation any time soon. It might take a while and some very dedicated developers, but it will eventually happen.

**Comment by paulsapps** [comment]
If you are "seriously" asking this then you have no chance and no clue.

**Comment by AniLeo** [comment]
There are probably a few libraries that are **similar** but PS4 is a whole new console. 

I don't see why would you even want to use stuff from RPCS3 when making a new emulator for PS4, maybe  for taking notes from a few similar OS functions.

1. File system encryption is different, the way PUP and PKG works as well. Go get PS4UPDATE.PUP and try installing it on RPCS3 (spoiler: it doesn't work). You already have tools that do unpkg and pup extraction you can base yourself on anyways (like https://github.com/Keyaku/ps4tools).

2. Using official SDKs is illegal as you said, so there's no point in your question. You have open-source homebrew SDKs like PS1Light (http://www.psdevwiki.com/ps3/PSL1GHT) for PS3 and PS4-SDK (https://github.com/CTurt/PS4-SDK) for PS4.

3. It depends. Easy or hard, it varies from developer to developer and more importantly than that is if someone is willing to do it. PS3 emulation was deemed impossible by many a few years back but we have a bunch of recent console emulators nowadays (PS3, Xbox 360, 3DS, Wii U...). Even if something is easy it won't be done just sitting around and waiting for someone else to do it.

**Comment by InX-Invader** [comment]
It would be best to use open source community tools to see how the PS4 functions* as well as actually getting a console that has the ability to do the webkit exploits to see if you can do anything. One of the major problems with the PS4 in terms of development is that we don't have much on it as the homebrew scene hasn't really taken off, that and there's very little documentation on the way the system works as a whole.

**Comment by Blaypeg** [comment]
https://www.youtube.com/watch?v=-AoHGJ1g9aM

This is the best description I've seen about how a PS4 works and how that relates to a standard PC. It really has very little in common with a PS4

**Comment by InX-Invader** [comment]
@Blaypeg gave an excellent video to show just how convoluted the PS4 really is, people hear that "Oh, the PS4 uses x86, it should be easy to emulate. Right?" and they don't even realize that the entire system might be worse than the PS3 ever was...

**Comment by paulsapps** [comment]
There you have it, DIY the exploit and get hacking..

**Comment by kacek** [comment]
time to cut this offtop. @oscarbg if you have more questions like that, you can post them on our [forum](http://www.emunewz.net/forum/forumdisplay.php?fid=172). Issue tracker is only for RPCS3 development related stuff.

**Comment by oscarbg** [comment]
thanks for responses.. @kacek thanks for fórum link..

**Comment by Davidherrmann** [comment]
Hay
