### ISSUE TITLE
Thread (highCellSpursKernel)} SPU: Function call without $LR

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#2760]
When Load Most Games Show This Error in log
is this Error critical ?
need to fix ? or no important
@Nekotekina

**Comment by hcorion** [comment]
This is a known debug message and it will get fixed in it's own time, please close this bug report.

Also, please don't tag the devs needlessly like that. If an issue needs the attention of Nekotekina, he'll respond to it.

In the future you should ask questions like this on Discord https://discord.me/RPCS3 or the forums http://www.emunewz.net/forum/forumdisplay.php?fid=172
