### ISSUE TITLE
Inconsistent roadmap

### ISSUE THREAD

**Issue by C0rn3j** [RPCS3/rpcs3#2809]
https://rpcs3.net/blog/2017/05/21/lead-graphics-developer-kd-11-is-joining-nekotekinas-patreon/
Short term: – Enable Vulkan on Linux, which will bring a tremendous performance improvement for some games.

vs

https://rpcs3.net/roadmap
Medium term goals:
Enable Vulkan graphic renderer for Linux.

I haven't checked for other inconsistencies.

**Comment by AniLeo** [comment]
There has been a fork of Vulkan working on Linux since like last year, but the person never submited their changes. See #2186

kd-11 asked for those to be submitted so he would finish it but since they weren't, kd-11 will soon work on getting Vulkan working on Linux. Main roadmap should be updated though, will do now.

**Comment by AniLeo** [comment]
Roadmap updated with kd-11's goals, thanks for the reminder.
