### ISSUE TITLE
Kingdom Hearts HD 1.5 Remix - Black Screen

### ISSUE THREAD

**Issue by 4k-developer** [RPCS3/rpcs3#2877]
OS: Windows 10
CPU: AMD A10-7700K Radeon R7
GPU: AMD Radeon R7
Log File: https://pastebin.com/1g5gX74f 

Game window opens up, then the typhies are set up, then a black screen

**Comment by AniLeo** [comment]
A few things are wrong by just quickly checking the log. 
Never use D3D12 unless the game doesn't work on the other options and don't place disc games inside dev_hdd0, this is explained on the quickstart guide.
Closing this since the tracker isn't for support. 

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](http://www.emunewz.net/forum/forumdisplay.php?fid=172) for that.

The issue has been marked as **Invalid** and closed.
