### ISSUE TITLE
Flickering with Freesync

### ISSUE THREAD

**Issue by David-Martin-Pereira** [RPCS3/rpcs3#2954]
Specs:

CPU: i7 6700k, stock
GPU: AMD r9 Fury Nitro, stock
Memory: 16Gb DDR4 @2400Mhz
OS: Windows 10 Home
Monitor: Nixeus VUE-24

When Freesync is enabled you can see a constant flickering when running in fullscreen. It happens with OpenGL, D3D12 and Vulkan.

**Comment by raven02** [comment]
what is your freesync hz?

**Comment by David-Martin-Pereira** [comment]
144 Hz

**Comment by isshininu** [comment]
Please report your Nvidia driver version.
It seems that 384.* driver causes this.

**Comment by David-Martin-Pereira** [comment]
It's AMD

**Comment by kd-11** [comment]
rpcs3 does not attempt to vsync the swapchain at all currently which is why you get tearing. vsync does not mean lock to 60 or something, just that we tell the present engine to never queue anything and just throw the current swapchain image on the screen. Try using a low framerate cap like 30 and see if it helps.

**Comment by David-Martin-Pereira** [comment]
thanks, I will try :)

**Comment by scribam** [comment]
@David-Martin-Pereira Is it still an issue?

**Comment by kd-11** [comment]
Closing as issue has not been updated in over 6 months. Also, its a problem for the AMD team, not rpcs3.
