### ISSUE TITLE
Disgaea 4 Win32 error randomly

### ISSUE THREAD

**Issue by jaywong281096** [RPCS3/rpcs3#2955]
I've been getting this error along with other errors that cause the game to freeze every 30 min to an hour
Help would be appreciated.

---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC0000005.
Segfault reading location ffffffffffffffff at 0000000000480e95.
Instruction address: 0000000000480e95.
Function address: 000000000047ff50 (base+0x46ff50).
Module name: 'rpcs3.exe'.
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000.

**Comment by AniLeo** [comment]
These crashes are common in other games like Persona 5 and many will be fixed when libgcm gets LLE, which is already WIP. Please use the forums for support in the future.
For those errors, a full stacktrace is needed, otherwise the error says nothing.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](http://www.emunewz.net/forum/forumdisplay.php?fid=172) for that.

The issue has been marked as **Invalid** and closed.
