### ISSUE TITLE
Project Diva F 2nd doesn't load normal songs due to FIOS inaccuracy

### ISSUE THREAD

**Issue by Waelwindows** [RPCS3/rpcs3#2965]
The game has mentions of FIOS in tty.log when trying to load a normal song. The game is stuck in an infinite loop after

**Comment by PREPERADE** [comment]
Now i know why it don't load any game data.
because it can't install game data when it first boot. Orz.
When i boot game first time messagebox appeared and said. "The Game need to install game data."
But install process is failed and can't load any kind of game data.
I think If install process works correctly then we can play this game.

**Comment by AniLeo** [comment]
That is irrelevant to the FIOS issue that affects the game.
Game installs data properly here, it's an issue on your end.

**Comment by Sangabc** [comment]
Actually the game data is that when you boot he game for the first time, it will ask if it can install data of the game, after we accepted the progress failed leaving the rpcs3 to freeze! Still happen on the latest build! I have just tested

**Comment by AniLeo** [comment]
Closing
