### ISSUE TITLE
Odin Sphere: Stuck on 'Setting up trophy information'

### ISSUE THREAD

**Issue by ZeroSplice** [RPCS3/rpcs3#3009]
Game gets stuck occasionally on 'setting up trophy information' screen

Occasionally being the key word here. The game will load fine and on the exact same set of settings it will not load the next around. Here's the log when it gets stuck: (by the way, the FPS still indicates that the game is running even though it is stuck. The trophy bar does not load.)
```
E {PPU[0x1000005] Thread (CRI FS File Access 1) [0x00c59090]} sys_fs: sys_fs_open(“/dev_hdd0/game/BLUS31601INST/USRDIR/Odin2_OR_US.CPK”): failed to open file (flags=0, mode=0)
E {PPU[0x1000005] Thread (CRI FS File Access 1) [0x00c59090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT
S {Audio Thread} XAudio 2.9 initialized
E {PPU[0x1000015] Thread (FiberFunc) [0x00c3ac90]} cellSaveData: cellSaveDataEnableOverlay(enable=1)
E {PPU[0x1000016] Thread (FiberFunc) [0x00c3ac90]} cellSaveData: cellSaveDataEnableOverlay(enable=1)
E {PPU[0x1000017] Thread (FiberFunc) [0x00c3ca18]} sceNpTrophy: sceNpTrophyRegisterContext(context=0x1, handle=0x1, statusCb=*0xb39608, arg=*0x28b029ac, options=0x1)
E {PPU[0x1000018] Thread (FiberFunc) [0x00c3ca70]} sceNpTrophy: sceNpTrophyGetTrophyUnlockState(context=0x1, handle=0x1, flags=*0x28b029bc, count=*0x28b029cc)
E {PPU[0x1000005] Thread (CRI FS File Access 1) [0x00c59090]} sys_fs: sys_fs_open(“/dev_hdd0/game/BLUS31601INST/USRDIR/Odin2_RE_US.CPK”): failed to open file (flags=0, mode=0)
E {PPU[0x1000005] Thread (CRI FS File Access 1) [0x00c59090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT
E {PPU[0x1000005] Thread (CRI FS File Access 1) [0x00c59090]} sys_fs: sys_fs_open(“/dev_hdd0/game/BLUS31601INST/USRDIR/Odin2_RE_US.CPK”): failed to open file (flags=0, mode=0)
E {PPU[0x1000005] Thread (CRI FS File Access 1) [0x00c59090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT
```

Exact same settings.

**Comment by YaPeL** [comment]
yep, on my case, I was never able to get past that screen, I'm talking about trying 50 times.
The "error" log on sceNpTrophy may be a bit missleading, since it always log that part as an error (its not).
If I had to bet, it feels like a thread may be finishing too soon or something like that, anyway, I'm just writing to suscribe to this.

**Comment by Krusher97** [comment]
The game getting stuck on the trophy screen seems permanent. Didn't manage to get past it even after 20 tries.

**Comment by MarcoEstevez** [comment]
I managed only pass this stage once on an older build

**Comment by Caudecius** [comment]
I'm also stuck in the trophy sceen. ssshadow said in the RPCS3 forum that the problems is actually in the game, as the emulator is too fast, which causes problems with synchronization, quoting:

__________
"This is a definite game bug. Basically RPCS3 is too fast which causes some broken synchronization code in the game itself to fail. This can be fixed by making the game frame rate much lower as it starts up. See in the screenshot here how I slowed down the game to ~6 fps which seems to certainly get past the bug. 

Actually, we speed up the game and therefore lower frame rate if you get what I mean. Anyway, just download cheat engine, attach to RPCS3, and use the speed hack at a factor 10 or more (just try 100). Then start the game. When you are past the trophy screen you can turn speed hack off and play as usual. I tested several times and it seems to only work with interpreter. LLVM fails every time, even slowed down to 0.1 fps. 

**Edit: Of course be careful with this tool. Download it here: https://github.com/cheat-engine/cheat-engine
Make damn sure not a remnant of this tool is in memory if you are going to play online games. Restart you computer after using it, because it will lead to VAC ban for example**." 
_______________

I'm not willing to try that fix since it can lead to a VAC ban, so we have to beg for a patch fix like the one made for Dragon's Crown.

________________________
i7-7700, Radeon R9-270x 2gb, HyperX 8GB ram 2666MHz.
[Log.txt](https://github.com/RPCS3/rpcs3/files/1211929/Log.txt)

**Comment by Caudecius** [comment]
Maybe the solution is the same as this: https://github.com/RPCS3/rpcs3/issues/3013

**Comment by RipleyTom** [comment]
```
PPU-c8537ec20b4560fb14d51ce02b2bb21f65ea64ae: #OS BLES02241 Sync Issue Hack
  - [be32, 0x721024, 0x39000001]
```

Note that unlike Dragon's Crown I'm not sure it's the game's fault and the fix is rather dirty(whereas in dragon's crown it's essentially a bugfix).

**Comment by JacobAL** [comment]
Same problem here. @RipleyTom, is that a patch? If so, how do I get it to work. I tried patch.yml with that text in both the main directory and the game config directory.

Interestingly, the game launched fine the first time after recompiling.

**Comment by shome4568** [comment]
RipleyTom Can you make patch for BLIM61239 ?
Please help me :)

**Comment by inoueyuichi** [comment]
@amakuramio How to pause?

**Comment by ajtpak** [comment]
hoping for a fix

**Comment by mralmostperfect** [comment]
> hoping for a solution, game's still bugged sadly.

hey, good news! the patch doesn't work in the 7299 build, but it does work in the newer 7497 build, I just tested it

**Comment by Megamouse** [comment]
please retest

**Comment by Megamouse** [comment]
should be fixed

**Comment by tesla2105** [comment]
This game worked flawlessly for the last couple of months, then today after I updated rpcs3 to the build 0.0.7-9186, this bug started happening again (I haven't updated rpcs3 for at least two weeks)
