### ISSUE TITLE
PARAM.SFO not found when booting from a disc with several games

### ISSUE THREAD

**Issue by aakh1361** [RPCS3/rpcs3#3062]
> E {PPU[0x1000000] Thread (main_thread) [0x01421090]} sys_fs: sys_fs_open(“/dev_bdvd/PS3_GAME/USRDIR/TR8/USRDIR/BIGFILE.000”) failed: device not mounted
E {PPU[0x1000000] Thread (main_thread) [0x01421090]} 'sys_fs_open' failed with 0x8001003a : CELL_ENOTMOUNTED

![0](https://user-images.githubusercontent.com/25039098/28490678-3c0e1882-6ef5-11e7-883b-2850efed7dba.jpg)

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1167316/RPCS3.zip)

**Comment by AniLeo** [comment]
Did you delete PS3_DISC.sfb?

**Comment by aakh1361** [comment]
No
This File Is Exist

**Comment by rhythmthief** [comment]
Same issue with The Darkness (2007)

![sadasdsda](https://user-images.githubusercontent.com/20905355/28501620-02ef8182-6f9d-11e7-971f-4ac03fab7f05.PNG)

**Comment by Zangetsu38** [comment]
yes, issue for the darkness and for Wipeout HD last update already signaled at devloppert

**Comment by Xcedf** [comment]
BTW, replacing with CELL_OK makes Darkness go to menu

**Comment by Zangetsu38** [comment]
hah funny that lol

**Comment by Zangetsu38** [comment]
little same think in motorstorm rc with update 1.03 and in motorstorm 1 show this for rc
>sys_fs_open(“/dev_hdd0/game/NPEA00333/USRDIR/liveryeditor/patch_1.rpk”): failed to open file (flags=0, mode=0)
E {PPU[0x1000000] Thread (main_thread) [0x00f3f090]} 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT
F {PPU[0x1000000] Thread (main_thread) [0x0030ce28]} MEM: Access violation reading location 0x68

but this file not exist, so it is normal, but game stopped directly

**Comment by Zangetsu38** [comment]
no close this issue, all game have this issue no changed

**Comment by MarioSonic2987** [comment]
Is this still an issue?

**Comment by aakh1361** [comment]
yes
but now show 

> E {PPU[0x1000000] Thread (main_thread) [0x01430090]} 'sys_fs_open' failed with 0x8001003a : CELL_ENOTMOUNTED, “/dev_bdvd/PS3_GAME/USRDIR/TR8/USRDIR/BIGFILE.000” [1]

**Comment by nevuk** [comment]
Same issue exists with Cross Edge.  
Try to boot Cross Edge (BLUS30348 ) with LLVM PPU compiler and it will throw an error window and hard crash RPCS3 (won't even compress the log that is generated, had to do it manually).  (None of the other settings matter, does it with any SPU decoder and any renderer). 

I think the relevant part of the log is this, but not totally sure. Log provided. 
'sys_fs_open' failed with 0x8001003a : CELL_ENOTMOUNTED, “/SEC/SEC00_HAMADA.sec” [1]

May be a fairly low priority issue as I'm not sure it affects any other games, and the game will run with the other compilers. 

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/2372867/RPCS3.zip)
Screenshot (since I'm unsure if all data is in log) 
<img width="661" alt="llvm" src="https://user-images.githubusercontent.com/6707114/45390115-06746200-b5ec-11e8-9c16-7befe08d000f.png">

Computer Information : 
RPCS3 Version: 
0.0.5-7330 
Ryzen 1600x, 16 GB RAM, Nvidia GTX 1060

**Comment by AniLeo** [comment]
@nevuk If it works with Interpreters then it has nothing to do with fs returning CELL_ENOTMOUNTED
@aakh1361 Seems like lack of game collection support, your log clearly shows the emulator is not picking up the PARAM.SFO properly

**Comment by digitaldude555** [comment]
Not an issue anymore.

**Comment by AniLeo** [comment]
Closing as implemented / fixed
