### ISSUE TITLE
CurrentSettings.ini not located with other configuration files

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#3063]
Archlinux here.
After compiling rpcs3, when I launch it, the folder GuiConfigs is created in the current directory.
And the file CurrentSettings.ini contains some data (ex: to not display the welcome screen).
It should be located with the other config files (/home/user/.config/rpcs3), because if I create a package and install it, the rpcs3 binary is in the /usr/bin folder and it can't create (luckily) the GuiConfigs folder.
So it always displays the same welcome screen.

**Comment by hcorion** [comment]
Yes, the problem is [line 23 in rpcs3/rpcs3qt/gui_settings.cpp](https://github.com/RPCS3/rpcs3/blob/821a8c6e65d0af5f20838acee88528d35672b204/rpcs3/rpcs3qt/gui_settings.cpp#L23)
Which just gets the executable directory, which works fine on Windows, but not on Linux.

I don't have time to fix this right now, but the proper solution would just be to `#ifdef` for linux and use `fs::get_config_dir()`

If someone else could implement that it would be awesome.
