### ISSUE TITLE
Add RPCS3 version/build to the game window title.

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#3152]
This is minor but it would help with debugging, I see people report issues with screenshots all the time but forget to mention their build of RPCS3.

**Comment by isshininu** [comment]
Users screenshots are useless without logs, i guess.

**Comment by Oceangraves** [comment]
I still think it would still be helpful, also need a message in some of the error dialogs for the generic errors. If it said something like "This is a generic error, please post the log if you want to report this."

Just small things that would help the devs not have to wait hours/days for a response so they can debug an error.

**Comment by hcorion** [comment]
This is really a non-issue IMO. We don't need to clutter up the game window window title, and in 90% of the cases, the log provides more help than the build number.

**Comment by Oceangraves** [comment]
Okay, I just thought it would be helpful.

**Comment by legend800** [comment]
While this won't help the debugging use case much, I do believe having the branch name would bring a lot of value when sharing screens and videos in the threads, discord, YT, etc. 

There's a lot of spam (in Discord especially) because people want to know two things "What build is that?" and "Where can I get that build?". The second question is beyond the scope of this ticket (I vote a #Builds channel), but the first question COULD be answered by this simple implementation. 

Let's be honest, there are a lot of build branches out there, that won't stop (nor should it). We could avoid a lot of back and forth and confusion if we can set aside a few chars at the end of the title bar for text to be entered the states the branch.

**Comment by AniLeo** [comment]
Solved by #3186
