### ISSUE TITLE
RSX: Texture resides in render target memory, but requested type is not 2D - Resident Evil Code Veronica

### ISSUE THREAD

**Issue by luisloco** [RPCS3/rpcs3#3257]
The game loads without problem using save file, the problem is when you are in the inventory and the inventory is left black screen but the game is heard when you walk.

![resident evil codigo veronica 2](https://user-images.githubusercontent.com/5092869/29431745-aade2838-835e-11e7-96d1-1fe74d2d1279.png)
![resident evil codigo veronica 3](https://user-images.githubusercontent.com/5092869/29431771-c561b918-835e-11e7-8b78-6602fe833b61.png)
![resident evil codigo veronica 6](https://user-images.githubusercontent.com/5092869/29431787-d05bf356-835e-11e7-86ab-73bbcbb85b8a.png)

**BlackScreen**
![resident evil codigo veronica error blackscreen 6](https://user-images.githubusercontent.com/5092869/29431838-03a6e112-835f-11e7-975b-378452dd4f91.png)
**Main**
![resident evil codigo veronica error 7](https://user-images.githubusercontent.com/5092869/29431870-208d9eba-835f-11e7-9208-df03172c0938.png)
**Inventory**
![resident evil codigo veronica 6](https://user-images.githubusercontent.com/5092869/29431787-d05bf356-835e-11e7-86ab-73bbcbb85b8a.png)

**Comment by PeterMcteague** [comment]
Do you have a log file for that?

**Comment by luisloco** [comment]
[rpcs3 resident evil code veronica.zip](https://github.com/RPCS3/rpcs3/files/1234770/rpcs3.resident.evil.code.veronica.zip)

**Comment by kd-11** [comment]
@luisloco Try https://ci.appveyor.com/project/kd-11/rpcs3/build/0.0.3-903. Its an old outdated branch but I was in the process of reworking some parts of the renderer. Just update if anything is different with that build. Set GPU texture scaling to on and disable write color buffers (with that specific build). If it fails, then try with write color buffers enabled and strict mode rendering.

With all that said, you are using an intel HD graphics chip. Driver and hw bugs on intel iGPs do cause missing graphics in games.

**Comment by Vlakipn** [comment]
Tested with that specific build and settings you've provided and results were same as master. Im using GTX970 and not integrated intel and yet, same issue is present.
Problem (besides missing graphics) has something to do with light, because whole intro (movie) is alot darker as it should be. While im not OP of this issue, im very interested in this game to work and will provide help (testing ,etc). Log included.
Thanks for your good work!


[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1243248/RPCS3.zip)

**Comment by luisloco** [comment]
@kd-11 Run the tests and the problem continues another thing also with the resident evil raccoon city happens the same problem the whole menu works perfectly.

**Comment by Vlakipn** [comment]
Made video with ps2 version comparation:
https://youtu.be/G0tPuRHfbxM

**Comment by Vlakipn** [comment]
@kd-11 
Made a test with current master (0.0.3-6067) and build from your fbo-fixes branch (0.0.3-943) and it ended with these results:

Master:
Game works with same issue as before - game loads, everything works untill a scene where you equip lighter, afterwards, screen is black you can see sounds and move char (footsteps are heared) - game does not hang or freeze. With OpenGl you need to enable Write color buffers or Texture scaling - otherwise you wont get anything than black screen (from start). Same is with Vulkan (color buffers needed).

fbo-fixes 0.0.3-943 build:
With OpenGL - screen is black (only sound can be heared), even if you enable color buffers or texture scaling, it doesent show anything. With Vulkan there is everything (even WITHOUT color buffers). It acts same as on master, BUT, when you equip lighter, game freezes with this error:

> F {rsxthread} class stdruntime_error thrown Working buffer not big enough, buffer_length=67108864 allocated=64263168 requested=9008 guard=65536 largest_pool=9216
(in file crpcs3rpcs3emursxd3d12..Commonring_buffer_helper.h74)

I hope it helps.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1289141/RPCS3.log.gz)

**Comment by Vlakipn** [comment]
With latest @kd-11 commit to master 0.0.3-6272, now on that spot (when it only renders black screen and letters),
this error appears:
E {rsx::thread} RSX: Texture resides in render target memory, but requested type is not 2D (0) x1513

p.s. again must repeat - this issue is present with BOTH renderers, not just GL. Therefor this issue should be renamed.

**Comment by Vlakipn** [comment]
Goes to Ingame with @kd-11 PR  #3699 
There are still major glitches, white objects, but not black screen after intro anymore.
https://youtu.be/Od9BpbOClFw

**Comment by kd-11** [comment]
Closing since the main issue reported here is fixed
