### ISSUE TITLE
Add Mapping Controller for Xinput. DS4 and Joystick

### ISSUE THREAD

**Issue by Oky12** [RPCS3/rpcs3#3289]
I have a joystick and the mapping controller is wrong. As X turns into O. I want to set my joystick control mapping. But nothing. The mapping menu only for the keyboard

**Comment by Megamouse** [comment]
there already exists an issue for those requests #3027

**Comment by Oky12** [comment]
Ok i understand on issue #3027.
But i have question.
On current build Rpcs3 is still only played single player or now is support multiplayer?

**Comment by Asinin3** [comment]
@Oky12 RPCS3 works with local multiplayer but has no plans to work online.

**Comment by Oky12** [comment]
Ok .... rpcs3 only supports local multiplayer. But only support in what controller?

**Comment by Asinin3** [comment]
RPCS3 works with a lot of controllers, DS4 is natively supported and we have Xinput support which covers a lot of controlers such as the Xbox controllers and DS3 with SCP-Toolkit or another xinput wrapper.

There is pretty much no limit to what controller you can use because you can just map the buttons to keyboard buttons and use it like that. However that doesn't let you have full axis support for triggers, joysticks etc.

**Comment by Oky12** [comment]
Ok... Only console controller (DS4. Xbox360 Etc) is supported local multiplayer. Thanks to comment my issue. I will close this issue
