### ISSUE TITLE
Demons Souls random crashing

### ISSUE THREAD

**Issue by odaddyrizla** [RPCS3/rpcs3#3305]
demons souls works fine (albeit slow) for indiscriminate amounts of time then RPCS3 crashes and i get this puppy:

---------------------------
Fatal error
---------------------------
Unhandled Win32 exception 0xC0000005.
Segfault reading location 000000800b000010 at 00000000004c3590.
Instruction address: 00000000004c3590.
Function address: 00000000004c3410 (base+0x4b3410).
Module name: 'rpcs3.exe'.
Module base: 0000000000010000.
RPCS3 image base: 0000000000010000.

RPCS3 then stops responding and i have to ctrl+alt+del the sucka

computer specs are mac pro with bootcamp windows 7 64 (please dont hate me) w3680, 32gb ram, gtx1080fe.

EDIT: i can recreate the problem and put up my log file if needed, happens every time i play

**Comment by Asinin3** [comment]
Yeah, I think you're going to need to post a log.

**Comment by odaddyrizla** [comment]
will play until it happens and post. apologies for not doing sooner, my log was 88 meg after that particular crash, otherwise i'd have posted it.

**Comment by Asinin3** [comment]
88mb is actually quite small, once you compress it into an archive it will be well below 5mb. It's pretty common to compress a 1gb log file down do ~18mb depending on what method you use to compress it.

**Comment by odaddyrizla** [comment]
fantastic, i won't hesitate to post it next time. thank you very much for clarifying. my knowledge of coding/github etc is nil.

**Comment by christ776** [comment]
I'm also getting crashes on latest master build. Will post a log later then!

**Comment by kd-11** [comment]
Segfaults usually need backtraces, which is difficult if you don't have a development setup.

**Comment by odaddyrizla** [comment]
it happened again, this time while talking to item deposit guy in nexus. 
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1251414/RPCS3.zip)

**Comment by Dani1977** [comment]
Hi,

I've random crash . I was in Boletaria first visit .



this my event view log

[rpcs3_event_view.zip](https://github.com/RPCS3/rpcs3/files/1251867/rpcs3_event_view.zip)
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1251869/RPCS3.zip)

Thanks, regards .

**Comment by odaddyrizla** [comment]
i forgot to mention that all these crashes happened under vulkan also (thankyou for the reminder Dani1977)

**Comment by desbh** [comment]
This has been going on since many-many nvidia driver releases. If this is indeed a driver bug, as kd-11 suggests, maybe finding a workaround would be a good idea, as nvidia doesn't seem to care, or even acknowledge the problem. Other Vulkan applications (like DOOM) don't seem to have this problem.

Additional info to what has been posted so far:

The crash is always accompanied by multiple logs in the event viewer.
The TDR is logged at the same time as the crash. The crash itself is probably caused by the TDR.

Log1  (windows/application): https://pastebin.com/Tr5z2UUR
Log2  (windows/application): https://pastebin.com/JeD8n8cz
Log3  (windows/application): "Display driver nvlddmkm stopped responding and has successfully recovered."

**Comment by kd-11** [comment]
Shouldnt be a problem anymore with current master.
