### ISSUE TITLE
Intel: GLSL - ERROR: 0:222: 'r8' : syntax error syntax error

### ISSUE THREAD

**Issue by luisloco** [RPCS3/rpcs3#3313]
![error 2](https://user-images.githubusercontent.com/5092869/29714126-46889e72-8967-11e7-9767-f9973d7bfe71.png)

![error 3](https://user-images.githubusercontent.com/5092869/29714127-4baa6052-8967-11e7-9eef-0da61d66a8cf.png)

![error 4](https://user-images.githubusercontent.com/5092869/29714132-5838f266-8967-11e7-85b6-a2d955a1ce18.png)

![error 5](https://user-images.githubusercontent.com/5092869/29714148-66dd98ee-8967-11e7-9633-b4f6964b7092.png)

![error 6](https://user-images.githubusercontent.com/5092869/29714156-73667cf2-8967-11e7-8a90-253ed966480b.png)

log
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1251832/RPCS3.zip)

**Comment by AniLeo** [comment]
·W 0:00:00.350101 Experimental Build Warning! Build origin: RPCS3/rpcs3/master/=3311
I'll keep this issue only despite of this only because Pull Request #3311 doesn't touch any code per se, only changes a text string.

·E 0:00:42.078888 {rsx::thread} RSX: OpenGL: initialization of glDepthBoundsEXT failed.
·E 0:00:42.078929 {rsx::thread} RSX: OpenGL: initialization of glGetTextureImage failed.
·E 0:00:42.078937 {rsx::thread} RSX: OpenGL: initialization of glTextureBufferRange failed.
·E 0:00:42.078957 {rsx::thread} RSX: OpenGL: initialization of glTextureBarrierNV failed.
·! 0:00:42.078963 {rsx::thread} RSX: 4.3.0 - Build 20.19.15.4703
·! 0:00:42.078964 {rsx::thread} RSX: 4.30 - Build 20.19.15.4703
·! 0:00:42.078965 {rsx::thread} RSX: Intel

This is your issue. Intel's GLSL compiler is bad.

**Comment by kd-11** [comment]
The intel glsl compiler does not like the line `vec4 r8 = vec4(0., 0., 0., 0.);` despite the declaration being completely valid. This is a driver bug on their part.

**Comment by luisloco** [comment]
@kd-11 Is intel controller problem? I have the last version

**Comment by kd-11** [comment]
Intel windows drivers have many bugs. Its 'normal'. It also cannot compile some basic ternary operations for whatever reason. Its clearly not compliant. There are intel workarounds in the code already - not sure how much more we can keep making workarounds for one GPU vendor.

**Comment by luisloco** [comment]
@kd-11 The best option is to use a video card

**Comment by kd-11** [comment]
Looks like the intel compiler thinks r8 is a glsl reserved word - its not.

**Comment by AniLeo** [comment]
Closing as superseded by the Intel GPU Megathread #6199
