### ISSUE TITLE
GL/VK Venetica Rendering issues

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#3347]
Tested by https://github.com/RPCS3/rpcs3/commit/818df50bb58f87489e28803dbcfe215b2290576f

**PS3:**
![venetica real](https://user-images.githubusercontent.com/11453507/29804824-ceb83656-8c85-11e7-968c-43d7ff514916.PNG)

**RPCS3 GL:**
![venetica ogl](https://user-images.githubusercontent.com/11453507/29804785-8a805824-8c85-11e7-931e-0971da5a90cd.PNG)

**RPCS3 VK:**
![venetica vk](https://user-images.githubusercontent.com/11453507/29804788-8dd7048c-8c85-11e7-80a5-51944e65919f.PNG)

**[RenderDoc GL](https://mega.nz/#!mdsmgICC!qb9JUBPb7_X37Rec2pYmb40qilUdsYjgAoJiNpYhC7A)**
**[RenderDoc VK](https://mega.nz/#!vJtxFCIZ!ac6RGQXhtL6JDVe2OVITGnA1Il3CPFnFmyKF9nPCkJo)**

**[LOG GL](https://mega.nz/#!rJ80HQRL!x6rEzTJlk9a1co6z05RSg0jJBvebTzh7zFpnzWiCWpU)**
**[LOG VK](https://mega.nz/#!ndcAlTQL!omvRuPJc7s8cIyW1w51ycaHriUyppXmEiuvbcXRmEgI)**

**Comment by scribam** [comment]
OpenGL looks good on master (98b715d8c89f3c57b5e0e9f0a541a53d13e96617)

![screenshot from 2018-04-25 18-29-37](https://user-images.githubusercontent.com/25406440/39259611-29e76126-48b7-11e8-912a-67e4073006d8.png)

I can not test Vulkan, @JohnGodgames can you?

**Comment by JohnGodgames** [comment]
I'm closing it, because vulkan is already fixed too.

**Comment by 2x9Mon** [comment]
It's playable as of now, the main menu is bugged on Vulkan either way, It just doesn't load the texture properly. FIFO must be set to Atomic, otherwise it crashes after the first few cutscenes. There are also a few minor visual glitches at certain places of the game, other than that it's running pretty stable 
![Untitled](https://github.com/RPCS3/rpcs3/assets/38780759/9c0f5b63-5e11-4896-86c1-289e04d0ec75)
![3](https://github.com/RPCS3/rpcs3/assets/38780759/728b57c7-cf5b-44e6-b1bc-afc78c311f83)
![4](https://github.com/RPCS3/rpcs3/assets/38780759/93992373-7328-4806-a535-e65bb2957e3d)
![5](https://github.com/RPCS3/rpcs3/assets/38780759/92a2138a-db7d-420c-9b5f-7591656a07fa)

[veneticafifoLOG.zip](https://github.com/RPCS3/rpcs3/files/15456673/veneticafifoLOG.zip)
[VeneticaDefaultSettingsLOG.zip](https://github.com/RPCS3/rpcs3/files/15456672/VeneticaDefaultSettingsLOG.zip)

**Comment by AniLeo** [comment]
For the main menu bug you are seeing, you need to open a new ticket, this ticket is 6 years old, surely whatever was the root cause for the original bug back then is not the same bug anymore.
Ask on Discord first because you're potentially missing settings.
