### ISSUE TITLE
GL/VK Army of Two - Rendering issues

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#3348]
Tested by https://github.com/RPCS3/rpcs3/commit/818df50bb58f87489e28803dbcfe215b2290576f

**Real HW:**
![army real](https://user-images.githubusercontent.com/11453507/29805321-737a3eca-8c89-11e7-81c7-774b26bfade7.PNG)

**RPCS3 GL:**
![army gl](https://user-images.githubusercontent.com/11453507/29805290-3883a432-8c89-11e7-9326-c00cc4a15a49.PNG)

**[RenderDoc GL](https://mega.nz/#!7MlygSga!UCCLF2cuLninbbD7X48-bHFzNc5yYj42ExzaiKClT3A)**
**[LOG GL](https://mega.nz/#!eYkEWbIT!1tG1wKs10wdWq1w6E5fTVeErWAdIHkL6MgkO_T9-JKE)**

**Comment by Asinin3** [comment]
Still having the same issue in master, and still requires the "write color buffers" option or rendering is mostly white in-game.

![image](https://user-images.githubusercontent.com/15137035/31324117-b8f4297e-acf6-11e7-95c4-b924761ba3ea.png)
Looks the same with OGL

I'm guessing this was fixed in kd-11s fork or something due to some screenshots showing fixed rendering.

**Comment by Xcedf** [comment]
Not an issue anymore, or at least part of UE3 issue tracker

**Comment by AniLeo** [comment]
Closing as solved
