### ISSUE TITLE
GL/VK Soul Calibur V - Rendering issues

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#3355]
Tested by https://github.com/RPCS3/rpcs3/commit/64a6fbe39ff089d0155a36aeb0d3c6360d223ad9

**RPCS3 GL:**
![soul calibur v gl](https://user-images.githubusercontent.com/11453507/29827622-bc9df5e6-8cda-11e7-83a9-70927c81e6d2.PNG)

**RPCS3 VK:**
![soul calibur v vk](https://user-images.githubusercontent.com/11453507/29827609-b74bedaa-8cda-11e7-96ef-e2e7431d3593.PNG)

**[RenderDoc GL](https://mega.nz/#!bQUiQQoY!aBLPcmk6WNoZFV6ywy2LD5x4oyJOsZBRhSeD8L1kUYc)**
**[RenderDoc VK](https://mega.nz/#!eRMjiBJY!m-TRP17je_bPPLn4laDi7DgPBlwgUk534EAbs7SbGHI)**

**[LOG GL](https://mega.nz/#!bFU3VYBQ!bUPxguLbRnW7Q-OF96OA2ZFgPJWgFWNHtCzJGjoNOcQ)**
**[LOG VK](https://mega.nz/#!jBFiBKqQ!31Us1--W5x0h9j5xYc0HKBOl9qI1p8Sf73r-Zzi1HuU)**

**Comment by AniLeo** [comment]
Please retest

**Comment by raveskirza** [comment]
Better But still bright

GL
![image](https://user-images.githubusercontent.com/28158623/35372366-82e6828a-0167-11e8-8e70-dac6c7c7adc6.png)


VK
![image](https://user-images.githubusercontent.com/28158623/35372232-c4cd1476-0166-11e8-939f-31c216c59bef.png)

**Comment by MarioSonic2987** [comment]
Still an issue?

**Comment by raveskirza** [comment]
Better than before but still character colors are off

GL
![image](https://user-images.githubusercontent.com/28158623/39376250-fbc176ba-4a1e-11e8-90b6-d4a960418e06.png)


VK
![image](https://user-images.githubusercontent.com/28158623/39376213-df142a62-4a1e-11e8-82af-a481e132fe79.png)

**Comment by toccata10** [comment]
Testing on Archlinux, r9 fury, mesa 18.0.1:
If you tick "Write Color Buffers", the overbright pb goes away with Ogl. Unfortunately, there's a big performance hit (it goes from 31fps to 20fps). With Vulkan, colors are still wrong.
Still a few glitches with the shadows, but otherwise, the rendering is nice.
![selection_092](https://user-images.githubusercontent.com/7478580/39392675-61e9075a-4aba-11e8-8058-16440802ed0c.jpg)
![selection_093](https://user-images.githubusercontent.com/7478580/39392676-6203edcc-4aba-11e8-8c68-340494a88a4a.jpg)
![selection_094](https://user-images.githubusercontent.com/7478580/39392677-621bff0c-4aba-11e8-9897-5d3e236d766a.jpg)
Same thing in Soul Calibur IV and its overblooming pb: tick the wcb setting and it renders correctly (didn't see in glitches in shadows and it works with Ogl and Vulkan).
![selection_089](https://user-images.githubusercontent.com/7478580/39392687-8dd12bae-4aba-11e8-95fe-b60dd0cf98d9.jpg)
![selection_090](https://user-images.githubusercontent.com/7478580/39392688-8de8d70e-4aba-11e8-8c12-553ec4833cee.jpg)

**Comment by kd-11** [comment]
These issues were fixed long ago, SCV now renders correctly for some time.
