### ISSUE TITLE
Add timestamps to log output

### ISSUE THREAD

**Issue by TGEnigma** [RPCS3/rpcs3#3363]
Convenient but also useful, because it makes it easier to tell when something has occurred, especially when using less verbose log filters.

**Comment by PeterMcteague** [comment]
By default logs timestamp the number of h/m/s/fracts since the game was booted. 

Making the change is easy enough but it's possible that the time since execution is really useful in it's current format (Would need someone who does more low level work to comment on that).

I currently have a branch where time is logged as 15:51:03.693729 , so the current time with the old fractal on the end. This leaves the current precision for debugging and allows users to say "The time was X when the error happened", which might make debugging easier.
