### ISSUE TITLE
SPU: Unknown/Illegal instruction (0x9ba8417e) - Counter-Strike Global Offensive [NPUB30589]

### ISSUE THREAD

**Issue by JusicP** [RPCS3/rpcs3#3371]
With SPU Interpreter "class std::runtime_error thrown: Unknown/Illegal instruction (0x9ba8417e)"
With SPU Recompiler (ASMJIT) this error
![error](https://user-images.githubusercontent.com/25232950/29993506-8d70801a-8fc1-11e7-9d71-93de14e9910b.png)
SPU Interpreter log
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1271956/RPCS3.log.gz)
SPU Recompiler log
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1271953/RPCS3.zip)

**Comment by elad335** [comment]
From a small research, when trying to open its spu image as a standalone spu SELF program (found in `/dev_hdd0/game/NPUB30589/USRDIR/bin/rawspu_gcmdraw_spu.self`) it gives the same error:

F {RawSPU[0x0] Thread (TEST_SPU) [0x00104]} class std::runtime_error thrown: Unknown/Illegal instruction (0x9ba8417e)
(in file Emu\Cell\SPUInterpreter.cpp:37)

@Nekotekina Since you wrote most of the spu image loaders' code, any ideas?

**Comment by elad335** [comment]
fixed in #4728
