### ISSUE TITLE
[FIXED] Scott Pilgrim [NPUB30162] infinitely repeating socket error 10045

### ISSUE THREAD

**Issue by Manic020** [RPCS3/rpcs3#3380]
~~Booting up v1.03 Scott Pilgrim vs. The World: The Game [NPUB30162] in any recent version of RPCS3 causes an infinitely repeating socket error, which then causes some visual and input lag and generates massive log files. Otherwise the game seems to work fine with a config edit (setting Disable Vertex Cache to true). Happens regardless of decoder or renderer settings. Only fix found so far is to use an old version of RPCS3 from June 2017 (2b0736b7) or roll the game version back to v1.01. Log attached.~~

~~[RPCS3_log.txt](https://github.com/RPCS3/rpcs3/files/1272679/RPCS3_log.txt)~~

The issue appears to have been fixed in recent updates.

**Comment by hcorion** [comment]
I believe it goes farther if you change `Firmware Settings`->`Load Automatic and Manual Selection` and select `libnet.sprx` in the `firmware libraries` section.

**Comment by MarioSonic2987** [comment]
@hcorion Enabling that module, allows Saints Row: The Third and Saints Row IV to play videos.

**Comment by Manic020** [comment]
@hcorion Thanks, that did the trick!

**Comment by Manic020** [comment]
Damn, I don't know if I missed this or if it just started happening after leaving it alone for a while, but now I'm getting a repeating error saying "HLE TODO: Unimplemented syscall sys_net_bnet_recvfrom -> CELL_OK". Log attached.

[RPCS3_log2.txt](https://github.com/RPCS3/rpcs3/files/1273086/RPCS3_log2.txt)

**Comment by Drive251** [comment]
as per @legend800  and @clienthax
"Not sure why, this has been confirmed by others in the thread. Maybe because your version is not updated + dlc or something

Update:
Load times/net code spamming only impacts updated versions of game
Clienthax is investigating.

It's just broken net code - the issue is that networking is running when it's set to off. I did have a go at fixing the netcode lastnight but haven't got it to a decent non spamming state. I'm going to have to run some tests on my decr later to see what the heck the real ps3 does with no network connection
"
http://www.emunewz.net/forum/showthread.php?tid=178174&page=7

issue with:
https://github.com/RPCS3/rpcs3/pull/2879#issuecomment-320416246

**Comment by Manic020** [comment]
Alright, that makes sense seeing as the v1.03 patch added online play. I rolled back to v1.01 of the game with just the Knives DLC and it seems to be working fine now, although some scary looking errors still pop up. I'll attach a log for my working launch just in case it ends up being helpful and I'll update my original post to state that this problem is only with v1.03 in case this thread stays open.

[RPCS3_log3.txt](https://github.com/RPCS3/rpcs3/files/1273291/RPCS3_log3.txt)

**Comment by AniLeo** [comment]
Is this still an issue?

**Comment by Manic020** [comment]
I don't think so, but I'm not 100% sure. I've been using a hacked PS3 lately instead of the emulator so I haven't been keeping up.

**Comment by legend800** [comment]
It's fixed! :)

**Comment by Asinin3** [comment]
@Manic020 Since this is fixed can you please close it?

**Comment by Manic020** [comment]
I’ve tried, I can’t figure out how :/

**Comment by Asinin3** [comment]
@Manic020 There's a big red close button at the bottom of the comment box, if you can't see it then disable your browser add-ons maybe.

**Comment by Manic020** [comment]
Oh wow. I don’t know how the hell I missed that lol. Thanks.
