### ISSUE TITLE
PS4 Controller not properly recognized

### ISSUE THREAD

**Issue by sambow23** [RPCS3/rpcs3#3462]
Ever since the controller settings got changed, whenever I would select "DualShock 4" It would say "E HLE: [DS4] No controllers found!". But whenever I would select "Evdev" it would recognize it, but the controls we're messed up. This is on Linux by the way, specifically version  "v0.0.3-50-b141b43 Alpha". It did not happen before the controller settings were changed.

**Comment by twdarkeh** [comment]
DS4 no longer works in Trails of Cold Steel, Final Fantasy X/X-2 Remaster, Lost Dimension, and a host of other games on windows after this commit. Have to revert to keyboard input, which makes the emulator largely unusable to games that require analog sticks to play(all of the above).

**Comment by hcorion** [comment]
Tagging @RipleyTom

**Comment by whymsical210** [comment]
Can confirm its broken Hyperdimension Neptunia (The original)

**Comment by jarveson** [comment]
For the linux issue, try #3471, it shouldn't fix the issue, but will hopefully output a different error message which will help track down the true issue

**Comment by twdarkeh** [comment]
I should clarify that my comment applies to Windows 7, I suppose, so this doesn't seem to be a Linux specific issue.

**Comment by twdarkeh** [comment]
#3471 Seems to fix the issue on windows 7, at least.

**Comment by Megamouse** [comment]
I wonder if the DS4 is still undetected.

Button Layout should not be a problem after my pad PR.

**Comment by kernsback** [comment]
For Linux, this problem still exists on rpcs3-v0.0.3-2017-11-11-8fc9862-8730_linux64. Selecting Dualshock 4 gives the No controllers found! error message. Selecting Evdev is accepted. I can set the calibration values in jstest-gtk and everything looks good until I press the triggers while the emulator is running. Depressing the right trigger randomly sets the left hat to extreme left, and the trigger value is set to an extreme negative value (-32767 so it's max negative signed int value) instead of the calibrated 0. Likewise the left trigger and right hat attain some weird relationship. The right hat seems to be giving correct values but its zero is offset to a max negative int value to the left. Depression of the left trigger seems to be mapped to up/down on the right hat, and at the same time the right hat's left/right is mapped to an up/down output.

Games seem to interpret the right trigger as pressing multiple buttons at once, including start, left hat to the left (which is randomly assigning the zero to a strange value until the left hat is moved), and some other button.

I've experimented with different setups to see if this is a driver issue and the problem persists over all of them.

**Comment by Megamouse** [comment]
can someone retest this please?

**Comment by Illynir** [comment]
I have always this problem. DS4 not recognised.

**Comment by tijder** [comment]
Same problem here. Still not showing the DS4 by input output devices.

**Comment by Illynir** [comment]
I rectify: I downloaded the latest build in appimage and now everything is good. Fixed for me. :)

![image](https://user-images.githubusercontent.com/22648460/34328351-3a0f7406-e8dd-11e7-92ff-db8f4df8daa1.png)

**Comment by Megamouse** [comment]
I think this can be closed then

**Comment by AniLeo** [comment]
Closing as solved

**Comment by xacutaz** [comment]
to fix this you simply need to install ds4drv and run ds4drv --hidraw in a terminal with elevated privileges and you must also run ./rpcs3 wih elevated privileges , it worked for me 
https://github.com/chrippa/ds4drv

**Comment by natemonster321** [comment]
Sorry to comment on such an old issue, but for anyone who googled "rpcs3 hid_open_path" like me and only found this issue, the problem occurs on linux because rpcs3 doesn't have access to /dev/uinput. Basically, depending on distro, you may need to add a udev rule something like this: `SUBSYSTEM=="misc", KERNEL=="uinput", MODE="0660", GROUP="input"` to your system, and make sure you're in group `input`
