### ISSUE TITLE
Shader cache recompiles by video drivers on second loading

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#3498]
That's what I figured out during this time for issue #3416.
I have NVidia card, so I'll be write about it as an example.

Slow cache loadings on second running emulator happen because in fact it's not re-loading of compiled data -- it's a new compiling process that video drivers do! For some reasons they sometimes clears %AppData%\Roaming\NVIDIA\GLCache\ contents -- on new game loading, on running different emulator version, on system rebooting etc. Compiled data not exist, so it starts from scratch on loading shader_cache pipelines. And it's that a pain in the ass.

I suggest developers to think about it, and implement saving compiled caches in game data folder to exclude permanent data losses. Or maybe make some own format that will be translated to GLCache on game loading.

**Comment by woj1993** [comment]
@Psycho-A It seems like it. It was weird for me that on second loading of Dragon Ball Raging Blast 2 Demo rpcs3 was returning errors that I would expect while compiling shaders not while reloading.

**Info.** Nvidia drivers deletes precompiled shaders because games are trying to use least shaders and they have small size, for this and many others reasons driver will only store 250 MB of shaders in cache.

**Comment by rodjun** [comment]
So that explains it, that's probably why CEMU had its own compiled shader cache and the "generic" pre driver compilation  ones which are shareable, rpcs3 only has the generic ones and depends fully on the driver for caching the compiled ones if i understanded everything correctly.

**Comment by isshininu** [comment]
Hm, looks like true.

**Comment by kd-11** [comment]
Closing as discussion is no longer active. Binary compatible shader cache can be implemented in future for OGL, for vulkan spir-v is the best we can do, and that is clearly not what causes the slowdown but nvidia's driver architecture.
