### ISSUE TITLE
Vulkan: ZCull Emulation

### ISSUE THREAD

**Issue by Cornflak** [RPCS3/rpcs3#3514]
When using Vulkan, the sun is always showing through buildings and casts a lens flare. OpenGL solves it, but the frame rate suffers a bit more. 
![capture](https://user-images.githubusercontent.com/32245614/31005066-c590703a-a4bc-11e7-90cf-dc6dcbdf4bc5.PNG)

**Comment by ScorchEmber256** [comment]
Sounds like an RSX issue because some games rely on depth culling, maybe @kd-11 could look into that :|
![capture](https://user-images.githubusercontent.com/13728013/31040066-5b41cf3e-a5c6-11e7-9aba-fc2bd0315506.PNG)
![2nd](https://user-images.githubusercontent.com/13728013/31040067-5d1c0180-a5c6-11e7-98b2-f687c49e62a9.PNG)

Log spams a different indirect problem with animated textures: 
E {rsx::thread} RSX: Blit request denied because the destination region does not fit!

**Comment by kd-11** [comment]
Zcull emulation on vulkan is still not done.

**Comment by geo98** [comment]
When more or less it's planned to be? (a rough idea)

**Comment by frymezim** [comment]
@geo98 
Put a $1000 [bountysource](https://www.bountysource.com/) for that he'll fix it for you.

**Comment by geo98** [comment]
@frymezim What do you mean?

**Comment by Lmmb74** [comment]
@geo98 BountySource is a service where you can publish a reward for fixing issues in your projects, or earn money fixing published issues

**Comment by geo98** [comment]
@Lmmb74 It seems very interesting, but I wanted to know what @frymezim meant.

**Comment by raven02** [comment]
Just seen the vulkan zcull emulation somewhere and looks like it fixes the lens flare .

https://github.com/popbob/rpcs3/commits/vk-zcull

**Comment by AniLeo** [comment]
Closing as it has been implemented by #3827
