### ISSUE TITLE
Regressions with #3563 / #3557

### ISSUE THREAD

**Issue by Asinin3** [RPCS3/rpcs3#3572]
~~While the #3563 PR fixed an issue where RPCS3 would always freeze when entering/exiting full-screen, with resolution scaling enabled I did have a segfault with this in the log after exiting full-screen (happened after a few hours.)~~

~~``·E 2:02:17.047421 {rsx::thread} RSX: Vulkan API call has failed with an error but will continue: Present surface is out of date (VK_ERROR_OUT_OF_DATE_KHR)
(in file C:\rpcs3\rpcs3\Emu\RSX\VK\VKGSRender.cpp:1593)
·E 2:02:29.558077 {rsx::thread} RSX: Vulkan API call has failed with an error but will continue: Present surface is out of date (VK_ERROR_OUT_OF_DATE_KHR)
(in file C:\rpcs3\rpcs3\Emu\RSX\VK\VKGSRender.cpp:1593)``~~

~~[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1373163/RPCS3.log.gz) (logfix)~~

~~Using latest Nvidia drivers~~

Fixed

**Comment by kd-11** [comment]
Even knowing why the thing segfaults, nvidia's design choice here is just strange. Why segfault if another present request is issued?
The problem is that the spec is not very clear about what to do about this. I assumed accessing the surface would return an error and not crash even after the error has been logged. This is because AMD handles surfaces differently - Window resize does not destroy the swapchain and present is expected to be called to transfer ownership of swapchain images back to the present engine. Nvidia throws a fit and dies instead. 
I'll look into just poking at the driver and hoping it doesn't die like everything else with vulkan. UGH

**Comment by isshininu** [comment]
Ugh...
btw, scaling to 200% works perfectly, but 300% (4K) dies when entering to fullscreen for all my 3 games.

**Comment by Asinin3** [comment]
@isshininu Dies with what?

**Comment by isshininu** [comment]
Dies with UGH 

Seriously, i cannot reproduce this now.

**Comment by Asinin3** [comment]
My issue with RPCS3 crashing when entering full-screen has been fixed with: #3581 since no one else posted any regressions I'm closing this.
