### ISSUE TITLE
Periodic fatals after merging #3581, #3571 or #3574

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#3589]
Silent Hill Downpour, BLUS30565.
Use GPU texture scaling,
VSync,
Anisotropic Filter 4x,
Resolution scale: 200%
Win 7 x64, Core i5, 8Gb RAM, GTX 760 Ti

After latest updates I periodically get random falls right during 10-20 minutes of game which were never encountered before.

On Vulkan it's:
> ·F 0:12:11.498134 {rsx::thread} class std::runtime_error thrown: Driver returned 0 images for swapchain
> (in file c:\rpcs3\rpcs3\emu\rsx\vk\VKHelpers.h:922)

On OpenGL I get Virtual Memory Verification failed error.

Also, emulator stops working after this.

**Comment by kd-11** [comment]
I'll close this since its likely not an emulator problem, but a problem with your PC setup. Looks like something is very wrong with the driver setup. Have you recently updated windows or your driver? A driver returning no available swapchain images is a bad sign. Do other games somehow work with vulkan+rpcs3? Swapchain is created as the first step so I doubt it will just work. Reopen if only silent hill is affected.

**Comment by kd-11** [comment]
Also, I have to ask, how did you trigger swapchain error after 20 minutes? Window resize? Alt-tab from fullscreen?

**Comment by Psycho-A** [comment]
I've updated video drivers a week ago, and didn't anything suspicious. I can't normally check other games because they are very slow to me, and I can't play them normally...
