### ISSUE TITLE
[Regressions] BLJM61149, NPJB90690 (maybe more)

### ISSUE THREAD

**Issue by Renusek** [RPCS3/rpcs3#3603]
Yakuza (Ryu ga Gotoku) Ishin and Ishin Demo regressed heavily. Before 0.0.3-6220 (started crashing with this build I think, but still renders the graphics accurately) game was looking good, little to no graphical issues (#3520, vulkan was near perfect, opengl had black human models), but since 0.0.3-6272 (maybe earlier? will try to find out when exactly this happened) the game is no longer showing game graphics (no models, no map), only UI is still being rendered. This issue might be also happening for Yakuza 0 and Yakuza Kiwami, but I don't have these games dumped right now, so if anyone else can test them, please do and post results here.

How it looked before
![mainmenubefore](https://user-images.githubusercontent.com/4978744/31585171-a27606d8-b1bd-11e7-8a52-ee1d633c5972.png)
![ingamebefore](https://user-images.githubusercontent.com/4978744/31585172-a5e3663a-b1bd-11e7-8a59-e14300b7bcef.png)
![ingamemenubefore](https://user-images.githubusercontent.com/4978744/31585174-a8262c02-b1bd-11e7-91bf-c190e45f2c27.png)

How it looks now 
![mainmenunow](https://user-images.githubusercontent.com/4978744/31585023-52859e66-b1ba-11e7-876d-a73c8e79c256.png)
![ingamenow](https://user-images.githubusercontent.com/4978744/31585025-59172eca-b1ba-11e7-9233-703b566a0daa.png)
![ingamemenunow](https://user-images.githubusercontent.com/4978744/31585027-5b45df16-b1ba-11e7-9e35-2ecdfd13e00c.png)

NPJB90690 new log (regressions) [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1385431/RPCS3.log.gz)

NPJB90690 old log [0.0.3-6172] (graphics 👌 ) [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1385464/RPCS3.log.gz)

**Comment by Neucomac3** [comment]
have you tried leaving the room the demo starts in yet? I've been trying this as well and it seems the issue is a littel more complicated than it just not rendering anything besides the UI. It *is* rendering, but not correctly.
![image](https://user-images.githubusercontent.com/32991174/31970987-f25cb59c-b911-11e7-83c8-34d809df4b76.png)
![image](https://user-images.githubusercontent.com/32991174/31971017-0f5f4a7e-b912-11e7-90ed-6b5efba68c59.png)
![image](https://user-images.githubusercontent.com/32991174/31971057-2c7b5f30-b912-11e7-9ee7-3d30922cece4.png)
Additionally, some light sources seem to be rendered, which you can see in the distance here.
![image](https://user-images.githubusercontent.com/32991174/31971101-4be84b62-b912-11e7-8f00-ac6febdb7245.png)
and the skybox is *sort of* there, but not correctly.
![image](https://user-images.githubusercontent.com/32991174/31971145-6a6a2f10-b912-11e7-9e9f-140cd2982fe0.png)
Attaching my log file too, just in case someone wants to look into this.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1412693/RPCS3.log.gz)

**Comment by Renusek** [comment]
Fixed in #3744, at least in Ishin (couldn't test all of the affected games - Yakuza Ishin/0/Kiwami and their demo versions)
