### ISSUE TITLE
Input lags and frame skipping

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#3640]
When FPS is lower than ~20, emulator skips some button pressings if they matched these dropped frames. Holding pressings doesn't help - seems like emulator detects only pressing event instead of reading if button already pressed. Can this be fixed somehow? Some games that requires pressing buttons with certain frequency at Quick-Time Events are not playable because of this issue.

**Comment by kd-11** [comment]
No, the emulator checks the button state, not the press event. Controllers don't work like that, i.e Its harder to try and capture button events, than it is to just check current state. If its a 60fps game, the massive loss of frames (~70% dropped) will lead to input lag. You could try enabling frame skip as a workaround, but if its due to stutter, there's no workaround at the moment other than a best of a PC. Frame skip can be enabled in the config file, although I would not recommend it unless the game is 60 fps natively and does not manage its own frametimes.

**Comment by Psycho-A** [comment]
@kd-11 
I use both keyboard and controllers, and skipping pressing events repeat the same way. Games I tried are mostly 30 fps max, so even loss of 10 frames makes sense...
