### ISSUE TITLE
Fullscreen vs. Borderless Windowed

### ISSUE THREAD

**Issue by ThatFlint** [RPCS3/rpcs3#3650]
I've been playing Persona 5 on rpcs3 and currently I'm on build 0.0.3-6573. One thing I noticed was that when I tried to play in fullscreen, the performance would go downhill a LOT, until going back to windowed.
Furthermore as stated by joshuacode751 in pr https://github.com/RPCS3/rpcs3/pull/3638, the achievement popups are currently not working in fullscreen mode.
It would be good for both of these issues to be fixed, but a quick and easy temporary solution for these issues would be to allow for a borderless windowed mode (preferably toggleable with a hotkey from regular windowed mode)

**Comment by kd-11** [comment]
QT doesn't do true fullscreen. Its something with the display stack detecting borderless window and somehow disabling popups. You can see the Qt code handling fullscreen here:
https://code.woboq.org/qt5/qtbase/src/plugins/platforms/windows/qwindowswindow.cpp.html#1898. They even mention that "true" fullscreen (via ChangeDisplaySettings with CDS_FULLSCREEN) is not used at all and is instead faked. Thats why your monitor resolution does not change when you switch to fullscreen despite the window resolution being different from desktop resolution.
I suspect the nvidia driver detects a fullscreen window and sets some windows flags to enhance performance. This is particularly evident since intel and AMD drivers have popups working fine, but no amount of tinkering with window flags or messages ever gets anything to show on top of an nvidia window (as tested by a volunteer on discord).

**Comment by Margen67** [comment]
So it's not possible to get exclusive fullscreen with QT?

**Comment by kd-11** [comment]
No

**Comment by BParks21** [comment]
@kd-11 How does dolphin do EFS then? They use QT as well?

**Comment by MSuih** [comment]
Kd's response was from two years ago; exclusive fullscreen has been added to vulkan and could be implemented into rpcs3 by someone who knows a little bit of vulkan. Also, I'm pretty sure that dolphins exclusive fs only worked with directx at first, I haven't checked the codebase recently if they've added support for other backends

**Comment by BParks21** [comment]
I would like to see it implemented in vulkan. I've tested all of dolphins backends and they all work with EFS. I feel like it would help improve frame pacing and reduce input lag.

**Comment by kd-11** [comment]
Vulkan defaults to exclusive on all known drivers atm. Thats just forced in the driver. I'll see about optional borderless but I don't expect an improvement.

**Comment by BParks21** [comment]
@kd-11 Oh so vulkan is already using EFS in RPCS3?

**Comment by kd-11** [comment]
If you don't specify (which is how most drivers without the EFS extension work), it uses whatever the driver thinks is best. Nvidia definately uses EFS by default which caused us endless problems before since it would grab the whole foreground and lead to situations where dialogs were not showing up in front of the game window. So I'm confident EFS will do nothing for nvidia.

**Comment by IngwiePhoenix** [comment]
What's the current status on this? I noticed that whenever I send a game to fullscreen, my monitor blacks out as it changes resolutions. This usually happens with EFS but not with borderless. Since the Borderless setting does not appear in the configuration tabs, I suppose this still hasn't been implemented as a toggle/setting?
Thanks!
