### ISSUE TITLE
"(RenderThread) class std::runtime_error thrown: Trap!" - Crysis 3 [BLUS30976]

### ISSUE THREAD

**Issue by JusicP** [RPCS3/rpcs3#3687]
RPCS3 v0.0.3-3-db5c250 Alpha | HEAD
Black screen. Happens on all settings.
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/1433432/RPCS3.zip)

`F {PPU[0x1000016] Thread (RenderThread) [0x0144517c]} class std::runtime_error thrown: Trap!
(in file Emu\Cell\PPUInterpreter.cpp:3098)`

**Comment by JusicP** [comment]
![image](https://user-images.githubusercontent.com/25232950/32320390-4eb101bc-bfc6-11e7-8c6a-2546e31ddbea.png)

**Comment by dio-gh** [comment]
Traps are not errors, but signals. Currently RPCS3 obeys them, causing games to pause when a Trap signal is sent by the game. This is usually due to games trying to assert certain actions have happened in time, meaning this is nigh impossible to have fixed without
* cycle accurate emulation

or
* ignoring trap signals.

Another ticket has been opened for auto-continuing when encountering a Trap signal. Therefore, this ticket is closable. Not an issue.

**Comment by elad335** [comment]
Fixed by #7233
