### ISSUE TITLE
Skate 3 Fps buff

### ISSUE THREAD

**Issue by Darkpaladi** [RPCS3/rpcs3#3940]
Specs/ Version 

---> RPCS3 v0.0.4-6223-a1fa10ac Alpha | HEAD
Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz | 4 Threads | 7.97 GiB RAM | AVX+
GeForce GTX 1060 6GB

When Changing from Career mode to Free Mode there is a notable speed buff. Also when doing air tricks RPCS3 gives me 60+fps but right when I touch the floor, its laggy again.

**Comment by elad335** [comment]
@Darkpaladi attach rpcs3.log.gz else the issue will get closed

**Comment by Darkpaladi** [comment]
@elad335 Where may I find the rpcs3.log.gz?

**Comment by elad335** [comment]
@Darkpaladi play the game until you encounter the problem , close rpcs3 , go to rpcs3 main folder its there

**Comment by Darkpaladi** [comment]
Thank you

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1564701/RPCS3.log.gz)

**Comment by kamer1337** [comment]
in Debug tab disable Zcull occlusion, it should speed up the game at least for me it runs faster

**Comment by Darkpaladi** [comment]
@kamer1337 How do you get into the debug tab? 
Thanks!

**Comment by kamer1337** [comment]
@Darkpaladi 
in config file  set "Disable ZCull Occlusion Queries" to true

**Comment by AniLeo** [comment]
Closing as Invalid, there's no actual issue here being reported, just a general observation on game performance.

If you happen to find the regression on performance that happened recently on this game, please open a regression issue. You must state what's the build it regressed on (first build that started having the problem, from https://rpcs3.net/builds).
