### ISSUE TITLE
HLE: cellVdec - Unsupported time_base.num

### ISSUE THREAD

**Issue by TGEnigma** [RPCS3/rpcs3#4110]
Sonic The Hedgehog (NPUB30442) crashes with HLE cellVdec, works with LLE.
```
F {PPU[0x1000013] Thread (HLE Video Decoder)} class std::runtime_error thrown: Unsupported time_base.num (1000/1, tpf=1)
(in file Emu\Cell\Modules\cellVdec.cpp:339)
```

**Comment by Zangetsu38** [comment]
RR7 have same think

**Comment by TGEnigma** [comment]
I searched for vdec and couldn't find any issues related to it.

**Comment by Zangetsu38** [comment]
yes, for fix that, use libvdec, same for video freeze after finished, Siren blood etc, cellvdec have lot bug

**Comment by TGEnigma** [comment]
I see. Well I'll keep this particular issue open in case anyone else ever runs into it.

**Comment by scribam** [comment]
Works fine on Linux (Antergos).

![screenshot from 2018-04-01 22-14-18](https://user-images.githubusercontent.com/25406440/38177046-3f146258-35fa-11e8-9ac8-2bd16152d02a.png)

@Zangetsu38 @TGEnigma What's your operating system? Have you tried on Linux?

**Comment by TGEnigma** [comment]
Windows 10. I don't have a Linux system.

**Comment by scribam** [comment]
@TGEnigma Thanks for the feedback, it was useful to understand the situation which is identical to the issue #2550.

It might sound strange but this issue happens because you are using a case-insensitive file-system. Contrary to Linux, a (video) file, named RIBBON.MP4, is read which leads to the error you put in the description. This file is used to render a background wave effect in the menu selection but you will only find it on PS3 with the game "Gunstar Heroes" (see https://www.youtube.com/watch?v=sUg0vJl2HC0). For the other games like "Sonic The Hedgehog" (see https://www.youtube.com/watch?v=iX1lnQvTT7c) or "Streets of Rage 2" (https://www.youtube.com/watch?v=-dpJ6BJjBJM), there is no effect and RPCS3 on Linux works correctly.
I can't tell if it is a bug or if it was made on purpose by the devs who did these games. The difference I noticed was the SDK version: "Gunstar Heroes" is built on 2.50 whereas the others use 3.50.

IMO, on Windows, RPCS3 should behave like the PS3 in situations where case-sensitivity is important or we might face other issues.
I think the issue with cellVdec should not be bound with "Sonic The Hedgehog" or "Streets of Rage 2" but with "Gunstar Heroes" where I have the same fatal on Linux too.

**Comment by TGEnigma** [comment]
@Nekotekina since you're the author of most of the vfs code you should probably be notified of this.

**Comment by AniLeo** [comment]
Level 22 Gary's Misadventures - NPEB02332 from duplicate #4442
