### ISSUE TITLE
savedata: cellSaveDataUserAutoLoad called with a directory that doesn't exist (Regression)

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#4124]
LOTR - Conquest calls cellSaveDataUserAutoLoad on a directory that doesn't exist and throws access violation when reading memory upon calling  ```funcFile(ppu, result, fileGet, fileSet);```on savedata_op

The game used to work before, so this is a regression

Adding a sanity check on cellSaveDataUserAutoLoad before calling savedata_op solves the issue
```
const std::string base_dir = vfs::get(fmt::format("/dev_hdd0/home/%08u/savedata/", userId ? userId : 1u));
std::string dir_path = base_dir + dirName.get_ptr() + "/";

// Check if the directory exists first
// LOTR - Conquest calls cellSaveDataUserAutoLoad on a directory that doesn't exist
if (!fs::is_dir(vfs::get(dir_path))) 
{
    return CELL_SAVEDATA_ERROR_FAILURE;
}
```

Although I'm pretty sure the fix is correct, I'm also pretty sure this is not the way to go, and that it should be fixed within savedata_op itself.
_Note: I've also tested this with #3918 and the issue persists._

@jjsat Any ideas?

**Comment by jjsat** [comment]
As a first idea: Probably the check should be in savedata_op() when loading the PARAM.SFO. When the file does not exist the save is invalid and loading should fail I guess. It has to be figured out in what modes exactly this fails (could be fail for all loading modes and ok for all save modes).
https://github.com/RPCS3/rpcs3/blob/a27e2db4556e3f9bbe7d1da732ed08fa99d72039/rpcs3/Emu/Cell/Modules/cellSaveData.cpp#L473

**Comment by jjsat** [comment]
Ok. So this is what it looks like to me:

- funcStat is also called on the PS3 if the directory does not exist. This is ok.
- But if the save directory is not present the game returns CELL_SAVEDATA_CBRESULT_OK_NEXT as the result of funcStat instead of an error code (CELL_SAVEDATA_CBRESULT_ERR_NODATA or something). The game also does not fill in any values into the statSet parameter (=> all values 0).
- On the PS3 this causes a "****** sysutil savedata parameter error : 50 ******", so the param error code is returned and funcFile is never called.
- There is no check for this condition in the emu so the funcFile call crashes.
- The existing code after funcStat looks messy and while I have some code that works for this game it probably breaks something else.

There are also two other problems with the game:
- If the save exists and is valid the game still fails to load it successfully unless a delay is inserted. It looks like the another save related race conditions.
- If the game detects that a save is invalid it tries to bring up a native dialog for deleting the save. For this it tries to list all saves on the system by specifying "*" as the directory name. So wildcards seem to work on the PS3, but they do not on the emu. Because no savegame can be found the game gets stuck in an endless loop.

**Comment by AniLeo** [comment]
Retested on current master per request, still an issue as expected since this part of savedata wasn't touched since then - can only go Ingame with LOTR with existing savedata currently.

**Comment by elad335** [comment]
Can you post log for this?

**Comment by AniLeo** [comment]
RPCS3 v0.0.6-7932-d7ad991b Alpha | HEAD
AMD FX(tm)-8350 Eight-Core Processor | 8 Threads | 7.92 GiB RAM | AVXx

[BLES00412.log](https://github.com/RPCS3/rpcs3/files/3039843/BLES00412.log)

**Comment by elad335** [comment]
Fixed by adding the missing check for CELL_SAVEDATA_RECREATE_NO_X modes [here](https://ci.appveyor.com/project/elad335/rpcs3/builds/23593933).
