### ISSUE TITLE
VF5FS[NPUB30625] Graphic issues

### ISSUE THREAD

**Issue by ghost** [RPCS3/rpcs3#4150]
Thanks to RPCS3 team, Virtua Fighter 5 Final Showdown became much better graphical game than PS3 version. Thank you for your effort.
I found a few missing effects and graphic issues in VF5FS. I hope that fixing them help make RPCS3 more perfect.

1. At Wolf's stage, it doesn't snow.
2. There is not the hit effect like splashing water.
1-2
https://www.youtube.com/watch?v=9ke4O7dO2CA

3. At Shun's stage, as time goes by, the shape of mountain in a long distance is distorted.
   Default Resolution-1280X720 / Resolution Scale-100%(Default) / v0.0.4-6396-5b5f2d424(2018-02-06)
![shun](https://user-images.githubusercontent.com/36184914/35850033-e3e712da-0b66-11e8-89a4-ba5632f1a998.png)

4. Graphic issues at Customization menu
   Face > Nose/Mouth > Tattoo, Paint
   (Akira, Jacky, Wolf, Lei-Fei, Brad)
![akira](https://user-images.githubusercontent.com/36184914/35850045-ef031060-0b66-11e8-8b59-373723ac5bbf.png)

PC specs / Win10 / i5-7600 / GTX1060 / 16G

**Comment by dio-gh** [comment]
Needs retesting, this ticket probably long outdated.

**Comment by MarioSonic2987** [comment]
The graphical issues still happen in the current master (at least, 1,2 and 3). I can't confirm the last one.
![](https://cdn.discordapp.com/attachments/479420121396281344/631250873787482117/unknown.png)

[RSX Captures (Snow Mountain and River stages)](https://drive.google.com/open?id=1ZIT7VdUXiKfUCMox0LTaWVsMmnKEs4Pa)

**Comment by zombie167** [comment]
It's snowing at Wolf's stage.(Fixed in the PR - rsx: Implement point sprite coordinate generation #6966 )
https://github.com/RPCS3/rpcs3/pull/6966
It has the effect of hitting a splash Shun's stage and the outline of the mountains became normal
Unfortunately for some DLC items, the effect when worn on the character is still wrong

**Comment by MarioSonic2987** [comment]
@zombie167 
I can confirm that graphical issues previously mentioned are fixed:
![image](https://user-images.githubusercontent.com/20027681/73857887-db6d5c80-4837-11ea-9727-25fedf77409e.png)
![image](https://user-images.githubusercontent.com/20027681/73858798-40758200-4839-11ea-8cad-a26f64503829.png)

Although the outlines of the mountains are fixed by increasing the Resolution Scale:
![image](https://user-images.githubusercontent.com/20027681/73859760-d958cd00-483a-11ea-8611-eafde2e10da7.png)

Snowflakes become smaller when you increase Resolution Scale (200% in this case):
![image](https://user-images.githubusercontent.com/20027681/73859090-cabde600-4839-11ea-8663-9592f38507fd.png)

Sadly, I can't confirm the last one (wrong effects in customization items). You can enable Write Color Buffers if it fixes that bug. Or you can also try with Read Color Buffers, Write Depth Buffers and Read Depth Buffers.

**Comment by zombie167** [comment]
@MarioSonic2987

Sorry none of the above options can fix the wrong item display

**Comment by MarioSonic2987** [comment]
The mountains on the River stage no longer has blocky graphics in the distance with 100 % as Resolution Scale value.

![image](https://user-images.githubusercontent.com/20027681/81401563-de763280-912f-11ea-8c6a-a3b9ed797f21.png)

**Comment by zombie167** [comment]
Customization items are fixed 
rsx: Fix alpha ref #8166
https://github.com/RPCS3/rpcs3/pull/8166

 **Before**

![Akira Unfix](https://user-images.githubusercontent.com/22722505/83973950-62ccf880-a91c-11ea-8d6c-d66296f7688c.jpg)


**After**

![Akira Fix](https://user-images.githubusercontent.com/22722505/83973955-66f91600-a91c-11ea-941e-23808a454f6b.jpg)


 **Before**

![pal unfix](https://user-images.githubusercontent.com/22722505/83973960-69f40680-a91c-11ea-8056-63fa022a252a.jpg)


**After**

![pal fix](https://user-images.githubusercontent.com/22722505/83973962-6c566080-a91c-11ea-902f-9a18e4a32d7c.jpg)

**Comment by AniLeo** [comment]
Closing as fixed

**Comment by firetiger13** [comment]
There is not the hit affect like large water drop.
![VF5FS](https://user-images.githubusercontent.com/66947890/84647327-3d547600-af3e-11ea-9c95-2263f51e25f4.jpg)
