### ISSUE TITLE
Regression: GSFrame (#4029)

### ISSUE THREAD

**Issue by cybertronicgames** [RPCS3/rpcs3#4156]
On elad335 newest build 0.0.4-7889 of rpcs3 version the video screen starts up on the left bottom corner of the monitor. I reverted back to  kd-11's 5 day old 0.0.4-7852  build & the video screen starts up in the center of my monitor.

elad335 newest build 0.0.4-7889 
![screenshot_185](https://user-images.githubusercontent.com/14711758/35941350-8a38856e-0c17-11e8-98cc-6d48c0c1e0b3.png)

kd-11 5 day old 0.0.4-7852  build
![screenshot_182](https://user-images.githubusercontent.com/14711758/35941404-b7735c3e-0c17-11e8-9a55-7e1b860cf208.png)

**Comment by AniLeo** [comment]
No, this is not a regression on elad's latest PR, this is a regression on #4029

If you're reporting a regression, you must report the build that regresses it, not a random build, otherwise the issue is useless. In this case there's no problem since we know what caused the regression, but keep in mind for the future.

**Comment by Megamouse** [comment]
close please.

**Comment by AniLeo** [comment]
Isn't it supposed to actually center the frame

**Comment by Megamouse** [comment]
no it isn't. that's why said PR was made to begin with.
We wanted to have the frame on top of the app.
it's simple. If you want the frame to be centered; center your app.
In case you really need this to be centered anyhow.... you need to add yet another config entry

**Comment by cybertronicgames** [comment]
OK, good to know that it's not a regression & that the GSFrame was changed to do just that.
