### ISSUE TITLE
Ni No Kuni minor graphical issues with latest versions (tested with 6439)

### ISSUE THREAD

**Issue by Kadaban** [RPCS3/rpcs3#4178]
System: i7 8700k, 1070 running with latest drivers (using Vulkan in RPCS3), Windows 7, RPCS3 0.0.4-6439

The latest couple of versions of RPCS3 (this was tested on 6439) paired with ni no kuni have some kind of shader or texture problem. 

First issue:
![ninokuni-x-ray-texture-bug-6439](https://user-images.githubusercontent.com/5698994/36314409-0fc98254-1335-11e8-93d8-a0edfb1afb4b.jpg)
Notice the weird "lines" on the blondes heads which are actually present pretty much on all models but harder to spot in other places. These graphical glitches actually move with the character and are projected onto them. It even looks like you can see the lines move with their mouth movement but it's hard to make out. This glitch happened shortly after the game giving you a visual hint which could have been an overlay messing with everything later on. <strike>The bug itself didn't resurface yet and after saving, quitting, reloading, the bug didn't show itself again.</strike> Nevermind, this is present in <strike>at least all ingame cutscenes</strike> nearly everything ingame resembling an player character or NPC now. It also seems to ignore z-buffer restrictions as it's possible to see the glitches from a character model behind another model in front of the camera.

Second issue:
![ninokuni-border-shader-bug-6439](https://user-images.githubusercontent.com/5698994/36314589-94c83874-1335-11e8-97a9-b234a3c8b4ab.jpg)
This looks awfully close to what the actual graphical representation is on the ps3 with the black cel shading border around the characters (and I'm of course all for that!). Notice that Kublai (the guy in the back) has the border shading around most of his body. This could be making the scar on his face a tad too dark (reference here: https://i.ytimg.com/vi/f4MY7o_6Cfs/maxresdefault.jpg). Also take a look at Olivers hairline: It it's drawn with the border when kublais character model is behind him but stops where the model in the background stops. This behaviour is constant in contrast to the first issue.

If there's anything else that could help with identifying the problem

**Comment by kd-11** [comment]
Note: The borders were completely absent before and have now started partially working. This is an improvement, not a regression. Given that they are only now appearing hints at possible spu rendering for them.

**Comment by Kadaban** [comment]
Maybe I didn't make myself clear with the description: I'm all for the borders!
It's just that the other glitches are kinda distracting so we're trading one thing for another and as you can see from the image the borders aren't completely drawn in for all the characters, so we're only half way.
I do of course treat this "bug report" as super low priority and merely as a reminder as to what works and what doesn't as I can image the devs (including you kd-11) don't have the time to play all the games to check the progress all the time.

**Comment by tomventom** [comment]
@Kadaban Sorry for spamming here, but I've been trying to reach you! It's wafflecat, hit me up on Discord 
wafflecat#6798

**Comment by kd-11** [comment]
Both issues are likely just one bug where the cell shading algorithm isn't detecting edges properly. This pass is run on the cell itself.

**Comment by Relsig** [comment]
Just to add a bit of description, the lines have a rhyme and reason. it appears to be outlines of objects that a graphics designer would have z-culled, which is strange because you'd expect it to outline the opposite (only items that are actually displayed)


I took the liberty of downloading kadaban's picture and pointing a few things out

![ni no kuni 2 graphical issue1](https://user-images.githubusercontent.com/8096354/36610357-9f58935a-1895-11e8-9af7-b3a5254b2e2a.jpg)

1 ->  given the camera angle and the direction the character is facing it's likely that is an outline of the not visible side of her face

2 -> not visible side of her skirt

3 -> really obvious it's an outline of the not visible collar spikes

4 -> equally obvious that it's the portion of his body that's under his cloak.

it gets a bit crazy near the hair/face and at weird angles but given how many of the lines are easily attributed to this it's fairly likely that they all are.

**Comment by kd-11** [comment]
Fairly certain this was fixed already. Ask to reopen if not.
