### ISSUE TITLE
Double-click to fullscreen mode cause crash on Vulkan (any game)

### ISSUE THREAD

**Issue by isshininu** [RPCS3/rpcs3#4222]
Nvidia driver is 381.89-38**8**.**, Vulkan version affected:
1.0.42.1
1.0.54.0
1.0.61.0 (only several latest revisions of driver with 1.0.61.0 are not affected, 1.0.65.1 are not affected at all _yet_)

Symptoms: game runs normally in windowed mode, doubleclick causes crash with following error
·F 0:01:53.492774 {rsx::thread} class std::runtime_error thrown: Driver returned 0 images for swapchain
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\VKHelpers.h:1339)

I believe this bug report can exist.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1760625/RPCS3.log.gz)

**Comment by kd-11** [comment]
Retest if its fixed with newer driver revision. Does not happen with driver 388.59 for me.

**Comment by isshininu** [comment]
388.59 is really unaffected AFAIK

**Comment by AniLeo** [comment]
Seems irrelevant if it's fixed on newer drivers

**Comment by kd-11** [comment]
Well, the original bug is about the nvidia driver refusing to provide swapchain images after already accepting to generate the swapchain with a minimum image count (spec mandates at least 1 image to be provided). I think its a driver bug that they have fixed. The only thing would be to have rpcs3 show an error and then stop drawing anything but there is no guarantee that the driver would actually recover properly. If current drivers fix the problem then close it as fixed by the IHV.

**Comment by isshininu** [comment]
Closed.
