### ISSUE TITLE
Feature Request: The Virtual File System to also read the data folder.

### ISSUE THREAD

**Issue by vsub** [RPCS3/rpcs3#4224]
When I want to try some newer beta,I just extract it and set the Virtual File System to where my old RPCS3 is along with my games and saves.

All works fine exept the data folder.
I have to either copy the 500mb(for now)folder every time or wait for rpcs3 to compile the modules and then the shaders again

I don't know if this is intended behaviour or a bug but it would be nice to read the data folder too

**Comment by VelocityRa** [comment]
Not saying this isn't a bug, but you could also get around this without copying stuff by using a directory link. Windows calls them directory junctions (there's a slight difference but it's irrelevant).
So assuming you're on Windows you'd do `mklink /J data <path_to_old_data>`.

Just don't mistakenly delete it, because you'll delete the original files too, instead use `rmdir`.

**Comment by AniLeo** [comment]
data folder shouldn't be part of VFS IMO since it doesn't exist on PS3, it's emulator utilities folder

**Comment by dio-gh** [comment]
Nonsense request, closeable.
