### ISSUE TITLE
Native UI: Savedata issues with Japanese games (Circle opens and cancels UI)

### ISSUE THREAD

**Issue by Omoinemie** [RPCS3/rpcs3#4262]
![qq 20180309201420](https://user-images.githubusercontent.com/31991443/37207243-14b000a6-23d7-11e8-959d-5f98e8c71914.png)
![qq 20180309201430](https://user-images.githubusercontent.com/31991443/37207248-177fdafe-23d7-11e8-9292-2c6734e7120b.png)

**Comment by AniLeo** [comment]
So what happens when you press Circle? It works here..

**Comment by Omoinemie** [comment]
@AniLeo nothing to show

**Comment by AniLeo** [comment]
Attach a log then, maybe it has anything that tips off the problem

**Comment by samyuu** [comment]
Because circle is both the accept key for the game _and_ the cancel key for the native user interface,
the overlay gets cancelled immediately after being opened.
Until the Japanese control scheme is supported by the native user interface,
it can be disabled under Setting > Emulator > Use native user interface.
