### ISSUE TITLE
[BLES01987] The Witch and the Hundred Knight skips part of intro

### ISSUE THREAD

**Issue by Fwha** [RPCS3/rpcs3#4317]
RPCS3 skips the whole naming process and first minute or so when starting a new game.

RPCS3 v0.0.5-6553-af89b6219 Alpha | HEAD
Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz | 8 Threads | 15.96 GiB RAM | AVX+ | TSX

Here's my log, don't know how much that'll help. I think it's just failing to load the script.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/1836078/RPCS3.log.gz)

**Comment by dio-gh** [comment]
Cannot reproduce with `RPCS3 v0.0.7-8852-e9ea226e Alpha`, the underlying issue has probably been fixed since. This issue can be closed.

![image](https://user-images.githubusercontent.com/10439488/66597445-4915be80-eb9f-11e9-891d-192be4a27dd4.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3714099/RPCS3.log.gz)
