### ISSUE TITLE
RPCS3 Tekken 6 - Slow issue

### ISSUE THREAD

**Issue by FairyFaver** [RPCS3/rpcs3#4368]
https://youtu.be/8RJR9TzER2U - I uploaded a recording for further presentation of the problem.
Describing the issue; when I use the XAudio2 Audio Out, the game pauses after Loading Compiled files, then I can resume it to continue, then the rest of the game bugs. When I use null or OpenAL, the game goes smooth in the beginning but the sound is very buggy, either no sounds, or actually broken sounds. And then rendering models are actually way too slow. Is it my PC is too slow to run this or something else? I can't find any solutions anywhere!
Been searching from 12AM until now but I found nothing to fix this issue for RPCS3 Tekken 6. Don't really know why.
Specs:
Windows 7 Ultimate Service Pack 1
Processor: AMD A8-7650K Radeon R7, 10 Compute Cores 4C+6G
4.00 GHz
RAM: 8.00 GB (6.95 usable)
System type: 64-bit Operating System
Video Graphics Card: NVIDIA GeForce GTX 1050 Ti (4GB)

**Comment by Zangetsu38** [comment]
it is normal, you have very bad apu

**Comment by AniLeo** [comment]
This is not an issue, it's a support request since you're incorrectly setting it up plus your CPU is way below recommended specifications.

---

**Please read [**the guidelines**](https://github.com/RPCS3/rpcs3/blob/master/CONTRIBUTING.md) before opening an issue.**

Remember that the GitHub Issue Tracker is not the place to ask for support or to submit Game Compatibility reports. You must use [**our forums**](https://forums.rpcs3.net/forum-18.html) for that.

The issue has been marked as **Invalid** and closed.
