### ISSUE TITLE
Kingdom Hearts 2 and Birth by Sleep Observations

### ISSUE THREAD

**Issue by ArisKallergis** [RPCS3/rpcs3#4391]
Hello! These days I am running a kingdom hearts marathon and have made some observations.
Right now I am trying to get Birth by sleep (BBS) to work correctly. I have the european version of KH 2.5 Remix.
I'm using an Asus Rog G751 JY laptop.
Windows 8.1
i7 4720hq , 16GB RAM, GTX 980M

The things I'm talking about for BBS can be tested right in the opening cutscenes.

Using rpcs3-v0.0.5-6633-b0352d6e_win64: 
openGL renderer does things very slowly for me, but without graphical issues. 
With Vulkan, in the fourth cutscene (press start and skip scene three times), where Ventus is falling, there are some flickers to black and back, which become a lot more apparent in the next cutscenes. When I first get control of the character, framerate is a-ok, but when looking in 1st person mode, the same flickers happen. 
Write color buffers and/or disable vertex cache didn't do anything about it.
Trying strict rendering mode, the game freezes exactly at that fourth cutscene I mentioned above (I believe it might be right when it changes to the point where the flickers would happen).

I tried using older versions of rpcs3, to see if the flickering problem would be solved. 
The problem persisted backwards to rpcs3-v0.0.4-2018-02-23-ede76033_win64, BUT
it wasn't there when using rpcs3-v0.0.3-2017-10-09-6d6b2812_win64 (this is also the latest version that can play the start of KH 2 with Roxas, without dropping framerates when he is attacking. I think you know what I'm talking about, if not, ask me and I'll elaborate)

Unfortunately the rpcs3-v0.0.3-2017-10-09-6d6b2812_win64 version, has really low framerate even with Vulkan, though interestingly, with strict rendering mode on, it doesn't freeze in the 4th cutscene mentioned above.

Anyway my suggestion is that rpcs3-v0.0.3-2017-10-09-6d6b2812_win64 is a version that could be compared to the newest ones to see if regressions happened. I'm no experienced programmer though, so I may just be calling b*****it. 

Thanks for your work everyone, I'm having a blast these days!

**Comment by lastdance1** [comment]
Specs:
Windows 10
Intel Core i7-6820HK @ 2.7GH
Nvidia Geforce GTX 980M, driver version 391.01 (current)
32 GB of RAM.

RPCS3 version:
RPCS3 v0.0.5-6648-ea82b732a Alpha 
Intel(R) Core(TM) i7-6820HK CPU @ 2.70GHz | 8 Threads | 31.96 GiB RAM | AVX+ | TSX

My finding were consistent with @ArisKallergis. However, i found that when setting the default resolution to 720x576 and dropping my resolution scale to 50%, that this "solved" the problem in an unpleasant way. I would suggest that perhaps this it being caused by the games history as a psp game and having a natural resolution of 420x216. I'm not sure what caused the change between earlier versions of RPSC3 working and the current version not working, but _seems_ related to resolution scaling.

**Comment by dio-gh** [comment]
Checked with `RPCS3 v0.0.7-8852-e9ea226e Alpha`, I can't reproduce any of these issues. Both backends are speedy (although OpenGL **is** a touch slower, by about 5 fps), and I didn't notice any kind of black flicker nor in the mentioned 4th cutscene, nor in first person view. Using SRM didn't crash the emu on the 4th cutscene either.

As maybe a sidenote, I also noticed that the game doesn't support the current vblank and clock speed override methods, so it cannot be recapped to 60 fps. Shame.

The ticket is closeable.
