### ISSUE TITLE
Kamen Rider Battride War Genesis [BLJS10324]

### ISSUE THREAD

**Issue by 123kikiman** [RPCS3/rpcs3#4415]
The game was loaded but sometimes for over 10-15 minutes sound loss and cannot continue because game not loaded the sound properly

my spec
CPU: AMD Phenom II X4 955 3.2 GHz
RAM: 8GB
GPU: GTX 550 Ti 1GB(GDDR5)
OS: Windows 10 Pro

**Comment by n1dminhd** [comment]
Me too

**Comment by Renzero7** [comment]
Me too

**Comment by dio-gh** [comment]
After playing through the first level of the Story Mode, and then some more after applying all the game updates, I cannot reproduce this issue on `RPCS3 v0.0.7-8852-e9ea226e Alpha`.

Closeable.

**Comment by SirGouki** [comment]
I know this is an old issue, but I just wanted to respond to the last comment, as I had this happen too.  I've played the game with multiple variations of settings and nothing changes this issue.  Part of the problem is that this is not something that *always* happens within a few minutes.  I've had 2 instances where I could play this game for a full day and not get the problem.  Having said that, that majority of the time it happens seemingly randomly.  It does seem to have to do with the amount of sounds happening, as it happens way faster when I'm hitting a lot of enemies or chaining fast moves together in succession.  This has been seemingly confirmed by when I play slower characters it takes longer to happen.  Most commonly, it happens within the first 10-15 minutes, but I've had it take as long as 3 hours to show up.  This should probably be reopened as its still happening even in the most recent build of rpcs3 - RPCS3 Version: 0.0.12-10848-22dc2947 Alpha.  If there's something targetted I can look for I'll help try to narrow it down if I can.

**Comment by Guerdem** [comment]
I tested in the latest build (**v0.0.23-13883-befd7ceb Alpha**⁪) and it's not fixed. It is random, but it still happens very often. It kinda has a solution I guess, setting PPU decoder to "Interpreter (static)" seems solved the problem to me, but performance get worse.

PPU decoder: Interpreter (static) 
https://www.youtube.com/watch?v=IQZIMs-rKu4&ab_channel=Guerdem

PPU decoder: Recompiler (LLVM) - Audio just disappear at 2:56. Sometimes audio just don't disappear, but it is rare. 
https://youtu.be/09DKFe3i2i8

Log about audio issue [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/9087258/RPCS3.log.gz)

IOS: Windows 11 Home Single Language 64-bit
CPU: I5 10400f
RAM: 16GB DDR4
Mobo: Biostar H410MH
GPU: GTX 1650 Super 4GB

**Comment by Guerdem** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10047825/RPCS3.log.gz)

**Comment by Guerdem** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10050102/RPCS3.log.gz)

**Comment by Guerdem** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10057921/RPCS3.log.gz)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10058110/RPCS3.log.gz)

**Comment by Guerdem** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10304936/RPCS3.log.gz)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10304941/RPCS3.log.gz)

**Comment by Guerdem** [comment]
It's kinda useless and all, but I give a try to the "Fixed" mention build, and even that one it isn't solved the problem. I boot the game a first time, initially the music and SFX, but not cutscenes audio already disappear, what is odd, because even in the recent build it really unlikely to happen, it's more an in levels problem, I don't immediately close the emulator, and I give another try, what end up to the sound issue in the first battle.#

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10366808/RPCS3.log.gz) (Old Build RPCS3 v0.0.7-8852-e9ea226e Alpha)



> After playing through the first level of the Story Mode, and then some more after applying all the game updates, I cannot reproduce this issue on `RPCS3 v0.0.7-8852-e9ea226e Alpha`.
> 
> Closeable.

**Comment by Guerdem** [comment]
Here is a log from a recent build. I normally close right after the audio problem happen. 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/10366848/RPCS3.log.gz) (**RPCS3 v0.0.25-14517-310fa712 Alpha | master**)
