### ISSUE TITLE
Left and Right analog keyboard circle approximation issue

### ISSUE THREAD

**Issue by jobs-git** [RPCS3/rpcs3#4461]
The left analog is approximated by wasd keys in keyboard, while we can use two adjacent keys to do 45 degree of the analog, it could not do 22.5 degree, this makes 22.5 degree analog unemulatable at present.

As a test case, we can take Diablo 3>Inventory>select belt or armor

I dont know how nest could it be resolved, but I have 1 idea in mind.Mabye implement 1 key that emulates analog rotation, could be 1degree/200ms for counter closewise rotation then another key for clockwise rotation.

**Comment by Megamouse** [comment]
(that's what controllers are for.)
I guess I could interpolate the rotation so you can get that angle between pressing up and then right, at the expense of responsiveness, but pressing extra keys seems really overkill for that.

**Comment by jobs-git** [comment]
Which ever implementations would be welcome. 

If the delay you mention would not affect the timing that would be great as well! I think some games relies on timings, like GOW1 and 2, but alas, those games was a bit forgiving, so we can easilly register analog rotation from a well timed key presses.

**Comment by jobs-git** [comment]
Which ever the best implementations would be welcome.

If the delay you mention would not affect the timing that would be great as well! I think some game relies on timings, like GOW1 and 2, but alas, those games was a bit forgiving, so we can easilly register analog rotation from a well timed key presses.

**Comment by jobs-git** [comment]
Were there any progress?

**Comment by vsub** [comment]
Ignore if this is not related
I don't know if this is my gamepad fault but for example on persona 5 in wireless xinput mode when I try to move in some combined direction(up+left/right,down+left/right)I am walking instead of running

The only solution I find is to either use mmjoy(I think that was the name)or xinput in wired mode and I can cleary see that there is a difference when I test the analogs in the settings window
