### ISSUE TITLE
E boot failed on KH 2.5 pls help

### ISSUE THREAD

**Issue by HentaiLord69** [RPCS3/rpcs3#4484]
pls help everytime i open KH2.5 in the log it says E boot failed pls help
![image](https://user-images.githubusercontent.com/38706715/39218286-e1d554f8-47f1-11e8-81c3-fd5b6e43654a.png)

**Comment by tlm-2501** [comment]
First: this is not tech support, "pls help" goes elsewhere. The issue tracker is for reporing actual bugs in the emulator, which brings me to the next point...
Second: this isn't an emulator bug. You have a bad pirated copy of the game. Dump your own games, or you're on your own figuring out any problems pirated dumps may have.
Once you have dumped your own copy of the game from your own legally owned PS3 disc following the quickstart guide at http://rpcs3.net/quickstart, then (and *only* then) may you ask for help with getting it running. Even still, you wouldn't be doing it here, this is what our Discord server is for.
All that said, this issue is invalid. Close it.

**Comment by AniLeo** [comment]
smh pirates today can't even do it properly
