### ISSUE TITLE
Insomniac Games Trap issue

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#4516]
Some Insomniac games: Resistance 3, Ratchet & Clank: All 4 One, R&C: Nexus, R&C: QForce have trap error whe you try to run them, like this one
F {PPU[0x1000000] Thread (main_thread) [0x006cd558]} class std::runtime_error thrown: Trap! (0x6cd558)
there was a PR spu events from elad335 it was closed but on early version of PR there was a commit 495883b4 which fixed this error but caused major slowdowns in other games
i made a little selfbaked patch based on this, a minimal set of changes required for games to run, and almost without speed impact

R&C All 4 One
![27](https://user-images.githubusercontent.com/7060586/39635520-6ac14d5e-4fc6-11e8-8802-8ac4944b1a24.jpg)
![28](https://user-images.githubusercontent.com/7060586/39635521-6ae21516-4fc6-11e8-8d38-10cad207b151.jpg)
Resistanse 3 Demo
![29](https://user-images.githubusercontent.com/7060586/39635523-6b014c6a-4fc6-11e8-870a-b4a17d985c14.jpg)
and here's the patch
https://mega.nz/#!KFIHSKKD!y4kegaBv9ZMAK0m6__eZ1zGDkClOamonC7mP0zMvsbQ

Unfortunately as on original PR as on my hacked patch games also could catch Trap, they can run not from first try. Games itslef unfortunately don't reach ingame, they got stuck with driver error issue
Of course i'm not proposing these changes to be commited, please someone take a look

**Comment by TGEnigma** [comment]
A trap is an exception. By ignoring it, you're ignoring an exception thrown because something happened that basically made the game crash. Sadly it doesn't really help find the underlying issue, it only shows how well it does work despite the error mentioned previously. 
As Juhn mentioned, you'd be better off joining the discord and asking for further help there.

**Comment by Xcedf** [comment]
The recent master also has this Trap issue, but applying this hack to master, after latest SPU update seems to fixes Trap, games now start every time you run them

**Comment by isJuhn** [comment]
The reason why these games get stuck is because an SPU lr event isn't fired when it should be. A fix for what these games are doing would be hacky or decrease performance quite a lot. Jarves wrote a patch for ACiT that makes it behave in a way that rpcs3 can emulate. 
This makes the game go ingame but it crashes instantly. these patches can be specific for every ID so I translated it to my EU disc version and also managed to make a similar patch for Nexus. This makes Nexus go ingame and crash also. The same approach could maybe be applied to Insomniac's other games. 
Here's the patches https://pastebin.com/cLe4qfuP

Disclaimer, going ingame will crash your display drivers!

**Comment by isJuhn** [comment]
@Xcedf try [this](https://github.com/isJuhn/rpcs3/commit/0ef4e2ac33e7987629f69ea8969270d1935a315d) commit. It should be able to identify when you need accurate reservation updates, at least for Insomniac games (never seen it in any other games). I can confirm that it works with ACiT, Nexus and Fuse.

**Comment by Xcedf** [comment]
Well yea, i have message in console about accurate reservation update in these games with this commit but it ain't fixes the issue itself

**Comment by isJuhn** [comment]
Interesting, I've had reports about it fixing resistance 3. I'll have to look into the other games and see what they are doing.

**Comment by isJuhn** [comment]
Not sure why it isn't working on your end, QForce trial shows intro for me with that commit.
![image](https://user-images.githubusercontent.com/26828095/41181206-42bf7bfc-6b71-11e8-9717-34077ea41c61.png)

**Comment by Xcedf** [comment]
Applied your commit again and: Interpreter still may work or may trap
llvm: have traps all the time

**Comment by Xcedf** [comment]
Thanks a lot
