### ISSUE TITLE
CPU madness on Windows 7 since build 6817

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#4643]
Checked on Silent Hill: Downpour and here's the performance comparsion screenshots.
Both times player is fully idle at the same place and nothing happens around (it doesn't matter at all, because the same happens in menus too). All 100%-load splashes (with 5-10 seconds interval) are accompanied by several seconds freezes from FPS drops to screen hangings. No caches or smthn compiles during that time.

The emulator settings weren't changed during build update, and they're: Vulkan, LLVM, ASMJIT, SPU Threads: 1, Enable Thread Scheduler, Enable SPU loop detection.

CPU graph on latest build:
![cpumadness](https://user-images.githubusercontent.com/1223276/40382203-58b74872-5ded-11e8-9972-8b56fd5217d7.png)

CPU graph on 0.0.5-6796:
![cpuiscalm](https://user-images.githubusercontent.com/1223276/40382217-61eed59a-5ded-11e8-9207-c9db7abfe602.png)

**Comment by Ellimosudja** [comment]
Same for me.

**Comment by Psycho-A** [comment]
> From the looks of it, you seem to not have enough ram

High ram load is because it keeps about 3000 compiled shaders only, -- if I load less ones, the same CPU issues happens, no changes.

**Comment by Psycho-A** [comment]
I am alone here with this issue? Or it's just SH:D unique regression? As I remember, @isshininu have SH:D, maybe he check and says, how's going on his side? I can't check other games thoroughly because CPU load is maximum already, and FPS is low, and games like "Castle of Illusion" have too small CPU load contrariwise to detect splashes.

**Comment by TheRibbit** [comment]
i5-4670K 4.5GHz, 16GB 2133MHz RAM, R7 260X 2GB GPU, 18.4.1 drivers version, Windows 7 SP1 x64.

https://i.imgur.com/hA9SSPQ.png - 6796 (vulkan) - program compiled stopped at 74, then after some time did +1 and stopped again.
https://i.imgur.com/3FbqC9z.png - current master, 6845 (vulkan) - program compiled doesn't stop counting, till infinity.
but maybe it's another problem, because:
https://i.imgur.com/1FFeDjs.png - 6796 (opengl) - no CPU peaks and no whole OS freezing for 1-3 sec. program compiled 47.
https://i.imgur.com/hunfSjH.png - 6845 (opengl) - at every CPU peak OS freezes. program compiled 47.
I guess I should test every build one by one... 
I didn't go through logs, so I might have missed something.
[RPCS3-6796vulkan.log.gz](https://github.com/RPCS3/rpcs3/files/2038550/RPCS3-6796vulkan.log.gz)
[RPCS3-6796opengl.log.gz](https://github.com/RPCS3/rpcs3/files/2038551/RPCS3-6796opengl.log.gz)
[RPCS3-6845-opengl.log.gz](https://github.com/RPCS3/rpcs3/files/2038552/RPCS3-6845-opengl.log.gz)
[RPCS3-6845vulkan.log.gz](https://github.com/RPCS3/rpcs3/files/2038553/RPCS3-6845vulkan.log.gz)

**Comment by TheRibbit** [comment]
@Ellimosudja @Psycho-A 
What's your PC configuration? Something like this: "i5-4670K 4.5GHz, 16GB 2133MHz RAM, R7 260X 2GB GPU, 18.4.1 drivers version, Windows 7 SP1 x64."

**Comment by Psycho-A** [comment]
I'm checking it on two PCs, first one is
i5-2500 3,5 GHz, 8 GB RAM, GTX 750 Ti, Win10 LTSB 1604 x64
and second
i5-760 3,3 GHz, 8 GB RAM, GTX 760 Ti, Win 7 HP x64
Latest videodrivers everywhere.

Both PCs shows this issue on SH:D which never encountered on previous builds.

**Comment by jobs-git** [comment]
You might be swapping already, cause in me, I got only 600 shaders and RAM is 6Gig+, that was from 2Gig+. We can say that each shader consumes about 6.5 Mb of ram.

So:
600 shaders = 3.9Gig RAM usage
3000 shaders = 19.5Gig Ram usage

Since you only have 8Gig ram, and part of it is used by your system, yet your game needs about 19Gig ram, you will be swapping big time!

The commits you mentioned has implemented spu cache, which I think is a memory thing, overall cpu usage has decreased a bit and the latest master is the fastest rpcs3 build so far, that was from 27fps to 60fps, that was massive! 

So the issue falls into your hw, if you intend to run that 3000 shaders, at least upgrade your RAM. If it did not help then it could be those commits.

**Comment by TheRibbit** [comment]
What about me then? I have no shaders - and even if I had.. I have enough RAM (I tested with other soft running in background, but without it - are ~12GB free RAM for clean game not enough?) Also I have minimally eligible CPU (in terms of quickstart guide), unlike Psycho-A's, but I still have similar problems and behaviour. Only thing that my CPU is actually lacking is TSX (I have only AVX2 support). So if everyone with TSX has no problems with RPCS3, then, I think, it would be time to up "system requirements". But if someone would show up with Haswell (or older) i5 and say that they have none of the reported problems, then I guess we're just out of luck here, ha-ha...
(seriously, I have both infinity shaders compilation and stutters on master. is there something wrong with my PC?)

**Comment by RepeatingDigits** [comment]
I'm getting 100% CPU usage on the latest build (6847) playing Idolm@ster Gravure for You Vol. 9. 
I have 12GB of RAM, so that should not be a problem. Incredible amount of stuttering.
Performance considerably improved after using Battle Encoder Shirase 1.7.7 to limit CPU usage for RPCS3, however.

**Comment by Psycho-A** [comment]
> Since you only have 8Gig ram, and part of it is used by your system, yet your game needs about 19Gig ram, you will be swapping big time!
> 
> The commits you mentioned has implemented spu cache, which I think is a memory thing, overall cpu usage has decreased a bit and the latest master is the fastest rpcs3 build so far, that was from 27fps to 60fps, that was massive!
> 
> So the issue falls into your hw, if you intend to run that 3000 shaders, at least upgrade your RAM or maybe worse your system.

I already told - there's NO difference in how this issue behaves if I load 2000+ shaders or just that 100-200 that were compiled during my check. Btw, the last nVidia drivers solved excessive ram amount for me, and now all shaders always takes about 1200-1500 mb of physical RAM. I have NO any harddisk collisions on these CPU load peaks.

**Comment by jobs-git** [comment]
might be tsx or threads, mine was older cpu only avx but rpcs3 is so fast.

**Comment by isshininu** [comment]
CPU madness?
It looks like my CPU is not affected.
![703](https://user-images.githubusercontent.com/6324523/40585138-6089427e-61be-11e8-9f7f-94205f7f8bf8.png)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2042525/RPCS3.log.gz)

**Comment by TheRibbit** [comment]
Well yeah, 8+ threads is something from another league and much recommended.
Most of the problems with performance always was on 4 core cpus.

**Comment by Psycho-A** [comment]
@isshininu It's SH: Downpour too?
Had you check it during ~5 minutes, for example? As you can see on my graphs, it's real madness.

**Comment by isshininu** [comment]
No, i cannot check this on Windows 7 right now.
My processor doesnt support TSX either.

**Comment by Psycho-A** [comment]
@isshininu Funnily, but Windows 10 shows good results for me to, and even if I set "SPU Threads" to Auto. Seems like there are some difference in how the Emulator manages CPU on various Windows versions... I'll create new issue to pay attention to dev team...

**Comment by Psycho-A** [comment]
Checked on latest master build under Windows 7. Problems weren't gone, and became even worse. The emulator behaves like "SPU Threads" set to maximum, although it always set to "1" or "2" for me, and before build ~6798 these stuttering were noticed only if I set SPU Threads to Auto or >3. Opposite, on Windows 10, Auto SPU Threads leads to better performance. Seems like there were some changes in SPU behavior last time, or it's just broken for now on Windows 7. Please pay attention to this...

**Comment by Psycho-A** [comment]
I recorded two videos that nicely demonstrates what happened to the same game at the same scene after last updates. Hope you find it useful...

Build 6796:
https://youtu.be/CavHL-1PBhI

Current builds:
https://youtu.be/lTqMhDD00qs

**Comment by Psycho-A** [comment]
So, carefully checked all builds since 6796...

https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.5-6817/artifacts
- The first build the stutterings, CPU splashes and performance drops appeared

https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.5-6852/artifacts
- The build which hammered the last nail in the coffin (like on the video above)

**Comment by TheRibbit** [comment]
I have the same results on Windows 7 as @Psycho-A's.
(I tested Unnamed 5, as you can see somewhere above in this thread)

**Comment by Psycho-A** [comment]
Checked more detailed tests, using performance monitor.
It looks like SPU threads interrupts PPU threads in some periods, because I see that SPU takes about 80% of CPU time (other 20% is RSX) while PPU load slumps to completely zero in moments of peak CPU load. Setting "SPU Delay Penalty" to 16 helps this a little, but after couple minutes it becomes useless too.
