### ISSUE TITLE
[Suggestion] Separate Strict Mode functions in Debug tab

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#4648]
We had a talk with kd-11 some months ago (when Resolution scaling feature were implemented), in which there were suggestions to separate Strict Rendering Mode to several options or slider to help games that require SRM because of graphical glitches. 

What about making a compromise mode in which SRM stays where it is, but we might tweak SRM advanced options inside Debug tab? There's third empty column in Debug tab, that would good suitable for placing extra checkboxes there. We can do them inactive when SRM disabled, and auto-reenable them all when user is checking SRM checkbox (just to prevent occasional touches inside tab). 

So, the common behavior will saved for normal users, and extra features will added for advanced users who enabled Debug tab. Such partial control potentially might help with troubled games fixing SRM bugs and keeping Resolution Scaling feature work.

**Comment by kd-11** [comment]
This is doable after some more strict-only paths are promoted to stable so that we do not have a dozen separate options (this can get unmanageable quickly). I'm slowly integrating parts of strict into regular path when they meet 2 conditions:

1. They are proven to work correctly at all times.
2. They offer better performance or performance cost is negligible.

Unfortunately, the first condition means upscaling will never make it into strict mode but if most other paths are integrated, then applications requiring this option will reduce in number. Already in master is memory tagging and https://github.com/RPCS3/rpcs3/pull/4661 allows FIFO reordering in strict mode.

As the number of strict-mode paths goes down, it will become feasible to have a few checkboxes in debug tab separating the functionality. However, we are not there just yet. Many paths will also have to be written to take into account the changes that things like upscaling bring into the system before this is possible.

**Comment by kd-11** [comment]
SRM is now a relic that is almost never required for most games to function properly anymore. As such I feel we can close this.

**Comment by Psycho-A** [comment]
Cool! And I now can confirm it :)
