### ISSUE TITLE
RenderDoc hangs when capturing with Vulkan (build 6847)

### ISSUE THREAD

**Issue by pauls-gh** [RPCS3/rpcs3#4662]
I found that RenderDoc hangs while trying to capture traces for Tales of Vesperia.

I tracked it to the newer builds and it looks like it is caused when the Vulkan Memory Allocator (VMA) is enabled (which is the default setting).

To workaround
- disable VMA (in the debug tab)
- or use an older rpcs3 build before VMA was committed.  (I tested 6784 and it works ok)

Setup
Windows 10, update 1803
RenderDoc 1.0
rpcs3 build 6847

**Comment by kd-11** [comment]
This is not really a bug. Same thing happens with OpenGL if you don't enable legacy buffers. This is not specific to rpcs3 either, you need the same workarounds with any other engine using GL persistent buffers or VMA. The problem is that renderdoc has to monitor every memory allocation to track data, this includes within map/unmap sections and the data blocks are huge. Its why rdc cannot keep up, its a limitation of renderdoc and not a real problem.
