### ISSUE TITLE
Controls don't really work properly.

### ISSUE THREAD

**Issue by Mario3264** [RPCS3/rpcs3#4668]
Details about my computer are the same as my last issue.
Here is my issue: Controls are fairly intermittent and usually don't work. I have to spam a single button sometimes for it to register as a press. I use the keyboard.

**Comment by legend800** [comment]
This 'issue' needs to be closed/deleted.

1) You did not read the instructions before posted this. Do not do that again. 

2) This is not a help forum. This is for REAL defects with the emu. Your weird control issue is only with your setup and I've never experienced this nor seen anyone discuss something like this. This is an issue with your computer and it's inability to run games full speed causing some input latency/misses probably.

3) Don't say 'details about my computer in the last issue'. Again, you're not following instructions. You want me to go dig up some random issue of yours instead of you taking 2 seconds to just copy/paste that info here??

**Comment by Mario3264** [comment]
Sorry, I will do as you say...
