### ISSUE TITLE
Application not opening or responding

### ISSUE THREAD

**Issue by d3v1l401** [RPCS3/rpcs3#4718]
Trying to start RPCS3 and it doesn't show, nor crashes or anything.
In the task manager, the process is active but using 0% CPU, only 28.3 Mb of RAM and no HDD operations.

The origin of the problem is unknown from my standing right now, I do meet the requirements for the software to run:
- AMD Ryzen 7 1700X 
- NVidia 1080 Ti
- 32 GB RAM
- Currently running it on my Samsung EVO SSD
- PS3 update file is inside the folder

I don't have the time to setup the developer environment, but I did run in trough a debugger, it appears the problem is happening in Vulkan API, here's the screenshot.

![a](https://puu.sh/AAHzk/a65827add7.png)

The log files are simply empty, nothing is showing except my CPU info, no crash dumps or anything else:
`
RPCS3 v0.0.5-6905-dde4a9c6e Alpha | HEAD
AMD Ryzen 7 1700 Eight-Core Processor  | 16 Threads | 31.95 GiB RAM | AVX+
`

Just tried to install Vulkan SDK, nothing's changed.

**Comment by kd-11** [comment]
You had an amd card installed and removed it, but the driver is hanging around. There is an icd key in the registry and the driver files still exist meanong you did not wipe your system of the amd driver. Its some kind of driver big where the amd drivers will hang looking for hardware that is not there instead of refusing to load.

**Comment by d3v1l401** [comment]
Thanks a lot
