### ISSUE TITLE
Gamepad on Linux: evdev Analog sticks not working and unconfigurable

### ISSUE THREAD

**Issue by matheusfillipe** [RPCS3/rpcs3#4754]
The problem: Even thought I can use the analogs on other games on the same computer and they work perfectly, the configuring menu doesn't seem to work properly on rcps3 and all gets detected as RZ+ unless if I click on filter noise. Then the buttons are detected but the analogs still doesn't get detected. Even with the left analog moving correctly on that display, the right one only makes a diagonal path.

![screenshot_20180613_172624](https://user-images.githubusercontent.com/24435787/41376201-e6a97e50-6f2e-11e8-8d10-2732f6f59b48.png)

My controller was detected as a event7: microntek usb joystick. 

My OS is ubuntu bionic 18.04 LTS, 64 bits.
Spects: 16 gb ram, nvidia gtx 4050ti, i7 7th gen. 

```
RPCS3 v0.0.5-6934-88b6d5164 Alpha | HEAD
Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz | 8 Threads | 15.53 GiB RAM | AVX+
E HLE: Evdev Calibration: Added axis [ 5 = ABS_RZ = RZ+ ] to blacklist. [ Value = 128 ] [ Min = 0 ] [ Max = 255 ]
E HLE: Evdev Calibration: Added axis [ 2 = ABS_Z = LZ+ ] to blacklist. [ Value = 128 ] [ Min = 0 ] [ Max = 255 ]
E HLE: Evdev Calibration: Added axis [ 1 = ABS_Y = LY+ ] to blacklist. [ Value = 128 ] [ Min = 0 ] [ Max = 255 ]
E HLE: Evdev Calibration: Added axis [ 0 = ABS_X = LX+ ] to blacklist. [ Value = 128 ] [ Min = 0 ] [ Max = 255 ]
```

I've tried many different ways. This was installed from the appimage. I am compiling the current the emulator now i'm my machine and i'll test if the same issue happens. 

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2099796/RPCS3.log)

**Comment by matheusfillipe** [comment]
Well it turns out that the resulting binary I built doesn't even detect my joystick.

**Comment by Megamouse** [comment]
We already analysed this problem in the past.
Most evdev drivers assign axis values from ... let's say... -128 to +128.
They usually use 0-255 for triggers.
Therefore we also assume that in our current implementation as there is no way (known to us) to distinguish between axis and triggers otherwise.
A future implementation will most likely do what we do in the filter noise step, only that it doesn't add them to a hard blacklist but rather treats the resulting dirty axis in an approriate way.

But do not despair, as I already provided a workaround.
In your config dir you should see a file called `evdev_positive_axis.yml`
In there you should see each currently supported evdev axis with `false`.
simply use `true` for all axis that appear in your blacklist, then they will treated as axis instead of triggers.
In your case this would be at least ABS_X, ABS_Y, ABS_Z and ABS_RZ

**Comment by matheusfillipe** [comment]
Worked like a charm! This should be somewhere in the documentation or added on the GUI.

**Comment by matheusfillipe** [comment]
No neither with them both enabled or disabled, or any combination. 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2099967/RPCS3.log)

**Comment by Megamouse** [comment]
does it work when you simply use a keyboard instead of the controller?

**Comment by matheusfillipe** [comment]
yes

**Comment by Megamouse** [comment]
what do you mean with doesnt work? do they move at all?
or do you mean you can't do anything

**Comment by matheusfillipe** [comment]
yes they move, they even moved when my joystick was badly configured.

**Comment by matheusfillipe** [comment]
WORKED. My deadzones were at maximum and i decreased it a bit, now it works.

**Comment by Megamouse** [comment]
ok good, glad I could help.
can you please close this issue now that we sorted all out?
