### ISSUE TITLE
Wrong textures glitch in Persona 5 [0.0.5-6975]

### ISSUE THREAD

**Issue by Tymec** [RPCS3/rpcs3#4786]
It randomly happens after a while of gameplay on 0.0.5-6975.
It's really similar to #4298, but with textures not color.

Hardware:
CPU: i5-6600k
GPU: GTX770
OS: WIN10

![prtscr capture](https://user-images.githubusercontent.com/2727109/41670754-6e514ec4-74b5-11e8-81fa-dfc8fc99266a.png)
![prtscr capture_2](https://user-images.githubusercontent.com/2727109/41670755-6e70cce0-74b5-11e8-8f01-36505a36ddbd.png)
![prtscr capture](https://user-images.githubusercontent.com/2727109/41672042-2994ef1c-74b9-11e8-97d8-c9f8fb49b87a.png)

**Comment by ruipin** [comment]
As you say, this is being tracked inside #4298 since it's very closely related to it. See the various discussions inside it regarding swapped textures. Might be better to add your voice to that issue instead of creating a new issue.

Most of these texture swaps are related to conservative texture memory protection, and as such aren't necessarily a bug, but more that RPCS3 will try to get extra performance by not write-protecting all texture pages unless you enable strict rendering mode.

You can use a custom build that forces full-range texture memory protection even without strict rendering mode (which is the only required piece of strict rendering).

Note that there is a bug in this (which I have been unsuccessful in tracking down further, we'll have to wait for kd-11) which I can easily trigger in the Velvet Room and cause Persona textures to swap. It can also rarely occur outside the Velvet room.

https://github.com/ruipin/rpcs3/commit/dbcbc913f3f3a824680ea8962a291924c02fc7ee forces full-range protection on and adds a work-around for the aforementioned bug. Note that it is likely that the workaround is system-specific (this is likely very much timing-related) so YMMV.

**Comment by Tymec** [comment]
I see. Good to know that it's not something related to my PC.
