### ISSUE TITLE
Vulkan Renderer: Resolution Scale works only on first boot, ignored on subsequent boot

### ISSUE THREAD

**Issue by rdeleonp** [RPCS3/rpcs3#4815]
## System info

- Radeon Software Version - 18.6.1
- Graphics Chipset - Radeon (TM) RX 480 Graphics
- Windows Version - Windows 10 (64 bit)
- System Memory - 32 GB
- CPU Type - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz

## RPCS3 Version

- RPCS3 v0.0.5-7005-b9fd6ad37 Alpha | HEAD

## Steps to reproduce/compare

**GPU Renderer - OpenGL**
- Boot any game.
- On first boot, Resolution Scale works.
- On subsequent boot, Resolution Scale works.

**GPU Renderer - Vulkan**
- Boot any game.
- On first boot, Resolution Scale works.
- On subsequent boot, Resolution Scale does not work.

Attaching logs:

- [OpenGL first boot Resolution Scale works](https://github.com/RPCS3/rpcs3/files/2132844/OpenGL.first.boot.Resolution.Scale.works.zip)
- [OpenGL regular boot Resolution Scale works](https://github.com/RPCS3/rpcs3/files/2132845/OpenGL.regular.boot.Resolution.Scale.works.zip)
- [Vulkan first boot Resolution Scale works](https://github.com/RPCS3/rpcs3/files/2132846/Vulkan.first.boot.Resolution.Scale.works.zip)
- [Vulkan regular boot Resolution Scale does not work](https://github.com/RPCS3/rpcs3/files/2132847/Vulkan.regular.boot.Resolution.Scale.does.not.work.zip)

**Comment by kd-11** [comment]
Cannot confirm. Scaling works consistently here. The easiest way to check would be to use 50% scaling. Muddy results are more easily observable than trying to discern upscaling.

**Comment by rdeleonp** [comment]
@kd-11 / @MSuih 

Thanks for replying.

The difference is visually discernible.

I'm attaching the screencaps for first and regular boot using Vulkan.

Sorry if it's a silly question, but, for the 50% render test, what is it that I should look for, or what should I provide?

Thanks in advance.

**Vulkan first boot screencap:**

![vulkan first boot screencap](https://user-images.githubusercontent.com/20749249/42012623-db8a16c0-7a5e-11e8-9f74-fca6d925d82d.jpg)

**Vulkan normal boot screencap:**

![vulkan normal boot screencap](https://user-images.githubusercontent.com/20749249/42012790-8d4ef8f8-7a5f-11e8-9bb0-c2e9ea6a1d25.jpg)

**Comment by MSuih** [comment]
* Do two test runs, one at 50% scaling and one at 100%. Take a screenshot from each run when you encounter (or should encounter) the problem.
* If the resolution scaling doesn't work then the two screenshots should look identical. 
* If the one with 50% scaling still looks worse then the problem is not with resolution scaling but probably with the way Qt handles fullscreen.

Before anyone can attempt fixing the issue they'd first need to identify where the problem is. It could be related to resolution scaling or it could be an issue with fullscreen stretching the scaled image.

Also, if it is possbile try taking screenshots when the game is rendering 3D content (i.e. ingame). Logos and intro sequences are usually prerendered and thus resolution scaling can't do much to them.

**Comment by rdeleonp** [comment]
@MSuih 

Thanks for the guidance.

I tested on windowed mode at 100% and 50%, and there is indeed a difference, so Resolution Scale seems to be working.

**100% scale:**

![100](https://user-images.githubusercontent.com/20749249/42065506-d5e5a516-7b00-11e8-9fe7-8315e3752de0.png)

**50% scale:**

![50](https://user-images.githubusercontent.com/20749249/42065511-da590fe8-7b00-11e8-86dd-092e84189c42.png)

Indeed, it seems to be something related to fullscreen stretching, but only on boot. When setting full screen mode, on boot, the game immediately looks blocky, but when I un-maximize it fixes itself; then, I maximize again and it still looks as it should (not blocky).

Is this considered a bug? What would be the next steps?

**Comment by MSuih** [comment]
Yes, it's a bug. If you want to keep this report up you should modify the first comment to be more accurate as this isn't a bug with scaling. But I'm not sure how useful this report is since fullscreen has been broken for ages and nobody seems to be interested in fixing it.

Based on my own testing, the blocky graphics issue happens when window is maximised while shaders are being loaded. I'm not sure why it doesn't happen for you during first boot, but it could be that the first boot takes longer and the emulator hasn't had time to reach shader loading at that point. Also there are 3 other unintended results that can occur when going fullscreen and which one of them occurs depends on luck and the exact moment you go to fullscreen.

**Comment by rdeleonp** [comment]
@MSuih 

Thanks. I'll close this issue and create a new one with the complete information. Then I'll just link to this issue for reference.

Cheers.
