### ISSUE TITLE
SPU cache builds every game launch

### ISSUE THREAD

**Issue by Psycho-A** [RPCS3/rpcs3#4834]
In latest builds everytime we're launching game, the SPU compiling process goes, no matter, SPU ASMJIT or LLVM. Spu-§safe-v3/v4.dat files are created and updates, but seems like they doesn't read next launch. All RPCS3 settings tried to set to defaults, and I can't find some control that manages this. Moreover, number of functions growths with every next launch, f.e. there were ~56000 functions, but next time I see already ~61000 ones.

**Comment by Nekotekina** [comment]
If the cache keeps growing to insane size (let's say 100000), it's the unsupported engine at the moment, and the best solution for it is to delete and disable SPU cache for this game.

SPU cache can't really be compared to PPU cache.
ASMJIT doesn't have a possibility to save native executables for the next run, so it'll have to be built on every launch forever.

**Comment by Psycho-A** [comment]
@Nekotekina How can I disable SPU cache then?

**Comment by Nekotekina** [comment]
Sorry, it's currently only in config.yml as ``SPU Cache: true``. SPU cache contains original code which is read from the file and recompiled at startup.

**Comment by abbradar** [comment]
I can confirm SPU cache gets rebuilt each time when a game has LLVM recompiler enabled for SPU decoding. It happens with a HDD game but not with a disc game.

**Comment by Necrosan** [comment]
Confirming this bug. Cache gets rebuilt each time with LLVM recompiler enabled for SPU decoding.

**Comment by VelocityRa** [comment]
@Necrosan Thank you for necro-ing with 0 new information.

**Comment by vsub** [comment]
I don't know if this is currently expected behaviour but I am playing Atelier Shallie on 0.0.5-7161 and here is my testing result.

SPU ASMJIT with no cache file created and cache disabled:
The game loads fast and also all areas entererd for the first time,but the only problem is that during some skills execution in battle(they are just few),the game speed goes down and also the sound.
If that don't botter you(they are not that annoying),you can just play the game with ASMJIT

SPU ASMJIT with cache enabled:
The game works the exact same way with the slowdowns and buring the game startup,the cache is compiled for 1-5 seconds(depending on how big it is)and but you don't get anything from that,just making the game start slower

SPU LLVM with cache enabled and already created:
It can take WAY too much time to compile the spu cache depending on how big it is(when you go to all the places and load all of the sound effects and music,the cache size is around 5000-6000 and with a size in SAFE mode of 1mb and it takes around a minute to boot)

SPU LLVM with cache disabled and the cache file deleted:
You can call it PS3 slow loading,you just have to start the game and 
Wait sew seconds before the game intro appear(you can rename the opening.pam to make the game load faster...if you already skip it like a billion times)
Wait sew seconds after you load your save.
Wait few seconds when you get close to shallie in the ship(the game loading icon appear)
Wait few seconds when you go to the end of the town and go near Wilbell(the game loading icon appear again)
And wait few seconds when you enter in battle and use a skill

It may look much and you can say that that "Wait sew seconds before" can be translated to the time you wait during the cache compilating but it is definetly not(the time needed during the cache compilation is at least twice more)
After that the game works perfectly fine...untill you restart it(you have to go thru all that again(it's like this is the price you have to pay to use spu llvm and down get those slowdowns)

PS.This probably expected but disabling the cache don't prevent loading it,so if a file exist,it will be loaded and you will get those slow compilation times(it says that the file will not be deleted)and even if the cache is disabled and the file don't exist,an empty file will be created.

**Comment by AniLeo** [comment]
Can probably be closed, anything remaining to be discussed? Games that previously cached SPU objects forever no longer do on master builds.

**Comment by AizerMortenort** [comment]
sorry but i get spu cache build everytime i lauch my games with "master" builds
