### ISSUE TITLE
Feature Request: Set rpcs3 to low priority during the first time modules compilation

### ISSUE THREAD

**Issue by vsub** [RPCS3/rpcs3#4840]
This is a low priority because you are not doing this every day but when you start a game for the first time rpcs3 totally takes over the pc\laptop,you can't do anything during the compilation progress.

I know that there is an option to set the cores used during that time but setting rpcs3 process to low priority during that time,still allows you to use your pc\laptop(I don't even notest that rpcs3 is compiling modules when I set it to low priority even if it's set to use all cores(4+4HT)

That option can also be removed(setting the cores used....less options)if rpcs3 is set to low priority during that time

**Comment by nitrohigito** [comment]
Please don't, or at least make it non-default and optional. I'd shoot myself if I had to wait n times longer just so it wouldn't take up as many system resources.

Most of the time I launch a game, I actually *do* want the compilation to max out my pc, because I want to play the damn game asap, or know if it fails.

By the way, I doesn't throttle my PC much at all, nor on my desktop (i5 4440), nor on my laptop (i7 7700HQ), so you might have some other issues lingering around.

**Comment by vsub** [comment]
You will not wait n times longer if you just wait like you alway do because you are not doing anything else that will make the cpu work less harder on the current task(creating the llvm modules)
Rpcs3 is taking over the laptop/pc so hard that sometimes even the mouse freezes untill it's done

The laptop is with 6700hq on win10 and the pc is wth 4771 on win7 and both are acting the same way

**Comment by Nekotekina** [comment]
Why you don't just set 6 or 7 threads?

**Comment by vsub** [comment]
Creating 30 ppu modules

Normal - 1 minute and 25 seconds...mouse freezes from time to time and you can barely do anything
Idle while waiting - 1 minute and 25 seconds...the mouse don't freeze at all
Normal with 6 cores - 1 minute and 35 seconds while just waiting
Normal with 6 cores while using firefox - 1 minute and 40 seconds...firefox is running little slower
Idle with 8 cores while using firefox(doing the same things) - 1 minute and 35 seconds...firefox is running as if rpcs3 is not running

So as you can see,there is no difference idle vs normal if you are going to be waiting anyway

**Comment by Megamouse** [comment]
I dont think 10 seconds matter to you if you surf the fox anyway

**Comment by Megamouse** [comment]
And you didnt post the interesting idle low priority compilation anyway

**Comment by vsub** [comment]
Sorry,by "Idle" I meant Low priority(that's how it's named in Process Hacker(I use it instead of the windows task manager))

The point was not the time but the usage and if that change is done,then one less option in rpcs3.
If you choose to wait like now,there will be no change in the time needed

**Comment by jobs-git** [comment]
well for me i want it set to Real Time always.

**Comment by vsub** [comment]
And kill windows/get bsod(probaly)...I wouldn't even dare change it to High considering what I see on normal,let alone real time

**Comment by Megamouse** [comment]
The thing is. There are more use cases in which you want to set the nr of cores than just browsing.

**Comment by jobs-git** [comment]
but regardless, 

1. the program setting the priority it self is not a standard subroutine

2. user that are not admin could not start rpcs3

3. Others want rpcs3 running full extent possible.

**Comment by Megamouse** [comment]
People would add an option for that too. So we would just trade one for another

**Comment by vsub** [comment]
Well considering the difference,I would prefer choosing the priority than choosing how many cores rpcs3 uses during that time.

**Comment by Relsig** [comment]
@jobs-git

1. Both windows and Linux have an API for it.

2. Lowering process priority doesn't require admin. Afaik on windows you can also increase it to anything that isn't real time without privileges, though I haven't tried.

3. Lowering the process priority of rpcs3 during the initial compile/load shouldn't affect you in any significant way if you aren't interacting with your computer. 

Lowering process priority is the better solution, here's why: 

1. Anyone who has restricted cores so that they can actually operate their computer during the initial compile/load will -always- have reduced performance during those times vs only when they need to.

2. Anyone who hasn't probably won't notice the 1-2sec lowering the priority -may- cause during that initial load time but will appreciate being able to use their PC if they need to.

3. The system will be more stable during that compile time.

The best solution though? Use both. They're not mutually exclusive.

**Comment by yeeeeman** [comment]
Compilation of shades doesn't freeze my machine (6700hq). I can move the mouse as usual, even do multitasking. So you either have low specs or some software/driver issues.

**Comment by Relsig** [comment]
@yeeeeman Has nothing to do with shaders. It's the ppu/spu compiles. Currently, if they can, they will max out any threads assigned to them to complete the task and the system won't know that the task isn't as time sensitive as your system running.

We can tell the system to reserve resources (cores) currently but in addition we could tell the system that it's not as important as making sure your system is stable and responsive. In addition it should be trivial to make it only during only those times with no tangible downside.

**Comment by kd-11** [comment]
LLVM compile threads option has existed for quite some time now. You can now reserve cores for other needs if you so desire.
