### ISSUE TITLE
7166 is slower than 7161, by a lot

### ISSUE THREAD

**Issue by niko1point0** [RPCS3/rpcs3#4969]
I tested Minecraft, Spyro Dawn of the Dragon, Sonic Unleashed, and Cars 2.
All of these, while running SPU LLVM in 7166, is much slower than SPU LLVM in 7161
and also crash much more easily

My specs:
Intel i7 7700HQ
8gb ddr4 ram
GTX 1050
128gb SSD

**Comment by Nekotekina** [comment]
Please test intermediate builds to find last working build.
Although it looks like a problem on your side, no relevant changes were done in corresponding merges.

**Comment by vsub** [comment]
It is probably because on 7166 the Accurate xfloat is enabled by default and by testing it now on the latest beta,that option hits hard,it makes the audio and speed go way down

I am not sure if I should create an issue but here is my result on 0.0.5-7180
Atelier Shallie
I have been playing this game(and still play it)for above 100 hours and I can immediately notest if something is different,the emulation is almost at 100% perfect

ASMJIT - the game audio slows down(and the game speed but that is not that visible because can run fine even at 30fps)only while executing certain skills during batte.

LLVM without xfloat - no audio slow downs at all
The performance overlays says that the speed goes down but only during the camera change after a skill llvm without xfloat don't seems to care that the speed is lower,the audio still plays at full speedl
The bad side of not using xfloat is that you can sometimes walk thru walls or walk in invisible paths or on some places while Shallie is running,it looks like she is about to fall but it's not

LLVM with xfloat - you can't go thru walls anymore or fall somewhere BUT,during battle,the audio during or after some skills\effects slows down so much that even goes out of sync and on a lot of places that I know I did not have audio slow dows,I do now

Right now LLVM with xfloat works at least twice worse than ASMJIT(audio\game speed)
Sometimes I see how the fps indicator says full speed but the audio is way below 30fps

And finally,not using spu cache along with using xflot is a bad idea(sometimes the music don't even load or you start hearing some cracking sounds)...even worse with lowering spu thread priority(which I have been using almost all the time on this game with almost no problems at all)

6700HQ
16GB Ram
GTX 1060
WIn10
