### ISSUE TITLE
Some games have fps plummet randomly in-game to 2 fps with RSX error spammed

### ISSUE THREAD

**Issue by legend800** [RPCS3/rpcs3#4971]
In games like Captain America Super Soldier and House of the Dead Overkill (and I'm sure others) after playing for a certain time or hitting certain areas (no solid repro), the fps tanks to 1-2 forever with this RSX error spammed:

E {rsx::thread} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x50300FB0 x3
E {rsx::thread} RSX: Dangling reports found, discarding...
E {rsx::thread} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x50300FB0 x2
E {rsx::thread} RSX: Dangling reports found, discarding...
E {rsx::thread} RSX: nv406e::semaphore_acquire has timed out. semaphore_address=0x50300FB0
E {rsx::thread} RSX: Dangling reports found, discarding...
etc

This issue has plagued at least Captain America for a long time and was more frequent months ago. While it's less frequent it still happens a lot making it near impossible to get through certain scenes

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2280704/RPCS3.log.gz)

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by vsub** [comment]
Sorry about the spam but I have yet to find a game that spams non stop and I wanted to know if doing this have any effect on the speed.
In pcsx2(Onimusha 4)and citra(some games),the game spams in the console so hard that the speed goes way down and if I disable the logging or reduce it to something like fatal errors,the speed is restored.

So since I always keep mine on fatal errors in rpcs3,I was wondering if you will get your speed back if you do the same(yes I know that this will not fix the main problem but sometimes the log contains just spam,nothing usefull)
PS.I also set the RPCS3.log file to read only(I know that this way you can't post a log about the problem you have but I keep it like this because I don't need to...at least for now)

**Comment by legend800** [comment]
I don't know know how to adjust logging level in rpcs3 (or if you can) and RO on the log doesn't work since it creates it new every time. I think this is more of a functional issue then the log spam causing the intense slowdown anyway.

**Comment by vsub** [comment]
Right click in the console and choose Fatal
And about the log file...it works here,the file is always 0kb and that's not because of the console settings.
RPCS3 still writes a log but in ram and once you close rpcs3,it will also save the log(not possible in my case)and it also makes an archive with it(RPCS3.log.gz)
The file is not created but the archive contains the log probably in "notice" level

**Comment by legend800** [comment]
Thanks for trying but still no change. I'll try the AAA build and see what that does.

**Comment by John-Gee** [comment]
Thank you for this @vsub I was wondering why I wasn't getting anything in the console anymore but never tried right clicks.

**Comment by legend800** [comment]
Looks like some recent RSX changes fixed this. Closing.
