### ISSUE TITLE
Firmware installation (compilation) randomly fails

### ISSUE THREAD

**Issue by dio-gh** [RPCS3/rpcs3#4972]
The title is self-explanatory. Last time I experienced it was at build 7154 and I didn't want to wait any longer with reporting it, since it'll be already cumbersome to get around. **Further investigation is needed to reproduce the issue reliably, as currently that isn't possible.**

Host system contained an i5-4440 cpu, 8 gigs of RAM and ran a Windows 8.1 Pro (x64, build 9600).

*I don't have a picture or log of the crash, if I manage to dig something up or miraculously reproduce the bug, I'll post about it.*

*PS: Yes, I did check PS3UPDAT.PUP's integrity.*

**Comment by Megamouse** [comment]
possible duplicate of #4877

**Comment by nitrohigito** [comment]
@Megamouse i5-4440 has SSE3.

**Comment by Megamouse** [comment]
you're probably missing dev_flash in your directory

**Comment by nitrohigito** [comment]
It was a clean install. This only happened to me once, and I've seen another user reporting similar behaviour over at Discord at #help, roughly a week ago.

**Comment by nitrohigito** [comment]
Funnily enough, I managed to run into this issue again while bisecting builds to tackle some regression. This time I made a screenshot - unluckily, I cannot give you guys a log, since I was dumb, and restarted RPCS3 since. Sadly, it doesnt contain any useful information, so it's only to show you guys a proof.

![rpcs3-firmware-crash](https://user-images.githubusercontent.com/10439488/44004073-ae827f10-9e5c-11e8-85bc-b4c86c95225a.png)

**Comment by nitrohigito** [comment]
Thanks to dumb luck, I managed to reproduce this issue and finally collect a log about it with the current master (0.0.5-7510).

See system info in the original post above.

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2622243/RPCS3.log)

**Comment by dio-gh** [comment]
Closing as it's not sufficiently reproducible.
