### ISSUE TITLE
Skate 3 glitch (new) LLVM SPU xfloat

### ISSUE THREAD

**Issue by niko1point0** [RPCS3/rpcs3#4981]
I tried to explain this glitch earlier, and I explained it poorly. I apologize for that.
When I try to run Skate 3 with RPCS3 7180 with the SPU Decoder and Accurate xfloat, I will always fall through the floor, as soon as I try to jump on the skateboard. Thank you for your time

**Comment by AniLeo** [comment]
The game is now playable, this doesn't seem to happen on the latest master. Please ping for this to be reopened if this is still the case.

**Comment by stickman89** [comment]
Sorry to comment on a closed issue. This bug is still present. Having LLVM Recompiler enabled has always presented this bug for me in Skate 3 and Skate 2. If you can get off your board, you can navigate around the map without issue. 

Is this bug CPU specific, as I don't hear many other people complaining about this anomaly? ...Aside from the above report. 

Let me know how I can help, and what logs I can provide which will assist you. Also, whether you'd like me to file this as a new report, or if you'll simply reopen this issue.

Windows 10 Pro 64-bit
Intel i7 2700k @4.7GHZ
Nvidia GTX 1070 8GB
16GB RAM

**Comment by MSuih** [comment]
It is probably caused by your weak CPU. Many others have been using SPU LLVM in Skate 3 and there haven't been complaints about issue such as yours. Accurate xfloat isn't needed either, so it should be disabled to improve performance.

Skate 3 is known to have some issues such as slowmotion on slow or thread-limited CPUs, this could be another one of those.

**Comment by stickman89** [comment]
I wouldn't say my CPU is weak, it is still very relevant; and hense why I've held off from an upgrade for some time now. Nor do I believe I am thread limited; 4 cores - 8 threads, overclocked to 4.7GHz. Unless this issue is caused by a missing instruction set that SPU LLVM, or should I say 'Accurate xfloat', is dependant on, which newer architectures offer; then perhaps I can provide logs that help intrepret where this anomaly stems from? Surely that in itself helps to better code, and emulation compability. Anyhow, after some more investigation, I realised that yes; this is only a problem with 'Accurate xfloat' enabled. This bug does not appear with SPU LLVM enabled and 'Accurate xfloat' disabled.

**Comment by eatkinola** [comment]
Yes I have the same problem on a 5600g; disabling Accurate xfloat fixes the problem. Thanks!

**Comment by eM-Krow** [comment]
Bug still present, on a 5950X and 3080. Using LLVM. Overclocked and everything. It's a bug not an issue of a weak CPU.

**Comment by sabs21** [comment]
> Bug still present, on a 5950X and 3080. Using LLVM. Overclocked and everything. It's a bug not an issue of a weak CPU. It is 100% indeed caused by using Accurate xfloat.

I can also confirm this, I'm seeing the same issue with a 5950x and a 3080 ti

**Comment by ineedaham** [comment]
same thing.

rtx 30506gb oc, i5 9600k
