### ISSUE TITLE
Graphics corruption when using SPU LLVM

### ISSUE THREAD

**Issue by ThatAnnoyedGuy** [RPCS3/rpcs3#5012]
When using the new SPU LLVM recompiler, drake's body is partially missing. This issue does not occur with the ASMJIT recompiler.

Graphical settings seem to have no effect on the issue.

- RPCS3 Version: `0.0.5-7221-386e301ea`
- System Specs:
    i7-4790k 4.6GHZ
    Nvidia MSI GTX 1060 Gaming X 6GB
    16GB DDR3 memory 1800mhz
    480GB SSD.
 
I have attached both screenshots and a video. The screenshots naturally just show the graphical difference shown when using either recompiler, the video shows the settings i'm using and two runs of the game up until the graphics issue (which is as soon as it loads in-game)

I'm curious as to how an SPU bug affect anything remotely graphical? It took a while for me to pinpoint the cause of this issue down to the SPU (it was the last place I suspected).

Feel free to ask for further information. I'm happy to do other testing should you need more done.
Thank you

**SPU Recompiler = LLVM:**
![with_spu_llvm](https://user-images.githubusercontent.com/42360887/44316858-fff82d80-a425-11e8-8894-a06f2452abe7.png)

**SPU Recompiler = ASM JIT:**
![with_spu_asmjit](https://user-images.githubusercontent.com/42360887/44316855-fa9ae300-a425-11e8-8291-276a3aad29cd.png)

Video: https://youtu.be/PPw-JLdhZgE  (please watch at 720p, so you can see the text clearly).

**Comment by slashiee** [comment]
Is accurate xfloat enabled?

**Comment by AniLeo** [comment]
It's working as expected, you need accurate xFloat for accuracy if the graphics are broken

**Comment by AniLeo** [comment]
That's why it's a setting. Accuracy costs performance. For now, you're better off using ASMJIT. 

Whenever LLVM SPU is faster and more accurate by default and there's a speed benefit, it will be worth to use for that game.

**Comment by ThatAnnoyedGuy** [comment]
@AniLeo I understand that accuracy costs performance, that's natural.

My concern was more that does the LLVM SPU recompiler have a future to replace ASMJIT in terms of performance if people are going to have to enable extra accuracy settings that result in all of the gains being lost as a result?

We have been hearing that LLVM SPU is the future in terms of performance gains for a while, and whilst I know that it is not finished, having to enable extra settings to get games to work correctly with it that lose all purported gains by doing so is a little disconcerting.

Thank you.

**Comment by AniLeo** [comment]
Not really, it's possible to have better performance and fixed graphics with LLVM SPU on those games by just using some accurate instructions instead of all at the same time depending on the game. Something that will be looked into, as some people already reported on this regarding a few games.

ASMJIT is faster and currently less accurate than LLVM SPU in some of the instructions affected by Accurate xFloat - you can see games like Uncharted 1 where dead body movements are working properly with LLVM SPU and xFloat Accuracy but not SPU ASMJIT.

If you make all instructions completely accurate, the performance will be so slow you won't be able to play games properly. You either have some toggeable accuracy or all accuracy embedded in by default and everything slower including the games that don't need the instructions to be as accurate. It's not just an SPU LLVM thing, no decoder is accurate enough yet, and some accurate implementations of instructions are may have a performance cost big enough to consider having a toggle so that people with weaker hardware can still play games.

**Comment by ThatAnnoyedGuy** [comment]
@AniLeo Sounds like a solid plan.

Thanks for the reply. I am a computer programmer, so I'm aware of the challenges of accuracy vs speed. 
Should I close this, or do you wish to keep it open to track the issue?

Or feel free to close it yourself if you wish.

Thank you and keep up the great work RPCS3 team :)

**Comment by AniLeo** [comment]
Can you retest with the latest build without Accurate xFloat? Approximated xFloat is now the default, which balances speed and accuracy.

**Comment by AniLeo** [comment]
Likely not an issue anymore, retest

**Comment by niko1point0** [comment]
I am pretty sure this is no longer an issue. I’ve seen YouTube videos of uncharted working fine with LLVM.
