### ISSUE TITLE
Setup Continuous Integration for MacOS

### ISSUE THREAD

**Issue by kvark** [RPCS3/rpcs3#5015]
There is code for MacOS builds, the freshest update being #4996. However, it breaks often, and one can see it by the number of issues in the bug tracker related to MacOS builds. We need to setup TravisCI to test those builds, and preferably build it with and without Vulkan support.

**Comment by hcorion** [comment]
We already have the code for Mac builds in our .travis.yml, but I've been wary about wasting CI time on it because you can't do anything with RPCS3 on MacOS and thus have almost no-one compiling on Mac, at the time.
With portability using RPCS3 for testing though I would be willing to enable MacOS for travis.

**Comment by niko1point0** [comment]
I heard a rumor that Mac OS Mojave will not support OpenGL, I hope this isn’t a major problem for the RPCS3 developers

**Comment by kvark** [comment]
@niko1point0 Mojave is already out there in public beta, and I have it on multiple machines. It definitely still supports OpenGL :) I think your rumor applies to the *next* MacOS, whatever it's called.

> I hope this isn’t a major problem for the RPCS3 developers

The idea is to run with Vulkan renderer that goes though Vulkan Portability implementation over Metal, so OpenGL is not involved.
