### ISSUE TITLE
[Patreon Request] Reasons to donate

### ISSUE THREAD

**Issue by niko1point0** [RPCS3/rpcs3#5023]
Right now on Patreon, it says that the money donated will go towards full-time development, as well as covering expenses for new hardware that will be used to develop and test the emulator. To encourage people to donate, can you specifically mention what hardware you need, and how it will help you? Maybe someone will be willing to purchase it, and donate it to you.

**Comment by niko1point0** [comment]
Maybe there can be a link that says something like “for more information, click here”

**Comment by JhonLoveJoy** [comment]
IMHO, This has to do with the wide variety of hardware combinations on PC. They need to test the new implementations and bugs on AMD and NVIDIA GPUs, Intel and AMD CPUs, to ensure that everything is worked as well as planned.

**Comment by profzerg** [comment]
> IMHO, This has to do with the wide variety of hardware combinations on PC. They need to test the new implementations and bugs on AMD and NVIDIA GPUs, Intel and AMD CPUs, to ensure that everything is worked as well as planned.

Since this is a software thing, implementations must deal with architectures and API's such as x64, Vulkan and OpenGL. The most powerful rigs u can get, the most stuff u can deal with.

**Comment by Asinin3** [comment]
There's more to it than that. For instance certain GPU architecture can have different issues and kd-11 may need to debug an issue that for instance only affects GCN1.

**Comment by profzerg** [comment]
The patreon thing is ok for me, just wanted to clarify some nuances to justify hardware purchases as requested in thread. https://en.wikipedia.org/wiki/Graphics_Core_Next#Microarchitectures.

**Comment by AniLeo** [comment]
API implementation isn't done the same on every architecture, you need to test on different architectures when issues arise because different architectures have their issues, drivers are full of bugs. This was already the case many times so far and it will keep on being, we are not an AAA studio with direct driver team support to get instant fixes. Many emulator developers are waiting/wait for months and/or years for driver bugs to be fixed.

So yeah, kd-11 may buy several cards from different architectures when needed. For now, the team has a wide selection of cards ranging from low end to high end and from different architectures and vendors so we have been able to distribute testing properly.
