### ISSUE TITLE
Please change description of "Lower SPU thread priority"

### ISSUE THREAD

**Issue by niko1point0** [RPCS3/rpcs3#5069]
Right now it says "possibly slower or no difference on i7 or Ryzen". However, I am on i7-7700HQ and I get better performance with Lower SPU Thread Priority turned on, rather than off.

Does anyone else have similar results?

**Comment by Syst3mSh0ck** [comment]
What version of RPCS3 are you using? Are you seeing increased performance across all titles? What are your other settings and your hardware specs? Not enough information. Thanks,

**Comment by Relsig** [comment]
Actually the information he provided indicates that his processor has a relatively low clock speed (2.8 norm 3.8 turbo) and that he is most likely using a laptop. It's possible lowering the spu threads in priority will allow the other threads more time to work in such a case. It's also possible lowering their priority could improve their usage of their thread quantum leading  to less chug and additionally it's possible that it allows him to boost more frequently because other processes idle in that time.

The statement should read "high end processors" instead of I7/ryzen.

**Comment by vietnam13231** [comment]
And for me this option does completely nothing on my i5-4690@3.7GHz (4c/4t).

**Comment by sampletext32** [comment]
First, my VS shows, that Lower SPU Thread Priority currently doesn't affect emulation at all, being just a checkbox in UI and nothing more. 
Second, the tooltip says, that it can degrade performance with no sure of boosting it. 
Third, RPCS3 has changed a lot since issue opening and results may differ now.

So I think, this issue can be closed.

**Comment by AniLeo** [comment]
Yes, it's used
