### ISSUE TITLE
Regression: SRW Dark Prison [NPJB00521] stuck on new game (#4973)

### ISSUE THREAD

**Issue by paperming** [RPCS3/rpcs3#5327]
In the latest rpcs3 version 0.0.5-7491, it stuck during start a new game and keep in black screen, so I some playable setting in youtube for the game but unsuccessful. Then I downloaded the old version of rpcs3 in the playable tutorial which is 0.0.3-5 with same setting, and the game does not stuck and become playable

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2569358/RPCS3.log.gz)

**Comment by Asinin3** [comment]
Since this is a regression report, in order to fix it knowing which build broke this game is very important. If you can, test a ton of builds by jumping back a few months at a time until the game starts to work then slowly narrow it down to a single build which caused the game to break then let us know it would be very helpful. You can find old builds here: https://rpcs3.net/compatibility?b and for builds older than 6 months, check here: https://obk.ee/rpcs3/archive/

**Comment by paperming** [comment]
> Since this is a regression report, in order to fix it knowing which build broke the game is very important. If you can, test a ton of builds by jumping back a few months at a time until the game starts to work then slowly narrow it down to a single build which caused the game to break then let us know. This information would be key to fixing the issue, otherwise this issue is likely to just remain open until it gets fixed by accident. You can find old builds here: https://rpcs3.net/compatibility?b and for builds older than 6 months, check here: https://obk.ee/rpcs3/archive/

found it. It started from 0.0.5-7216 (#4973). Prevous Version 0.0.5-7195 still can play

**Comment by digitaldude555** [comment]
Its been over a year without an update.

**Comment by benderscruffy** [comment]
this can be closed
i have had no problems so far
