### ISSUE TITLE
Idea to improve FPS in games

### ISSUE THREAD

**Issue by niko1point0** [RPCS3/rpcs3#5335]
In many games I've tested, FPS rises when there are less polygons in the scene, and FPS drops when more polygons are in the scene.

Can we have a setting where users can set a maximum number of polygons in the scene, where extra polygons are ignored? This may cause a lot of visual glitches, but FPS will surely boost.

In many games I've tested, like Skate 3, Sonic Unleashed, Minecraft, Uncharted, and Spyro Dawn of the Dragon, FPS rises and falls depending on how many polygons are in the scene.

On the other hand, if we cannot have this feature, can users have the ability to manually adjust viewport? The viewport holds variables for minimum render distance and maximum render distance. I would love the ability to set the maximum render distance to 50% of the original game's render distance, allowing for less polygons to be drawn, and higher FPS to be achieved

**Comment by isshininu** [comment]
Have you tried "Disable ZCull Occlusion Queries" option in debug page?

**Comment by kd-11** [comment]
The supposed options are parts of the software stack, not the hardware stack, so, no, you cannot control things like the frustum because hardware no longer has those fixed function units for a very long time. You also cannot safely just stop drawing things after a certain number of draws; such hacks cannot be added to the emulator. You can use the debugger option to remove occlusion queries and make the games that use that feature believe that nothing outside the immediate area is visible, but thats a debug feature and you get garbage visuals in a lot of cases. If improving fps were that simple, we'd have done it already.

**Comment by niko1point0** [comment]
Ok. Thank you for the information

**Comment by niko1point0** [comment]
Where can I find the debug option to "Disable ZCull Occlusion Queries"?

**Comment by MSuih** [comment]
Enable the debug tab first by opening go to `RPCS3\GuiConfigs\CurrentSettings.ini` and change showDebugTab from false to true. After that you should see a new tab in the settings menu with settings like that one.

And as kd-11 said it will cause broken visuals and even crashes in some games.

**Comment by Ghostotakoi** [comment]
i guess he might mean decrease the shade accuracy, some emulators like dolphin or cemu have that option. in dolphin case is a slide from safe to aggressive and cemu have 3 options, low, medium and high.
**Dolphin**
![screenshot_20181114010622](https://user-images.githubusercontent.com/20958581/48463291-9039da80-e7a9-11e8-9796-2ff9dbe83497.png)
**Cemu**
![screenshot_20181114011025](https://user-images.githubusercontent.com/20958581/48463495-31c12c00-e7aa-11e8-982c-97b7b0ead284.png)

**Comment by kd-11** [comment]
We already have that; this is completely different. You may think of the options in the GPU tab as being similar as they offer the option to avoid heavy performance losses if a game is not using a feature.
