### ISSUE TITLE
Problems with passing files with command line

### ISSUE THREAD

**Issue by QuaiGoner** [RPCS3/rpcs3#5374]
Well, main issue is with the PKG files, that suppost to install first and not just booting. You made a separate menu entry for this files, but when i pass PKG file to the emu it gives me error, because it tries to load it as ELF/SELF file. Is it possible to merge these two menu entries (Install PKG and Boot SELF/ELF) into one (Load Game maybe?) and when it reads file extension as PKG it triggers installation algorithm, but when it anything else it tries to Boot as ELF/SELF file?

**Comment by 13xforever** [comment]
command line only accepts path to executable files to boot, it does not handle pkg/license installation, you'll have to do this manually through UI.

**Comment by QuaiGoner** [comment]
I understand that, but i thought that emu can be made handle PKG files through cmd too

**Comment by nitrohigito** [comment]
It perfectly can be made to, just someone needs to implement it first.

**Comment by Nekotekina** [comment]
It may be problematic because it collides with the ability to pass parameters to the emulated process.
At least the intent should be specified, like `--install-pkg /xx/x.pkg`

**Comment by bevanweiss** [comment]
I think there's no issue with passing the pkg files to install.
Although I'm unsure what happens if the order of the pkg files isn't specified correctly on the command line etc.

I'll have a look at it tomorrow, since it should be pretty simple for a first pass... my idea would be:
rpcs3 --install-pkg="pkg1path","pkg2path","pkg3path" "path\to\boot.bin" --vsync --other-boot-opts
and the packages would be installed first, just in sequence as they are listed.  If there is an error loading a package, then it would return an error code and return to the command line.
