### ISSUE TITLE
SCOTT PILGRIM VS. THE WORLD: THE GAME [NPUB30162] - Excessive Reverb Effect

### ISSUE THREAD

**Issue by xperia64** [RPCS3/rpcs3#5544]
rpcs3 0.0.5-7714-022550a4

In the tunnel section of the second half of the first level (Shopping District), a light reverb effect is supposed to be applied to the audio.
What happens instead in rpcs3 sounds like the reverb effect, but without the proper decay/cutoff needed, so the audio becomes excessively loud and clips.
Correct behavior can be seen here: https://youtu.be/B9ZO_XCSsuQ?t=301
(the footage is from the xbox 360 version, but the audio effect is essentially identical as far as I can tell compared with my real PS3)

System specs: i7-7700k, GTX 1080 Ti, Windows 10
Happens on any graphics or audio backend.
As far as I can tell, it also happens on any PPU/SPU mode.

I didn't notice anything interesting that seemed like it would be related in the log.

**Comment by xperia64** [comment]
The audio buffering setting has no effect.

**Comment by DanteBC** [comment]
Can confirm this issue on master. It has been like that for a while.

**Comment by nbmrjuhneibkr** [comment]
The problem is still present.

I'd also like to add that I encountered what appeared to be an invisible enemy in the same exact part of the 1st level. And I'm not the only one, as evidenced by https://forums.rpcs3.net/thread-178174-post-305192.html#pid305192

Considering that this game is not available on the original platform anymore (and may or may not have worked better in the earlier builds of RPCS3), this needs to be fixed sooner rather than later.
Or, at the very least, it would be useful to know what build of RPCS3 works best with this game.

rpcs3-v0.0.7-8673-aa262889
Game v1.03 (US) + Unlock & 2xDLC
Firmware 4.85

PPU: LLVM, SPU: ASMJIT
OpenGL, 1080p, 60fps limit, Vsync
Disabled Vertex Cache

**Comment by Asinin3** [comment]
retest

**Comment by xperia64** [comment]
Yes, the reverb is still excessive and loud as of rpcs3-0.0.12-10895-9db97278

**Comment by digitaldude555** [comment]
@xperia64 and now?

**Comment by xperia64** [comment]
Yes, still an issue as of v0.0.14-11765-e76d8eb0

**Comment by Yahfz** [comment]
@xperia64 still an issue? Maybe it changed after cubeb was added.

**Comment by xperia64** [comment]
I believe it's still an issue, however I think it may be related to the surround sound downmixing implementation or something else to do with surround sound/whatever audio APIs the ps3 has. I've discovered the game is indeed outputting full 7.1 for sound effects _and_ the reverby area described in the issue.

I recorded the surround channels on their own in audacity and they sound too loud coming out of just that, but idk.

**Comment by xperia64** [comment]
This seems be mostly resolved now?

With the Steam release, I went back to do some comparisons with the PS3 version again, and while the reverb effect may be slightly too subtle on rpcs3 now, it's far better than it was, and I'm calling it good enough until I can be bothered to get an HDMI capture card and record my real PS3.

(and as an aside, I feel like the PC version's audio is broken beyond repair, and that emulating the PS3 version provides a better experience at this time; fewer graphical glitches too).
