### ISSUE TITLE
Ni no Kuni AMD Graphical Glitch with Vulkan

### ISSUE THREAD

**Issue by KillZone** [RPCS3/rpcs3#5561]
I found one bug in Ni no Kun relating AMD GPUs:

 Using the Vulkan renderer causes the visual glitches can be seen in the pictures. In a diagonal line (picture 1, 2) weird colored pixels are flickering. (Note that the other visual glitches can be seen on these pictures are related to the screenshot issue, and they are not important in this one.)
The glitch is not present on all maps for example inside the house the game works perfectly (3). At outside if I stand still it gets somewhat better, but few glitched pixels still changing constantly. 
In OpenGL the problem is not present tho, and if I turn on strict rendering in Vulkan it seems to fix the problem.
![2019-01-16 19](https://user-images.githubusercontent.com/1431347/51250330-56967300-1996-11e9-8c64-2f84fd3505ef.png)
![2019-01-16 20](https://user-images.githubusercontent.com/1431347/51250332-572f0980-1996-11e9-9923-8bde858dd9b5.png)
![2019-01-16 21](https://user-images.githubusercontent.com/1431347/51250331-56967300-1996-11e9-8702-ebe6a0a2ca7b.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/2764273/RPCS3.log.gz)

System specs: Ryzen 1800x, RX 580, 16 Gb RAM, Windows 10 
RPCS3: v0.0.5-7731 Alpha [2019-01-16]

**Comment by Asinin3** [comment]
Diagonal line isn't specific to Ni No Kuni, it's an issue with AMD GPU's due to them using a different raster pattern. Can be fixed by using Strict Rendering Mode or hidden with a high resolution scaling value that is well above your native resolution. If you want to report graphical issues (for the 2nd issue) then we generally require a renderdoc or RSX capture of the scene. A save file at the location would be helpful too if it takes awhile to get to.

**Comment by KillZone** [comment]
I change the title a little bit then to "AMD Graphical Glitch with Vulkan, Screenshot bug" if it's okey.
RSX capture and save:
I took the capture with 4k and the line is still visible, but it moved from the bottom left corner to the upper right. Highresolution scaling does not seem to work in this instance.
[NPEB01158_20190116150011_capture.zip](https://github.com/RPCS3/rpcs3/files/2764452/NPEB01158_20190116150011_capture.zip)
[dev_hdd0.zip](https://github.com/RPCS3/rpcs3/files/2764453/dev_hdd0.zip)

**Comment by Asinin3** [comment]
The diagonal line stuff should be removed, and so should the screenshot issue. Keep this issue just for the NNK visual issue, I'm not sure if an issue for the screenshot issue would be valid but it should be done in its own report anyway. It's not clean to have 3 unrelated issues in one issue. (and the diagonal line issue was closed already since its an amd issue and fixed with Strict Rendering Mode like i said earlier).

**Comment by KillZone** [comment]
There are two issues. One is the diagonal line the other is the screenshot issue, there is no third. 

I have already mentioned the Strict Rendering Mode workaround in my original post, it's just that this way I can't play the game in high resolution since it disables the resolution scale. (Or is it possible to play at higher resolutions with Strict Rendering Mode enabled?)

I will create another issue for the screenshot issue.

**Comment by Asinin3** [comment]
Oh, i saw this screenshot:
https://user-images.githubusercontent.com/1431347/51250953-5e571700-1998-11e9-8188-301cd70d698a.png
and thought you were repoorting the visual issue on the ground there.

**Comment by kd-11** [comment]
Neither of the issues reported here are rpcs3 bugs.
1. Diagonal line is a general AMD issue, use strict mode to fix.
2. Screenshot being outdated: There is nothing we can do about this as the bug is between the screenshot software, microsoft's dwm and the driver vendor. Likely just windows' vulkan integration not being very good, no surprises there.

**Comment by KillZone** [comment]
So there isn't any fix for the grapchical glitch? I use the latest recommended drivers now. This issue seems to be 2 years old on other forums, and it says it should be fixed by the new drivers.

Thanks for the quick replies tho.

**Comment by kd-11** [comment]
Enable strict rendering mode in the GPU options. It will fix the glitch but you lose a lot of extras like high res rendering and anisotropic filter overrides.

**Comment by KillZone** [comment]
Thanks. I will update the issue if I find another workaround to help other AMD users. :)

**Comment by voinage** [comment]
@KillZone , just change the res to 7680×4320 and allow GPU scaling and Vsync. Rpcs3 can handle it without too much issue. The line will be gone without noticeable performance loss.

It's smooth on my rx 580 and r5 2600 rig.
