### ISSUE TITLE
unknown escape sequence: '\S'

### ISSUE THREAD

**Issue by arabek** [RPCS3/rpcs3#5562]
```make
rpcs3/rpcs3/rpcs3qt/osk_dialog_frame.cpp: In member function ‘virtual void osk_dialog_frame::Create(const string&, const u16string&, char16_t*, u32, u32)’:
rpcs3/rpcs3/rpcs3qt/osk_dialog_frame.cpp:77:53: warning: unknown escape sequence: '\S'
    input->setValidator(new QRegExpValidator(QRegExp("^\S*$"), this));
                                                     ^~~~~~~
```

**Comment by Megamouse** [comment]
I'll close this since it makes no sense to open an issue for every single compiler warning

**Comment by Megamouse** [comment]
I'll fix it later anyway, thx

**Comment by arabek** [comment]
Well, it did seem like this is a true bug since the \S escape sequence is being ignored as unknown, thus the qualifier in the regexp isn't working as expected. Thus my report. :)

**Comment by Megamouse** [comment]
I know, sorry. I actually knew that there was an issue with hawx2 where it would only accept S. But I only remembered 5 minutes after i closed the issue. The reason why i closed it was that i tested it before and it worked. But i think i copied a better regexp from stackoverflow afterwards and forgot to test it again, assuming it would work all the same.

Due to your issue I immediately knew where the bug came from. So thanks for that :)
