### ISSUE TITLE
Fast & Furious™: Showdown [NPUB31224] Regression JIT runtime

### ISSUE THREAD

**Issue by thx4ever** [RPCS3/rpcs3#5630]
This game was playable before JIT runtime implementation now it trow a error when try to play

> F {PPU[0x1000000] Thread (main_thread) [0x004f9e90]} class std::runtime_error thrown: Null function
> (in file c:\projects\rpcs3\utilities\jit.cpp:322)
> 

I'm using latest git version 
RPCS3 v0.0.6-7786-a36d3af3 Alpha | HEAD

Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz | 8 Threads | 7.95 GiB RAM | AVX+ | TSX
Nvidia Geforce GTX 1050 2GB DDR5
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/2825140/RPCS3.log)

**Comment by AniLeo** [comment]
This issue is unclear.. first JIT recompiler was added many years ago.
What build regressed this? In fact, the Playable report is made with PPU Interpreter so it's very likely there's no regression here at all.

Will be closed if no proper information is provided (build that regressed this, testing with PPU Interpreter.

**Comment by hch12907** [comment]
Could be commit 4292997, where jit_runtime is mentioned.

**Comment by Yahfz** [comment]
![image](https://user-images.githubusercontent.com/17715080/64065160-68a0eb00-cbe0-11e9-9d86-ef3231518598.png)
Played 3 chapters and couldn't reproduce the issue on master 8620. This issue can be closed.
