### ISSUE TITLE
Game crash when GPU Texture Scaling is not enabled

### ISSUE THREAD

**Issue by uaqlover** [RPCS3/rpcs3#5743]
last build the game was working RPCS3 v0.0.4-6095-222c0e0f Alpha | HEAD

![FPS_ 99 19 _ OpenGL _ 0 0 4-6095 _ CRASH COMMANDO™ _  NPUA80216  19_03_2019 3_35_44 AM](https://user-images.githubusercontent.com/45731484/54599823-b0e49c00-49f8-11e9-8e2e-c4306db8eb48.png)

in this build it break the game 
RPCS3 v0.0.4-6107-380f90b0 Alpha | HEAD

![899999](https://user-images.githubusercontent.com/45731484/54600177-6d3e6200-49f9-11e9-8977-7e1f9bd907b5.png)

the log file 

RPCS3 v0.0.4-6095

[RPCS3 v0.0.4-6095.log.gz](https://github.com/RPCS3/rpcs3/files/2982949/RPCS3.v0.0.4-6095.log.gz)

RPCS3 v0.0.4-6107

[RPCS3 v0.0.4-6107.log.gz](https://github.com/RPCS3/rpcs3/files/2982951/RPCS3.v0.0.4-6107.log.gz)

**Comment by Asinin3** [comment]
So, did you try all the builds after it broke? You're saying that you can confirm the build directly after broke it or what? Because the build directly after is from this PR https://github.com/RPCS3/rpcs3/pull/3038 . We need to know exactly where it broke or else you're basically telling developers to do your testing for you and test builds between now and two years ago.

**Comment by uaqlover** [comment]
last build the game was working RPCS3 v0.0.4-6095-222c0e0f Alpha | HEAD

![FPS_ 99 19 _ OpenGL _ 0 0 4-6095 _ CRASH COMMANDO™ _  NPUA80216  19_03_2019 3_35_44 AM](https://user-images.githubusercontent.com/45731484/54599823-b0e49c00-49f8-11e9-8e2e-c4306db8eb48.png)

in this build it break the game 
RPCS3 v0.0.4-6107-380f90b0 Alpha | HEAD

![899999](https://user-images.githubusercontent.com/45731484/54600177-6d3e6200-49f9-11e9-8977-7e1f9bd907b5.png)

**Comment by Asinin3** [comment]
Great, that's what we need to know. Provide log from the build that broke the game too. The log from 0.0.3 is probably useless.

**Comment by uaqlover** [comment]
here the log file 

RPCS3 v0.0.4-6095.log.gz

[RPCS3 v0.0.4-6095.log.gz](https://github.com/RPCS3/rpcs3/files/2982949/RPCS3.v0.0.4-6095.log.gz)

RPCS3 v0.0.4-6107.log.gz

[RPCS3 v0.0.4-6107.log.gz](https://github.com/RPCS3/rpcs3/files/2982951/RPCS3.v0.0.4-6107.log.gz)

**Comment by AniLeo** [comment]
380f90b0 is #3727
Which doesn't touch rsx_cache

And for the issue to be the PR's ERROR_INVALID_PARAMETER, before that PR the game would have to throw a Win32 error

**Comment by Emulator-Team-2** [comment]
@AniLeo 
The title is wrong this error has been fixed a long time ago. 
On latest master build this games crashes with (Unhandled Win32 exception).

**Comment by AniLeo** [comment]
Can you upload a log for master?

**Comment by Emulator-Team-2** [comment]
Fixed by #5785
Note:
-This game require to enabled `Use GPU texture scaling` in debug settings.
-'GPU texture scaling' was moved to debug setting some time ago because it caused issues in some games.
-Crash Commando has always required this option.

**Comment by AniLeo** [comment]
@kd-11 can you check why this game requires that? weird

**Comment by Emulator-Team-2** [comment]
Note: [ VK and GL texture cache error after enabling GPU texture scaling is fixed by #5785. ]

@kd-11 
Logs from Master:

Without GPU texture scaling:
<details> 
<summary>Win32-error-screenshot</summary>

![Bez tytułu](https://user-images.githubusercontent.com/38318848/55415068-a8e63980-556c-11e9-9e41-9c0579a063e3.png)

</details>

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/3034693/RPCS3.zip)

With GPU texture scaling crashes with:
[Vulkan]
`E {RSX [0x0200504]} RSX: Blit request denied because the source region does not fit!
F {RSX [0x0200564]} RSX: class std::runtime_error thrown: Assertion failed: !region.is_locked()
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vktexturecache.h:967)`
[OpenGL]
`F {RSX [0x0200564]} RSX: class std::runtime_error thrown: Assertion failed: !cached.is_locked()
(in file c:\projects\rpcs3\rpcs3\emu\rsx\gl\gltexturecache.h:858)`
[RPCS3-GPU texture scaling.zip](https://github.com/RPCS3/rpcs3/files/3034782/RPCS3-GPU.texture.scaling.zip)

**Comment by uaqlover** [comment]
with https://github.com/RPCS3/rpcs3/pull/5785/commits/3867400a734deed171acf7bc21f9bded2da26439 still game crashes with (Unhandled Win32 exception). but when enabling GPU texture scaling it works fine

**Comment by kd-11** [comment]
Retest please.

**Comment by Emulator-Team-2** [comment]
Tested with the latest master build (0.0.6-8330) no change.
Still crashes with error (Unhandled Win32 exception) without enabled GPU texture scaling.

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/6164
