### ISSUE TITLE
Lower performance on hexacore CPU when thread scheduler is enabled

### ISSUE THREAD

**Issue by smitdylan2001** [RPCS3/rpcs3#5799]
If I enable thread scheduler on my PC my performance will drop. I've heard that performance should improve, but won't because I have a Hexacore CPU. My specs are listed below. This is tested on v0.0.6-7932-d7ad991b. See added files for logs (thread scheduler enabled and disabled) and screenshots.

Ryzen 5 1600 (3,6 GHz all core)
16 GB DDR4 2666 MHz CL 15
GTX 1080 FE
Asus B350 Prime Plus
Some generic SSD+HDD

Thread scheduler disabled: 
![disabled1](https://user-images.githubusercontent.com/41569500/55683409-bec67680-593f-11e9-98dd-0dacafc4d03f.png)
![Disabled2](https://user-images.githubusercontent.com/41569500/55683320-968a4800-593e-11e9-8361-3828afebe7bf.png)
[RPCS3_TS_disabled.log](https://github.com/RPCS3/rpcs3/files/3051517/RPCS3_TS_disabled.log)

Thread scheduler enabled:
![enabled1](https://user-images.githubusercontent.com/41569500/55683407-b8d09580-593f-11e9-88ec-4326a267838b.png)
![Enabled2](https://user-images.githubusercontent.com/41569500/55683322-968a4800-593e-11e9-914c-8d9c712a5237.png)
[RPCS3_TS_enabled.log](https://github.com/RPCS3/rpcs3/files/3051518/RPCS3_TS_enabled.log)

**Comment by smitdylan2001** [comment]
Edited the photos because it seemed to be mixed up

**Comment by kd-11** [comment]
Looks like x600 class performance has changed quite a bit since ryzen launch - it used to be cripplingly slow with scheduler disabled (single digit fps). Its usually best when compared to a linux build running with scheduler disabled since the linux scheduler is 'perfect' when it comes to loading ryzen CPUs. If scheduler off matches linux then we can remove scheduler effect for all R5s and look into doing something for R7. I have not noticed any large changes on a 1700 but then again I have not done any benchmarking in the recent past. Of course a large sample size of games is required to gather useful statistics for such a thing, so it would be helpful if you could maybe add more comparisons. Would be cool to get feedback from other ryzen owners as well to rule out OS updates or driver versions being a factor.

**Comment by creeperjedi** [comment]
<details><summary>Dead Rising 2 showed a barely noticeable, but present, performance increase when Thread Scheduler was disabled</summary>
Disabled:
<img width="641" alt="Disabled" src="https://user-images.githubusercontent.com/38361979/55687148-9d618c80-5937-11e9-8f4a-294707686acd.png">
Enabled:
<img width="641" alt="Enabled" src="https://user-images.githubusercontent.com/38361979/55687150-a5213100-5937-11e9-9599-0d4a1af26e31.png">

[Disabled.log](https://github.com/RPCS3/rpcs3/files/3051848/Disabled.log)
[Disabled.log.gz](https://github.com/RPCS3/rpcs3/files/3051849/Disabled.log.gz)
[Enabled.log](https://github.com/RPCS3/rpcs3/files/3051853/Enabled.log)
[Enabled.log.gz](https://github.com/RPCS3/rpcs3/files/3051854/Enabled.log.gz)
</details>

Infamous showed no noticible change in performance

And Lego Star Wars III: The Clone Wars showed a 2-3 fps performance decrease when disabled



Ryzen 5 1600
16 GB DDR4 2400 MHz
GTX 1050 Ti
MSI B350 TOMAHAWK
419.67 Driver
Windows 1803

**Comment by legend800** [comment]
I've found it reduces performance for me too.  i7 6700k @4.5ghz., 16gb ram, Nvidia 1080
I just leave it disabled now.

**Comment by MSuih** [comment]
Thread scheduler has been disabled on Intel processors, having it enabled should not make any difference as the thread affinity doesn't change.

**Comment by creeperjedi** [comment]
That doesn't seem to be the case for everyone: #5621

**Comment by smitdylan2001** [comment]
I tested Skate 3, but both when it was enabled and disabled it was at 60 fps. Is there any game that would need further testing that I could test out?

**Comment by kd-11** [comment]
This sounds like it is random and the user needs to choose between keeping the setting on vs off depending on the game and cannot be done globally. If I have time I can try playing around with the pinning but it likely will lead to the same outcome. Handling this properly is not easy to do, unless we add a special CPU config helper to force the user to optionally choose optimal CPU settings upon detecting a CPU change OR first-time use. The setting seems to be doing its job correctly otherwise.

**Comment by kd-11** [comment]
Just an update: I recently checked the performance of my 1700 on the latest windows builds and they have certainly improved performance a whole lot on Ryzen. It used to be around 5x slower than linux but now its about 80% of the peak performance, so things are definately improving. Hopefully, this setting will eventually be unnecessary - it seems windows already works well enough with the 6 core chips.

**Comment by aqxa1** [comment]
I just want to add that I currently get better performance with the thread scheduler *enabled* on Linux with Persona 5 and a 2700 (Zen+ 8 core). This is surprising since it's only recommended on Windows systems, but it does mean some systems still benefit from RPCS3's scheduler.

**Comment by Asinin3** [comment]
Windows imporved Ryzen Scheduler significantly for 1903 years ago, and some users here were using older builds.
RPCS3 also has implemented more scheduler options and improved/modified the way the RPCS3 scheduler works in the back-end in 2020/2021. 

Closing as outdated.
