### ISSUE TITLE
Booting in God of War 3 [BCUS9811] shows up weird yellow screen artifact on latest build 0.0.6-7967

### ISSUE THREAD

**Issue by dlim389** [RPCS3/rpcs3#5825]
Spec:
i9-9900k
RTX 2080 Ti
64GB DDR4 RAM
Windows 10 Pro 64-bit

RPCS3 build: 0.0.6-7967
![gow 3 yellow artifact](https://user-images.githubusercontent.com/49124947/55994239-0150c180-5c66-11e9-91e7-189f005e5173.PNG)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3070665/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3070666/RPCS3.log.gz)

**Comment by AniLeo** [comment]
False/troll report, lots of settings changed to inappropriate values, specially

```
  Accurate xfloat: false
  Approximate xfloat: false
```

**Comment by nitrohigito** [comment]
You somehow managed to turn xfloat approximation off. Open `config.yml` and look for the line `Approximate xfloat: false`. Replace that with `Approximate xfloat: true` and you're done.

**Comment by dlim389** [comment]
....

**Comment by nitrohigito** [comment]
`Approximate xfloat` is enabled by default, has always been since it's implementation, and it still is. So yeah, I'm starting to think that Ani might not have been kidding with you, or you got rpcs3 from a source 
 different than the project's website.

**Comment by AniLeo** [comment]
Approximate xFloat has always definitely been enabled by default as mentioned.

And it's not a GUI setting, you literally have to go out of your way to disable it in `config.yml` to break the graphical output there.

**Comment by dlim389** [comment]
@AniLeo You're not helping at all... I just figured out that I had to download other build version v0.0.6-7969 that resolves yellow screen artifact.

**Comment by nitrohigito** [comment]
We already explained to you what setting to change, and I also already cross-checked with 7967, it (as expected) has xfloat approximation enabled by default as well. Our point still stands.

**Comment by dlim389** [comment]
Too little, too late... I troubleshoot myself.

**Comment by AniLeo** [comment]
Now you've done it: Fuck off.

First of all, this is not a help-desk, it's an issue tracker. You're the one not helping at all, in fact, you made a false issue report by using settings that knowingly cause issues which **CAN ONLY BE CHANGED BY GOING OUT OF YOUR WAY AND EDITING THE CONFIG.YML FILE MANUALLY**.
Fortunately one of our testers already knew what causes this yellow output, otherwise you would have wasted dev time of some developer who would just end up figuring out you're using borked settings and there's no issue at all.

Now you've done yet another false report as there's no code between 0.0.6-7967 and 0.0.6-7969 that changes any of that behavior, I would tell you to feel free to point out the line of code that changes such behavior but since there is none and I'm not wasting another nanosecond with this garbage I'm locking this issue right now.
