### ISSUE TITLE
[Feature Request] Automatic search of FNIDs in modules and their registration process

### ISSUE THREAD

**Issue by elad335** [RPCS3/rpcs3#5833]
This would allow to remove lots of stubbed functions that are LLE only anyways, enabling faster compilation, cleaner code, and make the process of adding new functions be absolute.
Some functions can be left for full name reporting.
This functionality can be backwards compatible with things like `ppu_execute` to find addresses by specified FNID from function name specified.
some IDA scripts are doing this process automatically, for example.

**Comment by Nekotekina** [comment]
I must have said on discord, I'm against removal of stubs. Compilation time for them is rather insignificant and cached in most cases.

**Comment by ruipin** [comment]
There's no reason we couldn't load in the FNID list from psdevwiki though. It would even be useful if we ever wanted to implement symbol lookup for the debugger / backtrace, for example.

**Comment by ruipin** [comment]
To expand on my comment above, I had considered for a while to add PPU / SPU backtrace whenever a guest thread crashes in some way (or a syscall). However, this only makes sense if we're decorating the backtrace somehow.

Ideally, we would parse the symbols table, and also decorate functions by FNID ("<module>_<FNID>" if we don't know the name, otherwise the name). In addition, we could supplement this list of FNIDs by loading in the 3000+ FNIDs available on the wiki.

This would both improve usage of the debugger and make causes of crashes more obvious in the log.
