### ISSUE TITLE
[Feature Request] Allow a game to be fully cached into RAM

### ISSUE THREAD

**Issue by niko1point0** [RPCS3/rpcs3#5989]
In the PPSSPP emulator, there is a feature to have an entire ISO stored in RAM while the game is playing. Although many PS3 games are too big to be stored in  RAM, there are many small games like Minecraft that can easily be cached completely in RAM. Can we have this feature in the emulator?

**Comment by RipleyTom** [comment]
I mean you could install any ramdisk software and have that without adding unnecessary bloat to Rpcs3.

**Comment by henriquenj** [comment]
Probably it already _is_ cached by the operating system as you play the game. Both Linux and Windows perform file system cache by default. Adding a secondary cache mechanism might making things slower.

**Comment by vsub** [comment]
The first attempt after system restart is always slower than the second attempt.

I tried before on a pc game(Kingdoms of Amalur Reckoning)that takes way too long to load and there was barely any difference

1.First load from the hdd after restart - slow
Second load from the hdd - faster
2.First attempt after restart from the ram drive - fast(it took the same amount of time it took on my second attempt from the hdd)

And it definitely it took a lot of time to copy the game to the ram drive(way more that trying to load it from the hdd after restart)

Also on PPSSPP,loading from ram is fast but not mind blowing.

You can imitate that feature if you want.
Create a batch file that copies the game into a ram drive(personally I use ImDisk because it have a feature to not allocate certain gigabytes from your ram and you will not have access to them but to dynamically increase the size of the ram drive and used ram)and then run it from there(this feature which will most likely not be implemented will do something similar)

**Comment by niko1point0** [comment]
Ok. Thank you for the information
