### ISSUE TITLE
Flickering in P5 in PR #5988

### ISSUE THREAD

**Issue by windyboy1704** [RPCS3/rpcs3#5999]
![Screenshot (236)](https://user-images.githubusercontent.com/5692900/58028712-84a6e200-7b45-11e9-95ad-e135e53372a9.png)

![Screenshot (241)](https://user-images.githubusercontent.com/5692900/58028480-00545f00-7b45-11e9-95c0-42ce5384d31b.png)

In 0.0.6-8147 (PR #5988) P5 starts to have flickering screen. By browsing Personas in the menu, if you press L1/R1 quick enough, you will see the flickering like picture 2. The first one is harder to reproduce the problem, but if you keep rotating using the right analog it may happen.
[Log file here](https://cdn.discordapp.com/attachments/319224795785068545/580230121336864769/RPCS3.log).
It happens on iGPUs (Intel HD 620 to be exact), I know iGPUs are not officially supported but previous versions don't have this flickering problem.

Video demonstration (spotted in Mementos): https://streamable.com/6vh1j

**Comment by Xertified** [comment]
Same this happens to me, thought it’s on an RX 570. This appears only on fullscreen, and not in windowed mode.

**Comment by johnsonbui** [comment]
Additionally, that merge reintroduces issues with the game freezing and being unable to recover.

i7-7700 w/ GTX 1070

**Comment by Whatcookie** [comment]
This isn't a driver specific issue I think. It seems to happen when gpu usage hits 100%.

I was testing out anv for something else, and noticed that this issue was happening on that driver, but only when gpu usage was hitting 100%. I switched back over to radv, and set my max gpu clock to 350mhz and was able to reproduce it in scenes where the gpu usage hits 100% there as well. 


<details>
  <summary>
Images:
</summary>
ANV 90% gpu usage

![Screenshot from 2019-05-22 15-06-23](https://user-images.githubusercontent.com/26352541/58202297-1b3de500-7ca5-11e9-900e-8e1216eecc3e.png)
ANV 100% gpu usage
![Screenshot from 2019-05-22 15-06-33](https://user-images.githubusercontent.com/26352541/58202306-1f6a0280-7ca5-11e9-8e8c-0b41d14754a5.png)
RADV 90% gpu usage
![Screenshot from 2019-05-22 15-13-59](https://user-images.githubusercontent.com/26352541/58202316-242eb680-7ca5-11e9-8859-72e3379655d0.png)
RADV 100% gpu usage
![Screenshot from 2019-05-22 15-14-12](https://user-images.githubusercontent.com/26352541/58202326-2abd2e00-7ca5-11e9-9fa6-e2bd4abeabc0.png)

</details>

**Comment by windyboy1704** [comment]
@Whatcookie on this PR right? Previous versions don't have this kind of problem on my specs until this PR is merged.

**Comment by Whatcookie** [comment]
Yes, only after the PR you mentioned.

**Comment by kd-11** [comment]
@Whatcookie Confirmed on AMD at 100% GPU load. Nvidia is immune to this issue though, but we know intel and AMD hw share a lot in common including the silver line bug that the PR fixed. I'll try and find time for this one in a few days.

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/6039

**Comment by windyboy1704** [comment]
#6039 also fixed the infamous "diagonal line". Appreciate your hard work.
