### ISSUE TITLE
shaderlog folder contains huge amount of files

### ISSUE THREAD

**Issue by vsub** [RPCS3/rpcs3#6027]
Ignore\close if this is not a bug(it's supposed to be like this)
I don't know the purpose of this folder but I thought maybe it is dumping the shades when the option "Log shader programs" is enabled

Isn't the cache folder where the shaders are stored,are those in the shaderlog folder part of what is needed to create the shaders?

The option "Log shader programs" is not enabled on any of my custom settings(and the global)but every time I run a game,this folder is created and files are saved there(right now there is 23k files in there)

RPCS3 0.0.6-8151-7de3c410

**Comment by AniLeo** [comment]
Yeah, shaderlog should be disabled by default

**Comment by vsub** [comment]
Yes it is disabled but the files are created

**Comment by vsub** [comment]
1.Delete the folder
2.Check the game custom settings to make sure the option is disabled(  Log shader programs: false)
3.Run a game for 10 seconds(the game have very little shaders)
4.Close rpcs3

11 files created

**Comment by vsub** [comment]
If I deny writing to that folder using the windows permissions(even tho the option is disabled),I will get two problems

1.If there is no shaders created(for example I clear the shaders cache and delete all of the files in shaderslog),I will get this message and rpcs3 will autoclose when I hit ok

{RSX Decompiler Thread} Unhandled exception of type 'class std::logic_error': fs::file is null

2.If I have shaders for the game,rpcs3 will stay at the shaders loading screen and nothing will happen

**Comment by kd-11** [comment]
Log shader programs currently dumps a vp_analyser.bin file and does not affect the output. This setting was originally (I assume, it was there for a long time) meant to control whether the program output is written into the log file. It still is by the way, but only on OpenGL. When D3D12 support was being added, it became obvious there was need to inspect users shader blobs and the folder dump was added but is not controlled by the option. RE work on the decompilers has come a long way and this option being forcefully enabled may be undesirable in current year, but back then we could not allow bug reports without an attached shaderlog folder, due to how immature the emulator was. With that, I guess we can re-expand the option to cover shaderlog writing; should be trivial to implement for any contributor.
