### ISSUE TITLE
Project Diva F and F2nd: Emulator freezes prior to intro video due to commit #6047

### ISSUE THREAD

**Issue by leopard20** [RPCS3/rpcs3#6051]
As the title says, the emulator freezes right before the intro videos. Tested various settings with no luck.
However, the older version I had (build 0.6.8089) works fine.

The issue might be present in other games as well, but I only have these two games to try.

OS: Windows 8.1
CPU: Intel Core-i7-4700HQ
GPU: GTX 860m
Emulator: v0.6.8193/Vulkan backend/other settings left as default

**Comment by RainbowCookie32** [comment]
I think that the issue is specifically caused by #6047, it also affects GT5 in my experience. Try if it works with 0.0.6-8180. If it does, then it's caused by the PR I mentioned before and it can be bypassed by manually loading libvdec in RPCS3's settings until there's a fix (or use the build before that PR).

**Comment by leopard20** [comment]
Yes. Build 0.6.8180 works. 
Should I close this now?

**Comment by RainbowCookie32** [comment]
Keep it open. It serves as a tracker for the regression

**Comment by RainbowCookie32** [comment]
Try if #6052 fixes the issue

**Comment by vsub** [comment]
Project Diva F works now on 0.6.8194

**Comment by RainbowCookie32** [comment]
Issue can probably be closed then
