### ISSUE TITLE
BLJM61322 - DENGEKI BUNKO FIGHTING CLIMAX IGNITION (電撃文庫 FIGHTING CLIMAX IGNITION) graphic glitches

### ISSUE THREAD

**Issue by rdeleonp** [RPCS3/rpcs3#6090]
![1](https://user-images.githubusercontent.com/20749249/59514205-00b0f300-8e82-11e9-818a-4bbefd331fe6.jpg)

![2](https://user-images.githubusercontent.com/20749249/59514220-07d80100-8e82-11e9-9f96-89b234329245.jpg)

![3](https://user-images.githubusercontent.com/20749249/59514235-0dcde200-8e82-11e9-8219-5d964fd159e9.jpg)

![4](https://user-images.githubusercontent.com/20749249/59514236-0dcde200-8e82-11e9-9e25-47176f65c9ab.jpg)

![5](https://user-images.githubusercontent.com/20749249/59514247-132b2c80-8e82-11e9-84e4-26caef999de4.jpg)

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3290868/RPCS3.log.gz)

**Comment by Emulator-Team-2** [comment]
@rdeleonp 
This problem is caused by enabled `Use GPU texture scaling`.
GPU texture scaling is disabled by default and was moved to debug setting some time ago.

Disable this option in `config.yml` and in your custom game config: /config/custom_configs/config_BLJM61322.yml.

Also disable these unnecessary options in GPU tab:
-Write Color Buffers.
-Strict Rendering Mode.
Reset `Resolution Scale Threshold` to 16x16(default).

**Comment by rdeleonp** [comment]
Hi.

@Emulator-Team-2, thanks for the info.

Deleted the YML files and then let RPCS3 recreate the settings; no more rendering glitches.

For future reference, should **_Write Color Buffers_** not be used when submitting issues?

I ask because I previously saw [mentioned](/RPCS3/rpcs3/issues/6029#issuecomment-496461299) that **_Write Color Buffers_** is in the list of PS3-compatible settings.

Please advise.

Cheers.

**Comment by Emulator-Team-2** [comment]
@rdeleonp 
I only mean, this game doesn't require this option.

Write Color Buffers usually fixes problems like:
-Missing graphics.
-Broken lighting ingame.
-Black Screen / textures.

**Comment by rdeleonp** [comment]
@Emulator-Team-2, thanks for the info.

Cheers.
