### ISSUE TITLE
Silent Hill Downpour [BLUS30565] RSX: Driver crashed with unspecified error ...(VK_ERROR_DEVICE_LOST)

### ISSUE THREAD

**Issue by alexsilva** [RPCS3/rpcs3#6091]
Silent Hill Downpour [BLUS30565]

RPCS3 v0.0.6-8254-8dafc8e5 Alpha | HEAD | Firmware version: 4.84
Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz | 8 Threads | 15.87 GiB RAM | AVX+

The evolution of compatibility with the game has progressed in an impressive way but eventually the emulator emits this fault as soon as I command to start the game. 
The game does not start and the emulator freezes when you try to start it again.

Main error: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)

[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3291233/RPCS3.log)

**Comment by Parthorisian** [comment]
Even since build8253 has been released it still goes ingame using opengl

**Comment by endervad** [comment]
This happens for me too, but in Persona 5 [NPEB02436] and in a different scenario: the game has a chance of crashing at transition screens. The more graphically intense scene, the higher chances of crash. And the longer a play the game, the higher chances of crash too.

RPCS3 v0.0.6-8273-cd0ef99d Alpha | HEAD | Firmware version: 4.84
Intel(R) Core(TM) i7-2860QM CPU @ 2.50GHz | 8 Threads | 15.98 GiB RAM | AVX

Crash lines in log:
`·W 0:17:00.221645 {RSX [0x01d2020]} RSX: Cache miss at address 0xCACD0400. This is gonna hurt...
·E 0:17:00.422409 {RSX [0x01d2020]} RSX: [vulkan] vk::wait_for_event has timed out!
·F 0:17:00.686575 {RSX [0x00aa6a4]} RSX: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file c:\projects\rpcs3\rpcs3\emu\rsx\vk\vkhelpers.h:989)`
Very similar lines can be seen in the issue starter's log.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3315692/RPCS3.log.gz)

Since in 8253 and 8254 MSAA was added, I'll try disabling it.

**Comment by rafael-57** [comment]
This also happens to me in Dante's Inferno

**Comment by endervad** [comment]
I tried PR #6112. I've been playing Persona 5 for about 5-6 hours and haven't expierenced a crash as it usually opened in about 3 hours. So I think you shoukld try this PR.

**Comment by alexsilva** [comment]
@endervad I think it was resolved. There is a time when I do not see this failure. Even the log messages have changed.
