### ISSUE TITLE
Failed to create cache directory

### ISSUE THREAD

**Issue by Crashdummyy** [RPCS3/rpcs3#6141]
Hey there,

I currently fail to start any game from within the cli.
I always get the following error: 
```
F LDR: class std::runtime_error thrown: Failed to create cache directory: E:/Emulators/RPCS3/cache/BLES00696/ppu-H2RsyY8QVhycwicPmN32qYWcFNVG-EBOOT.BIN/ (Access violation)
```

I am running RPCS3 on 232a35b6fcddfa39f22594cbc0650156c29b9327
This Problem occurs on every Game.

If I start it using the GUI everything appears to work fine..

**Comment by Megamouse** [comment]
It says you have an access violation. You either don't have the proper rights when using the console or the file is in use already

**Comment by Crashdummyy** [comment]
Thats strange.. I took ownage of the whole directory, even started the shell as Admin running the command using /runas
In Use would be strange, as I get this Error even when I restart my Computer.
Am I mistaken that /runas is the windows equivalent of sudo ?

**Comment by Crashdummyy** [comment]
I resolved it by navigation to the correct directory

**Comment by vsub** [comment]
The issue is closed but I just want to say why that happens

1.Run cmd which sets the working directory to the user profile folder by default
2.Type the rpcs3.exe path and the path to some game eboot and when you try to run rpcs3,you will get that error

When I check the "Current Directory",it says that it the user profile folder in C:\  not where rpcs3.exe is
This happens only if rpcs3 is in another partition

If you run a shortcut that points the "Start In" to another partition(that's just an example),you will get the same error

It will also happen if you drop an elf file to the exe but only if the elf file is in another partition

I am not sure if this is a windows thing or a bug in rpcs3(maybe a fix can't be added that rpcs3 set the working directory,the directory where rpcs3 is regardless of how it is started

**Comment by Crashdummyy** [comment]
> The issue is closed but I just want to say why that happens
> 
> 1.Run cmd which sets the working directory to the user profile folder by default
> 2.Type the rpcs3.exe path and the path to some game eboot and when you try to run rpcs3,you will get that error
> 
> When I check the "Current Directory",it says that it the user profile folder in C:\ not where rpcs3.exe is
> This happens only if rpcs3 is in another partition
> 
> If you run a shortcut that points the "Start In" to another partition(that's just an example),you will get the same error
> 
> It will also happen if you drop an elf file to the exe but only if the elf file is in another partition
> 
> I am not sure if this is a windows thing or a bug in rpcs3(maybe a fix can't be added that rpcs3 set the working directory,the directory where rpcs3 is regardless of how it is started

Sorry I didn't correct myself clearly.
I did have the same thought so I changed a few things.

- Both RPCS3 reside on a disk mounted at E:
- The executed command started from C: ( where the RestAPI I am using to launch it has its root )

So I am now doing something like this:

```cs
            var process = new Process
            {
                StartInfo =
                {
                    FileName = "rpcs3",
                    WorkingDirectory = payload.Path.Substring(0, payload.Path.LastIndexOf('\\')),
                    Arguments = $"\"{payload.Path}\"",
                    UseShellExecute = true,
                    Verb = "runas"
                }
            };
``` 
Here *payload.Path* is the path to the EBOOT.bin of the specific Game.
Executing the Command in that directory apparently works.
I guess that is because both rpcs3 ( in my path ) and the Game reside both on E:

**Comment by vsub** [comment]
It will work with any directory that is in the same partition as rpcs3.exe

**Comment by isuckdickforkills** [comment]
> I resolved it by navigation to the correct directory

how can you solve it!
can you teach me :<
