### ISSUE TITLE
Enabling Force CPU Blit causes black boxes in Resident Evil 4 [NPEB00342] 

### ISSUE THREAD

**Issue by Realmantik** [RPCS3/rpcs3#6175]
Enabling "Force CPU Blit" causes black boxes in Resident Evil 4 [NPEB00342] when you kick the enemy and in some other places.
![leon](https://user-images.githubusercontent.com/22906342/60891507-18537f80-a266-11e9-9484-339ad6859772.gif)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3373169/RPCS3.log.gz)

**Comment by kd-11** [comment]
You really should not be using developer options for gameplay. They are expected to break things sometimes.

**Comment by kd-11** [comment]
I'll close this with a bit of explanation - CPU blit works fine, but the emulator does not honor memory load operations due to their severe performance considerations. In this case it seems to be a clearly missing Z load which is not really avoidable with current framework. This is partially intentional since it is not expected to be actually used.

**Comment by Realmantik** [comment]
Without enabling CPU blit game on Vulkan crashes with fatal memory reading\writing violations

**Comment by kd-11** [comment]
You should report that error instead in its own ticket.

**Comment by Realmantik** [comment]
Issue is present on github, #6066 I have commented on it.
