### ISSUE TITLE
RPCS3 stopped starting when installed games are on windows share - regression

### ISSUE THREAD

**Issue by ruthan** [RPCS3/rpcs3#6226]
Hello,
i dont have time to find exact version, but its from 10-30 days, when emulator stopped starting when there are games installed on Windows network share which is not available, its worked for i dunno 2 years in all versions.

  I want to play, but i will upload log later.

**Comment by bevanweiss** [comment]
@ruthan Going to need more information around this.

- What version of Windows were you running when it last worked, and did you update Windows in the meantime?
- Are you running rpcs3 as an 'Administrator' or just with standard user permissions?
- Do you have UAC enabled on your computer?
- Are you able to browse from within rpcs3 (via Import dialog etc) to the network path?

**Comment by ruthan** [comment]
- WIndows 10 1809-1909, updates doesnt matter.
- Im running it without addiotional admin priviledges, but account is administrator.
- UAC is enabled, but i set it up for lowest still enabled level.
- Yeah imports are ok.

Same share is working fine for Cemu a lots of other emulators.

**Comment by bevanweiss** [comment]
Are these the only three games that you have in rpcs3?
Have you renamed folder names or anything similar?
Could you post a screenshot showing the import window from rpcs3 pointed at the path '//naspragl/!nas/GamesInstalations/!Playstation3-images/The.Elder.Scrolls.V.Skyrim.Legendary.Edition.PS3-DUPLEX/BLUS31202-[Skyrim]' thanks?

**Comment by dio-gh** [comment]
Nice cracked release you got there in the path by the way...

**Comment by ruthan** [comment]
I have much more games, log is old, is other folder names are normal.

I own the game, but im lazy to make own dumps, so used on dump by someone else.

**Comment by bevanweiss** [comment]
Still waiting on this information:
> Are these the only three games that you have in rpcs3?
> Have you renamed folder names or anything similar?
> Could you post a screenshot showing the import window from rpcs3 pointed at the path '//naspragl/!nas/GamesInstalations/!Playstation3-images/The.Elder.Scrolls.V.Skyrim.Legendary.Edition.PS3-DUPLEX/BLUS31202-[Skyrim]' thanks?

**Comment by ruthan** [comment]
No, you are trying to search problem, no wrong place, its not anything special with my install, you would have same problems, if you would windows share game on your machine. I simulated it on multiple pcs.

- No, i have more games
- No i did not renamed folders.

 Import window, im not aware anything like that, i just pointed RPCS3 to windows share directory where are my dumps..

**Comment by slashiee** [comment]
Nobody is gonna help you with your pirated copies, y'know.

**Comment by ruthan** [comment]
Making dumps and backups and hacking console is always sort of shady practice anyway, at he time i havent PS3 dumping compatible blue ray drive  in my PC, now i have. 
  When i own game, does it matter when i get my dumps? 

By the way specifically Skyrim i own probably by ten different ways if i count all platforms and versions.

  Otherwise, prove that is something wrong this this specific dump from log and after that we can argue about it.. i had same problem with copies which i made on my own.

**Comment by bevanweiss** [comment]
I've just tested this to a network drive using UNC, and the game successfully launched, and no issues with the quick game test I performed.  Certainly PPU/SPU/RSX all went ok.
There is an issue it seems with the 'Open Install Folder' option on the Game List context menu.  It opens the Window File Explorer on other games, but not on my test UNC share.
So, I suspect that this is an issue with your configuration, since "It works for me"

My path was pretty simple "\\10.0.0.4\BLES01811-[LIGHTNING RETURNS FINAL FANTASY XIII]"
You might want to try to simplify your path, remove '!' etc to see if you can get it working.  If so, then that might provide a lead on what the issue is.

**Comment by AniLeo** [comment]
It is irrelevant whether something is wrong with that specific dump or not, piracy discussion is not allowed, it's also irrelevant if you own 10 copies of the game if you use a pirated copy, specially a known modified one

I've removed such mentions and the log file

A relevant excerpt from a normal copy is `·W 0:00:43.484120 Recent Game not valid, removing from Boot Recent list: //naspragl/!NAS/GamesInstalations/!Playstation3-images/Demons Souls (2010)/BLES00932/PS3_GAME/USRDIR/EBOOT.BIN`

Would be helpful if someone could reproduce the same issue

**Comment by ruthan** [comment]
Legal disscussion:
It depends what pirated copy supposed to be - really. When i own real game disc, its ok when i make my own dump = own "pirate" copy backup, but its not ok when i used dump done by someone else? That is supposed to be difference / problem?

   Its this argument really based on some real legal facts, or its just way to hassle people which want to save time (my motivation), because they arent doing enough, they are not hardcore enough? And it could also depend on local law, afaik here is ilegal to share, but download copy of game which you already own, is ok.  I dont thing that is more "shady" or wrong than use cracks to make old games working, because of broken cd protections.

 About issue, its old. Overall loading of games was fixed not long after that, but there still some errors related to loading of assets so i let i opened, because primary fix was some quick hack from Nekotika etc. If you thing that is ok (not related network shares) for you, pleas close it.

**Comment by dio-gh** [comment]
> own "pirate" copy backup

No, that's just owning a backup.

> but its not ok when i used dump done by someone else?

Pirate releases are not (just) dumps.

> That is supposed to be difference / problem?

Indeed, we ask users to make their own backups of their own games, and are strict about this. 

> or its just way to hassle people which want to save time (my motivation), because they arent doing enough, they are not hardcore enough?

Yes, because we obviously like to just mess with people and waste their time... are you serious?

> And it could also depend on local law, afaik here is ilegal to share, but download copy of game which you already own, is ok.

Not just could, it does. We however try to act in good faith and appease to as many legislations and laws as realistically possible, so as to protect the legality of the emulator and avoid getting sued. Normally, this is a compelling argument, even for the uninitiated. Hope it gets through to you.

> I dont thing that is more "shady" or wrong than use cracks to make old games working, because of broken cd protections.

We don't care what people think of our stance against piracy. It is not up for discussion.

>  If you thing that is ok (not related network shares) for you, pleas close it.

We do not, hence it remained open despite the countless piracy group namedrops.

**Comment by ruthan** [comment]
Im really trying to find if some real law and logic behind all of this, because there is lots of urban legends around it.

Could you add some concrete law links EU/US? Because otherwise it seems to be only just some point of view, or self supporting argument.

  Because if its good for sake of argument you name it backup, if is not good for sake of argument you name it pirate copy. So lets say that some my friend found make backup for from my own dvd, its still ok, or not?  

   Also is there any difference on binary level, between my copy of game and friend copy of same game? Because on Steam, or for old games there where serial keys - as proof of ownership, but new games havent anything like that.

   Other thing is lets say that my cd /dvd is damaged.. i cant read some data, its still illegal just download copy somewhere?
  
   Its whole console modification for making dumps also completely legal, isn't it against some console manufacture EULA etc?

   Otherwise not thing that some can attack emulators, based on users behavior.. Its like attack Photoshop, because someone using it for some offensive pictures.. but its ok your project, so i dont mind to delete someone to be sure.

  By the way its using Sony docs for developers, about console HW + its SDK still 100% legal fair use for creating emulator, its some grey zone?

**Comment by dio-gh** [comment]
You sure don't mind demanding specific legal text despite me not being a lawyer, but since you ask so "kindly", I'll gather some stuff tomorrow. Then again, I'm pretty sure it's gonna be a waste of time on my end, since you'll just find some excuses or nitpicks either way, but whatever.

> Also is there any difference on binary level, between my copy of game and friend copy of same game?

Between your and a friend's copy no, between your and a pirated copy, there definitely can be. Depends on the release.

> isn't it against some console manufacture EULA etc?

There are several terms a user can accept while signing up for a service, but they are not equally legally binding. Plus as a reminder, you need not to own an actual PS3 console to use RPCS3. There's a list of compatible blu-ray drives on our website.

> Other not hypocrite proper solution would be implement same legal check as using real PS3.

You mean a check that could be instantly removed by even the most beginner of programmers? Sure would worth a lot, gee, how have we not thought of that! Would also prevent homebrew and test applications from running, what joy!

>  its SDK

I can't recall anyone ever getting their hands on the official SDK.

For the rest of your concerns I'll return to after trying gather those references you're looking for so much. After all, "we wasted your time", you want to waste mine right? Must be only fair.

**Comment by bevanweiss** [comment]
@ruthan @dio-gh can we please get away from the side-discussion for a little while? 👍 

@ruthan please rename the path to something simpler, without special characters and retest.  If that works, then slowly build back up the path until it doesn't work, and let us know the issue.
As noted, I tested, and it worked for me under Windows 10 v2004, and using UNC path with IP address specified (with latest version of rpcs3)

**Comment by RainbowCookie32** [comment]
Since dio is pretty busy right now, I took the liberty to do some research on the matter. So I'll chip in to not leave this hanging.

Under US law, I'm pretty sure that games fall under the definition of [a computer program](https://www.law.cornell.edu/definitions/uscode.php?width=840&height=800&iframe=true&def_id=17-USC-54980223-364936160). 
Based on that, I'll quote a section from [this](https://www.law.cornell.edu/uscode/text/17/117):

> (a) Making of Additional Copy or Adaptation by Owner of Copy.—Notwithstanding the provisions of section 106, it is not an infringement for the owner of a copy of a computer program to make or authorize the making of another copy or adaptation of that computer program provided:
> (1) that such a new copy or adaptation is created as an essential step in the utilization of the computer program in conjunction with a machine and that it is used in no other manner, or
> (2) that such new copy or adaptation is for archival purposes only and that all archival copies are destroyed in the event that continued possession of the computer program should cease to be rightful.

Reading this, you can see that dumping a game you own is perfectly fine ("that such a new copy or adaptation is created as an essential step in the utilization of the computer program in conjunction with a machine"), *but,* downloading a game isn't, since it goes against the second section ("(...) all archival copies are destroyed in the event that continued possession of the computer program should cease to be rightful."). I don't think you can guarantee that you are the only one in possession of that copy of the game.


EU law is a bit more complicated and I'm no lawyer, so I'm gonna do my best interpretation here. You can go out and do more research if you feel like it, this is as far as I'll get for now.
Looking at the [European Union Computer Programs Directive](https://web.archive.org/web/20070615133751if_/http://ec.europa.eu/internal_market/copyright/docs/docs/1991-250_en.pdf), computer programs are protected as literary works under the [Berne Convention](https://www.wipo.int/edocs/lexdocs/treaties/en/berne/trt_berne_001en.pdf).

Article 9 of the Convention says that "Authors of literary and artistic works protected by this Convention shall have the exclusive right of authorizing the reproduction of these works, in any manner or form." This blocks pirated games, as I'm pretty sure there's no authorization going on there. 

Going to the Directive, we can see Article 5 says the following:

> 1.
>  In the absence of specific contractual provisions, the acts referred
> to in Article 4 (a) and (b)* shall not require authorization by the right-
> holder where they are necessary for the use of the computer program
> by the lawful acquirer in accordance with its intended purpose,
> including for error correction.
> 2.
>  The making of a back-up copy by a person having a right to use
> the computer program may not be prevented by contract insofar as it is
> necessary for that use.

*Article 4 a and b mentions the reproduction and translation/adaption/arrangement of computer programs.

So here Article 5 covers making backups of games "for the use of the computer program
by the lawful acquirer in accordance with its intended purpose".

I think this should cover all needed bases, feel free to carry on more research to your heart's content if you want to, but I think we should keep this issue more on topic from now on.

**Comment by ruthan** [comment]
Thanks for explanation, im from EU.

 But i dont this understand how from my or friend copy became that evil pirated copy, that is main problem. So lets say, what my friend make me copy, because has more experience with dumping or compatible drive, hacked console..
   Can he share it to make to me online, to get avoid need to time consuming physical transfer? If this is still legal, is there difference when i download 1 to 1 copy made by some else, when i assume that copy actually the same on binary level and i own physical copy of such product? Because friend is not exactly some legal term, i can claim that he is my online friend.. and not thing that someone would be able to disproof that online friend cant me good enough friend.
  For example majority of archive.org content is based on this principle, its same thing is not ok with PS3, does it means that archive.org is doing something illegal too? Because i have lots of old cds and floppy with games (20-30 years old) and someone there are really not readable.. and they are very hard to get, not all are available online, to it would be really nice to could download them to still have possibility to use them.

  Sony IP - its not my main point, but i did not meant just some SDK, but there some wiki, which are from time to time linked here, i would bet my money that some info there is from developers which has Sony developers full package not public SDK, because such info making all developers life better. I thing that if Sony would really want to kill this project, they would be able to to point their finger to this as argument and its not really matters who leaked this info, but if some that knowledge was used or not.
  I personally dont thing that Sony is agains this project, because its nice competition to Xbox backwards compatibility and it could helps in future make backward compatibility working. Because some old PS1, or megadrives are already selling and are using emulators.

**Comment by ruthan** [comment]
@bevanweiss - i already did, but there is not too much knowledge, i never was hinted, when i was fixed and what exactly to test, i log i see my lots of games errors like these are these related to using of networking path, or its not related? 

Some example, but there is lots of errors with some path, so any hint what could be related to network would be nice:
`{PPU[0x1000014] Thread (RenderingThread) [0x01c11ee4]} SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00200/USRDIR/UNREALENGINE3/UTGAME/MOVIES/UT_LOADMOVIE1.TXT” [1]`
E {PPU[0x1000000] Thread (main_thread) [0x01c12000]} SYS: 'sys_fs_opendir' failed with 0x80010006 : CELL_ENOENT, `“/dev_hdd0/game/BLES00200/USRDIR/UNREALENGINE3/UTGAME/PS3CACHE” [1]`
`E {PPU[0x1000000] Thread (main_thread) [0x01c11ee4]} SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BLES00200/USRDIR/UNREALENGINE3/UTGAME/CONFIG/_EPICDLC_1.INI” [1]`
`E {PPU[0x1000000] Thread (main_thread) [0x00afde44]} SYS: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “/dev_bdvd/PS3_GAME/USRDIR/textures/lights/ui_fnt_mikadan_28.gtf” [1]`

**Comment by AniLeo** [comment]
This is not the place for legal discussion, refrain from further Off-Topic

**Comment by bevanweiss** [comment]
Those 'errors' don't look like real problems, unless accompanied shortly after by a crash or other issue.
The games often ask for files that simply don't exist (in certain situations), and then when the game is told it doesn't exist it operates with that knowledge. E.g. the check for the DLC ini file, not too surprising it would fail if you have no DLC content.
We (coding the emulator) don't know what the game will do when told a file doesn't exist, or if the file is really supposed to exist or not.

So, recommendations are:
A. Use a local storage device
B. Use games that you have personally dumped and verified from known working discs.

This won't solve all problems, corrupt files / filesystems / emu bugs do occur.
But you're not doing yourself any favours by ignoring all the recommendations, and thusly you're unlikely to get much help.

So... How you should proceed.
1. Get a legit dump that you have witnessed the creation of from a known good disc.
2. Test it on a local disk drive
3. If this works fine, move it to a network drive.
4. If that causes problems, then report the issue (providing a log of it working correctly, and a log of it not working correctly).

**Comment by ruthan** [comment]
Errors above are from new dumps and fully abstract dependency if data are stored locally or not network from code should be proper way how to code this.

**Comment by bevanweiss** [comment]
No one will complain if you want to write the code and submit a PR that does things the way you think is 'proper' :)

**Comment by ruthan** [comment]
This was really cheap argument. Let it opened and we will see in the future.

**Comment by bevanweiss** [comment]
A cheap argument.. and you got it for free... seems like a good deal ;)

So in my steps of 'How you should proceed', what things worked?
Did you run the game from your local disk without issues? (please provide the zipped log)
Did you then run it from the UNC path, and issues occurred? (please provide the zipped log)
