### ISSUE TITLE
[OpenGL vs Vulkan] Sly Cooper Thieves in Time

### ISSUE THREAD

**Issue by SZERO-1** [RPCS3/rpcs3#6246]
Hello guys,

Hope you're doing fine and **i must say great project over there !**

I just wanted to reported something strange, basically i tried out a few games from my old collection here and this one showed one funny thing.

Basically if i use **OpenGL** the **upscaling works fine** but switching to **Vulkan** it seems it gets on lower resolution possible **getting even pixalated image**.

My Build is:
CPU: I5 8400
GPU: GTX 1060 6GB
RAM: 16GB 2400MHz

**With Vulkan**
![imagem](https://user-images.githubusercontent.com/50744829/61598290-219ffd00-ac13-11e9-9093-7eb542beead7.png)

**Log from Vulkan:**
[RPCS3_Vulkan.log](https://github.com/RPCS3/rpcs3/files/3415165/RPCS3_Vulkan.log)

**With OpenGL**
![imagem](https://user-images.githubusercontent.com/50744829/61598302-717ec400-ac13-11e9-983d-0c467df5f5f3.png)

**Log from OpenGL:**
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/3415160/RPCS3.log)

**Comment by SZERO-1** [comment]
Okay i had found some issues reporting similar problems, and when used the options **Write Color Buffers** and **force CPU blit emulation** the RPCS3 was able to render properly and with the desired performance (from Vullkan render).

Problem Solved :D

**Comment by Zangetsu38** [comment]
If you said need enable cpu blit want said problème is not fixed here 🤔

**Comment by SZERO-1** [comment]
Okay @Zangetsu38 i was not aware of it, so i will reopen this issue.
Many thanks for your observation :)

**Comment by Asinin3** [comment]
Close issue. Resolution scaling is technically a hack. But you can use it with this game by forcing CPU Blit, as you discovered.

There's also a game patch now to disable MLAA, which allows you to use Resolution Scaling without Force CPU Blit or WCB. This is great for performance. And since Force CPU Blit breaks the torches rendering, it's better in that regard as well. https://youtu.be/p_gvO2jBWwI?t=264
