### ISSUE TITLE
Kingdom Hearts 1.5 HD remix Graphical Glitch (black spots all over the ground)

### ISSUE THREAD

**Issue by jh0nny2k** [RPCS3/rpcs3#6279]
Hi Guys,

Having graphical issue when ingame wherever i walk i see 2-3 black triangles : 
![Annotation 2019-07-28 230807](https://user-images.githubusercontent.com/21306966/62012248-97b0e080-b18c-11e9-8c51-75b299342c90.png)
Please see above photo.

These triangles are all over the place, i have played 2-3 levels and same issue occurs.
Please also see logs for more details and let me know what else can i provide to help with this issue.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3439533/RPCS3.log.gz)

Kind regards,
Ionut

**Comment by kd-11** [comment]
Increase resolution scaling threshold to 512 or greater. Its a known issue with upscaling. A more complete fix will be made available soon.

**Comment by MSuih** [comment]
This can be fixed by enablnig Read Color Buffers in Advanced tab of emulator settings. With it enabled there are no glitches visible on screen.

Without RCB:
![screenshot-2019_09_23_16_26_02](https://user-images.githubusercontent.com/19759300/65429595-19d12480-de1f-11e9-96ae-e2c8d29c4b24.png)

With RCB:
![screenshot-2019_09_23_16_27_37](https://user-images.githubusercontent.com/19759300/65429600-1c337e80-de1f-11e9-952f-984d0cc3602f.png)

This issue can be closed now.
