### ISSUE TITLE
System Clock set in 1972?

### ISSUE THREAD

**Issue by Rodokami** [RPCS3/rpcs3#6298]
So it seems the system clock went all crazy and is set in 1972. Also the date, month, hours and minutes are completely wrong. Is there a way to update it or change it to the actual time? 
ver : rpcs3-v0.0.6-8440-c219417f
specs: w10 64 bits, 8gb Ram DDR3, I5 3330 3.0 Ghz, GTX 970
![1972](https://user-images.githubusercontent.com/48815288/62418556-0f29b880-b642-11e9-9e2b-43d8645b6f54.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3464491/RPCS3.log.gz)

**Comment by MSuih** [comment]
This is probably related to #6291. Have you tried the pull request mentioned in it?

**Comment by Kian-Stevens** [comment]
I recorded the same issue in #6291, in which lap times were apparently set in 1972

**Comment by mavethee** [comment]
I think this issue is no longer a thing, at least in LiS, which I was loud about back back in the day issue was happening. I don't remember which pr fixed it but here you have a screenshot of latest master. @Rodokami please retest P4AU, cuz issue may be still a thing there. I doubt, but it's always better to check :p 
![image](https://user-images.githubusercontent.com/47083527/73604964-6f20fd80-4598-11ea-9c15-98ae3243d600.png)

**Comment by elad335** [comment]
Close it?

**Comment by mavethee** [comment]
@elad335 if comes to me, it's fixed, so yeah.

**Comment by AniLeo** [comment]
Closing, if you can still reproduce ping for reopening
