### ISSUE TITLE
Rogue Legacy [NPUB31512] opengl graphic glitches

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#6331]
using opengl results in all the graphics messed up
have tried different configurations but nothing works
![rogue](https://user-images.githubusercontent.com/2696404/62860945-6c092b00-bd34-11e9-8b30-25424dc20f2d.PNG)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3492015/RPCS3.log.gz)

**Comment by Emulator-Team-2** [comment]
@benderscruffy 
This problem is caused by enabled `Use GPU texture scaling`.
GPU texture scaling is disabled by default and was moved to debug settings.

Set `Use GPU texture scaling` in config.yml to false.

Also disable this unnecessary option in GPU tab for this game:
-Write Color Buffers.

And Reset Resolution Scale Threshold to 16x16 (default) in GPU tab setting.
Aspect ratio: Should be set to 16:9 by default.

Close this issue.

**Comment by benderscruffy** [comment]
thanks for thats
