### ISSUE TITLE
GRAN TURISMO HD Concept [NPEA90002] Font rendering regression

### ISSUE THREAD

**Issue by jade010** [RPCS3/rpcs3#6395]
PR #6357 fixed performance regression with GRAN TURISMO HD Concept [NPEA90002] but also introduced a new regression with fonts.

PR #6369 =>
![PR6369](https://user-images.githubusercontent.com/36518512/63598002-fa946c80-c5be-11e9-80a6-07e1a65f5107.PNG)
RSX Capture and log :
[PR6369_capture.zip](https://github.com/RPCS3/rpcs3/files/3534878/PR6369_capture.zip)
[PR6369.log.gz](https://github.com/RPCS3/rpcs3/files/3534879/PR6369.log.gz)

PR #6357 =>
![PR6357](https://user-images.githubusercontent.com/36518512/63599073-16007700-c5c1-11e9-8f54-71338e3f3a7d.png)
RSX Capture and log :
[PR6357_capture.zip](https://github.com/RPCS3/rpcs3/files/3534881/PR6357_capture.zip)
[PR6357.log.gz](https://github.com/RPCS3/rpcs3/files/3534882/PR6357.log.gz)

**Comment by jade010** [comment]
Changing the default resolution to 1920x1080 fixes the font rendering :
![Captura](https://user-images.githubusercontent.com/36518512/63631285-9953b400-c625-11e9-820e-2c30bd907029.PNG)
I don't know if this should be closed or needs to be fixed for 1280x720p mode 😕

**Comment by kd-11** [comment]
Leave it open.

**Comment by Andryshik345** [comment]
Reopen this issue, because other glitches was appeared. Or I should open another issue?
![изображение](https://user-images.githubusercontent.com/24612088/64059520-ae0cea80-cbd7-11e9-909b-bafd4d6c76ff.png)
![ezgif com-optimize(5)](https://user-images.githubusercontent.com/24612088/64059570-cb8e8400-cbd8-11e9-9914-0767993e3ad4.gif)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3562105/RPCS3.log.gz)

**Comment by kd-11** [comment]
That is unrelated to this issue and has existed for a long time. Only seems to happen with some settings configurations. I have seen it before but I have no idea how to reproduce.

**Comment by Andryshik345** [comment]
@kd-11 did you try to disable the anti-aliasing? I found that enable the AA is fixing this bug.
