### ISSUE TITLE
Wrong game title on game window.

### ISSUE THREAD

**Issue by gidan80** [RPCS3/rpcs3#6396]
After commit b56b425b19f46aa19e776e7c072d3a82d9413c4d if the user starts a disc game, then stops it, then starts an HDD game, the game title shows the disc game name instead of the HDD one.

**Comment by Realmantik** [comment]
I can confirm.

**Comment by Megamouse** [comment]
Please tell me the exact steps to reproduce this.
(what do you click etc.)

**Comment by gidan80** [comment]
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3539531/RPCS3.log.gz)
Look at row 3923 of the log.
Step to reproduce:

1. Boot a disc game titled "A"
2. Stop it at any time
3. Boot an HDD game titled "B"

You will see that in the game window the title is "A" instead of "B".

**Comment by vsub** [comment]
It probably has something to do with your paths and how that rev look for the title,because this does not happen here
My disk games are in dev_hdd0\disc
And my HDD games are in dev_hdd0\game

From your log
·! 0:00:11.400521 LDR: Path: H:/games/ps3/Persona 5 [USA]/BLUS31604-[Persona 5]/PS3_GAME/USRDIR/EBOOT.BIN
·! 0:00:11.401105 LDR: Title: Persona 5
.....
·! 0:00:29.323277 LDR: Path: F:/rpcs3/rpcs3-v0.0.5-7642-632b0f48_win64/dev_hdd0/game/NPEB00681/USRDIR/EBOOT.BIN
·! 0:00:29.323577 LDR: Title: NEOGEO STATION
METAL SLUG 2
..
·! 0:00:29.324865 LDR: Title was set from NEOGEO STATION
METAL SLUG 2 to Persona 5 - but you are not running Persona 5 after this

**Comment by Realmantik** [comment]
On most recent builds everything works fine for me.

**Comment by gidan80** [comment]
Can confirm. On latest master there is no issue.
I'm going to close this.
