### ISSUE TITLE
Rename no-gui to --headless and implement proper --show-gui parameter

### ISSUE THREAD

**Issue by Fisk24** [RPCS3/rpcs3#6397]
When launching games from the command line passing --no-gui doesn't appear to change anything about how the emulator presents it's self. Either way the main emulator window can still be seen behind the game

RPCS3 v0.0.6-795-gb70908c8f

I am running Manjaro Linux:
Intel® Core™ i7-4720HQ CPU @ 2.60GHz × 8
GeForce GTX 965M/PCIe/SSE2

**Comment by vsub** [comment]
Win10
Same here,adding the command does nothing different when staring a game from a shortcut.

And just for a test(because I was not sure if this was the command line),I added the no-gui command but without the -- which did not result in any kind of error dialog but rpcs3 just started as a process in the task manager and nothing appeared.

The only way to exit it was to kill the process(the window is not just hidden,rpcs3 is just starts as a process with no windows(including hidden...I can see that with Process Hacker))

**Comment by Megamouse** [comment]
Well. That's what it's supposed to do

**Comment by vsub** [comment]
Maybe I did not understand something
--no-gui this does nothing different than not adding it at all.The main window appear and after few seconds,the game window appear infront of it(which is what happens when you don't use that command line)

no-gui(without the --,which is probably the wrong way to add command lines) - this just starts the process and nothing else is happening.The game specified in the command line is not loaded.The process just stays there doing nothing and you can't run another instance unless you kill it

![2019-08-24_130233](https://user-images.githubusercontent.com/5032540/63637015-51597f00-c66f-11e9-94da-72109a1a8d64.jpg)

**Comment by Megamouse** [comment]
Yes. You're describing the exact thing that's supposed to happen

**Comment by MSuih** [comment]
You're asking for the emulator to not show a gui, so no gui is shown. It's supposed to be combined with instruction to start a specific game.

**Comment by vsub** [comment]
I am also adding a game to the command line but it is not running like any other emulator that have no-gui feature
What is the point of that command line if it does nothing

- This shows the main window and then the game window

"D:\Games\PlayStation\PlayStation 3\rpcs3.exe" "D:\Games\PlayStation\PlayStation 3\dev_hdd0\disc\BLES01815-[Tales of Xillia]\PS3_GAME\USRDIR\EBOOT.BIN"

- This shows the main window and then the game window...exactly the same behavior

"D:\Games\PlayStation\PlayStation 3\rpcs3.exe" --no-gui "D:\Games\PlayStation\PlayStation 3\dev_hdd0\disc\BLES01815-[Tales of Xillia]\PS3_GAME\USRDIR\EBOOT.BIN"

- The -- is missing here and this just start rpcs3,don't create any windows(including hidden)and it does not run anything.

"D:\Games\PlayStation\PlayStation 3\rpcs3.exe" no-gui "D:\Games\PlayStation\PlayStation 3\dev_hdd0\disc\BLES01815-[Tales of Xillia]\PS3_GAME\USRDIR\EBOOT.BIN"

It's like no-gui(without the --)is a option for "I want rpcs3.exe to stay in my taskmanager doing nothing and not allow me to run any game unless I kill it first"

**Comment by Megamouse** [comment]
It's not supposed to show anything. That's the whole point of it.

**Comment by Megamouse** [comment]
It's not meant for playing games

**Comment by vsub** [comment]
Well that's the first time I see a no-gui option that literally does that...not showing anything and stays in the taskmanager doing nothing expect preventing you from running any games.

The "--no-gui" option which is probably the correct one according to the source and the -h command line that shows all command lines,does literally nothing different(adding it or not)
With and without it,you have two visible windows

And if you add it in the incorrect way(without the --,according to -h),it will prevent you from using rpcs3 until you kill the process.

**Comment by Megamouse** [comment]
It's not doing nothing. It's literally running the game without a GUI (which will fail of course since the graphics Backend needs a frame or context to draw to).
You are not supposed to use it to play. It's just for debugging and running tests. 
You can already test the Spurs example with it. (See logs after running it.).
If you enable "exit rpcs3 after game stop" or what it's called, then it should also properly exit the process afterwards

**Comment by vsub** [comment]
Ok but I keep telling you "--no-gui" does nothing different than not adding the command line at all

Just to make it clear,is the correct command "--no-gui" or just "no-gui" because

"--no-gui" does the exact same thing as not adding it...the main window appear and after few seconds the game window appear

The same thing happen if I don't add a game path after that command line
Just this and run it
"D:\Games\PlayStation\PlayStation 3\rpcs3.exe" --no-gui
The main window appears like normal

With this,both windows appear like normal when you don't add the --no-gui command line
"D:\Games\PlayStation\PlayStation 3\rpcs3.exe" --no-gui "D:\Games\PlayStation\PlayStation 3\dev_hdd0\disc\BLES01815-[Tales of Xillia]\PS3_GAME\USRDIR\EBOOT.BIN"

But if you do this(even if "exit rpcs3 after game stop" is enabled)
"D:\Games\PlayStation\PlayStation 3\rpcs3.exe" **no-gui** "D:\Games\PlayStation\PlayStation 3\dev_hdd0\disc\BLES01815-[Tales of Xillia]\PS3_GAME\USRDIR\EBOOT.BIN"
or this
"D:\Games\PlayStation\PlayStation 3\rpcs3.exe" **no-gui**
RPCS3 will just appear in the taskmanager and it will do nothing....no CPU\GPU\HDD usage at all,just 45MB or ram used and nothing else

Killing the process will write to the log file the same thing as if you open and close rpcs3 without running anything
![2019-08-24_183218](https://user-images.githubusercontent.com/5032540/63640921-e1162200-c69d-11e9-9c48-2a85f950952f.jpg)

**Comment by Megamouse** [comment]
Yes. I never said it was --no-gui.
no-gui is correct

**Comment by dio-gh** [comment]
@Fisk24 @vsub This is called `headless mode`, and was implemented by mega himself ^^ for automated testing purposes. It is by design not supposed to open *any* windows. This mode is traditionally for automation purposes in **every** software that implements it. What you are describing is quite different, and while I myself would appreciate a feature like that too, that doesn't mean the `no gui` mode is non-functional. It does what it's supposed to, albeit you could argue there's some misnomer at play regarding it.

And while not processing double-dashed arguments kinda breaks the usual convention, it has always worked this way in RPCS3, so that isn't news either. You are expected to pass arguments to the launched `.(s)elf`s in a similar fashion as well, for example. So again, it's not that the mode is not working, you are just invoking it wrongly.

If there's any place in the emu where the way of passing the argument is written wrong (so as `--no-gui` instead of `no-gui`), please point to it so that it can be fixed. Otherwise, this issue is closable. You may want to open feature requests for those two things I just mentioned separately (for UI-less game launching and double-dashed argument processing).

**Comment by vsub** [comment]
Well then,the -h\--help\-? command line shows wrong info
Options:
  -?, -h, --help     Displays this help.
  -v, --version      Displays version information.
  --no-gui           Run RPCS3 without the GUI.
  --hidpi <enabled>  Enables Qt High Dpi Scaling.

Arguments:
  (S)ELF             Path for directly executing a (S)ELF
  [Args...]          Optional args for the executable

Only "no-gui" as command line does literally nothing than running rpcs3.exe and just sits in the taskmanager doing nothing even if you add a game to the command line and the process never auto closes.
Once you run it with that command line,rpcs3 will never auto exist because at least here ,it is doing nothing.

And btw using the name "no-gui" which does something completely different,will bring those kind of misunderstandings
Why not just name it -headless,that's not something common if it's a command line mainly used for debugging

**Comment by Fisk24** [comment]
I propose we change --no-gui to --headless, and make --no-gui do what it actually implies (hiding every part of the ui except the game window)

**Comment by idMauricio** [comment]
No windows isso não estas a funcionar ainda, como faço pra executar o game com args?
