### ISSUE TITLE
Question: "TSC: Bad" What does TSC actually it mean?

### ISSUE THREAD

**Issue by Zhythe** [RPCS3/rpcs3#6435]
As the title says.

**Comment by mavethee** [comment]
You shouldn't opening issue for that. RPCS3 have Discord for a reason. Issues on GitHub are for reggressions or feature request.

**Comment by MSuih** [comment]
https://en.wikipedia.org/wiki/Time_Stamp_Counter

The log line is supposed to show the frequency of this counter, but seems like some operating systems(?) hide the actual frequency and return a generic value instead. Emulator reports them as "Bad" TSC right now.

And yes, please ask questions in Discord or Reddit instead of opening issues for them.

**Comment by Zhythe** [comment]
Apologies for posting about this here and thank you for the response.

**Comment by Pysis868** [comment]
At least it was indexed so I found it.  Forum is probably the best place.

Found this: https://www.reddit.com/r/rpcs3/comments/ctafp2/should_i_be_worried_about_my_emulator_saying/

AnnieLeo (Staff) says don't be worried.

Then found this:
https://forums.rpcs3.net/thread-200690-post-306021.html

I'm sure that carries the same sentiment, just neat to read how different OS and their versions differ in this area.
