### ISSUE TITLE
[Regression] Army of Two: The 40th Day PR6357

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#6464]
After https://github.com/RPCS3/rpcs3/pull/6357 commit 05caa10f Army of Two The 40th Day have flickering issues in certain cases of aiming, here's the video
https://www.youtube.com/watch?v=g3N7-7ZXkoc
video's not mine but it's a perfect example
and here's the RSX capture
https://mega.nz/#!6B5h2Qgb!hpxiiU7MGwBI3Qqmu4QD5mb2upEHi22cvuSolPuRaqA

**Comment by Xcedf** [comment]
Did some more tests, revering only the first part of 05caa10 -2400th lines, is just enough to do it

**Comment by kd-11** [comment]
I know what the issue is, but there is no fix for the time being. The basic path of events is:
1. Render on surface target
2. Transfer to memory aliasing surface target
3. Invalidate surface target to force read from CPU
4. Since the corresponding read bit is not set (and even if it is set we use super_ptr for access) the graphics are missing
I need to finish work on the DMA cache and then redirect RCB/RDB to it instead of blindly using super_ptr. Or I can force RCB/RDB to use normal pointer at the cost of performance. Another alternative is for RCB/RDB to go through the texture cache somehow and perform a partial data collapse (again at the cost of performance).

**Comment by Xcedf** [comment]
Fair enough

**Comment by Xcedf** [comment]
Tried on latest builds, whatever it was it's fixed now
