### ISSUE TITLE
Nothing works on the latest alpha 0.0.7-8653

### ISSUE THREAD

**Issue by vsub** [RPCS3/rpcs3#6492]
It's been a while since the last time I updated rpcs3 and now when I tried the latest version,nothing works

I am getting this while trying to run any game while using nvidia and Vulkan
> F LDR: class std::runtime_error thrown: Assertion Failed! Vulkan API call failed with unrecoverable error: Out of video memory (VRAM) (VK_ERROR_OUT_OF_DEVICE_MEMORY)
> (in file C:\projects\rpcs3\rpcs3\Emu\RSX\VK\VKHelpers.h:275) 

nvidia and OGL
> F {RSX [0x0000000]} RSX: class std::runtime_error thrown: Verification failed (e=0x7f): 
> (in file C:\projects\rpcs3\rpcs3\Emu\RSX\GL\GLHelpers.h:937)

This while using intel and OGL
> F {RSX [0x0000000]} RSX: class std::runtime_error thrown: Verification failed: 
> (in file C:\projects\rpcs3\rpcs3\Emu\RSX\GL\GLHelpers.h:937)

And instantly dying(auto close)while using Intel and Vulkan

The weird part is,if I go back to the version I used before,rpcs3 is also doesn't work but any other emulator that can use OGL\Vulkan is working fine

And what is that suppose to mean

> F {PPU[0x1000000] Thread (main_thread) [0x00150e48]} class std::runtime_error thrown: Memory mapping failed - blame Windows (addr=0xc0000000, size=0xf900000, flags=0x43)

**Comment by AniLeo** [comment]
![image](https://user-images.githubusercontent.com/10283761/64477347-67e4f780-d192-11e9-85d3-390fc04541ae.png)

Doesn't crash for me on AMD, needs more information, logs, etc.

**Comment by vsub** [comment]
The usual,"Restart Windows fix",to fix your problems,fixed the problem

**Comment by M220** [comment]
They all point to the same problem with the memory and handling it. And everything works fine for me and Anileo, so it's a problem from your side and because of that, it would be better if the discussion continued in the dedicated discord server :)
Also, did you do a clean install of RPCS3 to see if that works? And did you overclock your RAM or changed the timing of it or...
If a clean install doesn't work then it's probably an issue with your windows and/or RAM
