### ISSUE TITLE
[NPEA00244] MOTORSTORM®: 3D RIFT no longer working

### ISSUE THREAD

**Issue by arabek** [RPCS3/rpcs3#6509]
Game crashes during startup. Fails with:
```
·F 0:00:09.783319 {RSX [0x0216968]} RSX: St13runtime_error thrown: Assertion failed: !region.is_locked()
(in file /home/arab/src/rpcs3/rpcs3/Emu/RSX/VK/VKTextureCache.h:1024)
```

Log: [RPCS3-master-v0.0.7-8673-aa262889.log.gz](https://github.com/RPCS3/rpcs3/files/3590235/RPCS3-master-v0.0.7-8673-aa262889.log.gz)

Last known working commit:
a5be410e3f03fb5a6e21ebe109715850694b368a

Log: [RPCS3-working-v0.0.7-8638-a5be410e.log.gz](https://github.com/RPCS3/rpcs3/files/3590237/RPCS3-working-v0.0.7-8638-a5be410e.log.gz)

**Comment by incognitoh** [comment]
yes, getting a very similar regression for AFRIKA™ BLUS30399, regression is also caused by #6467  It was ingame but now just menus.

AFRIKA RPCS3 v0.0.7-8670-0fcddf65:
vk:
F {RSX [0x0401590]} RSX: class std::runtime_error thrown: Assertion failed: !region.is_locked()
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\VK\VKTextureCache.h:1024)
ogl:
F {RSX [0x0310a40]} RSX: class std::runtime_error thrown: Assertion failed: !cached.is_locked()
(in file C:\projects\rpcs3\rpcs3\Emu\RSX\GL\GLTextureCache.h:835)

**Comment by kd-11** [comment]
Its a small collection of small lookup mask problems, I'll submit a fix soon. Technically this is a duplicate, but it can stay open as the trigger was a different commit.

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/6512

**Comment by arabek** [comment]
Works now. Awesome!
