### ISSUE TITLE
Angry Birds Trilogy [NPEB01235] glitchy graphics

### ISSUE THREAD

**Issue by benderscruffy** [RPCS3/rpcs3#6611]
during gameplay there are  graphic glitches with the birds and pigs and buildings
music doesnt play properly aswell
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3639348/RPCS3.log.gz)
[NPEB01235_20190922122547_capture.zip](https://github.com/RPCS3/rpcs3/files/3639349/NPEB01235_20190922122547_capture.zip)
[NPEB01235_20190922122106_capture.zip](https://github.com/RPCS3/rpcs3/files/3639350/NPEB01235_20190922122106_capture.zip)

**Comment by AniLeo** [comment]
Needs confirmation whether it happens on Vulkan as well or not

**Comment by benderscruffy** [comment]
sorry i cant test with Vulkan

**Comment by kd-11** [comment]
Looks to be broken mipmap LOD bias, broken mipmap generation code on the CPU by the game or shaders. Likely a combination of all the above.

**Comment by benderscruffy** [comment]
still happens in the latest master
here is a renderdoc
https://mega.nz/file/wrRQWKDC#cfnU_c9h6_t9m1_XaR-2dr7U9lSnnhscTlRhlUAk13c

**Comment by jokoputera** [comment]
Most of the shaders are being fix last month. Please recheck this game with latest master, then close if it fixed

**Comment by digitaldude555** [comment]
Fixed by #8367

**Comment by digitaldude555** [comment]
![Screenshot (2351)](https://user-images.githubusercontent.com/26138653/83954550-df93a000-a852-11ea-871c-f969222f347d.png)

**Comment by ultra0000** [comment]
There appears to have been a regression of some sort. Unsure if I should make a new issue for this (since I don't think it's directly related), or if this issue should just be re-opened.

<img width="1024" height="720" alt="Image" src="https://github.com/user-attachments/assets/25c16715-c65b-4dd3-9cfb-762158c06a15" />

<img width="1024" height="720" alt="Image" src="https://github.com/user-attachments/assets/d1fa1d02-bb8e-49e1-aab9-8171ca8de2a4" />

<img width="1024" height="720" alt="Image" src="https://github.com/user-attachments/assets/314fbff4-03f0-4900-8822-4dc5fff5b1bf" />
The game looked perfectly fine in older versions of the project.

**Comment by ultra0000** [comment]
UPDATE: v0.0.38-18522 appears to have fixed the issue.
<img width="1024" height="720" alt="Image" src="https://github.com/user-attachments/assets/ec126b3a-b78d-49fe-92b0-bdcfd7d69aae" />
