### ISSUE TITLE
Missing vcruntime140_1.dll file error

### ISSUE THREAD

**Issue by ThePapaw** [RPCS3/rpcs3#6651]
Just download v0.0.7-8779 Alpha [2019-09-26]  and when I try to run it, it is throwing a missing vcruntime140_1.dll error. I can go back to the previous version and everything is fine. Just when I try to update to this version or even a fresh install (Win 10-1903)

**Comment by MSuih** [comment]
Appveyor upgraded their Visual Studio version, so you need to update to latest version of Visual C++ Runtime as well. Link can be found in quickstart.

**Comment by AniLeo** [comment]
> THIS IS NOT A SUPPORT FORUM, FOR SUPPORT GO TO:
> https://forums.rpcs3.net
> or our discord:
> https://discord.me/RPCS3

...

**Comment by Psycho-A** [comment]
Is some way to back to previous VS version? I never needed to install newer Visual C++ Runtimes for any my software of even new games, and it's not really good if I need to do this only because of emulator. What about shipping vcruntime140_1.dll in the emulator bundle? It's the only new library that required emulator, and it works fine just with it and without VC2019 installed. Many software do such things, and this will free a huge number of users from installing unnecessary addons in their systems.

**Comment by kd-11** [comment]
New games come with their own vcredist that is installed silently without asking, but every piece of software since the 90s requires a runtime to work. Not sure what the huge problem is with installing the runtime; in the next year or so it will come bundled with games as developers upgrade to newer vs versions anyway.

**Comment by Psycho-A** [comment]
I just don't see any profits in "updates for updates"...

**Comment by kd-11** [comment]
Well, there was a bug in vs2017 that forced the update to vs2019; it wasn't done for fun. It worked fine with the old library until appveyor then decided to update the runtime on their end recently, this was not done by us.

**Comment by solo6807** [comment]
just install Microsoft Visual C++ Redistributable 2019 for your windows x86 or x64   that's all

**Comment by rajkosto** [comment]
Actually if you really don't want to require vcruntime140_1.dll (which is only required if you use EH4 exception handling, which lowers executable size and improves performance when exceptions are used) you can add a compiler switch vs in your project files...
```Add ‘-d2FH4-‘ to your cl.exe command line and ‘-d2:-FH4-‘ to the link line to revert back to the previous handler.``` source https://devblogs.microsoft.com/cppblog/making-cpp-exception-handling-smaller-x64/

but really, users should just install the runtime. it hurts nothing to always use the latest one since they are all backwards compatible.
