### ISSUE TITLE
Assertion failed on anv when rpcs3 is compiled with clang

### ISSUE THREAD

**Issue by linkmauve** [RPCS3/rpcs3#6848]
After the pipelines get compiled, rpcs3 invariably fails in this assert:
```
rpcs3: ../src/intel/vulkan/anv_private.h:1957: anv_buffer_get_range: Assertion `range + offset <= buffer->size' failed.
```

This happens on rpcs3 d53d7bb598545bf74836bfa2a3af96bb88880d3e, when running any game or homebrew using the Vulkan backend on Wayland using Mesa’s anv driver on an i5-8350u with an UHD 620 GPU, but only when rpcs3 is built with clang (9.0.0), with gcc (9.2.0) it works as expected.

Here is the stack trace from gdb: [rpcs3.txt](https://github.com/RPCS3/rpcs3/files/3762423/rpcs3.txt)

**Comment by linkmauve** [comment]
This issue has also been reported to anv: https://gitlab.freedesktop.org/mesa/mesa/issues/2016

**Comment by kd-11** [comment]
Attach the output of vulkaninfo command. It should be part of vulkan-utils or other similar package for your distro.

**Comment by linkmauve** [comment]
[vulkaninfo.txt](https://github.com/RPCS3/rpcs3/files/3780068/vulkaninfo.txt)

**Comment by baryluk** [comment]
I mentioned this on mesa, but could you try running rpcs3 with vulkan validation layers enabled first, and capturing renderdoc trace for replays?

**Comment by linkmauve** [comment]
I can’t capture renderdoc traces, as soon as I press PrntScr I see the memory usage skyrocket and then the OOM killer triggers and picks rpcs3.

I’m already in the process of enabling validation layers, just reading about it.

**Comment by kd-11** [comment]
From a quick glance, it looks to be the size of the view requested being too large. The buffer object is 16M but the view requested is 128M.

**Comment by kd-11** [comment]
@linkmauve I fixed the offending function earlier today I think. Check if it still happens.

**Comment by baryluk** [comment]
You can probably try this environment variables:

`VK_LOADER_DEBUG=all VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation`

or

`VK_LOADER_DEBUG=all VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_standard_validation`

without even modifying the source code.

Or manually add some command line flag to enable validation layer from inside the app.

VK_LAYER_KHRONOS_validation is more modern one, and incorporates all older validation layers. VK_LAYER_LUNARG_standard_validation is older validation meta-layer that loads other validation layers in proper order.

VK_LAYER_KHRONOS_validation by default enables I think all validation layers with exception of few minor ones, but it should be enough to capture issues related to buffer sizes and offsets. You can also configure some details in `vk_layer_settings.txt` in current working directory or in `$HOME/.local/share/vulkan/settings.d/vk_layer_settings.txt`, for example:

```
lunarg_core_validation.report_flags = info,error
lunarg_core_validation.debug_action = VK_DBG_LAYER_ACTION_LOG_MSG
```

Otherwise it might be not outputing anything, as that requires debug extensions and app initalized callbacks.

I would also recommend these, because the app is crashing some some messages my be lost otherwise:

```
lunarg_api_dump.no_addr = TRUE
lunarg_api_dump.file = FALSE
# Print all calls and arguments, or just function signature (names).
lunarg_api_dump.detailed = TRUE
# Force I/O flush after every line.
lunarg_api_dump.flush = TRUE
```

This is for older meta-layer, `VK_LAYER_LUNARG_standard_validation`, but I am sure there are similar flags for a new consolidated layer `VK_LAYER_KHRONOS_validation`.

**Comment by linkmauve** [comment]
Thanks for your guide!

Here is a log using the Khronos validation layer: [validation.txt](https://github.com/RPCS3/rpcs3/files/3780305/validation.txt)

**Comment by kd-11** [comment]
Ironically the imaging issues were fixed by https://github.com/kd-11/rpcs3/commit/c4e66f7ef34f591a4da5c617f9897583e26c041d which is not yet in master.
@linkmauve It would have been best to generate the log with a sample like triangle or cube to avoid the output noise. Btw, does master still crash running samples?

**Comment by baryluk** [comment]
Further reading on layers:

https://vulkan.lunarg.com/doc/view/1.1.82.0/windows/layer_configuration.html
https://www.khronos.org/assets/uploads/events/LunarG-Layers-Webinar-Sept-2016.pdf
https://www.lunarg.com/wp-content/uploads/2019/04/UberLayer_V3.pdf
https://www.lunarg.com/wp-content/uploads/2019/06/GPU-Assisted-Validation-Phase-2_final.pdf


Yeah. I expect compilation with clang leads to some undefined behaviour, probably due to a bug in your code that is optimized differently, i.e. uninitalized variable used somewhere.

Running under `valgrind` could (with debug symbols present) help with that too.

I you should fix all validation layers errors you have:

https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkPipelineDepthStencilStateCreateInfo-depthBoundsTestEnable-00598
https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkBufferImageCopy-imageOffset-00197
https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkBufferImageCopy-imageOffset-00198
https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkDestroyInstance-instance-00629


It is possible the second or third one listed above is actual culprit, but I am would be certain of that.

**Comment by kd-11** [comment]
1. There was indeed an unitialized variable, this was already fixed by https://github.com/RPCS3/rpcs3/commit/479d92d075b161b27101a9ba683a0a23b800bf30

2. The image extent problems were solved by https://github.com/kd-11/rpcs3/commit/c4e66f7ef34f591a4da5c617f9897583e26c041d but this has not been merged into master yet. It was caused by some compressed textures not aligned to the block dimensions.

3. ANV is the first driver I have seen where depthBounds is not enabled by default, we actually need it for rpcs3 to work correctly since PS3 uses it. I'll add the enable flag when creating instance to remove the error.

4. The dangling surface object is a bug in the wayland path since it does not appear on windows or X11, although it couldn't have caused the crash. Will clean it up later.

**Comment by baryluk** [comment]
Great to hear. I think you need to check `VkPhysicalDeviceFeatures` first for `depthBounds == 1` (and exit application otherwise I guess, or try other physical device if there are multiple of them), which means the driver and hardware does support it, and then when creating a `VkDevice` via `vkCreateDevice` pass `VkDeviceCreateInfo`, with `VkDeviceCreateInfo::pEnabledFeatures` pointing to your (zero initalized) `VkPhysicalDeviceFeatures` with `depthBounds = 1`, to enable it. (You should NOT just blindly pass full `VkPhysicalDeviceFeatures` returned from `vkGetPhysicalDeviceFeatures` or `VkPhysicalDeviceFeatures2`, as that can have serious performance impact).

Most drivers (including Intel one) are pretty lax and will enable and support depthBound stuff even if you not enable it, but that is against the spec generally.

**Comment by baryluk** [comment]
https://vulkan.gpuinfo.org/listfeatures.php says that about 75% of devices (on Windows, Linux and Android) support depthBound in features, which is a bit low. Exploring the data base deeper, could tell you which devices and platforms does support it or not.

**Comment by kd-11** [comment]
Looks like intel isn't on the list of drivers/devices supporting depth bounds testing. I'll see about just emitting an error and attempting to continue while skipping the bounds test. VIsuals may break but at least it shouldn't just crash/die.

**Comment by baryluk** [comment]
You are right, the vulkaninfo.txt file by @linkmauve indeed shows missing support for this:

```
VkPhysicalDeviceFeatures:
=========================
...
	depthBounds                             = 0
...
```


It does also explain why the gpuinfo DB only shows 75% for the supported.

It is possible to emulate depth bounds at least one sided , but with major performance impact, by clearing depth buffer , rendering full screen quad with specified depth, and then rendering your geometry with depth write disabled, or something. I don't know. Very hackish. Or maybe it can be done somehow with clip planes. Or maybe there are ways to discard fragments in fragment shader? GLSL supports keyword 'discard' in fragment (pixel) shaders, that terminates the shader and do not write to color or depth/stencil buffers. You could set min/max depth bounds via some uniforms or push constants. Or maybe you don't really need depth bound tests. Things are up to you.

**Comment by baryluk** [comment]
I checked mesa source and depth bounds should be supported on Intel GFX12 (Intel Tiger Lake and Intel Xe dGPU). Also in the driver there is a minor workaround for DOOM and Wolfenstain (idTech engine) to fake support, by saying it is supported anyway, and hope for the best...

But indeed it looks like Gen11 and older hardware doesn't support it.

**Comment by linkmauve** [comment]
Note that the current check, introduced in 7a5c20ef858979e35c9655e682add93f6d24b8c8, completely prevents rpcs3 from running on anv on any existing Intel GPU. You should first check for the feature on the physical device before enabling it.

It crashes with:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Assertion Failed! Vulkan API call failed with unrecoverable error: Requested feature not available (VK_ERROR_FEATURE_NOT_PRESENT)
(in file rpcs3/Emu/RSX/VK/VKHelpers.h:810)
zsh: abort (core dumped)  bin/rpcs3
```

**Comment by kd-11** [comment]
> You should first check for the feature on the physical device before enabling it.

Should I though? I mean, the rest of the code assumes the driver has support for the requested feature, not whether the backend supports it. The only result here will be a change of the assert message to refuse to boot if the hardware does not support the required extensions. Either way, its not booting with MSAA enabled on ANV.

**Comment by linkmauve** [comment]
Oh, I didn’t know it was used like that also when emulated, but it makes sense as force-enabling it on other emulators can also break effects (I’m thinking about the goo in Super Mario Sunshine for instance).

Anyway, I just built rpcs3 with clang and can’t reproduce this issue anymore, so I guess we can close it and move this discussion to #6916, thanks!

**Comment by baryluk** [comment]
> Should I though?

Yes. This is required by the Vulkan spec.

>  I mean, the rest of the code assumes the driver has support for the requested feature, not whether the backend supports it.

Driver is free to return errors, crash or result in incorrect rendering if you don't ask for it. This is exactly what did happen. This is a correct behaviour and anv crashing is not anv bug at all. It is done on purpose (error checking at runtime would make it have impact on performance).

**Comment by kd-11** [comment]
Clearly you misunderstand, I don't mean not checking for feature support - this is already done. I mean, there is no fallback path for the missing feature so the rest of the backend need not check for the feature and choose to do something else. There is only one outcome - assertion.
