### ISSUE TITLE
anv: Assert due to missing shaderStorageImageMultisample feature when anti-aliasing is enabled

### ISSUE THREAD

**Issue by linkmauve** [RPCS3/rpcs3#6916]
Here is the capture which triggered this issue: https://files.sshnuke.net/BLUS30109_20191029014409_capture.7z

This happens on rpcs3 ff423f7d377b05322b9f1838458152cd092c842f, running on an i5-8350u with an UHD 620 GPU, with Mesa 78285af2b37, using the Vulkan backend.

Here is the stack trace of the crash: [rpcs3.txt](https://github.com/RPCS3/rpcs3/files/3783508/rpcs3.txt)

This doesn’t happen when anti-aliasing is disabled instead of auto.

**Comment by kd-11** [comment]
It crashes because ANV does not support image load store on the format. We need image load/store to do image resolve and unresolve without falling back to a graphics pass which is slow and cannot be executed asynchronously. A workaround is to just disable antialiasing for ANV since we cannot tell before the game is launched if it will require antialiasing on a given format. By the way, the triggering format is the spec-guaranteed format VK_FORMAT_B8G8R8A8_UNORM; if this format is not supported in compute, its highly likely none of them will be.

**Comment by kd-11** [comment]
Before I nuke AA on intel, need someone to check how it behaves with properietary windows drivers.

**Comment by linkmauve** [comment]
I’ve also cross-referenced it at Mesa: https://gitlab.freedesktop.org/mesa/mesa/issues/2019

**Comment by baryluk** [comment]
Before reporting to Mesa, please follow similar procedure of using validation layers first, as I explained here:

https://github.com/RPCS3/rpcs3/issues/6848

If you can also run entire rpcs3 under valgrind (and preferably have Mesa compiled with `-Dvalgrind=true` and debug symbols enabled `-ggdb` in c_args and cc_args ), if you can.

**Comment by baryluk** [comment]
@kd-11  Would it more useful to detect  a format property? The `VkFormatFeatureFlags` for linearTiling and optimalTiling list `Vk`FormatFeatureFlagsBits`, that are supported for each format, i.e. `VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT / VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT` maybe?

If you have a launcher or something that don't have this info available, it is probably best to return with an error back to launcher and popup an error with some message why. Would at least prevent a crash, and user will be able to switch back to auto or disabled.

**Comment by kd-11** [comment]
That's what I was intending on doing. The framework for checking format flags is there and already used for other things like image filtering; but this will have the same effect of disabling AA on intel cards.

**Comment by kacperoo29** [comment]
Well it happens on a AMD R9 390 with most recent drivers too, so it isn't a Intel issue only. After disabling AA or switching to OpenGL everything works fine.

**Comment by kd-11** [comment]
See https://github.com/RPCS3/rpcs3/pull/6919. AMD issue is unrelated to this one.

**Comment by kd-11** [comment]
How does the official intel driver work? Does it support image_load_store? I assume it should in theory since it should exist on OpenGL as well, meaning ANV is simply missing the featureset. Either way I see no reason to keep this open.

**Comment by linkmauve** [comment]
Anv is the only official Vulkan driver on Linux, there are no other drivers for this hardware.

**Comment by Leopard1907** [comment]
Then Intel team should fix it. Jason Ekstrand and others i mean. Also if you can , try with Iris. Maybe that can change things a bit.

**Comment by linkmauve** [comment]
Iris is an OpenGL driver (the one I use incidentally), I haven’t been able to play much with it in rpcs3 due to #6835 so far, as I mostly don’t use Xwayland.

**Comment by kd-11** [comment]
From the reply from the issue.. `Both of which our driver/HW doesn't support.`

An assert is not really a problem if it does not cause the application to stop working in an unexpected way and rpcs3 no longer asserts the driver with current release, it should throw in the application and suggest the user disable MSAA to work around it. As for intel hardware, it may actually not support shader storage images in hw, I can't tell for sure without someone checking with the proprietary driver. Either way, that's for the driver team to work on.

**Comment by paulche10** [comment]
Hi all
Please, take a look on https://gitlab.freedesktop.org/mesa/mesa/issues/2019
It's not a mesa issue.

**Comment by kd-11** [comment]
I'm fairly certain that was agreed upon from the beginning and workarounds added. ANV/Intel hw cannot use the PS3's MSAA feature at the moment based on supported features. To "fix" the remaining assert (which the emulator will warn the user is going to happen due to missing support) shader storage image support is required.

**Comment by AniLeo** [comment]
Referencing https://gitlab.freedesktop.org/mesa/mesa/-/issues/3355 regarding this issue

Regarding the Windows proprietary Intel driver, it works with Anti-Aliasing enabled and it exposes `shaderStorageImageMultisample = true` on vulkaninfo

On anv, the feature is not exposed and the emulator crashes

Since there's no hardware support for this feature, being a hardware issue, RPCS3 should probably have a failsafe here and check whether this feature is present or not instead of crashing if it isn't
