### ISSUE TITLE
Problems with multiple gamepads after #6615 (linux)

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#6921]
Archlinux, rev9047
I have 2 gamepads: an arcade stick and a xbox controller.
If I declare just 1 of them (player1:evdev, player2:null): it works fine.
But if I declare player1:arcade stick, player2:xbox, it's all messed up: in the gamepad test application, if I press any button on the arcade stick, it doesn't register. If I move the analog stick on the xbox, it registers as analog left stick. But if I press any button on the xbox, nothing registers.
rev8768 was working with 2 gamepads
rev8769 is not working, so the culprit is #6615

**Comment by wilsoft-gt** [comment]
Same issue here (I think)
RPCS3 Version: 0.0.7-9075-531afe0f Alpha
Ubuntu 18.04.1

lsusb log:

> Bus 001 Device 002: ID 0079:0006 DragonRise Inc. PC TWIN SHOCK Gamepad
> Bus 001 Device 011: ID 0079:0006 DragonRise Inc. PC TWIN SHOCK Gamepad

When I connect the first one it works perfect, the issue is when I connect the second one and configure it, when i move the left stick on Player 1 it moves the stick in Player 2 and player one stop working. I think that it is taking the 2 controllers as one.

**Comment by RipleyTom** [comment]
Can you try https://github.com/RPCS3/rpcs3/pull/6950 ?

**Comment by wilsoft-gt** [comment]
> Can you try #6950 ?

How can I do that? I'm using the appimage one

**Comment by wilsoft-gt** [comment]
> Can you try #6950 ?

Worked perfectly with #6950 !! thanks a lot @RipleyTom

**Comment by toccata10** [comment]
Fixed. Thanks.
