### ISSUE TITLE
Skate 3 [BLES00760] possible z-culling issue.

### ISSUE THREAD

**Issue by Cereal-Killa** [RPCS3/rpcs3#6932]
I have noticed that by simply rotating camera towards a direction which contains a large area to render, but! that view is blocked by another object, the fps will still drop anywhere between 10 to 20 frames.

Could this possibly be an issue with z-culling since the stuff cannot be seen and thus should not affect the performance?

Facing a direction which leads to the end of the map:
![xh2etCZyd9](https://user-images.githubusercontent.com/25939765/68046478-bdcdab80-fcba-11e9-8e52-5911c833a8f7.png)

Facing the opposite direction that contains the remainder of the map:
![ZfqZNrPc9M](https://user-images.githubusercontent.com/25939765/68046552-e6ee3c00-fcba-11e9-8dd7-26be4f157534.png)

[RPCS3 .log.gz](https://github.com/RPCS3/rpcs3/files/3799112/RPCS3.log.gz)

**Comment by kd-11** [comment]
Performance drops cannot be tracked as an "issue" otherwise we'd have thousands of open issues. Problems with PS3 zcull model conflicting with vulkan are well known at this point. That being said, maybe try [this experimental build.](https://ci.appveyor.com/project/kd-11/rpcs3/builds/28332085) If nothing changes, its not really zcull. Skate3 can hammer the GPU with a ton of small draw calls which is why performance can drop at times, but agian this is known. Progress is steady in alleviating this problem, you can check builds from 6-12 months ago and see a huge difference compared to present day.

**Comment by Cereal-Killa** [comment]
Thank you @kd-11, tried that build and the same thing happens, made a short video any case.


[https://wetransfer.com/downloads/9f2b08f382332ff8f0a1f2f538a2940720191101185520/975e1de0cb494650e50f8a00fc25a43a20191101185520/5e30ed](url)
