### ISSUE TITLE
Need for Speed Most Wanted 2012 Prototype audio issues

### ISSUE THREAD

**Issue by jason0987** [RPCS3/rpcs3#7070]
RPCS3 v0.0.7-9207-e050dcbc Alpha | master | Firmware version: 4.85
AMD Ryzen 5 3600 6-Core Processor | 12 Threads | 15.58 GiB RAM | TSC: Bad | AVX+
Operating system: POSIX, Name: Linux, Release: 5.4.1-2.g41180ce-default, Version: #1 SMP Wed Dec 4 05:46:13 UTC 2019 (41180ce)
·! 0:00:00.000000 RSX: Found vulkan-compatible GPU: 'AMD RADV/ACO POLARIS10 (LLVM 9.0.0)' running on driver 19.99.99

No matter the Audio Backend, OS, SPU Decoder, PPU Decoder or any other settings, in-game audio will always break to varying degrees. Xfloat seems to play a role here as enabling Accurate xfloat gives the worst results (you will only hear crackling and popping).
[https://www.youtube.com/watch?v=eY3tU-Grtzo](url) - RPCS3
[https://www.youtube.com/watch?v=CjY-TwwKSz8](url) - PS3 (also has a download link in the comments)

[rpcs3.zip](https://github.com/RPCS3/rpcs3/files/3932225/rpcs3.zip)

**Comment by Asinin3** [comment]
Accurate xfloat uses extremely slow code paths. Generally audio can be awful the slower the audio threads are running. So performance is key. Try default settings with vulkan (so ppu+spu llvm and no accurate xfloat). Then try 1, 2 and 3 preferred spu threads and disabling spu loop detection.

Generally speaking this is just a generic issue and I doubt anything can be found from the log file aside from settings. Some games have far better audio on 16threaded CPU's because the audio thread isn't being starved.

**Comment by jason0987** [comment]
> Accurate xfloat uses extremely slow code paths. Generally audio can be awful the slower the audio threads are running. So performance is key. Try default settings with vulkan (so ppu+spu llvm and no accurate xfloat). Then try 1, 2 and 3 preferred spu threads and disabling spu loop detection.
> 
> Generally speaking this is just a generic issue and I doubt anything can be found from the log file aside from settings. Some games have far better audio on 16threaded CPU's because the audio thread isn't being starved.

So can nothing really be done about this? Maybe giving the audio threads higher priority?

**Comment by Asinin3** [comment]
The audio will probably just get better on its own as performance improve. Like you said, the settings I suggested did help, it's probably just a general performance issue and we need more optimizations. For this reason, reports like "audio is broken in x game" usually don't do much for us because it's generally just due to a combination of the way that game handles audio mixing and RPCS3 not being fast enough, or the user not having enough threads or a fast enough cpu to get around starving the audio threads.
