### ISSUE TITLE
Skylanders: Spyro's Adventure verification failed (e=0x57) on sys_usbd_transfer_data

### ISSUE THREAD

**Issue by Graubek** [RPCS3/rpcs3#7101]
Hello, why i can't play Skylanders Spyro's Adventure? It writes me: F {PPU[0x1000017] Thread (300e3d50)} class std::runtime_error thrown: Verification failed (e=0x57): 
(in file C:\projects\rpcs3\rpcs3\Emu\Io\Skylander.cpp:105) What i can do with that?
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/3964814/RPCS3.log.gz)
![Bez tytułu](https://user-images.githubusercontent.com/58905125/70861628-1eded500-1f31-11ea-9c98-0fb311f3b09e.png)

**Comment by AniLeo** [comment]
@RipleyTom is probably the right person to triage this

**Comment by RipleyTom** [comment]
I tried it and sadly even if I remove the asserts and use a repaired "file/figure" the game fails to load the figure properly(it seems to loop endlessly).
Probably no easy fix but I'll take a look when I have time.

**Comment by bevanweiss** [comment]
@Graubek are you able to retest and confirm that it is still an issue? (and if so, please provide a fresh log)

**Comment by Frozenreflex** [comment]
I know this is pretty old, but I've been trying to play this game and have gotten a similar issue. The error seems to be occurring 5 lines down from the one above, but they're both verify(HERE). Using the emulated portal. I've got a log here, I couldn't find the location of the log files so I copied the one in the window to a text file. The game seems to crash at different points, sometimes it crashes with the loading circle icon, sometimes it crashes on a dark green screen, and once I got to the logo. I don't think it matters, but I'm using Linux Mint. I'm also using a build that is a week old since the newest builds cause all of my games to crash on start.

[spyro.txt](https://github.com/RPCS3/rpcs3/files/5654692/spyro.txt)

**Comment by RipleyTom** [comment]
Did you follow the instructions here?
https://wiki.rpcs3.net/index.php?title=Help:Peripherals_and_accessories#cellUsbd_Set-up_Instructions

Real portal should work just fine with the emulator as long as you setup the proper driver for it.

**Comment by Frozenreflex** [comment]
Ah, I didn't know that was a thing. I set up the USB device and that works now, thanks, I guess the next thing would be finding out why the portal emu crashes? The list of character IDs is also out of date if i recall correctly.

There seems to be absolutely atrocious lag spikes, it wouldn't crash like it has before but it would freeze for a solid one or two minutes before going back to normal for ten or so seconds, and the music and background ambience would play normally.
