### ISSUE TITLE
RSX code in maintenance mode

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#7220]
RSX code is now in maintenance mode until all current regressions are fixed. This is a meta tracker for this subtask:

Blockers:
1. Reported
- [x] https://github.com/RPCS3/rpcs3/issues/7241
- [x] https://github.com/RPCS3/rpcs3/issues/7240
- [x] https://github.com/RPCS3/rpcs3/issues/7225
- [x] https://github.com/RPCS3/rpcs3/issues/7224
- [x] https://github.com/RPCS3/rpcs3/issues/7063
- [x] https://github.com/RPCS3/rpcs3/issues/6968
- [x] https://github.com/RPCS3/rpcs3/issues/6822
- [x] https://github.com/RPCS3/rpcs3/issues/6735
- [x] https://github.com/RPCS3/rpcs3/issues/6719
- [x] https://github.com/RPCS3/rpcs3/issues/6341
- [x] https://github.com/RPCS3/rpcs3/issues/6311
- [x] https://github.com/RPCS3/rpcs3/issues/6197
- [x] https://github.com/RPCS3/rpcs3/issues/6156
- [x] https://github.com/RPCS3/rpcs3/issues/6032
- [x] https://github.com/RPCS3/rpcs3/issues/5938
- [x] https://github.com/RPCS3/rpcs3/issues/5872
- [x] https://github.com/RPCS3/rpcs3/issues/5526

2. No specific issue raised
- [x] MTRSX causes emulator freeze with "vk::wait_for_event timed out" error messages.
- [x] R&C new games need WCB to flip properly.

**Comment by Aurez** [comment]
what about #6719 ?

**Comment by kd-11** [comment]
Added

**Comment by StevenMiller123** [comment]
Wouldn't #6803 be related to this? It was caused by PR #6737 (rsx: Recover from invalid writes to CELL_GCM_NV4097_SET_INDEX_ARRAY_DMA)

**Comment by kd-11** [comment]
No, it was always supposed to be crashing. We went so far as to check what a PS3 would say about the crap DBZ was pushing to RSX and it also crashed. May be improved by the fifo wake PR currently open.

**Comment by kd-11** [comment]
Note to self: remember to investigate https://github.com/RPCS3/rpcs3/issues/6419
While not really a bug, its worth reviewing the implementation while I'm at it.

**Comment by Xcedf** [comment]
@kd-11 while making a new gow custom version i discovered that this https://github.com/RPCS3/rpcs3/issues/6419 was wrong, the real issue is in PR -https://github.com/RPCS3/rpcs3/pull/6359, and only WCB path became slower, noticed in GoW and RDR yet not have time to investigate it properly. https://github.com/RPCS3/rpcs3/issues/6419  was wrong so closing it.

**Comment by kd-11** [comment]
Closed it.

**Comment by incognitoh** [comment]
(BLES00668)  This regression is over 6 months old caused by #6164  it basically affects player's faces. it seems to be always just the opponent's face.. and the glitch occurs throughout the entire match. the glitch doesnt seem to happen on all players but it does on most of them i tested.  last build that works correctly is 0.6-8341-b9130dd6.  regression is still active on current master.   

rsx capture: https://mega.nz/#!lYFVyA7R!PvHz9GhwV1xIYGhKB1l75tzUpnnDAPJB2SmPC_WnoME
<details>
<summary>pics</summary>
<br>
0.0.6-8341-b9130dd6:

![tp0](https://user-images.githubusercontent.com/39333810/72205252-d8589980-344e-11ea-81b0-8eada9e6b2c9.jpg)

0.0.6-8349-2548057e:
![tp1](https://user-images.githubusercontent.com/39333810/72205251-d7c00300-344e-11ea-8bbb-3336a880dabf.jpg)

master:
![tp3](https://user-images.githubusercontent.com/39333810/73473098-2a0f8800-435a-11ea-9285-8f8cbda83bf1.jpg)


win 10
gpu gtx1070 -driver 441.66

</details>

**Comment by kd-11** [comment]
Wasn't this fixed months ago? I'm pretty sure I pushed a fix for it at some point.

**Comment by AniLeo** [comment]
#7395 should be added, regressed from a recent PR for one of the issues here

**Comment by kd-11** [comment]
It's trivial enough to be 'fixed up' so I don't think it earns a place with the other major regressions from before this ticket.

**Comment by PlatinSource** [comment]
I hope I am not too late, but I think issue #6311 (Regression: Sacred 2 [BLES00410]) was forgotten, or was it left out on purpose?

**Comment by kd-11** [comment]
I'll add it, but update your findings with the very latest master just in case.

**Comment by kd-11** [comment]
Major problems fixed. Will keep doing cleanup as testing continues for the next few days.
