### ISSUE TITLE
[Regression] Uncharted 2 shadow-map depth issue. Nvidia Only?

### ISSUE THREAD

**Issue by Xcedf** [RPCS3/rpcs3#7241]
Found  time to debug this one at last, in Uncahrted 2 at some points shadow-mapping looks wrong and line-artifacted.
Issue happened in https://github.com/RPCS3/rpcs3/pull/6448 commit 4311cf142.
The issue itself looks like this:
![31](https://user-images.githubusercontent.com/7060586/72301574-3ddb9e80-3678-11ea-8ce9-b438ea1d719b.jpg)
![30](https://user-images.githubusercontent.com/7060586/72301578-4633d980-3678-11ea-9ccf-2d5aebcb2aa0.jpg)

Since i'm on Nvidia, looked only at that. In commit 4311cf142 optimal_kernel_size old value is 16 current value is 1, considering the commentary about Nier and it's performance i looked on some other values, and 4 is minimal to get correct footage, so:

At optimal_kernel_size = 4;
![33](https://user-images.githubusercontent.com/7060586/72301602-58ae1300-3678-11ea-83e0-0e27b8f966c3.jpg)
![32](https://user-images.githubusercontent.com/7060586/72301607-5e0b5d80-3678-11ea-843d-dc20c3943dcc.jpg)

I don't have Nier to sy if there's a performance impact, and of couse i can't say what's going on on other vendors.
And all these screens from older build, which is look fine with all these values, when i try to set optimal_kernel_size = 4 on current builds i have no shadowmapping at all:
![36](https://user-images.githubusercontent.com/7060586/72326824-01806080-36c1-11ea-99e4-75d32f058235.jpg)

and fmv sceen looks like this
![29](https://user-images.githubusercontent.com/7060586/72301619-6a8fb600-3678-11ea-88de-1459c8a07f85.jpg)
will do more tests about it.

**Comment by Xcedf** [comment]
Update:
The second half of regression while applying optimal_kernel_size = 4 on newer builds caused by
https://github.com/RPCS3/rpcs3/pull/6941, first two commits, mostly second commit i guess

**Comment by kd-11** [comment]
Those parameters should not affect visual output, only performance. Need RSX capture to verify at the very least. Since the 'bytes_per_invocation' number is just kernel_size * group_size, the calculations should just have had 4x more invocations compared to kernel_size = 4 but does the same amount of work. I have no idea why its misbehaving on nvidia, could be another quirk that needs workarounds and possibly reporting.

**Comment by kd-11** [comment]
If you have a pascal GPU, try getting a renderdoc capture as well, my GPU may be able to replay it.

**Comment by Xcedf** [comment]
I'm on Maxwell 1070, and seems foud some way to put it in newer revisions
in VKCompute.h line 283, multiplying gl_GlobalInvocationID.x by KERNEL_SIZE as it was before the PR allowed me to set kernel_size = 4 without any graphical issues:
![33](https://user-images.githubusercontent.com/7060586/72345610-3e5e4e80-36e5-11ea-89ab-ffcbd30f2fef.jpg)
![32](https://user-images.githubusercontent.com/7060586/72345615-428a6c00-36e5-11ea-8f50-f0369f24ead3.jpg)

**Comment by kd-11** [comment]
1) 1070 is pascal, so your RDC may be replayable on my 1050ti
2) I added a fix for the KERNEL_SIZE to the compute heap PR https://github.com/RPCS3/rpcs3/pull/7244

That being said, it should still have no effect on the visual output whether you use 4 or 1 since the input works with full dwords; I'm guessing something else is wrong with the setup which can only be determined by looking at the RDCs for it. RSX capture may also help to recreate the conditions locally and examine why the GPU seems to care how many bytes are consumed per invocation.

**Comment by kd-11** [comment]
Actually nvm, I know whats wrong.

**Comment by kd-11** [comment]
Ok, pushed another small fix to the same PR. Get two RDCs of a simple scene with the PR build, one with size 1 and another with size 4 so we can see what can be now causing the error.

**Comment by Xcedf** [comment]
@kd11 here's two render docs from scene with flashlight
kernel_size =1
https://mega.nz/#!OAIngAbK!d5ZpxgIP1_Ent3WehIuJgq_QM2iA0LnELODKeatWPQA
kernel_size =4
https://mega.nz/#!zIRXTK6J!PGv-nw-cxPNmdRJh1MfdYPqMMQz9bB6zMDTYMJWwP_g

**Comment by kd-11** [comment]
Thanks.

**Comment by kd-11** [comment]
It's a write ordering issue, resolved with https://github.com/RPCS3/rpcs3/pull/7249
