### ISSUE TITLE
[Feature Request] Compile shaders from raw RSX shader cache

### ISSUE THREAD

**Issue by SonofUgly** [RPCS3/rpcs3#7255]
Currently raw shader data is cached, but it seems to go unused. If the raw cache is there and the target API shaders aren't, they should be compiled from the raw cache at boot instead of having users replay through the game to rebuild the cache.
This would prevent users having to rebuild their cache after the shader version changes, or when switching between OpenGL and Vulkan.
It would also make sharing shaders much more viable, as users could just share the raw cache which would never become outdated.

**Comment by kd-11** [comment]
You cannot compile the raw shaders by themselves, a PS3 is not one-to-one mappable to a PC. You need emulation state structures as well to help decode the raw shaders; they cannot be compiled by themselves. Changes in the data stored as 'relevant emulation state' are what invalidate the previous cache.

**Comment by SonofUgly** [comment]
Well that's unfortunate.
> You need emulation state structures as well to help decode the raw shaders

What's the use of saving raw shaders at all then?

**Comment by kd-11** [comment]
> What's the use of saving raw shaders at all then?

How are we supposed to compile the shaders before loading the game without them? You can grab them at runtime but until the game actually boots and is running, you need them as an input.

**Comment by SonofUgly** [comment]
Guess I really don't understand how RPCS3 handles shaders. So recompiled shaders (say vulkan) aren't saved on disk, the /pipelines/vulkan/ are 'emulation state' information and that's used at game boot to recompile the raw shaders to vulkan shaders?

**Comment by kd-11** [comment]
Yes. This is currently done this way to avoid invalidating the cache too often. While it is possible to eventually support hybrid loading, tests show that the decompilation step is actually not time-consuming. e.g with the current multithreaded loading, it can take less than a second to load a ton of shaders from an SSD. Loading means loading from disk and decompiling to API-specific formats. The next step is the slow part of any GPU program loading - linking. This is where the various stages are put together into a single unit that can be used directly. You cannot cache this, its cached by the driver itself.

**Comment by SonofUgly** [comment]
Okay, so I think that's similar to what Cemu and yuzu's OpenGL transferable cache does. Is the difference then just their 'emulation state' is simpler/locked down, while RPCS3's is more complex/in development? Do you think there will be a point were things are finalized and shaders wont be invalidated?
Thanks for taking the time to explain things.

**Comment by kd-11** [comment]
I have no idea what cemu/yuzu are doing, it depends on the graphics chip being emulated. And yes, eventually there should be no need to invalidate the cache, but can't make any promises due to unknown unknowns. Sometimes everything looks good until you encounter a corner case and have to restructure again. Depending on the microcode structure the chip uses for shaders, it may be possible to precompile the raw shaders, but the PS3 is not friendly enough to do so as part of the shader's variable state is stored in GPU registers separate from the shader itself. This includes things you would never expect including what type of texture is being sampled for example (1D, 2D, 3D, cubemap, they all share the same instruction with no hints). There are other examples of critical information being loaded outside the shader code itself making things inconvenient.
I'd say, just be patient, even now rpcs3 keeps shader cache versions for a long time, it's quite rare these days for the structure to change.
