### ISSUE TITLE
Resistance 2 Graphical Issues.

### ISSUE THREAD

**Issue by digitaldude555** [RPCS3/rpcs3#7294]
- [x] Broken Flashlight. 
![Screenshot (898)](https://user-images.githubusercontent.com/26138653/72750637-10d24300-3bc6-11ea-9594-c6b73077ac7b.png)

- [x] Broken lighting when close to rocks.

Normal.
![Screenshot (887)](https://user-images.githubusercontent.com/26138653/72750681-2f383e80-3bc6-11ea-94f4-c0a161d0823a.png)
Zoomed in it turns white.
![Screenshot (888)](https://user-images.githubusercontent.com/26138653/72750715-424b0e80-3bc6-11ea-9dbd-736c195b7826.png)

Might be other issues if you guys know report them here.

**Comment by lainiwaku** [comment]
there are a level that is almost dark and is supposed to be played with torchlight,  you still can finish the level since there are very little light but it's like  a complete maze to find the way out 
torch ON 
![Screenshot (37)](https://user-images.githubusercontent.com/1077909/73859951-2341b300-483b-11ea-95de-74194a129684.png)
torch OFF
![Screenshot (38)](https://user-images.githubusercontent.com/1077909/73859965-26d53a00-483b-11ea-9f2e-58c0fe322f58.png)

**Comment by digitaldude555** [comment]
![Screenshot (2363)](https://user-images.githubusercontent.com/26138653/84564281-b484e100-ad69-11ea-88af-ff2bb8028060.png)
flashlight and lighting fixed, closing.
