### ISSUE TITLE
Would it make a Cg to SPIR-V translator without GLSL ?

### ISSUE THREAD

**Issue by metarutaiga** [RPCS3/rpcs3#7309]
I found DXVK that has a DX9 shader translator (decoding DXSO and emit it in SPIR-V module).
But RPCS3 still seem to support OpenGL? maybe GL_ARB_gl_spirv can support it if we abandon GLSL?

**Comment by kd-11** [comment]
It's being worked on but not a priority. Not much to actually gain from this either other than making it harder to write the other shaders we require for vertex decode, compute or UI, so the glsl version will never go away. It works for dxvk because both shaders in and out are supposed to run on the same device (PC)  making the featureset compatible. Unfortunately for us there is heavy emulation of instructions making it a pain to work in IR only.

**Comment by metarutaiga** [comment]
I known it couldn't boost any graphic performance. 
The graphic vendors are doing a optimization from SPIR-V to ISA always.
So I think how about the shader compiling time, where is the slowest part?

Otherwise,  RPCS3 is using VK_NV_glsl_shader in Vulkan right?

**Comment by kd-11** [comment]
> So I think how about the shader compiling time, where is the slowest part?

Program linking is the slowest part. Nothing can be done about that other than trying to use some annoying tricks like telling the driver to link without optimizations.

> Otherwise, RPCS3 is using VK_NV_glsl_shader in Vulkan right?

No, we just generate SPIRV with glslang and feed it to the driver. Only nvidia supports that extension, and having two different paths for one API is going to be a maintenance problem. Makes more sense to limit the possible points of failure whenever possible, and the drivers will usually optimize the SPIRV input anyway.
