### ISSUE TITLE
[Feature Request] add Patch Manager (optional)

### ISSUE THREAD

**Issue by Oky12** [RPCS3/rpcs3#7346]
this Feature make user easily manage(enable. disable and modify) Game patch from [Rpcs3 wiki](https://wiki.rpcs3.net/index.php?title=Help:Game_Patches). 
for example. i want enable 60 fps patch and disable hud element for persona 5. i just open Patch manager and enable it. without edit code in patch.yml

![Screenshot_144](https://user-images.githubusercontent.com/30838114/73467182-8d7ad380-43b5-11ea-8855-fb2c7aa14fd5.png)

this feature look same with graphic pack on Cemu emulator.

sorry for my bad english

**Comment by B-Knight49** [comment]
To add - and perhaps you meant this by "from RPCS3 wiki GitHub" - it'd be nice if it listed all patches found at an online resource. That way we could have all patches available in a list and clicking them downloads it. 

In the far future, a place whereby patches can be uploaded from anyone would really improve the community. Obviously you'd need disclaimers and maybe even a stats system; "sort by downloads" as an example so that people can differentiate between generally favourable/trusted patches and newer ones. 

I imagine this'd probably require different formatting of the patching system though. Maybe something where each patch is stored in its own file so that way it can simply be added/removed with a single click (or drag-and-drop) as opposed to editing the patch.yml. 

Definitely something to keep an eye on, particularly given the expansion into patches that immensely improve performance and graphical fidelity in games like The Last of Us and Uncharted.

**Comment by lainiwaku** [comment]
(btw i don't know if it has already  suggested, but being able to upload hte game  directly from  rpcs3 would be nice also)

**Comment by illusion0001** [comment]
Work in Progress #8335

**Comment by HerrHulaHoop** [comment]
The Patch Manager has been implemented. This issue can be closed now.

**Comment by Oky12** [comment]
> The Patch Manager has been implemented. This issue can be closed now.

Ok 👍
