### ISSUE TITLE
Feature Request: Performance improvements for non-tsx CPU

### ISSUE THREAD

**Issue by jobs-git** [RPCS3/rpcs3#7405]
RSX have been very well optimized, sometimes reaching 2k fps! I look forward that non-tsx cpu also get some attention.

**Comment by Asinin3** [comment]
I managed to get this on my Ryzen 1700, over a year ago. Obviously indicating that RPCS3 has finished development and AMD has won the fight. RPCS3 stable release is being delayed because Intel is too slow.
![image](https://user-images.githubusercontent.com/15137035/73935203-ec999480-492f-11ea-9168-0d65d0110e3a.png)
Okay, thats enough shitposting from me for today.

**Comment by AniLeo** [comment]
This is a non-issue, TSX path is obviously faster but it's not like non-TSX is intentionally slower and/or not improved on
