### ISSUE TITLE
Auto-updater not able to execute AppImage after updating

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#7414]
After updating the AppImage, renaming the previous one to `_AppImage_.old` and closing RPCS3, the attempt to open the up-to-date AppImage will fail with:

```
fusermount: old style mounting not supported

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory
```

OS: Manjaro 18.1.5

**Comment by soredake** [comment]
Same on arch with latest appimage.

**Comment by Leopard1907** [comment]
Same here on Mint 19.3 ( Ubuntu 18.04 based )

**Comment by soredake** [comment]
Still a problem on kubuntu 20.04

**Comment by Megamouse** [comment]
any update?

**Comment by AniLeo** [comment]
Still an issue

**Comment by Megamouse** [comment]
Are you doing the steps manually or is this the auto-reboot after an update?

**Comment by AniLeo** [comment]
It's the auto-reboot after the update, if I reopen it manually then it works

**Comment by KawaiiDinosaur** [comment]
Still an issue. 5.17.9-arch1-1, Plasma 5.24.5.

> fusermount: old style mounting not supported
> 
> Cannot mount AppImage, please check your FUSE setup.
> You might still be able to extract the contents of this AppImage 
> if you run it with the --appimage-extract option. 
> See https://github.com/AppImage/AppImageKit/wiki/FUSE 
> for more information
> open dir error: No such file or directory

**Comment by AniLeo** [comment]
I've always had this problem. I don't think anyone knows how to solve it. It should be possible, as I use other program that's an AppImage and it can do this just fine.

**Comment by RipleyTom** [comment]
What happens atm is:
Rpcs3 appimage => appimage handler extracts to /tmp/ => real rpcs3 executable in tmp is launched => update => we update the appimage file => we launch the new appimage => it tries to extract to /tmp/ and fails because rpcs3 is still running(or the appimage handler is still running and has active handles on the files?).

I see 2 possible solutions:
-Use the appimage updater system, not sure how well we can integrate it to rpcs3 though, I had a look at it and it seems to require a static .zsync files to contain latest update information and seems very rigid, I'm not sure how good it would be for us. It also requires adding another lib to rpcs3(libAppImageUpdate).
-Change extraction directory per version of rpcs3, I think this may be done by renaming $APPDIR before packing it up so each version extracts in a different place? (see https://github.com/RPCS3/rpcs3/blob/master/.ci/deploy-linux.sh#L41 ). Maybe @hcorion can tell me if it's a bad idea.

**Comment by qurious-pixel** [comment]
`$APPDIR` is a specific variable used by the appimage defined as the tmp mount point. it changes on each run, so no need to rename it. 

I would have the appimage launch `$APPIMAGE` which is the absolute path to the appimage, essentially launching a new instance (at a new mount point "$APPDIR") once the updater has closed.

```
$APPIMAGE = /path/to/RPCS3.AppImage
$APPDIR = /tmp/.mount_rpcs3.<random string>
```

**Comment by RipleyTom** [comment]
> `$APPDIR` is a specific variable used by the appimage defined as the tmp mount point. it changes on each run, so no need to rename it.
> 
> I would have the appimage launch `$APPIMAGE` which is the absolute path to the appimage, essentially launching a new instance (at a new mount point "$APPDIR") once the updater has closed.
> 
> ```
> $APPIMAGE = /path/to/RPCS3.AppImage
> $APPDIR = /tmp/.mount_rpcs3.<random string>
> ```

That is what we were already doing but your comment put me on the right path, it seems we needed to unset APPDIR before launching the new AppImage.

**Comment by thesourcehim** [comment]
It seems problem came back, I started having in a couple of days ago in Fedora 40.
