### ISSUE TITLE
sys_usbd: Lego Dimensions Pad (0x0E6F / 0x0241)

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#7761]
Lego Dimensions Pad is akin to Skylanders Pad, it allows the game to read external objects

VID: 0E6F
PID: 0241

It's currently not whitelisted / implemented on sys_usbd

**Comment by SuperToad64** [comment]
So how would someone implement this? Can you add the hardware ids to sys_usbd from RPCS3's GUI itself? Or do you have to recompile the entire project after you edit the sys_usbd.cpp file? If you do have to compile the entire project how would you go about this? Because the building tutorial on this github is pretty vague: https://github.com/RPCS3/rpcs3/blob/master/BUILDING.md

Someone should make a detailed tutorial on how to do this. There is a tutorial but it is outdated: https://wiki.rpcs3.net/index.php?title=Help:Building_RPCS3

Also while we are at it we should update the tutorial for adding peripherals to RPCS3: https://wiki.rpcs3.net/index.php?title=Help:Peripherals_and_accessories

**Comment by SuperToad64** [comment]
Anyone got any ideas? I would like RPCS3 to detect the Lego Dimensions Portal Pad. Because the game runs fine but once you enter the game it says it requires the Lego Dimensions Portal Pad. Maybe we can add it the same way the Skylanders Portal was added.

**Comment by SuperToad64** [comment]
Thanks guys! The Lego Dimensions Portal works perfect! Thank you so much for implementing this!

**Comment by alexandrage** [comment]
It does not work for me

**Comment by cherbert** [comment]
Not working for me either. cemu can find the pad just fine. Despite this so called fix RPCS43 is not finding the USB pad.
