### ISSUE TITLE
RPCS3 does not compile with system LLVM

### ISSUE THREAD

**Issue by hedmo** [RPCS3/rpcs3#7787]
## Quick summary
RPCS3 compiles with buildin LLVM but not system LLVM and it would be nice to have this option
again.

regards 

## Details
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/4334875/RPCS3.log)

**Comment by AniLeo** [comment]
Built in LLVM is modified and it's from the LLVM 11 branch

**Comment by hedmo** [comment]
So there is no way to use my system LLVM? I am running the latest version of  LLVM 11.

**Comment by clienthax** [comment]
As previously stated.. our version of llvm has modifications that will differ from the standard builds.

**Comment by hedmo** [comment]
as i understand from your answers, there is no way to use a system llvm build with RPCS3
because you have modified your version of LLVM  that hard? and there is no way to adapt RPCS3 to use a system LLVM build .dont you have that build option in RPCS3? as far as i understand this is that you have a build option to build RPCS3 with system LLVM but does not support it?

**Comment by dio-gh** [comment]
> and there is no way to adapt RPCS3 to use a system LLVM build .dont you have that build option in RPCS3?

Our LLVM fork is pulled into the repo through the git submodules system, see the `.gitmodules` file  for details. I guess you could maybe remove LLVM from there and modify the build config files (cmake or msbuild) accordingly to use your system libraries instead? I'd say that's an exercise for the reader, I don't know if there's any further messing around is needed or not.

The caveat for using stock LLVM is that you'll lose performance and some not-yet-upstreamed bugfixes (see [here](https://github.com/RPCS3/llvm-mirror/commits/master) for the commits we layer on top). It's not that we couldn't use stock LLVM, it's that it doesn't make sense for us to. We don't keep a fork around for no reason.

Overall, this thread reads a lot more like a support request than an issue ticket, so I'd recommend visiting the #development channel on our [Discord](https://discord.me/rpcs3) instead, and closing this ticket.

**Comment by hcorion** [comment]
Yes, it makes no sense to build with system LLVM, we've already gone through this.
RPCS3 is constantly bumping it's dependency to LLVM to newer git versions, which of course break API compatibility. 
You also can't just use the latest LLVM git version, because LLVM is known to change the API with announcement, and then all of a sudden RPCS3 won't compile with whatever git version of LLVM you have.

It's unreasonable for us to support this officially. If you for some reason do want to use system LLVM, it's easy enough to modify the CMake, but it just doesn't make sense for us to support it.

Please close this issue.
