### ISSUE TITLE
ci: FreeBSD

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#7885]
CirrusCI has support for FreeBSD, I couldn't find any other CI solutions with FreeBSD support
https://cirrus-ci.org/guide/FreeBSD/

This could be a good idea to have, in order to prevent breaking RPCS3 in BSD (FreeBSD at least) by accident in the future as it already happened a few times. If too slow compared to the other CI builds, it can be made to be a non-blocking status in order not to bottleneck PR merge times.

Tagging @jbeich

**Comment by hcorion** [comment]
Can this get assigned to me? I'll probably do this in the future.

**Comment by jbeich** [comment]
Random notes:
- 896d16ec7b86 broke build with Qt 5.13 but 5.14 [hasn't landed yet](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=244964), see [workaround](https://github.com/freebsd/freebsd-ports/blob/008242281e2b9982b85f26f7b75ea260939d5e45/emulators/rpcs3/files/patch-qt-5.13).
- 64ed2f1151e7 broke build with libc++ 8 which is part of base system on FreeBSD 11.3/12.1, see [workaround](https://github.com/freebsd/freebsd-ports/blob/008242281e2b9982b85f26f7b75ea260939d5e45/emulators/rpcs3/files/patch-libc%2B%2B8). libstdc++ from GCC is not supported because Qt5 is built with libc++, so mixing libc++ and libstdc++ would either break build or lead to a crash.
- 9569ae24e01f + 7b54d386f221 forces Clang 9 but Clang 8 is default on FreeBSD 11.3/12.1, see [workaround](https://github.com/freebsd/freebsd-ports/blob/008242281e2b9982b85f26f7b75ea260939d5e45/emulators/rpcs3/files/patch-CMakeLists.txt). If necessary `llvm90` or `llvm10` can be installed to get newer Clang.
- Building without `-DUSE_SYSTEM_FFMPEG=on` is not supported yet due to missing binaries. PPSSPP is in the same boat. Only important if you plan to distribute prebuilt RPCS3 for FreeBSD outside of system packages or if RPCS3 fails to build against new major FFmpeg release for a long time.

Example clean build:
```
$ pkg install git
$ git clone --recurse-submodules https://github.com/RPCS3/rpcs3

# Mandatory dependencies (qt5-dbus and qt5-gui are pulled via qt5-widgets)
$ pkg install cmake ninja qt5-qmake qt5-buildtools qt5-widgets qt5-concurrent glew openal-soft ffmpeg

# Optional dependencies (libevdev is pulled by qt5-gui; sdl2 is pulled by faudio)
$ pkg install alsa-lib pulseaudio faudio evdev-proto vulkan-headers vulkan-loader

# Actual build
$ mkdir rpcs3_build
$ cmake -DUSE_SYSTEM_FFMPEG=ON -G Ninja -B rpcs3_build rpcs3
$ ninja -C rpcs3_build
```
