### ISSUE TITLE
VK_DEVICE_LOST results in RPCS3 closing

### ISSUE THREAD

**Issue by jacob1218** [RPCS3/rpcs3#7907]
## Quick summary
In rpcs3, if the graphics device is lost, when the game is closed, rpcs3 will crash without an error instead of going back to the game list.

## Details
I can reproduce this every time. Not sure if it helps, but log from GT5 attached.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4408132/RPCS3.log.gz)

**Comment by arcadee1977** [comment]
GT5：

F {PPU[0x1000023] Thread (9qstY) [0x01d7562c]} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file d:\a\1\s\rpcs3\Emu\RSX\VK\VKHelpers.cpp:957)

F {PPU[0x1000021] Thread (gFKsE) [0x00a22898]} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file d:\a\1\s\rpcs3\Emu\RSX\VK\VKHelpers.cpp:957)

**Comment by Satan86** [comment]
Please retest

**Comment by uaqlover** [comment]
It fixed @AniLeo
