### ISSUE TITLE
NCAA14 FPS consistency

### ISSUE THREAD

**Issue by huskereurocat** [RPCS3/rpcs3#7928]
When playing NCAA 14 on RPCS3 you can change the vblank setting from 60 to 120 and the cut scenes and replays are rendered in 60 FPS. However, the rest of game play remains at the original FPS rate and gets rendered at 35-45FPS or so. Can this setting be programmed to render the entire game footage, including the cut scenes and replays, at 60FPS? 

![Base Profile Screenshot 2020 04 02 - 23 34 59 17](https://user-images.githubusercontent.com/52609668/78324637-d9273600-753a-11ea-843a-cfe417c01bf7.png)
This is the 60FPS screenshot in one of the cut scenes.

![Base Profile Screenshot 2020 04 02 - 23 34 53 58](https://user-images.githubusercontent.com/52609668/78324741-2c00ed80-753b-11ea-802d-f05123eab0df.png)
![Base Profile Screenshot 2020 04 02 - 23 34 51 15](https://user-images.githubusercontent.com/52609668/78324761-3a4f0980-753b-11ea-88b3-421ef567161a.png)
These are screenshots of just regular game play without the benefit of rendering at 60FPS.

**Comment by RainbowCookie32** [comment]
I don't think this is an emulator issue. Some games use vblank for the timing of some things, and hardcoded values for others. This seems to be the case, it probably needs a patch to work at 60fps properly, which is not something to open an issue for

**Comment by MSuih** [comment]
Vblank only does what the name says, it increases frequency of the vertical blanking signal. Whether the game developers base their frame delivery on vblank or not is outside of our control., and thus vblank isn't "broken" even if it does not increase framerate cap.

In this case, the part of the engine which renders cutscenes seems to use different timing method compared to main gameplay, probably because it was developed as separate component by different people or with different design goals. You can try modifying clocks scale to see if it affects cutscenes without causing issues to gameplay, and if it doesn't work then the game will need some other method such as custom patch.

**Comment by huskereurocat** [comment]
Thanks for the explanation.
