### ISSUE TITLE
[Feature Request] Add wheel emulation support

### ISSUE THREAD

**Issue by PixelPickaxe** [RPCS3/rpcs3#7936]
## Info
I have a [Logitech Driving Force](http://sv.wikipedia.org/wiki/Fil:Logitech-Driving-Force-PS3.jpg) steering wheel. It is compatible natively with a PS3 system as well as a PC. RPCS3 sees it as a standard game controller instead of as a wheel.

**Comment by RipleyTom** [comment]
Note that there are some wheels are already accepted as passthrough by rpcs3:
https://wiki.rpcs3.net/index.php?title=Help:Peripherals_and_accessories

Of particular note for you is lgFF_c283_c29b which regroups every device with VID 0x046D and PID >= 0xC283 and <= 0xC29B.
If that is what your device is you just need to follow the instructions in the wiki and it should work.

**Comment by bevanweiss** [comment]
@PixelPickaxe have you had a chance to test this with your wheel?
If this is working for you, please close the issue.  If it's not, please advise of the issue, and provide a log.

**Comment by PixelPickaxe** [comment]
So, yeah it worked with the instructions provided, but I'd prefer to not have to install a new driver, since I use this wheel for other games frequently.

**Comment by RipleyTom** [comment]
The game interacts with the device directly on ps3, that's why you need Zadig to set a generic usb driver. Proper windows drivers won't let us access the device directly so us going through actual normal drivers is not going to happen.

In short issue can be closed.

**Comment by MSuih** [comment]
It should be possible to add a emulator layer which accepts input by using some standardized wheel API and then pretends to be a compatible USB device to the emulated game, passing wheel input to it without requiring low level device access. That won't be easy to do but I don't see it being impossible either.

I feel like the original issue of wheel emulation is valid, although it's hard to say if and when it will be addressed.

**Comment by ChassyFlaps** [comment]
Has any more thought been put into this? SDL supports wheels and the current passthrough method requires spending quite a hefty chunk of change to be able to play your older games with a wheel you already have

**Comment by Lillowh** [comment]
It is worth mentioning that the SDL support in PCSX2's QT releases have support to emulate wheels such as the Driving Force Pro and Driving Force GT with modern wheels, including force feedback. Considering how expensive the equipment on its own, let alone the extra gear to use these interchangeably, I believe some serious thought should be considered into supporting these types of solutions rather than passthrough only.

**Comment by ChassyFlaps** [comment]
Well i had to spend 100 dollars for a usb adapter in order to use your software with my own hardware. This is not ideal and truthfully a seriously lack luster implementation. I think it would be worth looking into supporting this for your users. I helped with PCSX2s recent FFB update (testing etc) if you need the help ill offer it here too.

**Comment by ikt32** [comment]
@ChassyFlaps I made #11438 a while ago where such a generic approach was requested, but it appears the issue hasn't been picked up.

**Comment by doobydooby72** [comment]
I wish it was plug n play like pcsx2 is... So convenient
