### ISSUE TITLE
Running a Game in Fullscreen Disables the HDR Setting in Windows 10.

### ISSUE THREAD

**Issue by seanocali** [RPCS3/rpcs3#7975]
## Quick summary
Launching a game in fullscreen disables the HDR setting in Windows 10.

## Details
Here is the Windows 10 HDR setting:
[https://www.digitalcitizen.life/sites/default/files/gdrive/win10_hdr/hdr_10.png](https://www.digitalcitizen.life/sites/default/files/gdrive/win10_hdr/hdr_10.png
)

Launching a game with EPSC3 (0.0.9-10135-4ff69dc0 Alpha) in fullscreen mode or Alt-Enter into fullscreen will disable the HDR setting in the OS if it was already on. Not just an annoyance, but a serious problem with certain HDR displays that need to be power cycled any time this setting is changed or else color palette is totally out of whack. It happens with OpenGL or Vulcan. Using Nvidia GTX 1070. The two games I tested were BLES00276 and BCES00301.

**Comment by SullieLore** [comment]
I'm also experiencing this issue.

**Comment by Passingby1** [comment]
I can confirm this is still happening with RPCS3 0.0.13-11336 and Windows 10 20H2. To be fair, Windows 10's HDR support is a mess still, but, other full screen apps and games manage to automatically switch back and forth between HDR and SDR, RPCS3 does not know how, so after exiting RPCS2 Windows 10 remains in SDR until you manually switch it on again.

**Comment by kd-11** [comment]
We don't support HDR in any form, nothing about using rpcs3 in fullscreen tells the system to behave differently. What is likely happening is the graphics driver is auto-detecting the application is running in fullscreen and disabling HDR. Then forgets to switch back (or the monitor is unable to do so) automatically when the program closes fullscreen window.
Technically this would be an NVIDIA bug. Applications do not need to explicitly add HDR support for the system to switch back to it upon exit, otherwise all old software without HDR would have the same issue. Unfortunately I do not have a HDR monitor to check where the system is messing up, but we'll likely figure out a workaround.

**Comment by mirh** [comment]
Another solution would be supporting HDR in the first place (see also https://github.com/libretro/RetroArch/pull/13456).

**Comment by nicktones** [comment]
Setting the following option to 'true' in the vulcan part of config.yml fixes this issue.

`Force Disable Exclusive Fullscreen Mode:`
