### ISSUE TITLE
Ratchet & Clank Future: Tools of Destruction hangs at Voron Asteroid Field space level

### ISSUE THREAD

**Issue by UltimateKamaro** [RPCS3/rpcs3#8108]
Update: I dumped a digital copy of Ratchet & Clank Future: Tools of Destruction (NPUA80965) from my CFW PS3 and now this issue persists even on a non-challenge mode playthrough. (Updated log posted on this post)

The game black screens hangs upon loading the Voron Asteroid Field level and there's no way to fix it.

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5011636/RPCS3.log.gz)

![Screenshot 8_2_2020 12_25_05 AM](https://user-images.githubusercontent.com/64123339/89115510-fa4f5300-d456-11ea-8839-39bc22ff8904.png)

![Screenshot 8_2_2020 12_25_10 AM](https://user-images.githubusercontent.com/64123339/89115491-be1bf280-d456-11ea-9aad-f381cdd55a4e.png)

Nvidia GeForce RTX 2080 with Max Q GPU
Intel Core i7 8th Gen

**Comment by UltimateKamaro** [comment]
> Update: I dumped a digital copy of Ratchet & Clank Future: Tools of Destruction (NPUA80965) from my CFW PS3 and now this issue persists even on a non-challenge mode playthrough. (Updated log posted on this post)
> 
> The game black screens hangs upon loading the Voron Asteroid Field level and there's no way to fix it.
> 
> [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5011636/RPCS3.log.gz)
> 
> ![Screenshot 8_2_2020 12_25_05 AM](https://user-images.githubusercontent.com/64123339/89115510-fa4f5300-d456-11ea-8839-39bc22ff8904.png)
> 
> ![Screenshot 8_2_2020 12_25_10 AM](https://user-images.githubusercontent.com/64123339/89115491-be1bf280-d456-11ea-9aad-f381cdd55a4e.png)
> 
> Nvidia GeForce RTX 2080 with Max Q GPU
> Intel Core i7 8th Gen

Let me know if there's a fix on this issue. Bc the game is unplayable and unfinishable if there's no fix.

**Comment by Bla5turbator** [comment]
Getting the same issue since i started a challenge mode playthrough; before that it didn't happen. Log chucks out these errors:

E {PPU[0x100000c] Thread (fios mediathread) [0x00ba1ee4]} SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCES00052/USRDIR/packed/levels/level_transitions/level_uncached.psarc” [1]
E {PPU[0x100000c] Thread (fios mediathread) [0x00ba1ee4]} SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCES00052/USRDIR/packed/levels/level_transitions/level_textures.psarc” [1]
E {PPU[0x100000c] Thread (fios mediathread) [0x00ba1ee4]} SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCES00052/USRDIR/packed/levels/space combat i/level_cached.psarc” [1]
E {PPU[0x100000c] Thread (fios mediathread) [0x00ba1ee4]} SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCES00052/USRDIR/packed/levels/space combat i/level_uncached.psarc” [1]
E {PPU[0x100000c] Thread (fios mediathread) [0x00ba1ee4]} SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCES00052/USRDIR/packed/levels/space combat i/level_textures.psarc” [1]
E {PPU[0x100000c] Thread (fios mediathread) [0x00ba1ee4]} SYS: 'sys_fs_stat' failed with 0x80010006 : CELL_ENOENT, “/dev_hdd0/game/BCES00052/USRDIR/EBOOT.BIN” [1]

**Comment by hanlonmj** [comment]
Having the same issue here
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5551780/RPCS3.log.gz)

**Comment by radzio481** [comment]
I had the same problem,but after windows reinstall issue is fixed and game do not crash on voron now.

**Comment by Bibilunic** [comment]
I have the same problem on my first playthrough

**Comment by MohamedChaabouni** [comment]
Problem still persist in here. I have the same issue. Any fixes ? 
Ryzen 7 3700X; GTX 1660 Super (6GB)

**Comment by DarkShadix** [comment]
I'm getting a very similar bug but it is happening on the Rakar star cluster instead.
i7 9700K; GTX 1660 Ti (6GB)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5984291/RPCS3.log)

**Comment by oosfoos** [comment]
I was able to get past this issue by restarting my computer. Restarting rpcs3 didn't seem to work, but a computer restart did for some reason :/

**Comment by Onyxtinct** [comment]
Same issue with my gtx 1070. Game goes black screen and freezes after the loading screen to voron belt on my first play through. I hope somebody finds a fix for this :(

**Comment by xlj44400** [comment]
Hanging During Entry to Voron Asteroid Belt
Game is likely to hang upon beginning the entrance cutscene to the Voron Asteroid Belt. It is possible to get through this scene during the first playthrough, but still crash here during NG+.

Fix: Update Windows 10 Features to version 20H2.

https://wiki.rpcs3.net/index.php?title=Ratchet_%26_Clank_Future%3A_Tools_of_Destruction#Hanging_During_Entry_to_Voron_Asteroid_Belt

this maybe window10 system version so old, I update  win10 1809 -> 1909, this work for me;

**Comment by MSuih** [comment]
Retest, #10744 might've resolved this

**Comment by JimScript** [comment]
Can this be closed? Because after #10744 I have been able to enter every space level on a computer that has been on for days consistently. In other words, this problem is fixed and should be closed.
