### ISSUE TITLE
Gran Turismo 5 graphical corruption on 1920x1080

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#8297]
When I use a resolution of 1920x1080 on Gran Turismo 5 BCES00569 with an AMD GPU on Vulkan, graphical corruption occurs. This does not happen on Nvidia cards. Strict rendering mode appears to fix the corruption as well.

Ryzen 7 2700
Radeon RX 580 20.4.2
Windows 10 2004
![Screenshot_6](https://user-images.githubusercontent.com/1712979/83053173-04209880-a059-11ea-9d42-ac99066bf651.png)
![Screenshot_7](https://user-images.githubusercontent.com/1712979/83053176-04b92f00-a059-11ea-9607-6317fbdcc7b3.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4690703/RPCS3.log.gz)
https://www.dropbox.com/s/f9vbfzt2pllg2yc/BCES00569_20200527202956_capture.zip?dl=0

**Comment by kd-11** [comment]
If strict mode fixes the issue why is this filed as a bug then? I get the feeling people think strict mode is a hack or workaround but it's actually what we're supposed to be doing on PC all the time, the option to disable it is just there to help with performance.

**Comment by xddxd** [comment]
That's exactly what I thought, that it's a workaround. Closing.

**Comment by kd-11** [comment]
Strict mode does things correctly for the PC platform, a lot of things that work on RSX work just fine on nvidia cards for example because even 15 years later the modern cards still share a lot with the RSX. Ofc this means using something from AMD or intel is going to be hit or miss. A lot of illegal techniques are used on PS3 (e.g framebuffer feedback loops) and the correct way to do them on PC is slow, so we tend to avoid using strict mode, but sometimes there is really no other way. Maybe the option can be renamed to something else to convey this message.
