### ISSUE TITLE
Missing special characters

### ISSUE THREAD

**Issue by lyntur** [RPCS3/rpcs3#8348]
Silent Hill Downpour (BLUS30565) spanish language, everything shows correctly except for special characters, specifically accents (é, á, í, ó, ú) which are replaced by weird symbols, is there any way to fix this?
![Captura de pantalla (3)](https://user-images.githubusercontent.com/51327725/83812813-70844300-a6bc-11ea-80fa-dd38997dac55.png)

**Comment by AniLeo** [comment]
Seems like the wrong characters are being used, should be an overlay bug, @kd-11

**Comment by kd-11** [comment]
Is that really our overlay? The font doesn't look like one of ours. Might be a bug in cellFont

**Comment by AniLeo** [comment]
Ah of course it's not the native overlay

**Comment by Megamouse** [comment]
This might be the proper font (found on youtube)
![image](https://user-images.githubusercontent.com/23019877/86416052-344aff00-bcc9-11ea-966b-3adb92df98d4.png)

**Comment by lyntur** [comment]
? But what's the solution then? Cause I didn't change any font

**Comment by Megamouse** [comment]
I think this was closed by mistake

**Comment by kd-11** [comment]
Yea, my mistake, I was going through already fixed bugs to close and this one was in my notifications.

**Comment by bevanweiss** [comment]
The PS3 uses freetype for the font handling library, and we appear to be using a more compact library (stb_truetype.h).
Is there any info on the history as to why stb_truetype.h was selected instead of just bringing in freetype?
I'm wondering if it might be an implementation difference between stb_truetype.h vs freetype.h (i.e. the stb_truetype.h support for accented fonts isn't quite as complete as freetype).
The rpcs3 screenshot doesn't even appear to be using the custom font here... (which might also be the issue)
@lyntur can you please attach the log file?  It might have an error related to the font selection here.

**Comment by bevanweiss** [comment]
It works fine for me
![image](https://user-images.githubusercontent.com/2055446/97279865-a1ddf500-188f-11eb-8d7f-51311c1c2ffb.png)

**Comment by benderscruffy** [comment]
Can be closed
