### ISSUE TITLE
Grand Theft Auto 4: Complete Edition [BLES01128] Doesn't load after #7776

### ISSUE THREAD

**Issue by bilalfakhouri** [RPCS3/rpcs3#8374]
Hello Developers
I got a problem and here is what I found:

Grand Theft Auto 4: Complete Edition [BLES01128] Doesn't load after #7776 pull request (rpcs3 0.0.9-9911) the pull request I mentioned caused the issue.

After launching the game I can chose between the three versions in the game like this:
<a href="https://ibb.co/Hxxjd1G"><img src="https://i.ibb.co/SddzrWV/GTA-IV.png" alt="GTA-IV" border="0" /></a>

In the latest working rpcs3 version 0.0.9-9905 (before the issue) after selecting a version from the three and pressing X button the game loads normally, and this is the log for that:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4741173/RPCS3.log.gz)

In **0.0.9-9911 version** I could chose also one game edition from the three but after Pressing X the game doesn't load at all and I got these errors in the log file:

`E {PPU[0x1000003] Thread (SecondarySpursHdlr1) [0x007db604]} SYS: 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]

E {PPU[0x1000002] Thread (PrimarySpursHdlr0) [0x007d948c]} SYS: 'sys_spu_thread_group_join' failed with 0x00000000 : 0 [1]

E {PPU[0x1000001] Thread (PrimarySpursHdlr1) [0x007db604]} SYS: 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]

E {PPU[0x1000004] Thread (SecondarySpursHdlr0) [0x007d948c]} SYS: 'sys_spu_thread_group_join' failed with 0x00000000 : 0 [1]

E {PPU[0x1000005] Thread (_gcm_intr_thread) [0x007b833c]} SYS: 'sys_event_queue_receive' failed with 0x00000000 : 0 [1]`

Here is **the full log for that**:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4741177/RPCS3.log.gz)

Thanks for making rpcs3!

**Comment by quaddamage1** [comment]
I've queued up a pull-request that fixes this particular problem. The game now loads past the menu and begins.
Question for @Nekotekina: I'm unclear about when and how `vfs::escape()` and `vfs::unescape()` are supposed to be used.
#7776 added escapes for names that can't be used in Windows filenames. This game happened to have a file named `COMP.BIN`, which was incorrectly (since it's not of the form `COM[0-9]) escaped.
If a game had a file named `COM9.BIN`, the VFS code added by #7776 would have changed the name to `!COM9.BIN`. While loading the game, `sys_process_exit2` queues up a callback which causes `Emu::BootGame()` to pass the escaped path containing this name to `fs::exists()`, which calls `::stat()` with this escaped filename. Presumably that would fail, since the escaped path would not exist. Is that a bug? 
Thanks

**Comment by bevanweiss** [comment]
Hi @quaddamage1  (I'm not nekotekina).. but I might give you an answer a bit quicker.
Those particular file names relate to Windows restrictions.
https://docs.microsoft.com/en-au/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN

Some discussion has been had lately regarding case-sensitivity, and overall ways to make the Windows filesystem handling a bit closer to the PS3 native handling.  If there was a way to have Windows ignore the DOS compatibility filenames it would be good, but I haven't seen such.  Possibly the POSIX flag might 'help'... but others will know more.
