### ISSUE TITLE
Upscaling doesn't work for ninja gaiden 3

### ISSUE THREAD

**Issue by wjtz** [RPCS3/rpcs3#8379]
Upscaling doesn't work for ninja gaiden 3,and turning on high resolution will cause graphics problems

Config:
Windows 10 64-bit  2004
GeForce RTX 2070S
i7-9700k @ 4.9GHZ
16GB RAM
RPCS3 :  v0.0.10-10469

**Comment by anseesaw** [comment]
720p auto
![3](https://user-images.githubusercontent.com/28805459/83967702-82512a80-a8f6-11ea-8228-8a340253c3d5.png)
＞720p
![2](https://user-images.githubusercontent.com/28805459/83967708-8bda9280-a8f6-11ea-9adb-6868cebe8a0f.png)

**Comment by kd-11** [comment]
This is a problem for discussion on discord forums. Attempting to run the game in ways it was not intended by the original developers will carry risk of things breaking, there is nothing to be done for that since the only possible "fix" is to patch the offending code which is not part of the emulator itself. A slider "resolution scaling threshold" is provided in the graphics options, try increasing that in steps of 64 and see if it fixes the problem.

**Comment by jeremybris** [comment]
@wjtz @anseesaw set "Resolution Scale Threshold" x580 to fix. https://www.youtube.com/watch?v=2in2rn49Zvc
