### ISSUE TITLE
NINJA GAIDEN Σ2 [BLUS30380] - Crash during menu video

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#8383]
I booted up NGS2 for the first time in a while and had it run idle in the main menu for a while, because I know that the game likes to compile PPU modules a lot during the menu video, and I didn't want that to happen as much ingame.

But after a while it simply locked up and showed a fatal error.

```
·W 0:14:20.618860 {RSX [0x05968e0]} RSX: Framebuffer setup failed. Draw calls may have been lost
·S 0:14:20.637371 {RSX Decompiler Thread} RSX: New program compiled successfully
·W 0:14:20.640834 {RSX [0x05e81fc]} RSX: Framebuffer setup failed. Draw calls may have been lost
·W 0:14:20.640848 {RSX [0x05e8570]} RSX: Framebuffer setup failed. Draw calls may have been lost
·! 0:14:20.648150 {RSX Decompiler Thread} RSX: FP not found in buffer!
·E 0:14:20.648202 {RSX Decompiler Thread} RSX: Bad src reg num: 15
·E 0:14:20.648208 {RSX Decompiler Thread} RSX: Bad src reg num: 15
·E 0:14:20.648211 {RSX Decompiler Thread} RSX: Bad src reg num: 15
·E 0:14:20.648215 {RSX Decompiler Thread} RSX: Bad src reg num: 15
·W 0:14:20.648259 {RSX Decompiler Thread} RSX: Shader does not write to any output register and will be NOPed
·F 0:14:20.648295 {RSX Decompiler Thread} SIG: Thread terminated due to fatal error: Unknown register name: unk
(in file d:\a\1\s\rpcs3\Emu\RSX\VK\VKCommonDecompiler.cpp:153)
```

[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4742622/RPCS3.log.gz)

**Comment by islandking2000** [comment]
I can't reproduce the issue you mentioned, NG2sigma still works for me in the latest build.

**Comment by VladWinner** [comment]
I have the same error with BLES00016
`S {RSX Decompiler Thread} RSX: New program compiled successfully x14
E {RSX Decompiler Thread} RSX: Unknown/illegal instruction: 0x7c (forced unit 0)
S {RSX Decompiler Thread} RSX: New program compiled successfully x2
E {RSX Decompiler Thread} RSX: Unknown/illegal instruction: 0x7c (forced unit 0)
S {RSX Decompiler Thread} RSX: New program compiled successfully
E {RSX Decompiler Thread} RSX: Unknown/illegal instruction: 0x7c (forced unit 0)
S {RSX Decompiler Thread} RSX: New program compiled successfully x28
E {RSX Decompiler Thread} RSX: Unknown/illegal instruction: 0x46 (forced unit 1)
E {RSX Decompiler Thread} RSX: BRK opcode found outside of a loop
E {RSX Decompiler Thread} RSX: Unimplemented SIP instruction: CAL
S {RSX Decompiler Thread} RSX: New program compiled successfully x36
E {RSX Decompiler Thread} RSX: Hanging block found at end of shader. Malformed shader?
S {RSX Decompiler Thread} RSX: New program compiled successfully x33
E {RSX Decompiler Thread} RSX: Unknown/illegal instruction: 0x35 (forced unit 0)
S {RSX Decompiler Thread} RSX: New program compiled successfully x17
E {RSX Decompiler Thread} RSX: Unknown/illegal instruction: 0x35 (forced unit 0)
S {RSX Decompiler Thread} RSX: New program compiled successfully x19
E {RSX Decompiler Thread} RSX: Unknown/illegal instruction: 0x7c (forced unit 0)
S {RSX Decompiler Thread} RSX: New program compiled successfully x91
E {RSX Decompiler Thread} RSX: Bad scale: 4
E {RSX Decompiler Thread} RSX: Unexpected precision modifier (7)
x2
E {RSX Decompiler Thread} RSX: Bad scale: 4
E {RSX Decompiler Thread} RSX: Unexpected precision modifier (7)
x2
S {RSX Decompiler Thread} RSX: New program compiled successfully x37
E {RSX Decompiler Thread} RSX: Unknown/illegal instruction: 0x7c (forced unit 0)
S {RSX Decompiler Thread} RSX: New program compiled successfully
E {RSX Decompiler Thread} RSX: Hanging block found at end of shader. Malformed shader?
S {RSX Decompiler Thread} RSX: New program compiled successfully x58
E {RSX Decompiler Thread} RSX: Unknown/illegal instruction: 0x3f (forced unit 0)
S {RSX Decompiler Thread} RSX: New program compiled successfully x7
E {RSX Decompiler Thread} RSX: Unknown/illegal instruction: 0x3f (forced unit 0)
S {RSX Decompiler Thread} RSX: New program compiled successfully x49
E {RSX Decompiler Thread} RSX: Hanging block found at end of shader. Malformed shader?
S {RSX Decompiler Thread} RSX: New program compiled successfully x59
E {RSX Decompiler Thread} RSX: Unknown/illegal instruction: 0x3f (forced unit 0)
S {RSX Decompiler Thread} RSX: New program compiled successfully x42
E {RSX Decompiler Thread} RSX: Bad scale: 4
E {RSX Decompiler Thread} RSX: Bad src reg num: 15 x4
F {RSX Decompiler Thread} SIG: Thread terminated due to fatal error: Unknown register name: unk
(in file d:\a\1\s\rpcs3\Emu\RSX\VK\VKCommonDecompiler.cpp:153)`

**Comment by Megamouse** [comment]
Well. It didn't crash in my latest test, but now it suddenly starts loading something in the middle of the video and is stuck
![image](https://user-images.githubusercontent.com/23019877/107149755-bb94db00-695a-11eb-818f-126d47ebdd84.png)

**Comment by Megamouse** [comment]
I cannot reproduce this anymore.
