### ISSUE TITLE
Windows: ProcessMonitor reports FileSystemControl INVALID DEVICE REQUEST for PPU cache entries

### ISSUE THREAD

**Issue by bevanweiss** [RPCS3/rpcs3#8635]
## Quick summary
Similar to the BUFFER OVERFLOW on the game list images, it appears the PPU cache writes generate a bunch of INVALID DEVICE REQUEST entries.  My initial thought is that this is possibly just a part of the dynamic file create process that happens, and someone might know more definitively than me.

## Details
Screenshot showing this below
![image](https://user-images.githubusercontent.com/2055446/88473007-8abffc00-cf5c-11ea-9a03-d1ea7332fffb.png)

as with the BUFFER OVERFLOWs, it's not stopping RPCS3 from operating, or impacting on functionality as far as I'm aware, so would have a very low priority.  Someone might even just know that this is 'intended operation' of the Windows file create process and this issue can be closed 'immediately'.  Otherwise it's just a tracking item for someone to eventually look into..

#### 1. Please attach RPCS3's log.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/4977204/RPCS3.log.gz)

#### 5. Please provide your system configuration:
* OS - Windows 10 2004
* CPU - Intel i7-9750H
* GPU - Nvidia RTX2060M

**Comment by Megamouse** [comment]
Those are internal results that aren't really caused by anything we do specifically.
BUFFER OVERFLOW simply signals that a requested buffer is too small. The software then requests one of the correct size.
The INVALID DEVICE REQUEST could be anything tbh, and is probably caused by some win api stuff.
I don't think any of these are worth looking into any more than I just did.
If there's no user facing bug, then I don't see any issue here.
