### ISSUE TITLE
RPCS3 instantly freezes

### ISSUE THREAD

**Issue by whsmk54** [RPCS3/rpcs3#8720]
## Quick summary
RPCS3 instantly freezes after i change something in the settings.

## Details
Yesterday RPCS3 began to freeze, before that everything worked fine. I decided to completely reinstall it. I downloaded clean RPCS3, installed the firmware. I haven't even installed the game yet, but as soon as I change something in the settings, RPCS3 just freezes. It's strange, 2 days ago I played without problems. 

#### 6. Please provide your system configuration:
* OS: Windows 10 2004 (Build 19041
* CPU: Ryzen 5 2600
* GPU: RX 590
* Driver version: 20.8.1

**Comment by kd-11** [comment]
Update or close.

**Comment by Asinin3** [comment]
Closing ticket due to lack of information, and no update.
If issue is still occurring, please advise and we can re-open. But we will need to know what build started causing this problem. https://rpcs3.net/compatibility?b has old builds, can try some before the issue started. Then post log file, and as much info as you can.
