### ISSUE TITLE
Cannot compile under VS 16.7+

### ISSUE THREAD

**Issue by elad335** [RPCS3/rpcs3#8730]
Compiler errors indicate something with <bit> library functions but its very unclear, although it's reported fixed in 16.8 preview 1 but may require a workaround.

**Comment by bevanweiss** [comment]
Here's the changes that I made to get it building under v16.8 Preview 1
https://github.com/bevanweiss/rpcs3/tree/fix_MSVC_compile_error

I had reported the issue with the stdc++ <bit> library (in 16.7) to Microsoft, and they advised that it would be fixed in the next release (which I assume to be 16.7.1).
There are also some changes to the compiler memory usage, which appeared to just push us over the 4GB size accessible by a 32bit process, hence cl.exe started having issues.  That's why the VC project files all gained the x64 toolchain setting.  It was only really needed on emucore, but I added it to all for consistency.

**Comment by bevanweiss** [comment]
Is it worth adding a specific #error clause to the types.h header where we currently have the workaround for __cpp_lib_bitops which specifically calls out the issues with 16.7.0 and 16.7.1?

As far as I'm aware, with the broken <bit> header in these two releases, there's just no way for either of these releases to work (with us using bitops).
I've just tried on 16.7.1 and had the same issue as I saw on 16.7.0 ('_Is_standard_unsigned_integer' undefined)

**Comment by yxmline** [comment]
16.7.2 VCToolsVersion 14.27.29110
\VC\Tools\MSVC\14.27.29110\include\bit(36,1): error C2975 “_Test”:“std::enable_if_t” Invalid template parameter

**Comment by saramibreak** [comment]
'_Is_standard_unsigned_integer' is defined in 'limits'. This is also used in 'chrono', 'xmemory'.
To enable it, '__cpp_lib_bitops' is required to be defined.
This is already defined in "Utilities/types.h", but 'limits' is used before it is defined.

I edited directly emucore.vcxproj, GLGSRender.vcxproj, OpenAL.vcxproj, VKGSRender.vcxproj, XAudio.vcxproj and rpcs3.vcxproj. But this is not a smart way, I think.

**Comment by bevanweiss** [comment]
@saramibreak We're currently likely to 'jump over' the v16.7 release.
The CI has been held back to v16.6, and quite a few of the devs that are on VS community and hence can't easily use an older version are running v16.8 Preview 1/2 without issues.

**Comment by kiwidoggie** [comment]
Still broken in 16.7.3, do you know which release they were going to get to it (or have a link to the bug report on vs bug tracker?) @bevanweiss ?

**Comment by dio-gh** [comment]
it's gonna be fixed with 16.8, which is why he says:

> quite a few of the devs that are on VS community, and hence can't easily use an older version, are running v16.8 Preview 1/2 without issues.

**Comment by elad335** [comment]
Once 16.8 is out it will become the minimum required version for rpcs3 and this issue will be closed.
