### ISSUE TITLE
Freezes and BSOD when I try and start any game

### ISSUE THREAD

**Issue by Dannylad9862** [RPCS3/rpcs3#8831]
When I lunch RPCS3 the launcher will stat but as soon as i try to launch any game it says at the top in the title bar "(Not Responding)" and then blue screens and computer

**Comment by bevanweiss** [comment]
@Dannylad9862 Was there an issue template that you were asked to fill in?  You've really not provided much information.
i.e. You say BSOD so I assume you're running Windows... but I've had to assume that, because you haven't mentioned.  And that leaves a few different Windows open...
So tell us details :)
What OS version, what graphics card, and what GPU driver are you running, what CPU, everything applicable to your computer, if you want to tell us that you have a red case, with RGB lights... fine... not so important, but it's better than leaving out all the details....
Provide us the rpcs3 log file if it's available in the rpcs3 directory after the crash recovery, or provide us with details of ALL of the settings that you have configured.
Given it was a BSOD, there should have also been a message presented telling you what caused the BSOD.  It might have said something about an IRQ not equal or something equally meaningless to you.  It possibly also gave you a file name that meant nothing to you.  They mean something to us, so tell us that information.

Help us to help you...

**Comment by Dannylad9862** [comment]
plesae see text document 

[github.txt](https://github.com/RPCS3/rpcs3/files/5171656/github.txt)

**Comment by Asinin3** [comment]
@bevanweiss The rpcs3 log contains most of this info best to just ensure they post the log first and other info second. As you can see when we don't clarify for the rpcs3.log.gz file people spam the comment section with a copy paste too.

**Comment by bevanweiss** [comment]
Ouch... be a little prepared for attack from not posting that log in .zip / .gz format ;)

Right... so your video driver says no.
I'd recommend doing an uninstall of the video driver, including removing settings, and then reboot.  And then re-install latest drivers (from fresh download), and then reboot.  And then see if that solves it.
Sorry for the horrible IT tech support 'solution'.  But given it's a driver side BSOD, there's not much that rpcs3 should really do.
The driver shouldn't crash the system...

**Comment by bevanweiss** [comment]
@Asinin3 It would be even better if we could somehow prevent issues from being raised without a log file attached :)
And in my defence I said 'log file', not 'log file contents copied and pasted into a comment' ;)

**Comment by Asinin3** [comment]
bevanweiss The log is from a pirated game. We dont support this and the issues get closed anyway. Like that issue from Ruthlan earlier. We dont just knowingly ignore that fact and assist anyway..

**Comment by bevanweiss** [comment]
How do you spot the pirated game?  I'm not ignorant, I'm just clueless :)

This seems like even more incentive for a magic issue gateway
no log, no issue raised..
log contains pirated game reference, no issue raised..
