### ISSUE TITLE
Demon's Souls ragdoll physics freeze

### ISSUE THREAD

**Issue by basementApe** [RPCS3/rpcs3#8875]
## Quick summary
Interacting with corpses or breaking crates by rolling causes the game to freeze. 

## Details
The emulator still runs but trying to close the game window produces an error message as seen in screenshot 4. Screenshot 1 is the game running normally. In screenshot 2 I ran into the corpse a second earlier which caused the game to freeze.

[RPCS3ragdoll.zip](https://github.com/RPCS3/rpcs3/files/5195560/RPCS3ragdoll.zip)

![dsbug1](https://user-images.githubusercontent.com/71020874/92607267-16f46b80-f2de-11ea-8fcb-85ac323cf43d.png)
![dsbug2](https://user-images.githubusercontent.com/71020874/92607284-1c51b600-f2de-11ea-9b95-0c83546b0d43.png)
![dsbug3](https://user-images.githubusercontent.com/71020874/92607293-1f4ca680-f2de-11ea-932e-97cd20689fb1.png)
![dsbug4](https://user-images.githubusercontent.com/71020874/92607297-21af0080-f2de-11ea-935e-e930aebee75e.png)

* OS
Windows 10
* CPU
Ryzen 5 2500U
* GPU
Vega 8
* Driver version
20.8.3
* RAM
8 gb

In addition to build 0.0.12-10848-22dc2947 Alpha I also tested on builds 0.0.6-8477 and 0.0.5-7227 so this problem appears to go way back.

**Comment by AniLeo** [comment]
Known issue with weak parts, you have a Ryzen 5 2500U, it's caused by lack of performance (you can't execute SPU code fast enough). Your PC is too weak for this game, essentially.

**Comment by basementApe** [comment]
Hmm. Not to argue your point or anything; I know my CPU is relatively weak. But still, the emulation runs at a very high framerate for other parts of the game (57-61 fps). Seems like quite the bottleneck when physics kicking incauses everything to go from 60fps to full crash. Is there a chance that the physics emulation can be optimized in the future so CPU's like mine can keep up?

**Comment by AniLeo** [comment]
You're not actually running the game at 60 FPS even though it appears as such. The SPU parts of the engine such as audio and physics are terribly running behind because your CPU is way too weak. Also, the tutorial is much much lighter than any normal map after it. You may figure out a way to not crash through proper settings, but slowdowns and lag spikes are expected, as well as the game being incredibly slow when physics come into play, plus audio looping in certain cases.

The game works just fine if you use decent hardware (like the desktop parts mentioned on our recommended requirements), you just can't expect to run a workload this heavy on such a weak CPU.

**Comment by elad335** [comment]
Although crashing rpcs3 on close afterwards may indicate its an rpcs3 issue and not a game issue.

**Comment by AniLeo** [comment]
This is probably because there some incorrect settings being used there - as I mentioned the crashing itself is likely fixed through support, although I've seen that happen on games running way too slowly even with regular settings. It's just going to be very unplayable regardless.

**Comment by basementApe** [comment]
Thanks for the replies. You were right, it was a settings issue. The problem went away when I set SPU Block Size from Mega to Safe.
