### ISSUE TITLE
Regression: Several games have flashing disappearance of the objects (#8347)

### ISSUE THREAD

**Issue by JohnGodgames** [RPCS3/rpcs3#8889]
Tested with **RPCS3 Version: 0.0.12-10866-b48c0366 Alpha**

Several games have flashing disappearance of the objects.You need to stand still and wait for some seconds to see objects disappearing.

#### 2. Please attach TWO logs:
* build with regression.
https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-d47d597b3449f3c3911189a3f0e1cceb05ce9444/rpcs3-v0.0.10-10464-d47d597b_win64.7z
* commit - https://github.com/RPCS3/rpcs3/pull/8347

* build that works as expected.
https://github.com/RPCS3/rpcs3-binaries-win/releases/download/build-334d0bbc86f1403d19d65cba192b6c82223aa6c0/rpcs3-v0.0.10-10462-334d0bbc_win64.7z

* **LOGS (regression):**
[Magus RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5204551/Magus.RPCS3.log.gz)
[Planet 51 THE GAME RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5204552/Planet.51.THE.GAME.RPCS3.log.gz)

* **Affected games:**
Fairytale Fights
Magus
Planet 51
Saw
The Bourne Conspiracy
and it looks that all of UE3 games are affected

https://en.wikipedia.org/wiki/List_of_Unreal_Engine_games

#### Screenshots
**Magus (missing doors)**
> ![magus 1](https://user-images.githubusercontent.com/11453507/92805213-357b6500-f3b9-11ea-926c-7d640cd959c5.jpg)
> ![magus 2](https://user-images.githubusercontent.com/11453507/92805218-3613fb80-f3b9-11ea-9ed3-a52285e31ecc.jpg)

**Fairytale Fights (missing tree)**
![fairy 1](https://user-images.githubusercontent.com/11453507/92805511-783d3d00-f3b9-11ea-873c-b5c97c1d12c6.jpg)
![fairy 2](https://user-images.githubusercontent.com/11453507/92805517-78d5d380-f3b9-11ea-9468-7cbaa7bc3db8.jpg)

**Planet 51**
![planet 1](https://user-images.githubusercontent.com/11453507/92805846-bdfa0580-f3b9-11ea-9499-3b7b6e4455b7.jpg)
![planet 2](https://user-images.githubusercontent.com/11453507/92805850-bf2b3280-f3b9-11ea-90c0-e8e9363a47ef.jpg)

**Saw**
![saw 1](https://user-images.githubusercontent.com/11453507/92816483-e4be3900-f3c5-11ea-9239-2b4c19380ce0.jpg)
![saw 2](https://user-images.githubusercontent.com/11453507/92816485-e556cf80-f3c5-11ea-96ba-0b7181c3b585.jpg)

#### PC Specs. :
CPU - Intel Core i7 8700K @ 5.0 Ghz
RAM - G.SKILL 32GB DDR4 3600MHz CL16
GPU - GeForce RTX 2080 SUPER GAMING OC 8G
OS - Windows 10 64bit

**Comment by jeremybris** [comment]
Same with Toy Story 3

**Comment by kd-11** [comment]
Specifically with the UE3 result, I am well aware of what is broken in that PR. It does however require a bit of rewriting on the vulkan side which is in progress; may take a day or two to sort it all out.
You can verify if it is indeed a vulkan regression by confirming if OpenGL is unaffected - if it is, then that is not the same bug in the regression report.

**Comment by jeremybris** [comment]
Me? Toy Story 3 – OpenGL is _unaffected_. You are a coding god! I can’t test the other games.

**Comment by JohnGodgames** [comment]
OpenGL is unaffected...verified

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/9032

**Comment by jeremybris** [comment]
@kd-11, Toy Story 3 is good now. Thank you. 

When you upscale the resolution or increase the Vblank rate, as mentioned in #5526, the issue is still present. But natively it works great. Maybe the fix here can be applied to that issue? Idk.

**Comment by JohnGodgames** [comment]
I've tested **Magus** / **Planet 51** / **Saw** with https://github.com/RPCS3/rpcs3/pull/9032 and issues are gone .Thank you

**Comment by kd-11** [comment]
@jeremybris Messing with virtual hardware features can trip up games that have hardcoded values in the released code so it is expected in rare cases that trying to enhance things just breaks them. What is important is achieving PS3 compatibility first then working around game-specific problems usually with patches because each game probably relies on specific behavior unto itself.

**Comment by Asinin3** [comment]
Ratchet & Clank: A Crack in Time has flickering textures caused by https://github.com/RPCS3/rpcs3/pull/8347

![4Ek6IRnuZA mp4-00 00 04 167-#1](https://user-images.githubusercontent.com/15137035/99862420-9c06d580-2be9-11eb-8286-83e5982d76b2.png)
![4Ek6IRnuZA mp4-00 00 04 200-#1](https://user-images.githubusercontent.com/15137035/99862427-a32de380-2be9-11eb-880a-ee24ce146aad.png)

Save: [BCUS98124_SAVE_2.zip](https://github.com/RPCS3/rpcs3/files/5576818/BCUS98124_SAVE_2.zip)

Easy to reproduce. Just leave the game running for ~15 seconds and you should see it. Sometimes Ratchet flickers, other times the world does. Flickers only happen for a single frame.

[Log After Regression](https://github.com/RPCS3/rpcs3/files/5576811/RPCS3.zip)
[Log Before Regression](https://github.com/RPCS3/rpcs3/files/5576816/RPCS3.zip)

**Comment by kd-11** [comment]
That PR was broken and all the changes in there were removed and reimplemented, so I guess it's going to be a "from scratch" investigation :(

**Comment by Asinin3** [comment]
That sucks, well if you need me to test any commits or anything just let me know.

**Comment by digitaldude555** [comment]
![Screenshot (290)](https://user-images.githubusercontent.com/26138653/106048926-27bb4780-60ee-11eb-932b-a6c038c60bec.png)
![Screenshot (291)](https://user-images.githubusercontent.com/26138653/106048929-2a1da180-60ee-11eb-8251-38856024b54f.png)
Fixed. Can close.
