### ISSUE TITLE
DJ Hero 2 regression 

### ISSUE THREAD

**Issue by Crafty-The-Fox** [RPCS3/rpcs3#8895]
[RPCS3_Regression.log](https://github.com/RPCS3/rpcs3/files/5212099/RPCS3_Regression.log)

## Quick summary
The game went from Playable to loadable, as the game loads but crashes at the Activision screen 

## Details
Before the build, the game was working perfectly fine and as expect. I recently updated to see the game throwing an Access violation reading location 0x214 (unmapped memory) error once it reached the Activision screen (it shows up after the game loads)  . i went back to a build that was 6 days ago, and it worked. 

#### 1. Build/PR:
PR #8835 (Build 0.0.12-10858) introduced the said regression, as the PR/build before it was working fine

#### 2. Please provide your system configuration:
* Windows 10 Home 1909
* i7 9700k @ 4.9 GHZ
* 2070 super
* 451.67

#### 3. Logs:
[RPCS3_Regression.log](https://github.com/RPCS3/rpcs3/files/5212100/RPCS3_Regression.log)
[RPCS3_not_regressed.log](https://github.com/RPCS3/rpcs3/files/5212104/RPCS3_not_regressed.log)

**Comment by Crafty-The-Fox** [comment]
apparently this PR makes all games require everything to be uppercase, and my game does not have all of the files uppercase. i did not expect this.

**Comment by bevanweiss** [comment]
> apparently this PR makes all games require everything to be uppercase, and my game does not have all of the files uppercase (because my game was modded). I did not expect this to happen.

This is not the case (<- pun)....
What it requires is that all filenames should have the **correct case**, this means that they should match what the PS3 expects them to be.

Prior to this PR, Windows would provide the first matching file (by filename) to the game without regard for case sensitivity.  This did result in some issues, which can only be (accurately) resolved by having Windows use the same case sensitive behaviour that the PS3 and *nix environments use.
Obviously this has started to reveal numerous situations where people have mistakenly named files 'wrong' in the Windows environment, resulting in rpcs3 no longer recognising these files as being the same files that the game is requesting (because arguably they are not... the filename does not match the filename that the game has requested).
