### ISSUE TITLE
Regression: SIG: Thread terminated due to fatal error: Assertion failed: !region.is_locked() in L.A Noire

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#8910]
After PR #8664 (v0.0.11-10717-bd21930d), L.A Noire crashes in the menu with the following errors:
`E {RSX [0x0048958]} RSX: A texture was found in cache for address 0xc0000000, but swizzle flag does not match`
`F {RSX [0x0048958]} SIG: Thread terminated due to fatal error: Assertion failed: !region.is_locked()
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKTextureCache.h:1157)`

Log from last working build (v0.0.11-10715-107129f9):
[10715.zip](https://github.com/RPCS3/rpcs3/files/5228485/10715.zip)

Log from latest master (v0.0.12-10883-92d65ff3):
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5228495/RPCS3.log)

**Comment by HenriqueLJ** [comment]
I'm having the same problem but in Kingdom Hearts 1.5, when transitioning from the bizarre room to the queens castle.

`E {RSX [0x002b634]} RSX: A texture was found in cache for address 0xc4402000, but swizzle flag does not match`


`F {RSX [0x002b634]} SIG: Thread terminated due to fatal error: Assertion failed: !region.is_locked()
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKTextureCache.h:1157)`


[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/5228668/RPCS3.zip)

![image](https://user-images.githubusercontent.com/18234027/93273965-81e6ec00-f78f-11ea-8804-074a2a49e671.png)

**Comment by kd-11** [comment]
Fixed by https://github.com/RPCS3/rpcs3/pull/8927

**Comment by Lucas15846** [comment]
hello, I have this error in god of war 3 but other games are fine, does anyone know how to fix 

F {Progress Dialog Server} SIG: Thread terminated due to fatal error: Null object.
(in file D:\a\1\s\rpcs3\Emu\RSX\Overlays\overlay_controls.cpp:38[:19], in function image_info) (e=0x00000570[1392])
(in file D:\a\1\s\Utilities\File.cpp:1028[:22], in function xnull) (e=0x00000570[1392]
