### ISSUE TITLE
God of War III occasional freezes at beginning of game

### ISSUE THREAD

**Issue by aaronjwood** [RPCS3/rpcs3#9021]
## Quick summary
It's not often but there are times when the emulator will fail due to `SIG: Thread terminated due to fatal error: Dead FIFO commands queue state has been detected!`. This happens right before you first take control over Kratos in the first playable part of the game.

### System configuration:
Windows Server 2019 Datacenter
Ryzen 3950x
Nvidia 2080 Ti
GPU driver 456.55
64GB DDR4

### Misc details
Running with the disable MLAA and disable SPU MLAA patches enabled.

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/5321139/RPCS3.zip)

**Comment by aaronjwood** [comment]
Had a similar freeze later in the beginning part of the game, but the reason for the crash was different:
```
·E 0:16:26.283518 {RSX [0x000098c]} RSX: FIFO: RET found without corresponding CALL (last cmd = 0x20000)
·F 0:16:26.286762 {RSX [0x015b2b0]} SIG: Thread terminated due to fatal error: rsx::get_address(offset=0x10dca0, location=0x66626660): Local RSX REPORT offset out of range!
(in file D:\a\1\s\rpcs3\Emu\RSX\rsx_methods.cpp:588)
```

[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/5321170/RPCS3.zip)

**Comment by Asinin3** [comment]
Make a custom config for the game then set wake-up delay to ~150us. It resolves most of the crashes. I don't really see the point in spamming the issue tracker like this

**Comment by aaronjwood** [comment]
I'm not aware of all the custom tweaks to get it working. I don't know the internal details of the PS3 hardware and how it's being emulated. I can back off on the reporting of crashes, I thought reporting defects like this would be helpful. What does everyone here expect for bug reports?

**Comment by Asinin3** [comment]
God of War 3 is listed as ingame, so issues are expected. It's not like we need an issue report on github to let us know all the games that are listed as ingame are not yet stable or have some other issue.

In terms of reporting crashes the errors in the logs themselves typically don't show the cause of the problem. And thus are generally not all that useful for developers unless the error itself is quite unique and hitting something that hasn't really been reported before. Generally speaking; I would limit reporting game crashes to regression reports where you can identify which build/pull request caused the game to break. So if your game was working before and then stopped working, find which build/pull request broke it and submit a report.

If you have a graphical issue in a game, check the wiki, check the forums perhaps it needs a specific setting? If it's not listed, experiment see if any settings fix it. If it's still broken, check youtube or forum and see if it was working before, if it was find where it broke. If it was always broken then reporting it might not be useful because a developer would have to investigate it specifically. And typically issues like that just end up getting fixed randomly as changes are made to the emulator. But if you really want to report it, then make a a renderdoc and/or rsx capture.

If you're unsure, ask in https://discord.me/rpcs3

**Comment by Hinotoumei** [comment]
They added the warning to change the delay in the newest version update. Some games will crash and before it never stated too in depth. Now it tells you to change the delay if experiencing issues. 
You might also want to consider changing the games plagued by this issue (seems to be the same ones all the time,) to not declare that they work with default settings. Changing the delay is not a default setting afterall.

Would just get rid of a lot of headache.
