### ISSUE TITLE
Regression: Graphical artifacts in GTA V (#8984)

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#9038]
After PR #8984 (rpcs3-v0.0.12-10953-9baef8c7), GTA V has white dots all over the screen.

10953
![Screenshot_11](https://user-images.githubusercontent.com/1712979/95137205-462cba00-0770-11eb-8af0-83c44f87352f.png)
[RPCS3broken.log.gz](https://github.com/RPCS3/rpcs3/files/5330345/RPCS3broken.log.gz)
https://www.dropbox.com/s/h7k4uh03alic9sg/BLES01807_20201006010125_capture.7z

Last working build (rpcs3-v0.0.12-10950-264df111)
![Screenshot_12](https://user-images.githubusercontent.com/1712979/95137288-68263c80-0770-11eb-8163-ad5f4601cb07.png)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5330348/RPCS3.log.gz)

Skyrim is also affected by this, but it doesn't go in-game on master.

**Comment by kd-11** [comment]
Need some renderdocs from you on this one.

**Comment by xddxd** [comment]
![image](https://user-images.githubusercontent.com/1712979/95170154-a6e1e400-07bc-11eb-81f9-6213ce3b7da6.png)
Yes, GL is also broken albeit it's much less present (The metal gate). I'm surprised it even works since last time I tried GL on this game it would just crap itself and crash on the loading screen.
Vulkan rdc: https://drive.google.com/file/d/1G-C-i-svjOr35-FFwz3C6jgtwYzqLvGT/view?usp=sharing

**Comment by kd-11** [comment]
This is a hardware instruction compiler thing, probably only present on AMD and other than reverting the change, there is no easy workaround. The current implementation is already itself a workaround as neither AMD, NVIDIA nor INTEL correctly had the instructions I needed correctly working in their SPIRV compilers. That being said, I'm still working on the shader stuff, I might think of some other (probably better) way of doing the same downcast.
FTR the issue here is precision loss when going from F32 to F16 which seems to generate slightly different values on AMD. Emulating F32 to F16 casts is horrendously slow however, and I would like to avoid that at all costs.

**Comment by xddxd** [comment]
Fixed by... something. Not an issue anymore.
