### ISSUE TITLE
Vulkan Validation Errors / Warnings when using Validation Configurator and adding diagnostic layers

### ISSUE THREAD

**Issue by bevanweiss** [RPCS3/rpcs3#9054]
## Quick summary
When adding additional validation layers via the Vulkan Configurator, there are a number of warnings and validation errors presented which, if fixed up, might help to obtain better behaviour from various graphics cards (since validation errors puts us into Vulkan Undefined Behaviour territory).

## Details
Validation errors first..
Validation Error: [ UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotUpdated ] Object 0: handle = 0x46817500000cb440, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0x50363c8d | VkDescriptorSet 0x46817500000cb440[] encountered the following validation error at vkCmdDraw() time: Descriptor in binding 10 index 0 requires an image view of type VK_IMAGE_VIEW_TYPE_1D but got VK_IMAGE_VIEW_TYPE_2D.

Validation Error: [ SYNC-HAZARD-WRITE_AFTER_WRITE ] Object 0: handle = 0x1f464100000f2447, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0xfdf9f5e1 | vkCmdCopyImage: Hazard WRITE_AFTER_WRITE for dstImage VkImage 0x1f464100000f2447[], region 0. Access info (usage: SYNC_TRANSFER_TRANSFER_WRITE, prior_usage: SYNC_TRANSFER_TRANSFER_WRITE, write_barriers: 0, command: vkCmdClearDepthStencilImage, seq_no: 164, reset_no: 12).

Validation Error: [ SYNC-HAZARD-READ_AFTER_WRITE ] Object 0: handle = 0x60cd5300000c858d, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0x4cb75b2d | vkCmdDrawIndexed: Hazard READ_AFTER_WRITE for VkImageView 0x60cd5300000c858d[], in VkCommandBuffer 0x1151d8608[], and VkPipeline 0xb80ab40000008972[], VkDescriptorSet 0xfff57a00000f7379[], type: VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, imageLayout: VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, binding 42, index 0. Access info (usage: SYNC_VERTEX_SHADER_SHADER_READ, prior_usage: SYNC_IMAGE_LAYOUT_TRANSITION, write_barriers: SYNC_FRAGMENT_SHADER_INPUT_ATTACHMENT_READ|SYNC_FRAGMENT_SHADER_SHADER_READ, command: vkCmdPipelineBarrier, seq_no: 383, reset_no: 12).

And then Validation warnings

Validation Performance Warning: [ UNASSIGNED-BestPractices-vkCreateCommandPool-command-buffer-reset ] Object 0: handle = 0x115c15a68, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x8728e724 | vkCreateCommandPool(): VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT is set. Consider resetting entire pool instead.

Validation Warning: [ UNASSIGNED-GeneralParameterError-RequiredParameter ] Object 0: handle = 0x115c15a68, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x99fb7dfd | vkCmdDraw parameter, uint32_t vertexCount, is 0

Validation Performance Warning: [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object 0: handle = 0x115c15a68, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x4dae5635 | vkCreateRenderPass(): Layout for color attachment reference 0 in subpass 0 is GENERAL but should be COLOR_ATTACHMENT_OPTIMAL.

Validation Performance Warning: [ UNASSIGNED-CoreValidation-Shader-OutputNotConsumed ] Object 0: handle = 0x1aa1b30000000c42, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0x609a13b | vertex shader writes to output location 1.0 which is not consumed by fragment shader

Validation Warning: [ UNASSIGNED-CoreValidation-Shader-OutputNotConsumed ] Object 0: handle = 0xb65e790000000c48, type = VK_OBJECT_TYPE_SHADER_MODULE; | MessageID = 0x609a13b | fragment shader writes to output location 1 with no matching attachment

Validation Performance Warning: [ UNASSIGNED-BestPractices-DrawState-ClearCmdBeforeDraw ] Object 0: handle = 0x11441af98, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x6c5e402 | vkCmdClearAttachments() issued on VkCommandBuffer 0x11441af98[] prior to any Draw Cmds. It is recommended you use RenderPass LOAD_OP_CLEAR on Attachments prior to any Draw.

Validation Performance Warning: [ UNASSIGNED-BestPractices-vkCmdClearAttachments-clear-after-load ] Object 0: handle = 0x115c15a68, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x8b5931c4 | vkCmdClearAttachments() issued on VkCommandBuffer 0x11441af98[] for the depth attachment in this subpass, but LOAD_OP_LOAD was used. If you need to clear the framebuffer, always use LOAD_OP_CLEAR as it is more efficient.

#### 1. Please attach RPCS3's log.
RPCS3 Log attached, but no significant gameplay issue identified (apart from bad z-fighting which has been reported already).
[RPCS3.zip](https://github.com/RPCS3/rpcs3/files/5358589/RPCS3.zip)

Vulkan Validation Warnings attached below
[rpcs3 Vulkan Validation Warnings.zip](https://github.com/RPCS3/rpcs3/files/5358590/rpcs3.Vulkan.Validation.Warnings.zip)

#### 5. Please provide your system configuration:
* OS - Windows 10 2004
* CPU - Intel i7-9750H
* GPU - Nvidia 2070M
* Driver version - 456.38.0.0

**Comment by kd-11** [comment]
These are going to vary depending on the game being tested. That being said, some notes:
1. Yes, we do alias 1D and 2D on purpose. This is a design decision made a while back to avoid generating duplicate images, a 1D image and a 2D image with a height of 1 are identical from a PS3 pov but not PC. We could also just completely scrap 1D textures entirely, but I have yet to encounter a GPU that has issues with 1D emulation like this.
2. The hazards are going to be game specific. I am curious what sequence of commands resulted in them being emitted although most of the time they may be harmless - e.g if its complaining about use of a temp resource.
3. The warnings are pretty much useless for us. They're decent suggestions if you're writing your own game, but here the game running the command sequences is a PS3 game. We cannot make any assumptions with what its going to do next, so common optimization tactics are not suitable here. We have to assume all possible paths will happen, because unfortunately PS3 (and honestly PC as well) hardware really does not care about most of these things. The underlying GPU driver cleans up most of these for us anyway. Would be nice to revisit these much later in development when there isn't much left to fix behavior-wise for the emulator.

**Comment by kd-11** [comment]
Let's use https://github.com/RPCS3/rpcs3/issues/9495 for this discussion. It has a lot more traction and is constantly updated.
