### ISSUE TITLE
[Feature Request] Being able to map DJ Hero tables on RPCS3

### ISSUE THREAD

**Issue by Crafty-The-Fox** [RPCS3/rpcs3#9111]
## Quick summary
you currently cant map DJ Hero tables on RPCS3, at all.

## Details

Even though there is an option in the menu for controller settings, it doesn't to anything in game/pull up a turntable thing that you can map to. I would like this to change, sort of as "emulating" a dj hero controller.

#### 1. Please describe, what part of RPCS3 would be affected by your feature:
* Gameplay
* Input
* UI

#### 2. Please tell us, why your feature is important to RPCS3.
This would make many other people who have wii/xbox 360 turntables be able to play DJ hero on RPCS3.

#### 3. Please attach screenshots of the feature implemented in other projects.
![image](https://user-images.githubusercontent.com/59181698/96799210-993d7880-13d0-11eb-8465-c8b83096f122.png)

#### 4. Please provide your system configuration:
* Windows 10 Home 64 bit
* 9700k at 4.9GHZ
* 2070 super
* 456.71

**Comment by bevanweiss** [comment]
So Dolphin currently allows emulation of the same USB device? (The DJ Hero Turntable).

That might make things easier, since it would mean in the Dolphin source code there could possibly be the different USB transfers that are required for each of the turntable controls.

This is the real challenge with emulating USB devices in RPCS3, the emulator itself isn't responsible for interpreting the USB transfers, the PS3 kernel passes these straight through to the application (game), so we don't get to just say to the game 'Crossfade Left'.. we have to work out what sequence of USB transfers the game itself interprets as 'Crossfade Left'... and that's typically not simple.

**Comment by Crafty-The-Fox** [comment]
Yes, Dolphin has this same feature.

**Comment by Florin9doi** [comment]
Dj Hero controller is described here: https://frontjang.info/m/entry/DJ-Hero-Turntable-for-PS3-%ED%95%98%EB%93%9C%EC%9B%A8%EC%96%B4%EC%A0%81-%EB%B6%84%EC%84%9D

**Comment by Crafty-The-Fox** [comment]
Not sure when the PR will come, but its been done by a friend of mine:
https://github.com/shockdude/rpcs3/tree/turntable_emulation

**Comment by Satan86** [comment]
Issue should stay open until a pull request to implement it is merged

**Comment by barapuntoexe** [comment]
no entendi nada del procedimiento :C
