### ISSUE TITLE
Uncharted 2 crash with SIG: Thread terminated due to fatal error: PPU Trap!

### ISSUE THREAD

**Issue by Loacoon1** [RPCS3/rpcs3#9216]
## Quick summary
Uncharted 2 crashes

## Details

Uncharted 2 crashes apparently randomly, with error code :

F {PPU[0x1000000] Thread (main_thread) [0x00527c64]} SIG: Thread terminated due to fatal error: PPU Trap!
(in file ../rpcs3/Emu/Cell/PPUThread.cpp:1098)

#### 1. Please attach RPCS3's log.
I have no log because the most recent in my ~/.cache/RPCS3 folder is from March...

#### 5. Please provide your system configuration:
* OS Manjaro Linux
* CPU AMD Ryzen 3700X
* GPU Geforce RTX 2070
* Driver version 455.38
* 16GB 3600Mhz RAM

**Comment by zminhquanz** [comment]
Try to clear PPU Cache , and recompile again , it's seem a bad cache of PPU , not a bug

**Comment by Loacoon1** [comment]
Okay so I had to update RPCS and erase all caches for it to work, but I've been able to pass the crash point. Thanks!

**Comment by redisdwarf** [comment]
Hello, i've got the same problem only with the game Tekken Tag Tournament 2 since an update in 2020.
I tried to clear all caches especially PPU, update the bios to the last version, to reinstall RPCS3, to reinstall Windows but it I meet the same issue.

**Comment by RainbowCookie32** [comment]
Stop posting the same message over different threads. If you need support, use [our Discord server](https://discord.me/RPCS3) instead

**Comment by redisdwarf** [comment]
Just fuck you.

 

De : Matias ***@***.***> 
Envoyé : samedi 1 mai 2021 18:13
À : RPCS3/rpcs3 ***@***.***>
Cc : redisdwarf ***@***.***>; Comment ***@***.***>
Objet : Re: [RPCS3/rpcs3] Uncharted 2 crash with SIG: Thread terminated due to fatal error: PPU Trap! (#9216)

 

Stop posting the same message over different threads. If you need support, use our Discord server <https://discord.me/RPCS3>  instead
