### ISSUE TITLE
Games freezing with TSX-FA after (#9232)

### ISSUE THREAD

**Issue by AphelionWasTaken** [RPCS3/rpcs3#9238]
## Quick summary
As of PR #9232, some games freeze during gameplay with TSX-FA enabled.

## Details
Some games such as Demon's Souls are freezing after several minutes of gameplay with TSX-FA enabled. The first build with this issue is 0.0.13-11212 (PR #9232), which is already marked as "bad"; however, the issue persists on the current master build.

#### 1. Please provide _exact_ build (or commit) information that introduced the regression you're reporting.
0.0.13-11212 (PR #9232)

#### 2. Please attach TWO logs:
First broken build - [RPCS3 - 9232.log.gz](https://github.com/RPCS3/rpcs3/files/5519018/RPCS3.-.9232.log.gz)
Last working build - [RPCS3 - 9231.log.gz](https://github.com/RPCS3/rpcs3/files/5518942/RPCS3.-.9231.log.gz)

#### 4. Please attach screenshots of your problem.
![Untitled](https://user-images.githubusercontent.com/61633628/98707627-dcdb3080-2345-11eb-9cfb-d24b8b8f845a.png)

#### 6. Please provide your system configuration:
* OS - Win 10
* CPU - 8600K
* GPU - 1060 6GB
* Driver version - 452.6.0.0

**Comment by lainiwaku** [comment]
i have lot of freezing at last of us loading, don't know  if it's the same regression but i hope it is !

**Comment by griever-gf** [comment]
I totally confirm this TSX bug! It drived me crazy before I found the reason! In Demon's Souls, yes.

As far as I remember, these random freezes happened since 0.0.13-11166 version at least. In some versions these freezes happened rarely on not at all (one time I was able to play 8+ hours without freezes). But I remeber these random freezes since 0.0.13-11166 version (I don't tried earlier versions).
In 0.0.13-11122 version, which I attach, these freezes became worse, more frequent, but they are happened before too!

1. Presents at least since 0.0.13-11166.
Still presents in 0.0.13-11122.

2. These are two log files for 0.0.13-11122. Workings is TSX off, broken is TSX on. I have no time to check earlier versions.
[RPCS3.log.by_GrieverGF.broken.gz](https://github.com/RPCS3/rpcs3/files/5526845/RPCS3.log.by_GrieverGF.broken.gz)
[RPCS3.log.by_GrieverGF.working.gz](https://github.com/RPCS3/rpcs3/files/5526846/RPCS3.log.by_GrieverGF.working.gz)

4.  ![capture_001_12112020_001927](https://user-images.githubusercontent.com/1813367/98866653-55450d00-247e-11eb-9ea5-7c8eda44692b.png)

6. OS - Win 10
CPU - 6600K
GPU - GTX 970
Driver version - 457.09 (27.21.14.5709)

**Comment by griever-gf** [comment]
UPD: after turning off TSX freezes still can happen, but very rarely, I suppose one time per 5 hours usually.
Maybe I have multiple freeze issues, I don't sure. But turning off TSX helped a lot anyway.

I'll try to get a crash log without TSX later.

**Comment by Nekotekina** [comment]
#9266 may fix this

**Comment by Asinin3** [comment]
Someone in discord confirmed Demon's Souls doesn't crash with TSX-FA and latest build from Neko. Please confirm and close.

**Comment by AphelionWasTaken** [comment]
Confirmed and closed. #9266 has been merged and I've been running the game for an hour on the current master build with TSX-FA. This no longer seems to be an issue.

**Comment by griever-gf** [comment]
I approve that the lasest build freezes very rarely. BUT it looks like perfomance decreased on 4-cores CPUs. Sometimes random slowdowns happen and I need to kill apps like browser to fix this.

**Comment by griever-gf** [comment]
I approve that the lasest build freezes very rarely. BUT it looks like perfomance decreased on 4-cores CPUs. Sometimes random slowdowns happen and I need to kill apps like browser to fix this. And rare freezes still can happen, now with creating a giant log file, more than 1 GB, so I need to kill the emulator to fix this.

**Comment by BioflakesDG** [comment]
Yeah using the latest build 0.0.13-11265-28cbba5a #9291 there's no freezes, but performance on my 8600k is worse. I can confirm that on #9231 performance is better.
