### ISSUE TITLE
Red Dead Redemption Windows on Houses Flickering 

### ISSUE THREAD

**Issue by Kristijan1001** [RPCS3/rpcs3#9339]
## Quick summary
The windows on houses keep flickering only happens when using Vulkan, i am using a 2070 Super i9 9900k

## Details

Flickering House Windows.

#### 3. Please attach screenshots of your problem.
https://i.imgur.com/0akWeaE.jpg

https://i.imgur.com/WuEsRTO.jpeg

#### 5. Please provide your system configuration:
* Windows 10
* i9 9900k
* 2070 SUPER
* Last Nvidia Drivers

**Comment by AniLeo** [comment]
Known issue, unsure if we already have it on tracker or not, kd-11 is aware

**Comment by sibradzic** [comment]
Same issue here, Linux @ RX5700 Mesa 20.2.3 AMDVLK. Been like this for most of 2020 RPCS3 releases. Disabling anti-aliasing makes it go away.

**Comment by sibradzic** [comment]
> Known issue, unsure if we already have it on tracker or not, kd-11 is aware

Not really, I've been looking for it left and right for quite a while, thought it is Linux/mesa/AMDVLK specific, but then after seeing this report it looks like it is a generic issue.

**Comment by kd-11** [comment]
Its been like this since RDR first rendered visuals. Turning off MSAA doesn't really fix it either, it still happens in far away structures but the MSAA version is even more trippy than usual. It's a known issue, but its not too severe compared to some other game-breaking issues which is why its still present.
