### ISSUE TITLE
SoulCalibur V [BLUS30736] upscaling glitches

### ISSUE THREAD

**Issue by toccata10** [RPCS3/rpcs3#9436]
I've wanted to report this for a long time.
When I saw the upscaling rewrite, I hoped that the upscaling problems in SoulCalibur V
[BLUS30736] would be gone.
Unfortunaltely, not.
So, maybe they are already known, but I didn't see any recent issue on this.
My system is an i7-8700k with r9 fury on Archlinux (mesa 20.3).
When upscaling by 200 or 300% (4k), 2 things:
1) Resolution Scale Threshold has to be around 200 to avoid some glitches, or you get this:
![2020-12-09_20-27-200](https://user-images.githubusercontent.com/7478580/102140100-13cdc600-3e5f-11eb-9fbe-7fc9fcca2873.png)
2) the upscaling is not "stable": the image is cycling between very good to very blocky (blockier than without upscaling) every 2 seconds.
I tried to apply "disable spu mlaa-multiple titles(02)" as it talks about SoulCaliburV: no change.
Without upscaling:
![2020-12-09_20-24-100](https://user-images.githubusercontent.com/7478580/102140184-2f38d100-3e5f-11eb-9394-3838f1c23a71.png)
With the 300% upscaling, the image is sometimes like this (looking great):
![2020-12-09_20-17](https://user-images.githubusercontent.com/7478580/102140309-5abbbb80-3e5f-11eb-9ef5-ab77dc4a55f7.png)
Then, it changes gradually to this (very blocky):
![2020-12-09_20-16](https://user-images.githubusercontent.com/7478580/102140432-7f179800-3e5f-11eb-9137-7a13127afbbd.png)
Then it comes back to great,..then blocky, and so on...
The fps is between 55 and 60fps.
No idea if this could be solved, but I suppose it's worth reporting the problem.
And, of course, the log:
[RPCS3-SCV.zip](https://github.com/RPCS3/rpcs3/files/5691817/RPCS3-SCV.zip)

**Comment by zombie167** [comment]
My situation is not as serious as yours.It can only be noticed when taking a screenshot or in the case of a static picture, generally showing the phenomenon of flickering.The solution is to set the VBlank frequency to 75 to eliminate that phenomenon, but the screen will become faster although the display is 60 frames

https://youtu.be/rTOogg8nraA

**Comment by digitaldude555** [comment]
@toccata10 retest

**Comment by MsDarkLow** [comment]
The problem still persists, however I believe this is not a valid issue because resolution scaling is a hack.
Here's a better demonstration of the issue.
![sxt8koyawU2](https://user-images.githubusercontent.com/9060436/107156874-bfcff100-6978-11eb-9856-c8ea11eaad28.gif)

I do however have good news. If you enable the ideal world settings (Write Color Buffers, Read Depth Buffers, Write Depth Buffers, Read Color Buffers, Force CPU Blit Emulation) AND MLAA Patch, you can upscale without issues. Here's proof of it.
![rXFHtoc9S62](https://user-images.githubusercontent.com/9060436/107156899-e726be00-6978-11eb-8d33-a21a0c342475.gif)

**Comment by MSuih** [comment]
Closing as resolved

**Comment by toccata10** [comment]
@MsDarkLow Thanks, SoulCalibur V has never looked so good (because of your settings). With a resolution scale threshold at 512x512, I've got neglectable artifacts and the game is splendid.

**Comment by VelociTraptor317** [comment]
@MsDarkLow @toccata10 I'm not sure if this is because of new emulator version, or different CPU, GPU, and driver configuration, but I am still getting the flickering issue even with the settings you suggested. Do you guys still have SoulCalibur V running without flickering even with modern emulator version, hardware, and drivers? These posts are pretty old so a lot could have changed. I appreciate any feedback I can get here :)
