### ISSUE TITLE
Regression: Hitting unreachable code in surface store on some games (#9434)

### ISSUE THREAD

**Issue by Kojikun1** [RPCS3/rpcs3#9474]
## Quick summary
Uncharted: Drake's Fortune start crashing on gameplay

## Details
Random crash  after start gameplay
```
Thread terminated due to fatal error: Unreachable
(in file D:\a\1\s\rpcs3\Emu\RSX\Common\surface_store.h:0x2f8[:0x18], in function get_surface_at)
```
Regression start with this build 0.0.13-11405
https://github.com/RPCS3/rpcs3/pull/9434

Regression Build log 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5721762/RPCS3.log)

Works as expected Build Log 
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5721770/RPCS3.log)

System Config
* OS Windows 10 Home 64bits 20H2
* CPU Intel Core i5 9300H
* GPU GTX 1650
* Driver Version 456.38

**Comment by slikvik55** [comment]
I'm getting exactly the same error but it actually happens on all Naughty Dog games. Same error on UC1, UC2, UC3 and TLOU. RPCS3 is working fine with ALL the other games I've tried.
 
[RPCS3-UC3.log](https://github.com/RPCS3/rpcs3/files/5736920/RPCS3-UC3.log)
[RPCS3-UC2.log](https://github.com/RPCS3/rpcs3/files/5736921/RPCS3-UC2.log)
[RPCS3-UC1.log](https://github.com/RPCS3/rpcs3/files/5736922/RPCS3-UC1.log)

System Config

- OS Windows 10 Pro 64bits 20H2
- CPU AMD 5600X
- GPU RTX 3060Ti
- Driver Version 460.89

**Comment by Kojikun1** [comment]
This Error Starts with this build 0.0.13-11405

**Comment by Joaozin-tech** [comment]
Ok problems occurs in games GOD OF WAR 3 DEMO E3 2009
GOD OF WAR 3 FULL GAME

**Comment by Kojikun1** [comment]
> Ok problems occurs in games GOD OF WAR 3 DEMO E3 2009
> GOD OF WAR 3 FULL GAME testing master rpcs3 0.0.13-11469

Post the logs too

**Comment by Joaozin-tech** [comment]
ok

**Comment by slikvik55** [comment]
@Joaozin-tech That's different error I'm afraid. The specific error we're getting is:

**Thread terminated due to fatal error: Unreachable
(in file D:\a\1\s\rpcs3\Emu\RSX\Common\surface_store.h:0x2f8[:0x18], in function get_surface_at)** 

and only occurs in the Uncharted Games and TLOU (all using the same ND engine).

I've tried the following games and they all work fine:
God of War 3
Ni No Kuni
Wipeout
Lollipop Chainsaw

**Comment by Joaozin-tech** [comment]
by observing this God of War he has the same error as The Last Of US at certain times he has this error and among others too

**Comment by slikvik55** [comment]
Sorry but I don't understand. The screenshots and logs you posted do **not** contain the error that the OP and myself are getting:
Thread terminated due to fatal error: Unreachable
(in file D:\a\1\s\rpcs3\Emu\RSX\Common\surface_store.h:0x2f8[:0x18], in function get_surface_at)

It is a **different** error so should be a different issue to open.

God of War 3 works fine on my system but in Uncharted, me and Kojikun1 get "Unreachable". If you have problems with God of War 3 and it is a different crash to this one, then maybe open it as a new issue so that the devs can deal with them separately?

**Comment by CodyMechanix** [comment]
I didn't figure out a fix on the current versions of the emulator, but the game works fine on the v0.0.13-11400 build.
