### ISSUE TITLE
Regression: Sonic Unleashed lost massive performance (#8888)

### ISSUE THREAD

**Issue by OrdinaryGP** [RPCS3/rpcs3#9476]
## Quick summary
Sonic Unleashed has lost from 3-50 FPS Depending on area. (Generally 5-9 FPS Loss)

## Details
Regression Occurred in The Form of massive framerate loss. This causes the game to differ even farther from the playable status. Many areas take a hit, minus a few. Jungle Joyride 2nd 3D Section is A Good Example of No change.

#### 1.
Issue Became Present in Merge #8888 
Build Name: 0.0.12-10869-9ff0b460 

#### 2. Please attach TWO logs:
Regression: [RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5722419/RPCS3.log.gz)
Before Regression: 
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5722431/RPCS3.log.gz)

#### 4. Please attach screenshots of your problem.
After Regression: ![SURegression1](https://user-images.githubusercontent.com/76417824/102742228-a663de80-4311-11eb-9e8a-0576080b394c.png)
Before Regression: 
![SURegression2](https://user-images.githubusercontent.com/76417824/102742266-bd0a3580-4311-11eb-847e-f4ae05c076ff.png)

#### 5. Please provide comparison with real PS3.
I do not have a framerate counter on PS3, and this is a build to build issue, not an issue with performance comparing RPCS3 to PS3.

#### 6. Please provide your system configuration:
*Windows 10 Home
* Ryzen 7 3700X
* Radeon RX 5600XT
* 20.11.2

**Comment by Augusto7743** [comment]
Sonic Unleashed on PS3 has an automatic frame rate engine. In some areas will be 30 FPS and in others 60 FPS having also slow downs that I not remember exactly what the exact value being less of 30 FPS.
SPU analizer will slowdown emulation in some CPUs.

I has Sonic Unleashed, but not is possible dump the disc. Thus I has tested the demo version and is running between 10-15 FPS on Linux Ubuntu 20.10 FX-6300 - 4 GB - GT 640.

Have you used Process Lasso Pro on Windows ? Process Lasso Pro help the system managing the CPU cores.

**Comment by OrdinaryGP** [comment]
That Sounds Kinda Like Bloatware, but I assure you this is an issue with RPCS3, since multiple people reported it before.

**Comment by Augusto7743** [comment]
Process Lasso Pro being bloatware ? When I had used windows the system and others software had better performance using Process Lasso. Have options to "fix" the windows thread scheduler bug with some CPUs and really emulators has better performance,
Now using Linux not need any thing .... is a wonderful OS ... I not return to windows

**Comment by OrdinaryGP** [comment]
Idk, I saw a 1fps-2fps increase using the Performance Mode option it has, I have not looked deeper into it, an explanation on how to use it could be helpful.

**Comment by Augusto7743** [comment]
I had used that software in windows .... Primocache and Process Lasso Pro are the best utilities for windows.
Windows thread scheduler has problems and look how they not wish really fix it  .... much promise to fix and not totally fixed.
Process Lasso has options to schedule the CPUs cores better than windows does ... Have option to select RPCS3 to be high priority and when the RPCS3 is running Process Lasso analyzes others tasks and low priorities for tasks not need to run.
Have options to disable core park and much more. You need select the RPCS3 executable name in process list and select options to enable performance boost thus Process Lasso has information what is the software that you wish to has better performance.
I had used AMD FX and had better performance. windows had problems had Ryzen was released having less performance.

Using now Linux and not need any software to fix thread scheduler. Linux use the AMD FX and Ryzen much better than windows and RPCS3 run better even in some times that the performance is similar to windows because not has drop in performance that happen when windows is trying start an task not need to run RPCS3 and thus RPCS3 drop FPS.
Even MAME run more fast in Linux being more of 10 % emulation speed.

The only problem even is that Linux use mainly OpenGL and was an big luck that Vulkan was released. GPU cards are designed mainly for DirectX, but now with Vulkan was an big step to Linux reach better graphics performance than using OpenGL.

If you wait information about the problem see the text in 
https://bitsum.com/portfolio/coreprio/
You to do an test in Linux and if the result not has performance issues open an report about it.

**Comment by Xcedf** [comment]
First of all TSX is not affected by regression, but since there much more people out there are non-TSX decided to do this one.
still a regression on recent master, but did a revert for PUTTLUC 9c88c36
and here's the results
master build (TSX disabled)
![15](https://user-images.githubusercontent.com/7060586/149029698-2bfa49ba-3b16-431b-b5a5-68fefcb8b479.jpg)
master build+non-accurate PUTTLUC (TSX disabled)
![14](https://user-images.githubusercontent.com/7060586/149029810-ba9fbf1b-b6d3-423f-b795-007e8340efd1.jpg)
and just for reference TSX Enabled
![13](https://user-images.githubusercontent.com/7060586/149029852-63d33322-c853-4005-bc86-f011ac327c64.jpg)

also nocited difference in SPU Test
master build (TSX disabled)
SPU Test v1.1.2 by GalCiv
SPU Task Avalanche completed in 4808 ms (PS3: 2740 ms)
PPU/SPU Ping-Pong completed in 2124 ms (PS3: 3045 ms)
SPU MFC 64 Bits War completed in 4133 ms (PS3: 3370 ms)
PPU/SPU MFC 64 Bits War completed in 4959 ms (PS3: 4443 ms)
SPU Integer Perf completed in 1961 ms (PS3: 8666 ms)
SPU Float Perf completed in 479 ms (PS3: 2379 ms)
SPU SpinLock completed in 3355 ms (PS3: 4409 ms)
PUTLLUC Perf completed in 9208 ms (PS3: 3853 ms)  - an atrocity!!!
PUTLLC Perf completed in 1767 ms (PS3: 3364 ms)
PUT Perf completed in 986 ms (PS3: 3984 ms)
Large PUT Perf completed in 1344 ms (PS3: 4454 ms)
--Completed 11 tests in 35127 ms--

master build+non-accurate PUTTLUC (TSX disabled)
SPU Test v1.1.2 by GalCiv
SPU Task Avalanche completed in 4812 ms (PS3: 2740 ms)
PPU/SPU Ping-Pong completed in 2063 ms (PS3: 3045 ms)
SPU MFC 64 Bits War completed in 4082 ms (PS3: 3370 ms)
PPU/SPU MFC 64 Bits War completed in 4869 ms (PS3: 4443 ms)
SPU Integer Perf completed in 1962 ms (PS3: 8666 ms)
SPU Float Perf completed in 477 ms (PS3: 2379 ms)
SPU SpinLock completed in 3247 ms (PS3: 4409 ms)
PUTLLUC Perf completed in 7166 ms (PS3: 3853 ms)
PUTLLC Perf completed in 1768 ms (PS3: 3364 ms)
PUT Perf completed in 967 ms (PS3: 3984 ms)
Large PUT Perf completed in 1320 ms (PS3: 4454 ms)
--Completed 11 tests in 32736 ms--
