### ISSUE TITLE
vkCmdEndRenderPass exception

### ISSUE THREAD

**Issue by Megamouse** [RPCS3/rpcs3#9490]
No idea how this happened, but I just got another exception in this line.

![image](https://user-images.githubusercontent.com/23019877/103020458-b580a180-4548-11eb-81b4-3657a8faece3.png)

**Comment by kd-11** [comment]
This can happen in local windows builds when there are some memory issues. In this case I suspect for whatever reason the renderpass was still registered as active for the current CB while it had already been closed. If it can be reproduced then I can proceed with the investigation, otherwise its just not possible to diagnose as the crash happens inside nvidia code.

**Comment by Megamouse** [comment]
I guess it can be closed then. Because it's rather rare and only happened when I tried to reproduce the other one
