### ISSUE TITLE
freebsd: Build failure, cannot find 'llvm11' package

### ISSUE THREAD

**Issue by AniLeo** [RPCS3/rpcs3#9518]
Build log: https://cirrus-ci.com/task/4850046283808768?command=install#L73

`pkg: No packages available to install matching 'llvm11' have been found in the repositories`

This started happening without any modifications from our side, any idea what happened @jbeich?

**Comment by jbeich** [comment]
`llvm11` [failed](http://beefy6.nyi.freebsd.org/data/121amd64-default/559329/logs/errors/llvm11-11.0.0_1.log) during [previous package build](http://beefy6.nyi.freebsd.org/build.html?mastername=121amd64-default&build=559329) on FreeBSD 12.* amd64 for `/latest` set. [The next build](http://beefy6.nyi.freebsd.org/build.html?mastername=121amd64-default&build=559535) already started and `llvm11` is [fine](http://beefy6.nyi.freebsd.org/data/121amd64-default/559535/logs/llvm11-11.0.0_1.log) again. Expect `llvm11` to reappear soon (sometime tomorrow UTC).

In general, FreeBSD builds packages as a set in order to prevent ABI issues. If something fails it's temporarily removed from the set.

**Comment by MSuih** [comment]
The builds aren't failing anymore, so I assume this is now resolved. Thanks @jbeich for explaining what the issue was.
