### ISSUE TITLE
Ridge Racer 7 (NPUB30457) - Menu not working on Online Battle

### ISSUE THREAD

**Issue by Back2Life888** [RPCS3/rpcs3#9522]
## Quick summary
The menu breaks on the Online Battle menu. 

## Details
If you go to Online Battle and then on Room, the game will be running fine but you can't use the controller. You can't even get out of the menu. The only way to get out of the Menu is to quit the game.

#### 1. Please attach RPCS3's log.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/5754350/RPCS3.log)
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5754352/RPCS3.log.gz)

#### 3. Please attach screenshots of your problem.
![jhjfsfjg](https://user-images.githubusercontent.com/76780043/103354921-d0728900-4ae7-11eb-9059-cd3e5b4528bf.PNG)

#### 4. Please provide comparison with real PS3.
I have a PS3 but its broken. I'm pretty sure that in the real PS3, you can navigate on the menu with no problems.

#### 5. Please provide your system configuration:
* OS: Windows 10
* CPU: Intel i7-6700
* GPU: NViDiA Quadro K620
* Driver version: 460.89
* etc.

#### Please include.
* Anything else you deem to be important

**Comment by AniLeo** [comment]
RPCN compatibility should be reported on the netplay channel on our Discord as we have a spreadsheet for tracking these: 
https://docs.google.com/spreadsheets/d/1Xp-662d12W13CZSzSiaBfB4BHwU2PyOFMdp_W4sA5Bo

Most games aren't compatible with RPCN yet, mainly due to unimplemented functionality.
The behavior you describe here is already included in the spreadsheet as well - "Game freezes whenever you try to go online".

**Comment by Back2Life888** [comment]
Not technically freeze.. The menu itself froze and I can't do anything..
