### ISSUE TITLE
Jak And Daxter 3 BCUS98281 - Flickering sky with Vulkan but not with OpenGL

### ISSUE THREAD

**Issue by Pouncha** [RPCS3/rpcs3#9741]
I thought this issue was fixed but not.
When you play Jak 3,the sky is still flickering during intro.
It's curious coz, before , this issue was there whatever the graphic renderer.Now,no more flickering with OpenGL but the game lost FPS.May it possible to get this flickering fix in vulkan renderer too ?
I use Windows 10 wiht I9 9900KF,GTX 1080 (last drivers) and 32go RAM
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/5942285/RPCS3.log.gz)

**Comment by Asinin3** [comment]
You stated yourself that this issue was fixed previously and now it's broken. But didn't do any testing as to when it broke again.
If it's a regression: Locate the **exact build** where it regressed, and tag the offending Pull Request, then attach a RSX/Renderdoc capture of the issue.
If it's not a regression. then we will still need a renderdoc/rsx capture. Closing issue until this info is provided.

**Comment by gamrXerus** [comment]
@Asinin3  I can confirm the flickering issue in both Jak 2 and Jak 3. It comes and goes really quickly so i tried my best to capture it. Hope this helps. 
Jak3 RSX capture
https://drive.google.com/file/d/1N5P4v7FINfNY9fPoKODqHjxr5o0rl8eW/view?usp=sharing
Jak2 RSX capture
https://drive.google.com/file/d/1w_yR5HiRXfZbpOFJvIM6z_ZU2WCUsXkj/view?usp=sharing
