### ISSUE TITLE
Emulator crashing when creating an RPCN account

### ISSUE THREAD

**Issue by KrisEnigma** [RPCS3/rpcs3#9821]
Hello, I just installed RPCS3, and when I try to make an RPCN account it crashes after filling the email (it's a gmail address).

This is the error message:
![RPCN error](https://user-images.githubusercontent.com/18688438/108694008-43dbba00-74dd-11eb-8a57-d497a72b1c0c.jpg)

Here's the log file:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6021176/RPCS3.log)

* OS: Windows 10
* CPU: i7-7700K
* GPU: NVidia GeForce 970
* Driver version: 461.40

Thanks for the help!

**Comment by Skynet19972029** [comment]
Exact same issue for 2 days now.
Tried again with 11786 just downloaded.

**Comment by ddm999** [comment]
As a quick fix for anyone running into this issue, you can downgrade your version of RPCS3 to make an account (download a week old version, extract just the executable into your RPCS3 directory, and use it just to make your account before returning to latest).

Seems like it must've been caused by #9812 ?
I think that's about when this started happening, and I don't believe any other commits nearby touched networking.
