### ISSUE TITLE
Regression: Unsupported image layout 0x5 on GTA V (#9434)

### ISSUE THREAD

**Issue by xddxd** [RPCS3/rpcs3#9887]
After PR #9434, GTA V crashes with 
`F 0:01:16.175684 {RSX [0x0094a14]} SIG: Thread terminated due to fatal error: Unsupported image layout 0x5
(in file D:\a\1\s\rpcs3\Emu\RSX\VK\VKRenderPass.cpp:83[:25], in function get_renderpass_key)`
Log from the last working build:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6074969/RPCS3.log.gz)
Log from latest master:
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/6074981/RPCS3.log)

**Comment by jokoputera** [comment]
Could you try with Uncharted Drake Fortune? Is it the same error?

**Comment by linkmauve** [comment]
Hi, this error also happens near the beginning of Persona 5, after a few jumps over the casino, and near the beginning of NieR during the fight after having obtained the book.

It can be fixed by adding `case VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL:` on line 81 in VKRenderPass.cpp, but I don’t quite understand how you use it.

**Comment by kd-11** [comment]
It is illegal to create a renderpass with VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL which is why the assert is there. I have tried to reproduce this bug without success previously. I'll see if the new scenarios yield better results.

**Comment by kd-11** [comment]
Afer some debugging with testers we have found this bug is triggered when using the Strict Rendering Mode option. I will push a fix asap.

**Comment by kd-11** [comment]
Retest with https://github.com/RPCS3/rpcs3/pull/10409
