### ISSUE TITLE
Distortion effects cause drastic increase in gpu usage

### ISSUE THREAD

**Issue by ruvaldak** [RPCS3/rpcs3#9890]
## Details
As the title says, distortion effects used in some games cause an extreme bump in gpu usage, to the point that it severely drops framerate. Affected games include:
- All three Ratchet and Clank games from the R&C Trilogy
- Ratchet and clank: Tools of Destruction
- Ratchet and clank: A Quest for Booty

I'm positive more games outside of the R&C series are affected. It's possible it's only older games affected by this, but I'm unsure.

#### 1. Please attach RPCS3's log.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/6076685/RPCS3.log.gz)

#### 2. If you describe graphical issue, please provide an RSX capture and a RenderDoc capture that demonstrate it.
[BCES01503_20210303094234_capture.zip](https://github.com/RPCS3/rpcs3/files/6076716/BCES01503_20210303094234_capture.zip)
[rpcs3-r&c3-frame2533.zip](https://drive.google.com/file/d/16czoZD20SAh_Ew-0jijm55YM4tcMnIgn/view?usp=sharing)

#### 3. Please attach screenshots of your problem.
![image](https://user-images.githubusercontent.com/15901769/109821734-48eae880-7c04-11eb-92af-ee40ee39fdf2.png)

#### 5. Please provide your system configuration:
- Windows 10 Pro x64
- Intel i7-9700k
- 16gb DDR4 3600Mhz CL14
- GPU0: NVidia GTX 1660Super 6Gb
- GPU1: NVidia GT 1030 2Gb
- 1920x1080 165Hz

I don't have very many games to test, mostly just the entire R&C collection as well as the full collection of LittleBigPlanet games, which, as far as I know, don't have these same kind of distortion/warping effects that are present on R&C games. I haven't tested R&C: A Crack In Time and games after it running on the same engine for the same issue, as it suffers from the "Unimplemented unnormalized sampling for texture type 3" issue (#8154) which can render the game unplayable. This issue doesn't seem to be related to just the fact that R&C Trilogy is a PS2 port, as R&C: Tools of Destruction and afterwards are all games designed for the PS3. A genuine PS3 doesn't have any form of framerate issues related to these distortion/warping effects.

**Comment by Asinin3** [comment]
Just because the performance drop is not visible on real PS3 hardware doesn't mean it isn't there. If this was a regression, or it was debugged and something was found to have been causing it then we could leave this open. Otherwise performance issues aren't very useful.

For instance, R&C 1-3 & Deadlocked have an ABSURD number of drawcalls and were lazy ports to PS3 that don't take advantage of how more "modern" hardware works compared to the PS2. This isn't an emulator issue, its just how the game was designed. And since the PS3 HW ran okay they didn't bother improving it. Things will improve over time with e.g Vulkan 1.3 and other advancements.
